#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Builder for Oxford Dictionary Part 1 (A-D) -> 260 words
"""
import json
import os
import re

def slugify(text):
    return re.sub(r'[^a-z0-9]+', '-', text.lower()).strip('-')

# 260 Distinct Oxford Headwords for Letters A - D
WORDS_A_D = [
    # A (continued)
    ("Balance", "noun", "B1", "/ˈbæl.əns/", "keseimbangan / saldo rekening / kesetimbangan",
     "Kondisi setara antara unsur-unsur; sisa dana di rekening.", "An even distribution of weight; remaining funds in an account.",
     ["Balanced", "Imbalance", "Equilibrium"], ["Equilibrium", "Symmetry", "Stability", "Poise", "Remainder"], ["Imbalance", "Instability", "Asymmetry"],
     "Maintaining a healthy balance between demanding professional responsibilities and restful family life is essential.",
     "Before making a large debit card purchase, check your checking account balance on the mobile banking application."),

    ("Ban", "verb", "B1", "/bæn/", "melarang resmi / mencekal / memblokir",
     "Melarang suatu tindakan atau barang secara hukum resmi.", "To officially or legally prohibit something from being done, sold, or used.",
     ["Prohibition", "Banned", "Outlaw"], ["Prohibit", "Forbid", "Bar", "Outlaw", "Disallow"], ["Permit", "Allow", "Authorize", "Legalize"],
     "The municipal government enacted an ordinance to ban single-use plastic grocery bags.",
     "International sporting federations voted to ban performance-enhancing anabolic substances across all competitive athletics."),

    ("Barrier", "noun", "B2", "/ˈbær.i.ər/", "rintangan / pembatas fisik / kendala penghalang",
     "Pagar atau hambatan yang menghalangi pergerakan atau komunikasi.", "A fence or obstacle that prevents movement or access; a circumstance that impedes progress.",
     ["Barricade", "Obstacle", "Hurdle"], ["Obstacle", "Hurdle", "Barricade", "Impediment", "Blockade"], ["Openway", "Access", "Aid", "Passage"],
     "Language differences should never act as a permanent barrier to collaborative humanitarian teamwork.",
     "Civil engineers constructed concrete sea barriers along the harbor promenade to deflect powerful storm surge waves."),

    ("Basic", "adjective", "A1", "/ˈbeɪ.sɪk/", "dasar / mendasar / pokok / elementer",
     "Membentuk fondasi utama atau bagian yang paling esensial.", "Forming an essential foundation or starting point; fundamental and simple.",
     ["Basically", "Basics", "Base"], ["Fundamental", "Essential", "Primary", "Elementary", "Core"], ["Advanced", "Complex", "Secondary", "Elaborate"],
     "Every citizen should have guaranteed access to basic healthcare, clean water, and nutritional food.",
     "The introductory computer science course begins with basic logic gates before advancing to algorithmic complexity."),

    ("Behavior", "noun", "A2", "/bɪˈheɪ.vjər/", "perilaku / tingkah laku / kelakuan",
     "Cara seseorang atau hewan bertindak dalam kehidupan sehari-hari.", "The way in which one acts or conducts oneself, especially toward others.",
     ["Behave", "Behavioral", "Conduct"], ["Conduct", "Demeanor", "Actions", "Deportment", "Manner"], ["Immobility", "Inaction"],
     "Parents reward positive social behavior to encourage kindness and cooperation in young siblings.",
     "Primatologists observe chimpanzee group behavior in wild sanctuaries to understand early hominid social hierarchies."),

    ("Belief", "noun", "B1", "/bɪˈliːf/", "keyakinan / kepercayaan / asas pandangan",
     "Sesuatu yang diyakini sebagai kebenaran; prinsip hidup.", "An acceptance that a statement is true or that something exists; trust, faith, or confidence.",
     ["Believe", "Believer", "Unbelief"], ["Conviction", "Faith", "Credo", "Tenet", "Trust"], ["Disbelief", "Skepticism", "Doubt", "Distrust"],
     "She holds a steadfast belief in the power of public education to transform impoverished communities.",
     "Freedom of religious belief and conscience is enshrined as an inviolable right in international human rights declarations."),

    ("Benefit", "noun", "A2", "/ˈben.ɪ.fɪt/", "manfaat / faedah / tunjangan kesejahteraan",
     "Keuntungan yang diperoleh dari sesuatu; dana tunjangan.", "An advantage or profit gained from something; a payment made by employer or state.",
     ["Beneficial", "Beneficiary", "Advantage"], ["Advantage", "Perk", "Profit", "Gain", "Assistance"], ["Disadvantage", "Drawback", "Detriment", "Loss"],
     "One major benefit of remote telecommuting is saving hours previously spent in congested highway traffic.",
     "The full-time corporate employment package includes comprehensive dental and optical healthcare benefits."),

    ("Betray", "verb", "B2", "/bɪˈtreɪ/", "mengkhianati / membocorkan rahasia / mengecewakan",
     "Mengingkari kesetiaan atau kepercayaan seseorang; membocorkan rahasia.", "To expose one's country or a person to danger by treacherous disloyalty; reveal secrets.",
     ["Betrayal", "Betrayer", "Treacherous"], ["Deceive", "Double-cross", "Expose", "Disclose", "Let down"], ["Defend", "Protect", "Support", "Remain loyal"],
     "He refused to betray his close comrades even when threatened with severe punitive sanctions.",
     "Unreliable encrypted password storage protocols can betray sensitive user credentials to malicious online eavesdroppers."),

    ("Bias", "noun", "B2", "/ˈbaɪ.əs/", "bias / keberpihakan / prasangka subjektif",
     "Kecenderungan untuk mendukung atau menolak suatu hal secara tidak adil.", "Prejudice in favor of or against one thing, person, or group compared with another, usually unfairly.",
     ["Biased", "Unbiased", "Prejudice"], ["Prejudice", "Partiality", "Partisanship", "Favoritism", "Slant"], ["Impartiality", "Fairness", "Neutrality", "Objectivity"],
     "Journalists must strive to eliminate personal political bias when reporting controversial election debates.",
     "Machine learning algorithms can inadvertently absorb human historical bias present in unfiltered training datasets."),

    ("Bizarre", "adjective", "B2", "/bɪˈzɑːr/", "ganjil / aneh sekali / tidak lazim",
     "Sangat aneh atau tidak biasa dalam penampilan atau kejadian.", "Very strange, unusual, or striking in appearance or effect.",
     ["Bizarrely", "Bizarreness", "Eccentric"], ["Strange", "Peculiar", "Odd", "Eccentric", "Weird"], ["Normal", "Ordinary", "Typical", "Conventional"],
     "Deep-sea oceanographers discovered a bizarre bioluminescent creature thriving near volcanic hydrothermal vents.",
     "The thriller movie featured a bizarre plot twist that left audiences debating its hidden symbolism for weeks."),

    ("Blanket", "noun", "A2", "/ˈblæŋ.kɪt/", "selimut hangat / hamparan penutup tebal",
     "Kain tebal penutup badan saat tidur; lapisan tebal.", "A large piece of woolen or thick fabric used for warmth; a thick covering layer.",
     ["Covering", "Layer", "Quilt"], ["Quilt", "Coverlet", "Layer", "Canopy", "Shroud"], ["Exposed ground"],
     "The rescue volunteers distributed warm wool blankets to families displaced by the winter blizzard.",
     "A thick blanket of early morning fog drifted across the mountain pine valleys, reducing road visibility."),

    ("Bleak", "adjective", "C1", "/bliːk/", "suram / gersang / tanpa harapan cerah",
     "Gersang dan dingin; tanpa prospek cerah atau masa depan baik.", "Lacking vegetation and exposed to the elements; offering little or no hope for future success.",
     ["Bleakness", "Bleakly", "Desolate"], ["Grim", "Desolate", "Dismal", "Gloomy", "Hopeless"], ["Bright", "Promising", "Hopeful", "Cheerful"],
     "The economic outlook for the coal-mining town appeared bleak following factory closures.",
     "Explorers trekked across the bleak Arctic tundra where biting sub-zero winds whipped uninterrupted across icy plains."),

    ("Blessing", "noun", "B1", "/ˈbles.ɪŋ/", "berkah / restu / anugerah keberuntungan",
     "Doa perlindungan ilahi; anugerah yang membawa keselamatan.", "A prayer asking for divine favor and protection; a beneficial thing that brings happiness.",
     ["Bless", "Blessed", "Grace"], ["Benediction", "Grace", "Boon", "Gift", "Favor"], ["Curse", "Bane", "Affliction", "Damnation"],
     "The arrival of monsoon rains was a true blessing for drought-stricken farming communities.",
     "Before embarking on her overseas university studies, she sought the heartfelt blessing of her grandparents."),

    ("Blockade", "noun", "C1", "/blɒkˈeɪd/", "blokade / pengepungan jalur masuk",
     "Tindakan menutup atau mengepung tempat untuk mencegah pasokan masuk.", "An act of sealing off a place to prevent goods or people from entering or leaving.",
     ["Block", "Besiege", "Embargo"], ["Siege", "Embargo", "Barricade", "Obstruction", "Quarantine"], ["Opening", "Access", "Free passage"],
     "The naval fleet enforced a strict maritime blockade around the disputed territorial straits.",
     "Protesting transport workers formed a peaceful road blockade outside the shipping terminal to demand wage parity."),

    ("Boast", "verb", "B2", "/bəʊst/", "membanggakan / menyombongkan kelebihan",
     "Berbicara bangga tentang diri sendiri; memiliki fitur hebat.", "To talk with excessive pride and self-satisfaction about oneself; to possess a proud feature.",
     ["Boastful", "Boasting", "Brag"], ["Brag", "Crow", "Flaunt", "Possess", "Show off"], ["Belittle", "Deprecate", "Hide", "Understate"],
     "The newly opened five-star resort can boast panoramic ocean views from every guest balcony.",
     "True champions let their athletic performance speak for itself rather than boast about past victories on social media."),

    ("Bold", "adjective", "B1", "/bəʊld/", "berani / tegas / mencolok / huruf tebal",
     "Tidak takut mengambil risiko; percaya diri dan tegas.", "Showing an ability to take risks; confident, courageous, and visually prominent.",
     ["Boldly", "Boldness", "Courageous"], ["Courageous", "Daring", "Audacious", "Brazen", "Vivid"], ["Timid", "Cowardly", "Faint", "Hesitant"],
     "She made a bold entrepreneurial decision to quit her corporate job and launch a solar startup.",
     "Key headings in the technical documentation are styled in bold typography to enhance readability."),

    ("Bond", "noun", "B1", "/bɒnd/", "ikatan batin / obligasi surat utang / ikatan kimia",
     "Hubungan emosional yang erat; surat utang pemerintah; ikatan atom.", "A strong connection between people; a financial debt security; a chemical attraction holding atoms.",
     ["Bonding", "Bonded", "Attachment"], ["Tie", "Attachment", "Alliance", "Affinity", "Obligation"], ["Severance", "Separation", "Rift", "Alienation"],
     "A shared passion for wildlife preservation forged an unbreakable bond between the two naturalists.",
     "Conservative pension funds invest a substantial percentage of capital in sovereign government bonds."),

    ("Boost", "verb", "B1", "/buːst/", "mendorong naik / meningkatkan / mendongkrak",
     "Membantu memajukan atau menaikkan performa atau pendapatan.", "To help or encourage something to increase, improve, or become more successful.",
     ["Booster", "Boost", "Uplift"], ["Enhance", "Elevate", "Amplify", "Augment", "Strengthen"], ["Decrease", "Diminish", "Dampen", "Impair"],
     "Eating a nutritious Mediterranean diet rich in leafy greens helps boost immune system resilience.",
     "The central bank lowered benchmark lending rates to boost consumer spending and stimulate business hiring."),

    ("Boundary", "noun", "B2", "/ˈbaʊn.dər.i/", "batas wilayah / garis batas perbatasan",
     "Garis yang menandai batas suatu bidang tanah atau wilayah.", "A line that marks the limits of an area; a dividing line; limits of acceptable behavior.",
     ["Bound", "Boundaries", "Border"], ["Border", "Frontier", "Perimeter", "Limit", "Demarcation"], ["Interior", "Center", "Unlimited space"],
     "Surveyors used satellite laser telemetry to verify the exact boundary between the neighboring farms.",
     "Establishing healthy personal boundaries at work prevents occupational burnout and preserves evening family time."),

    ("Bravery", "noun", "B1", "/ˈbreɪ.vər.i/", "keberanian / ketabahan hati menghadapi bahaya",
     "Sikap berani dan pantang menyerah saat menghadapi bahaya.", "Courageous behavior or character when facing danger, adversity, or fear.",
     ["Brave", "Bravely", "Courage"], ["Courage", "Valor", "Fortitude", "Gallantry", "Pluck"], ["Cowardice", "Timidity", "Fearfulness"],
     "The rookie firefighter was awarded a medal of honor for extraordinary bravery during the rescue.",
     "Historical records commemorate the bravery of peaceful suffragettes who marched despite police intimidation."),

    ("Breakdown", "noun", "B2", "/ˈbreɪk.daʊn/", "kerusakan mesin / rincian data / gangguan mental",
     "Kerusakan alat mekanis; analisis rincian data; krisis emosi.", "A mechanical failure; a detailed analysis or itemized list; a mental collapse.",
     ["Break", "Collapse", "Analysis"], ["Failure", "Collapse", "Analysis", "Itemization", "Classification"], ["Recovery", "Assembly", "Function"],
     "The invoice provided a transparent itemized breakdown of labor and materials costs.",
     "Highway maintenance crews responded promptly to a heavy truck breakdown obstructing the tunnel."),

    ("Breed", "verb", "B2", "/briːd/", "berkembang biak / mengembangbiakkan hewan",
     "Menghasilkan keturunan pada hewan; memelihara hewan ternak.", "To mate and produce offspring; to rear animals; to cause something to happen or spread.",
     ["Breeding", "Breeder", "Offspring"], ["Reproduce", "Propagate", "Cultivate", "Engender", "Spawn"], ["Extinguish", "Suppress", "Halt"],
     "Endangered sea turtles return to their natal beaches every few years to breed and lay eggs.",
     "Unregulated industrial pollution and stagnant puddles breed disease-carrying mosquito larvae during wet months."),

    ("Brief", "adjective", "A2", "/briːf/", "singkat / ringkas / tidak lama",
     "Berlangsung dalam waktu pendek; menggunakan sedikit kata.", "Of short duration; concise and not lasting a long time in speech or text.",
     ["Briefly", "Briefing", "Brevity"], ["Concise", "Short", "Succinct", "Fleeting", "Terse"], ["Long", "Prolonged", "Protracted", "Verbose"],
     "The military commander held a brief tactical briefing before deploying the search helicopter.",
     "After a brief coffee pause, the delegates resumed negotiating terms of the multilateral climate accord."),

    ("Brilliant", "adjective", "A2", "/ˈbrɪl.jənt/", "cemerlang / sangat cerdas / berkilau terang",
     "Sangat pintar atau berbakat; memancarkan sinar terang.", "Exceptionally clever, talented, or impressive; shining brightly with intense light.",
     ["Brilliantly", "Brilliance", "Luminous"], ["Intelligent", "Ingenious", "Dazzling", "Luminous", "Superb"], ["Dull", "Stupid", "Dim", "Mediocre"],
     "The young theoretical physicist proposed a brilliant mathematical framework to reconcile quantum mechanics.",
     "The nighttime sky over the Chilean high desert offered a brilliant, unobstructed view of the Milky Way galaxy."),

    ("Broad", "adjective", "B1", "/brɔːd/", "luas / lebar / mencakup banyak hal umum",
     "Memiliki ukuran lebar besar; mencakup berbagai macam topik.", "Having an ample distance from side to side; wide; covering a large scope of subjects.",
     ["Broadly", "Broaden", "Width"], ["Wide", "Spacious", "Extensive", "Comprehensive", "Sweeping"], ["Narrow", "Restricted", "Limited", "Specific"],
     "The university curriculum offers a broad foundational overview of both arts and empirical sciences.",
     "The presidential candidate enjoyed broad electoral support spanning working-class suburbs and urban districts."),

    ("Broaden", "verb", "B2", "/ˈbrɔː.dən/", "memperluas / menambah wawasan pikiran",
     "Membuat sesuatu menjadi lebih lebar atau mencakup lingkup luas.", "To make or become larger in width, scope, perspective, or variety.",
     ["Broad", "Broadly", "Expand"], ["Expand", "Enlarge", "Widen", "Diversify", "Extend"], ["Narrow", "Constrict", "Limit", "Restrict"],
     "Living abroad for an exchange semester helps students broaden their cultural horizons and empathy.",
     "The software enterprise decided to broaden its product catalog to include cloud analytics tools for healthcare."),

    ("Budget", "noun", "A2", "/ˈbʌdʒ.ɪt/", "anggaran belanja / bujet keuangan",
     "Perkiraan rencana pemasukan dan pengeluaran dana.", "An estimate of income and expenditure for a set period of time.",
     ["Budgetary", "Budgeted", "Fiscal"], ["Allocation", "Funds", "Allowance", "Finances", "Estimate"], ["Extravagance", "Debt"],
     "Families draft a monthly household budget to track grocery expenses and prioritize debt repayments.",
     "The finance ministry submitted the national fiscal budget proposal to parliament for legislative scrutiny."),

    ("Bulk", "noun", "B2", "/bʌlk/", "sebagian besar / volume besar / muatan curah",
     "Ukuran atau massa yang sangat besar; bagian mayoritas.", "The greater part or mass of something; large in size, volume, or unpackaged quantity.",
     ["Bulky", "Mass", "Volume"], ["Majority", "Mass", "Larger part", "Volume", "Mainstream"], ["Minority", "Small fraction", "Portion"],
     "The bulk of our company revenue is generated through annual cloud software subscriptions.",
     "Purchasing raw organic oats in bulk quantities significantly reduces single-use plastic packaging waste."),

    ("Burden", "noun", "B2", "/ˈbɜː.dən/", "beban berat / tanggungan moral / kesukaran",
     "Beban berat yang dipikul; kewajiban sulit yang menekan.", "A heavy load that is carried; a heavy duty, responsibility, or emotional worry.",
     ["Burdensome", "Unburden", "Load"], ["Load", "Weight", "Encumbrance", "Strain", "Affliction"], ["Relief", "Benefit", "Advantage", "Solace"],
     "Excessive student loan debt imposes a crushing financial burden upon young university graduates.",
     "Caring for an ailing family member requires community support systems so caregivers do not bear the burden alone."),

    # --- C ---
    ("Calculate", "verb", "B1", "/ˈkæl.kjə.leɪt/", "menghitung / memperhitungkan risiko / mengkalkulasi",
     "Menentukan nilai matematis dengan hitungan; memperkirakan akibat.", "To determine mathematically; to evaluate risk or consequences.",
     ["Calculation", "Calculator", "Computed"], ["Compute", "Reckon", "Determine", "Estimate", "Quantify"], ["Guess", "Ignore"],
     "Civil engineers calculate structural load stresses before pouring reinforced concrete foundations.",
     "Insurance actuaries calculate statistical mortality probabilities to price life insurance policies accurately."),

    ("Campaign", "noun", "B1", "/kæmˈpeɪn/", "kampanye / gerakan terorganisir / operasi militer",
     "Rangkaian kegiatan terencana untuk meraih tujuan sosial, politik, atau militer.", "A series of organized operations or activities to achieve a goal.",
     ["Campaigner", "Drive", "Movement"], ["Movement", "Drive", "Crusade", "Operation", "Effort"], ["Inaction", "Passivity"],
     "The health ministry launched a national vaccination campaign to eliminate childhood measles.",
     "Environmental activists spearheaded a grassroots campaign advocating for clean renewable solar microgrids."),

    ("Candidate", "noun", "B1", "/ˈkæn.dɪ.dət/", "kandidat / calon pelamar / calon peserta ujian",
     "Seseorang yang mencalonkan diri untuk posisi politik atau pekerjaan.", "A person who applies for a job or competes in an election.",
     ["Candidacy", "Applicant", "Nominee"], ["Applicant", "Contender", "Nominee", "Competitor", "Aspirant"], ["Incumbent", "Officer"],
     "The presidential candidate outlined an ambitious infrastructure investment blueprint during the debate.",
     "Recruiters interviewed each shortlisted candidate to evaluate their technical problem-solving capabilities."),

    ("Capacity", "noun", "B2", "/kəˈpæs.ə.ti/", "kapasitas / daya tampung / kemampuan kerja",
     "Jumlah maksimum yang dapat ditampung; kemampuan menghasilkan karya.", "The maximum amount that something can contain; ability to produce.",
     ["Capacious", "Capacitate", "Volume"], ["Volume", "Ability", "Competence", "Potential", "Aptitude"], ["Incapacity", "Inability", "Limitation"],
     "The newly renovated football stadium has a seating capacity of eighty thousand spectators.",
     "Human beings possess an astonishing psychological capacity for resilience during difficult life trials."),

    ("Capital", "noun", "A2", "/ˈkæp.ɪ.təl/", "ibukota / modal usaha / huruf kapital",
     "Kota pusat pemerintahan; modal kekayaan finansial; huruf besar.", "The most important city in a country; accumulated financial wealth; uppercase letter.",
     ["Capitalize", "Capitalism", "Asset"], ["Wealth", "Principal", "Funds", "Metropolis", "Assets"], ["Debt", "Liability"],
     "Venture capital firms invest seed funding in early-stage artificial intelligence startups.",
     "Jakarta served as the historic political and economic capital city of Indonesia for many decades."),

    ("Capture", "verb", "B1", "/ˈkæp.tʃər/", "menangkap musuh / merekam momen / merebut perhatian",
     "Mengambil seseorang sebagai tawanan; mengabadikan gambar/suara.", "To take into one's possession or control by force; record accurately in art or photo.",
     ["Captor", "Captive", "Seize"], ["Seize", "Apprehend", "Trap", "Record", "Ensnare"], ["Release", "Free", "Liberate", "Lose"],
     "The nature photographer managed to capture a rare snow leopard prowling across Himalayan ridges.",
     "The police worked with federal marshals to capture the fugitive bank robber after an extensive manhunt."),

    ("Casual", "adjective", "B1", "/ˈkæʒ.u.əl/", "santai / kasual / tidak resmi / sambilan",
     "Bersifat rileks, santai, dan tidak kaku; pekerja tidak tetap.", "Relaxed, informal, and unconcerned; not permanent or regular.",
     ["Casually", "Casualness", "Informal"], ["Informal", "Relaxed", "Nonchalant", "Occasional", "Temporary"], ["Formal", "Stiff", "Permanent", "Serious"],
     "Tech software companies often encourage a casual dress code of t-shirts and jeans for developers.",
     "She worked as a casual barista during her undergraduate university semester breaks."),

    ("Category", "noun", "B1", "/ˈkæt.ə.ɡri/", "kategori / kelompok klasifikasi / golongan",
     "Golongan orang atau benda yang memiliki ciri-ciri serupa.", "A class or division of people or things regarded as having particular shared characteristics.",
     ["Categorize", "Categorical", "Class"], ["Class", "Classification", "Group", "Bracket", "Division"], ["Whole", "Entity"],
     "The bookstore shelves are organized into clear categories such as science fiction, history, and poetry.",
     "The academy awards ceremony recognizes outstanding cinematic achievements across twenty-four distinct categories."),

    ("Celebrate", "verb", "A2", "/ˈsel.ə.breɪt/", "merayakan / memperingati hari besar / mengagungkan",
     "Melakukan kegiatan menyenangkan untuk memperingati peristiwa penting.", "To acknowledge a significant day or event with a social gathering or enjoyable activity.",
     ["Celebration", "Celebrant", "Celebrated"], ["Commemorate", "Honor", "Praise", "Toast", "Rejoice"], ["Mourn", "Lament", "Overlook", "Ignore"],
     "Families gather together to celebrate traditional lunar new year reunions with feasts and lanterns.",
     "The international scientific community gathered to celebrate the centennial anniversary of the discovery of insulin."),

    ("Certain", "adjective", "A2", "/ˈsɜː.tən/", "pasti / yakin tanpa ragu / tertentu",
     "Bebas dari keraguan; digunakan untuk merujuk orang/hal tertentu.", "Known for sure; established beyond doubt; specific but not named.",
     ["Certainly", "Certainty", "Sure"], ["Sure", "Confident", "Definite", "Convinced", "Specific"], ["Uncertain", "Doubtful", "Hesitant", "Ambiguous"],
     "I am absolutely certain that we can resolve this engineering bug before the software release.",
     "Certain bird species migrate thousands of kilometers across open oceans every autumn."),

    ("Challenge", "noun", "B1", "/ˈtʃæl.ɪndʒ/", "tantangan / ujian kemampuan / sanggahan",
     "Situasi sulit yang menguji tekad dan keahlian seseorang.", "A task or situation that tests someone's abilities; an objection.",
     ["Challenging", "Challenger", "Test"], ["Test", "Trial", "Hurdle", "Obstacle", "Defiance"], ["Ease", "Simplicity", "Agreement"],
     "Climbing the treacherous north face of Mount Eiger presents a formidable challenge for mountaineers.",
     "The legal team filed a formal constitutional challenge against the newly enacted corporate tax statute."),

    ("Champion", "noun", "B1", "/ˈtʃæm.pi.ən/", "juara turnamen / pembela hak gigih",
     "Pemenang kompetisi utama; pejuang yang membela hak orang lain.", "A person who has surpassed all rivals in a competition; a vigorous advocate.",
     ["Championship", "Championing", "Advocate"], ["Victor", "Winner", "Advocate", "Defender", "Hero"], ["Loser", "Opponent", "Critic"],
     "The tennis champion lifted the golden grand slam trophy amid thunderous applause from the crowd.",
     "Throughout her political career, she remained a steadfast champion of universal public healthcare."),

    ("Charity", "noun", "B1", "/ˈtʃær.ə.ti/", "amal kemanusiaan / lembaga donasi / kedermawanan",
     "Bantuan sukarela bagi yang membutuhkan; organisasi nirlaba.", "An organization set up to provide help and raise money for those in need; benevolence.",
     ["Charitable", "Charitably", "Philanthropy"], ["Benevolence", "Philanthropy", "Donation", "Alms", "Kindness"], ["Greed", "Selfishness", "Meanness"],
     "All proceeds from the annual charity gala were donated to rural pediatric clinics.",
     "Acts of quiet personal charity bring dignity and tangible relief to homeless community members."),

    ("Circuit", "noun", "B2", "/ˈsɜː.kɪt/", "rangkaian listrik / sirkuit balap / rute keliling",
     "Jalur tertutup aliran arus listrik; lintasan balap.", "A complete route around which an electric current can flow; a racetrack or tour.",
     ["Circular", "Circuitry", "Track"], ["Loop", "Course", "Track", "Network", "Route"], ["Line", "Break"],
     "Integrated microchips contain billions of microscopic electronic circuits printed on silicon wafers.",
     "Formula One drivers completed sixty laps around the challenging Silverstone racing circuit."),

    ("Circumstance", "noun", "B2", "/ˈsɜː.kəm.stɑːns/", "keadaan / situasi kondisi / faktor sekitar",
     "Fakta atau kondisi yang melingkupi suatu peristiwa.", "A fact or condition connected with or relevant to an event or action.",
     ["Circumstantial", "Situation", "Condition"], ["Situation", "Condition", "Factor", "Context", "Occurrence"], ["N/A"],
     "Under no circumstance should unauthorized personnel enter the high-voltage electrical substation.",
     "Judges evaluate mitigating family circumstances before handing down juvenile rehabilitation sentences."),

    ("Citizen", "noun", "B1", "/ˈsɪt.ɪ.zən/", "warga negara / penduduk berhak sipil",
     "Anggota sah dari suatu negara yang memiliki hak dan kewajiban hukum.", "A legally recognized subject or national of a state.",
     ["Citizenship", "Civic", "National"], ["National", "Resident", "Inhabitant", "Subject", "Voter"], ["Alien", "Foreigner", "Noncitizen"],
     "Every eligible adult citizen has the civic duty and constitutional right to vote in general elections.",
     "The embassy provides consular legal assistance and emergency evacuation aid to overseas citizens."),

    ("Clarify", "verb", "B2", "/ˈklær.ɪ.faɪ/", "mengklarifikasi / memperjelas uraian",
     "Membuat suatu pernyataan menjadi mudah dipahami dan tidak membingungkan.", "To make a statement or situation less confused and more clearly comprehensible.",
     ["Clarification", "Clarity", "Explain"], ["Explain", "Elucidate", "Illuminate", "Simplify", "Clear up"], ["Confuse", "Obscure", "Muddy"],
     "The professor paused the lecture to clarify the fundamental differences between mitosis and meiosis.",
     "The ministry issued a public statement to clarify misinformation circulating on social media regarding food prices."),

    ("Classic", "adjective", "B1", "/ˈklæs.ɪk/", "klasik / bermutu tinggi abadi / contoh teladan",
     "Diakui bermutu tinggi sepanjang masa; contoh tipikal yang sempurna.", "Judged over a period of time to be of the highest quality and outstanding of its kind.",
     ["Classical", "Classicism", "Timeless"], ["Timeless", "Vintage", "Traditional", "Definitive", "Standard"], ["Modern", "Ephemeral", "Second-rate"],
     "Pride and Prejudice is a classic masterwork of nineteenth-century English romantic literature.",
     "The patient presented with classic symptoms of influenza, including high fever, chills, and muscle aches."),

    ("Climate", "noun", "A2", "/ˈklaɪ.mət/", "iklim cuaca / iklim politik atau sosial",
     "Pola cuaca rata-rata suatu wilayah dalam jangka panjang; suasana umum.", "The weather conditions prevailing in an area over a long period; general prevailing trend.",
     ["Climatic", "Climatology", "Weather"], ["Weather pattern", "Atmosphere", "Environment", "Milieu", "Temperature"], ["N/A"],
     "Tropical rainforest climates are characterized by heavy rainfall and high humidity year-round.",
     "The volatile economic climate led investors to reallocate capital into secure treasury bonds."),

    ("Coherent", "adjective", "B2", "/kəʊˈhɪə.rənt/", "koheren / runtut / logis dan bersatu padu",
     "Tersusun secara logis, jelas, dan saling bertalian erat.", "Logical, clear, and consistent; forming a unified whole.",
     ["Coherence", "Coherently", "Logical"], ["Logical", "Consistent", "Lucid", "Articulate", "Orderly"], ["Incoherent", "Muddled", "Confused", "Disjointed"],
     "The candidate delivered a coherent, compelling vision for public transportation renewal.",
     "Writers must use clear transitional phrases to ensure paragraphs connect into a coherent argumentative essay."),

    ("Collaborate", "verb", "B2", "/kəˈlæb.ə.reɪt/", "berkolaborasi / bekerja sama dalam tim",
     "Bekerja bersama-sama dengan orang lain untuk menyelesaikan proyek.", "To work jointly on an activity, especially to produce or create something.",
     ["Collaboration", "Collaborative", "Cooperate"], ["Cooperate", "Team up", "Partner", "Join forces", "Conspire"], ["Compete", "Oppose", "Work alone"],
     "International scientists collaborate across continents to analyze seismic telemetry from active volcanoes.",
     "Engineers and graphic designers must collaborate closely to create intuitive, accessible user interfaces."),

    ("Collection", "noun", "A2", "/kəˈlek.ʃən/", "koleksi / kumpulan barang / pengumpulan dana",
     "Sekelompok benda yang dikumpulkan karena menarik; pengumpulan donasi.", "A group of things or people assembled together; gathering of money.",
     ["Collect", "Collector", "Accumulation"], ["Assortment", "Accumulation", "Anthology", "Array", "Gathering"], ["Distribution", "Dispersal"],
     "The metropolitan museum houses a renowned collection of ancient Egyptian artifacts and pottery.",
     "Volunteers organized a neighborhood collection of canned food and warm coats for the shelter."),

    ("Combine", "verb", "B1", "/kəmˈbaɪn/", "menggabungkan / memadukan menjadi satu",
     "Menyatukan dua hal atau lebih untuk membentuk satu kesatuan utuh.", "To join or merge to form a single entity or produce a shared effect.",
     ["Combination", "Combined", "Merge"], ["Merge", "Unite", "Blend", "Integrate", "Fuse"], ["Separate", "Divide", "Detach", "Isolate"],
     "The hybrid vehicle engine can combine gasoline and electric power to maximize fuel efficiency.",
     "Culinary chefs combine aromatic spices and local herbs to craft distinctive fusion sauces."),

    ("Comfortable", "adjective", "A2", "/ˈkʌm.fə.tə.bəl/", "nyaman / enak dipakai / tenteram",
     "Memberikan rasa enak pada fisik; bebas dari rasa sakit atau kekhawatiran.", "Providing physical ease and relaxation; free from stress or pain.",
     ["Comfort", "Comfortably", "Cozy"], ["Cozy", "Pleasant", "Relaxing", "Restful", "Snug"], ["Uncomfortable", "Painful", "Harsh", "Uneasy"],
     "The plush ergonomic armchair provides a very comfortable seat for long reading sessions.",
     "After receiving a competitive salary increase, the family enjoyed a comfortable lifestyle in the suburbs."),

    ("Command", "verb", "B1", "/kəˈmɑːnd/", "memerintah / mengomandoi pasukan / menguasai ilmu",
     "Memberikan instruksi resmi yang harus ditaati; memimpin.", "To give an authoritative order; to be in charge of; control.",
     ["Commander", "Commanding", "Direct"], ["Order", "Direct", "Instruct", "Control", "Lead"], ["Obey", "Follow", "Surrender"],
     "The seasoned admiral will command the multinational naval patrol exercises in the Pacific.",
     "Bilingual professionals command higher starting salaries in global management consulting firms."),

    ("Commercial", "adjective", "B1", "/kəˈmɜː.ʃəl/", "komersial / berkaitan dengan perdagangan / berorientasi laba",
     "Berkaitan dengan jual-beli dan bisnis mencari keuntungan.", "Concerned with or engaged in commerce; intended to make a profit.",
     ["Commerce", "Commercially", "Mercantile"], ["Mercantile", "Business", "Trade", "Profitable", "Marketable"], ["Nonprofit", "Charitable", "Personal"],
     "The downtown historic quarter was redeveloped into a bustling commercial and dining district.",
     "Commercial aircraft undergo rigorous pre-flight safety inspections before passengers board."),

    ("Commitment", "noun", "B2", "/kəˈmɪt.mənt/", "komitmen / janji setia / dedikasi teguh",
     "Kesiapan mengabdikan waktu dan energi pada suatu tujuan atau orang.", "The state or quality of being dedicated to a cause, activity, or promise.",
     ["Commit", "Committed", "Dedication"], ["Dedication", "Devotion", "Loyalty", "Obligation", "Pledge"], ["Indifference", "Apathy", "Disloyalty"],
     "Her tireless commitment to environmental education inspired thousands of young community volunteers.",
     "Signing the long-term lease represents a major financial commitment for the small bakery owner."),

    ("Commodity", "noun", "B2", "/kəˈmɒd.ə.ti/", "komoditas / barang dagangan bernilai / bahan mentah",
     "Bahan mentah atau produk pertanian yang dapat diperjualbelikan.", "A raw material or primary agricultural product that can be bought and sold.",
     ["Commodities", "Goods", "Merchandise"], ["Merchandise", "Goods", "Product", "Asset", "Material"], ["N/A"],
     "Crude oil, copper, and coffee beans are among the most heavily traded commodities globally.",
     "Clean drinking water is increasingly recognized as a vital human right rather than a commercial commodity."),

    ("Community", "noun", "A2", "/kəˈmjuː.nə.ti/", "komunitas / masyarakat setempat / paguyuban",
     "Kelompok orang yang tinggal di wilayah yang sama atau berbagi minat serupa.", "A group of people living in the same place or having a particular characteristic in common.",
     ["Communal", "Communities", "Society"], ["Society", "Neighborhood", "Fellowship", "Collectivity", "Guild"], ["Individual", "Isolation"],
     "The local neighborhood community organized a weekend tree-planting initiative in the public park.",
     "Online developer communities share open-source libraries and assist beginners with debugging code."),

    ("Company", "noun", "A1", "/ˈkʌm.pə.ni/", "perusahaan / perseroan bisnis / kebersamaan teman",
     "Badan usaha komersial; kehadiran teman yang menemani.", "A commercial business; the fact or condition of being with another person.",
     ["Companion", "Accompany", "Corporation"], ["Corporation", "Enterprise", "Firm", "Companionship", "Society"], ["Solitude", "Isolation"],
     "She founded a biotechnology company focused on developing biodegradable plant-based packaging.",
     "He truly enjoyed the warm company of old university friends during the holiday weekend gathering."),

    ("Compare", "verb", "A2", "/kəmˈpeər/", "membandingkan / menyejajarkan persamaan dan beda",
     "Memeriksa persamaan dan perbedaan antara dua hal atau lebih.", "To estimate, measure, or note the similarity or dissimilarity between things.",
     ["Comparison", "Comparable", "Comparative"], ["Contrast", "Collate", "Juxtapose", "Weigh", "Match"], ["Ignore", "Isolate"],
     "Consumer review websites help shoppers compare the technical specifications and prices of smartphones.",
     "Historians compare the political structures of ancient Athens and democratic republics in modern times."),

    ("Compensate", "verb", "B2", "/ˈkɒm.pən.seɪt/", "memberi kompensasi / mengganti rugi / mengimbangi",
     "Membayar ganti rugi atas kehilangan atau luka; mengimbangi kekurangan.", "To pay someone money in recognition of loss, suffering, or injury; offset an effect.",
     ["Compensation", "Compensatory", "Reimburse"], ["Reimburse", "Indemnify", "Repay", "Offset", "Balance"], ["Deprive", "Damage", "Penalize"],
     "The airline agreed to compensate passengers whose flights were canceled due to scheduling errors.",
     "Her extraordinary memory helped compensate for minor visual impairments when learning music scores."),

    ("Compete", "verb", "A2", "/kəmˈpiːt/", "bersaing / berkompetisi / berlomba meraih juara",
     "Berusaha mengalahkan orang lain dalam turnamen atau pasar bisnis.", "To strive to gain or win something by defeating or establishing superiority over others.",
     ["Competition", "Competitive", "Competitor"], ["Contend", "Vie", "Rival", "Battle", "Strive"], ["Cooperate", "Collaborate", "Surrender"],
     "Elite marathon runners from across the world gather in Boston to compete for the gold medal.",
     "Small independent bookstores innovate customer service to compete effectively against giant online retailers."),

    ("Competition", "noun", "A2", "/ˌkɒm.pəˈtɪʃ.ən/", "kompetisi / perlombaan / persaingan bisnis",
     "Acara perlombaan untuk menentukan pemenang; persaingan usaha.", "An event in which people compete against each other; rivalry in business.",
     ["Compete", "Competitive", "Competitor"], ["Contest", "Tournament", "Match", "Rivalry", "Contention"], ["Cooperation", "Monopoly", "Harmony"],
     "The national robotics competition challenged high school students to build autonomous rovers.",
     "Intense competition among smartphone manufacturers has driven rapid breakthroughs in camera quality."),

    ("Complex", "adjective", "B1", "/ˈkɒm.pleks/", "kompleks / rumit / berbelit-belit",
     "Terdiri dari banyak bagian yang saling terkait sehingga sulit dipahami.", "Consisting of many different and connected parts; not easy to analyze.",
     ["Complexity", "Complicate", "Intricate"], ["Intricate", "Complicated", "Elaborate", "Sophisticated", "Tangled"], ["Simple", "Straightforward", "Elementary"],
     "The human brain is an extraordinarily complex organ containing billions of interconnected neurons.",
     "Tax attorneys help international corporations navigate complex cross-border financial regulations."),

    ("Component", "noun", "B2", "/kəmˈpəʊ.nənt/", "komponen / bagian penyusun / elemen suku cadang",
     "Bagian atau elemen yang membentuk satu kesatuan sistem mesin/alat.", "A part or element of a larger whole, especially a machine or vehicle.",
     ["Compose", "Composition", "Element"], ["Element", "Part", "Piece", "Constituent", "Module"], ["Whole", "Total"],
     "The graphic processing unit is a vital hardware component for rendering high-resolution 3D animation.",
     "Trust and open communication are foundational components of every successful professional partnership."),

    ("Comprehensive", "adjective", "B2", "/ˌkɒm.prɪˈhen.sɪv/", "komprehensif / menyeluruh / lengkap mendalam",
     "Mencakup atau berurusan dengan semua elemen dari sesuatu secara lengkap.", "Including or dealing with all or nearly all elements or aspects of something.",
     ["Comprehend", "Comprehensively", "Thorough"], ["Thorough", "Exhaustive", "All-inclusive", "Complete", "Extensive"], ["Partial", "Incomplete", "Selective", "Limited"],
     "The university medical clinic published a comprehensive guide to adolescent mental wellness.",
     "Auditors conducted a comprehensive inspection of all corporate expenditure records over the past fiscal decade."),

    ("Conceal", "verb", "B2", "/kənˈsiːl/", "menyembunyikan / merahasiakan / menutupi",
     "Mencegah sesuatu terlihat atau diketahui orang lain.", "To keep from sight or prevent from being known; hide.",
     ["Concealment", "Concealed", "Hide"], ["Hide", "Cover", "Mask", "Shroud", "Disguise"], ["Reveal", "Disclose", "Expose", "Uncover"],
     "Camouflage coloration allows desert lizards to conceal themselves from predatory hawks.",
     "The witness attempted to conceal her anxiety while testifying before the courtroom jury."),

    ("Concentrate", "verb", "B1", "/ˈkɒn.sən.treɪt/", "berkonsentrasi / memusatkan perhatian / memekatkan",
     "Memusatkan seluruh pikiran pada satu kegiatan; mengumpulkan.", "To focus one's full attention or mental effort on a particular task.",
     ["Concentration", "Concentrated", "Focus"], ["Focus", "Center", "Direct", "Consolidate", "Intensify"], ["Distract", "Scatter", "Disperse"],
     "It is difficult to concentrate on complex mathematics problems when loud construction noises persist outside.",
     "The biotechnology lab developed a method to concentrate fruit extracts without losing vital vitamins."),

    ("Concept", "noun", "B1", "/ˈkɒn.sept/", "konsep / gagasan ide dasar / rancangan pemikiran",
     "Gagasan atau prinsip umum yang mendasari sesuatu.", "An abstract idea or general notion; a plan or intention.",
     ["Conceptual", "Conceive", "Idea"], ["Idea", "Notion", "Theory", "Principle", "Hypothesis"], ["Reality", "Concrete fact"],
     "Albert Einstein revolutionized our fundamental concept of spacetime through general relativity.",
     "The automobile company unveiled an electric sports concept car featuring solar roof panels."),

    ("Conclusion", "noun", "A2", "/kənˈkluː.ʒən/", "kesimpulan / akhir penutup / konklusi",
     "Keputusan atau kesimpulan yang dicapai setelah menimbang bukti; bagian akhir naskah.", "The end or finish of an event or process; a judgment reached by reasoning.",
     ["Conclude", "Conclusive", "Ending"], ["Ending", "Outcome", "Verdict", "Deduction", "Finale"], ["Beginning", "Introduction", "Start"],
     "The research paper's final conclusion recommended increasing municipal investments in wind energy.",
     "After hours of rigorous scientific debate, the committee reached the unanimous conclusion that the vaccine was safe."),

    ("Conduct", "verb", "B2", "/kənˈdʌkt/", "mengadakan penelitian / memimpin orkestra / menghantar listrik",
     "Melakukan suatu kegiatan terencana; memimpin musik; menyalurkan panas/arus.", "To organize and carry out; to direct the performance of musicians; transmit heat.",
     ["Conductor", "Conductivity", "Direct"], ["Manage", "Direct", "Administer", "Execute", "Channel"], ["Mismanage", "Halt", "Insulate"],
     "Marine biologists conduct annual coral reef health surveys across the Great Barrier Reef.",
     "Copper and silver are superior metallic elements that efficiently conduct electric currents."),

    ("Confidence", "noun", "B1", "/ˈkɒn.fɪ.dəns/", "kepercayaan diri / rasa yakin / rahasia pribadi",
     "Keyakinan kuat pada kemampuan diri sendiri; kepercayaan pada orang lain.", "The feeling or belief that one can rely on someone or something; self-assurance.",
     ["Confident", "Confidential", "Assurance"], ["Assurance", "Self-reliance", "Certainty", "Faith", "Trust"], ["Doubt", "Insecurity", "Hesitation"],
     "Speaking in public with clear diction builds personal charisma and professional confidence.",
     "The board of directors expressed absolute confidence in the chief executive officer's restructuring plan."),

    ("Confident", "adjective", "B1", "/ˈkɒn.fɪ.dənt/", "percaya diri / merasa yakin akan berhasil",
     "Merasa yakin akan kemampuan diri sendiri atau hasil positif.", "Feeling or showing confidence in oneself; self-assured.",
     ["Confidence", "Confidently", "Assured"], ["Assured", "Self-assured", "Positive", "Certain", "Bold"], ["Insecure", "Doubtful", "Timid", "Uncertain"],
     "She felt confident about her performance in the competitive national violin recital.",
     "Experienced public speakers maintain upright posture and steady eye contact to appear confident."),

    ("Confirm", "verb", "B1", "/kənˈfɜːm/", "mengonfirmasi / memastikan kebenaran / meneguhkan",
     "Menyatakan bahwa sesuatu itu benar, valid, atau pasti terjadi.", "To establish the truth or correctness of something; make definitive.",
     ["Confirmation", "Confirmed", "Verify"], ["Verify", "Corroborate", "Validate", "Affirm", "Authenticate"], ["Deny", "Refute", "Disprove", "Cancel"],
     "Please check your inbox and click the security link to confirm your airline flight reservation.",
     "Laboratory blood tests were ordered to confirm the doctor's initial clinical diagnosis."),

    ("Conflict", "noun", "B1", "/ˈkɒn.flɪkt/", "konflik / pertentangan pendapat / pertempuran",
     "Pertikaian atau pertentangan sengit antar individu, kelompok, atau negara.", "A serious disagreement or argument; a prolonged armed struggle.",
     ["Conflicting", "Clash", "Dispute"], ["Dispute", "Clash", "Struggle", "Discord", "War"], ["Harmony", "Peace", "Agreement", "Concord"],
     "Diplomats worked tirelessly through the night to prevent the regional border conflict from escalating.",
     "There was a scheduling conflict between the annual faculty senate meeting and the biology lecture."),

    ("Consequence", "noun", "B1", "/ˈkɒn.sɪ.kwəns/", "konsekuensi / akibat logis / dampak penting",
     "Hasil atau akibat yang terjadi karena tindakan sebelumnya; kepentingan.", "A result or effect of an action or condition; importance or relevance.",
     ["Consequent", "Consequently", "Outcome"], ["Outcome", "Result", "Effect", "Repercussion", "Aftermath"], ["Cause", "Origin", "Source"],
     "Rising global ocean temperatures are a direct consequence of unchecked greenhouse gas emissions.",
     "Teenagers are encouraged to weigh the long-term consequences of their academic decisions."),

    ("Considerable", "adjective", "B2", "/kənˈsɪd.ər.ə.bəl/", "cukup besar / tergolong banyak / patut diperhitungkan",
     "Cukup besar dalam jumlah, nilai, atau kepentingan untuk diperhatikan.", "Notably large in size, amount, or importance.",
     ["Considerably", "Consider", "Substantial"], ["Substantial", "Significant", "Sizable", "Noticeable", "Immense"], ["Insignificant", "Slight", "Minor", "Negligible"],
     "The solar farm generated a considerable amount of electrical energy for surrounding municipalities.",
     "She devoted a considerable portion of her retirement years to volunteering at the community food bank."),

    ("Constant", "adjective", "B1", "/ˈkɒn.stənt/", "konstan / terus-menerus / tidak berubah / setia",
     "Terjadi terus-menerus tanpa henti; bernilai tetap.", "Occurring continuously over a period of time; remaining unchanging.",
     ["Constantly", "Constancy", "Continuous"], ["Continuous", "Persistent", "Unvarying", "Steady", "Perpetual"], ["Intermittent", "Variable", "Inconstant", "Erratic"],
     "The constant sound of ocean waves crashing against the rocky cliff had a soothing effect.",
     "Maintaining constant laboratory temperature is critical when cultivating bacterial cultures for analysis."),

    ("Construct", "verb", "B1", "/kənˈstrʌkt/", "membangun gedung / menyusun konsep teori",
     "Mendirikan bangunan atau merancang struktur gagasan.", "To build or erect something; create or assemble an idea.",
     ["Construction", "Constructive", "Build"], ["Build", "Erect", "Fabricate", "Assemble", "Create"], ["Demolish", "Destroy", "Dismantle", "Ruin"],
     "Engineers used reinforced steel beams to construct the earthquake-resistant highway overpass.",
     "Philosophers construct logical arguments using well-defined premises to derive valid conclusions."),

    ("Consult", "verb", "B1", "/kənˈsʌlt/", "berkonsultasi / meminta pendapat ahli / merujuk buku",
     "Meminta saran profesional atau memeriksa informasi dalam buku rujukan.", "To seek information or advice from an expert; refer for guidance.",
     ["Consultant", "Consultation", "Confer"], ["Confer", "Seek advice", "Deliberate", "Ask", "Refer to"], ["Ignore", "Neglect"],
     "Patients should consult a certified physician before starting any strenuous exercise program.",
     "Architects consult municipal building zoning codes before drafting residential floor plans."),

    ("Consumer", "noun", "B1", "/kənˈsjuː.mər/", "konsumen / pemakai produk / pembeli",
     "Orang yang membeli barang atau memanfaatkan jasa untuk kebutuhan pribadi.", "A person who purchases goods and services for personal use.",
     ["Consume", "Consumption", "Buyer"], ["Buyer", "Customer", "Shopper", "Purchaser", "Client"], ["Producer", "Manufacturer", "Seller"],
     "Consumer protection laws shield shoppers from misleading product advertising and unsafe toys.",
     "Educated consumers increasingly prioritize buying organic, locally grown agricultural produce."),

    ("Continuous", "adjective", "B1", "/kənˈtɪn.ju.əs/", "berkelanjutan / terus-menerus tanpa putus",
     "Membentuk keseluruhan yang tidak terputus dalam ruang atau waktu.", "Forming an unbroken whole; without interruption.",
     ["Continuously", "Continuity", "Unbroken"], ["Unbroken", "Uninterrupted", "Constant", "Nonstop", "Perpetual"], ["Intermittent", "Broken", "Discontinuous", "Sporadic"],
     "The patient received continuous monitoring of vital signs in the intensive care unit.",
     "Continuous professional learning ensures software developers stay proficient in modern frameworks."),

    ("Contribute", "verb", "B1", "/kənˈtrɪb.juːt/", "berkontribusi / menyumbang dana/pikiran",
     "Memberikan sesuatu demi membantu tercapainya tujuan bersama.", "To give something in order to help achieve or provide something.",
     ["Contribution", "Contributor", "Donate"], ["Donate", "Provide", "Furnish", "Bestow", "Add"], ["Withhold", "Take", "Withdraw"],
     "Community members volunteered to contribute their time and woodworking skills to build the playground.",
     "Renewable solar and wind energy contribute significantly to national carbon reduction targets."),

    ("Contribution", "noun", "B1", "/ˌkɒn.trɪˈbjuː.ʃən/", "kontribusi / sumbangan amal / andil nyata",
     "Sesuatu yang diberikan untuk membantu mencapai hasil; tulisan dalam jurnal.", "A gift or payment to a common fund or collection; an active role in achievement.",
     ["Contribute", "Contributor", "Donation"], ["Donation", "Gift", "Grant", "Offering", "Input"], ["Deduction", "Withdrawal"],
     "Her groundbreaking contribution to theoretical physics earned her international academic accolades.",
     "The local bank made a generous financial contribution toward expanding the city children's library."),

    ("Convenient", "adjective", "B1", "/kənˈviː.ni.ənt/", "praktis / nyaman digunakan / mudah diakses",
     "Sesuai dengan kenyamanan atau kebutuhan seseorang; mudah dijangkau.", "Fitting in well with a person's needs, activities, or plans; easy to use.",
     ["Convenience", "Conveniently", "Handy"], ["Handy", "Suitable", "Accessible", "Practical", "Favorable"], ["Inconvenient", "Difficult", "Awkward", "Unsuitable"],
     "Living near the central subway station is extremely convenient for daily university commuters.",
     "Mobile digital banking apps offer a convenient way to settle household utility bills instantaneously."),

    ("Conventional", "adjective", "B2", "/kənˈven.ʃən.əl/", "konvensional / lazim / sesuai adat tradisi",
     "Berdasarkan apa yang sudah biasa dilakukan; tradisional dan lazim.", "Based on or in accordance with what is generally done or believed.",
     ["Convention", "Conventionally", "Traditional"], ["Traditional", "Standard", "Customary", "Orthodox", "Usual"], ["Unconventional", "Novel", "Radical", "Original"],
     "Conventional agriculture relies heavily on synthetic chemical fertilizers and industrial pesticides.",
     "The young artist rejected conventional portrait techniques in favor of bold abstract impressionism."),

    ("Convey", "verb", "B2", "/kənˈveɪ/", "menyampaikan pesan / mengangkut barang / mengekspresikan",
     "Mengomunikasikan pesan atau perasaan; membawa sesuatu dari satu tempat ke tempat lain.", "To transport or carry; communicate an idea or feeling.",
     ["Conveyance", "Conveyor", "Transmit"], ["Communicate", "Express", "Transmit", "Impart", "Transport"], ["Suppress", "Conceal", "Withhold"],
     "Poetry uses vivid imagery and metaphor to convey profound human emotions of grief and love.",
     "Subterranean pipeline networks convey clean drinking water from mountain reservoirs into the city."),

    ("Convince", "verb", "B1", "/kənˈvɪns/", "meyakinkan orang lain / membujuk dengan logika",
     "Membuat seseorang yakin akan kebenaran suatu hal melalui argumen kuat.", "To cause someone to believe firmly in the truth of something through argument.",
     ["Convincing", "Conviction", "Persuade"], ["Persuade", "Assure", "Satisfy", "Sway", "Win over"], ["Dissuade", "Deter", "Discredit"],
     "She managed to convince the university scholarship committee of her academic potential.",
     "No amount of argument could convince him to abandon his lifelong dream of sailing around the world."),

    ("Critical", "adjective", "B1", "/ˈkrɪt.ɪ.kəl/", "kritis / sangat penting menentukan / kritis analitis",
     "Mengekspresikan penilaian analitis; sangat penting untuk keberhasilan.", "Expressing adverse or analytical comments; of decisive importance.",
     ["Critically", "Criticism", "Crucial"], ["Crucial", "Vital", "Decisive", "Analytical", "Essential"], ["Unimportant", "Trivial", "Complimentary"],
     "Developing strong critical thinking skills enables students to discern credible research from bias.",
     "Prompt administration of antibiotics is critical in preventing bacterial infections from turning septic."),

    ("Crucial", "adjective", "B2", "/ˈkruː.ʃəl/", "sangat krusial / amat menentukan keberhasilan",
     "Sangat penting dan menentukan hasil akhir dari situasi genting.", "Decisive or critical, especially in the success or failure of something.",
     ["Crucially", "Critical", "Essential"], ["Essential", "Vital", "Pivotal", "Indispensable", "Paramount"], ["Insignificant", "Minor", "Trivial", "Optional"],
     "Early childhood reading immersion plays a crucial role in cognitive linguistic development.",
     "Maintaining sterile laboratory environments is crucial when preparing tissue culture samples for research."),

    ("Curious", "adjective", "A2", "/ˈkjʊə.ri.əs/", "penasaran / ingin tahu banyak / unik aneh",
     "Memiliki hasrat besar untuk mengetahui sesuatu; aneh menarik.", "Eager to know or learn something; strange and unusual.",
     ["Curiosity", "Curiously", "Inquisitive"], ["Inquisitive", "Inquiring", "Intrigued", "Peculiar", "Unusual"], ["Indifferent", "Uninterested", "Ordinary"],
     "The young child was curious about how solar panels convert sunlight into usable electricity.",
     "Archaeologists made a curious discovery of brass astrolabe instruments in an ancient shipwreck."),

    # --- D ---
    ("Damage", "noun", "A2", "/ˈdæm.ɪdʒ/", "kerusakan / kerugian fisik / ganti rugi",
     "Kerugian fisik yang menurunkan nilai atau fungsi benda.", "Physical harm caused to something in such a way as to impair its value or usefulness.",
     ["Damaging", "Damaged", "Harm"], ["Harm", "Injury", "Destruction", "Impairment", "Loss"], ["Repair", "Restoration", "Improvement"],
     "The coastal cyclone caused extensive structural damage to seaside piers and wooden houses.",
     "Insurance adjusters arrived promptly to calculate the financial damage incurred during the factory fire."),

    ("Dangerous", "adjective", "A2", "/ˈdeɪn.dʒər.əs/", "berbahaya / mengancam keselamatan",
     "Mampu menimbulkan cedera, kerugian, atau bahaya bagi jiwa.", "Able or likely to cause harm or injury.",
     ["Danger", "Dangerously", "Hazardous"], ["Hazardous", "Perilous", "Risky", "Unsafe", "Threatening"], ["Safe", "Secure", "Harmless", "Protected"],
     "Driving at excessive speeds on icy mountain roads is extremely dangerous for all motorists.",
     "Chemical laboratory workers wear protective goggles when handling corrosive and dangerous reagents."),

    ("Decade", "noun", "B1", "/ˈdek.eɪd/", "dekade / dasawarsa / kurun 10 tahun",
     "Periode waktu selama sepuluh tahun berturut-turut.", "A period of ten consecutive years.",
     ["Decadal", "Ten years", "Period"], ["Ten-year period", "Decennium"], ["N/A"],
     "Over the past decade, solar panel manufacturing costs have dropped by more than eighty percent.",
     "The 1960s was a turbulent decade marked by civil rights movements and space exploration milestones."),

    ("Decisive", "adjective", "B2", "/dɪˈsaɪ.sɪv/", "tegas menentukan / berkeputusan mantap",
     "Menyelesaikan suatu persoalan dengan pasti; mampu mengambil keputusan tegas.", "Settling an issue; producing a definite result; having ability to make clear decisions.",
     ["Decide", "Decisively", "Decisiveness"], ["Definitive", "Conclusive", "Resolute", "Firm", "Determined"], ["Indecisive", "Hesitant", "Doubtful", "Weak"],
     "The general made a decisive strategic maneuver that secured victory on the northern front.",
     "Strong corporate leadership requires the ability to make decisive choices under ambiguous market data."),

    ("Declare", "verb", "B1", "/dɪˈkleər/", "menyatakan secara resmi / mendeklarasikan kemerdekaan",
     "Mengumumkan sesuatu dengan jelas, formal, dan terbuka kepada publik.", "To state or announce clearly, firmly, and officially.",
     ["Declaration", "Declared", "Proclaim"], ["Proclaim", "Announce", "State", "Assert", "Pronounce"], ["Conceal", "Suppress", "Retract"],
     "The founding fathers gathered in the hall to declare national independence and sovereign self-rule.",
     "International travelers must declare commercial goods and high-value currency at customs border checkpoints."),

    ("Decline", "verb", "B1", "/dɪˈklaɪn/", "menolak dengan halus / merosot nilainya",
     "Menolak undangan secara sopan; mengalami penurunan jumlah atau mutu.", "To politely refuse an offer; to become smaller, fewer, or less.",
     ["Declining", "Decrease", "Refusal"], ["Refuse", "Reject", "Decrease", "Diminish", "Dwindle"], ["Accept", "Increase", "Rise", "Grow"],
     "She had to decline the banquet invitation due to a prior academic conference commitment.",
     "The population of native songbirds began to decline following the loss of natural woodland habitats."),

    ("Decorate", "verb", "A2", "/ˈdek.ə.reɪt/", "menghias / mempercantik ruangan / menganugerahi medali",
     "Menambahkan benda-benda indah agar ruangan tampak menarik; memberi bintang kehormatan.", "To make something look more attractive by adding decorative items; confer a medal.",
     ["Decoration", "Decorative", "Decorator"], ["Adorn", "Ornament", "Beautify", "Embellish", "Deck"], ["Deface", "Disfigure", "Strip"],
     "Families gather in December to decorate the evergreen pine tree with colorful glass ornaments.",
     "The army veteran was decorated for conspicuous bravery during the frontline rescue operation."),

    ("Dedicated", "adjective", "B1", "/ˈded.ɪ.keɪ.tɪd/", "berdedikasi tinggi / diperuntukkan khusus",
     "Mencurahkan seluruh waktu dan tenaga untuk tujuan mulia; dirancang khusus.", "Devoted to a task or purpose; exclusively allocated for a specific role.",
     ["Dedicate", "Dedication", "Devoted"], ["Devoted", "Committed", "Zealous", "Assiduous", "Allocated"], ["Apathetic", "Disloyal", "Uncommitted"],
     "She is a dedicated pediatric nurse who works tirelessly to comfort sick children and their parents.",
     "The new hospital wing contains dedicated research suites for clinical genomic cancer trials."),

    ("Defend", "verb", "B1", "/dɪˈfend/", "mempertahankan diri / membela hak di pengadilan",
     "Melindungi dari serangan fisik; membela posisi argumen.", "To protect from harm or attack; speak in support of.",
     ["Defense", "Defender", "Defensive"], ["Protect", "Shield", "Guard", "Champion", "Uphold"], ["Attack", "Assail", "Abandon", "Surrender"],
     "Legal advocates stand before the high court to defend the constitutional rights of vulnerable citizens.",
     "Soldiers were deployed to defend the fortified mountain pass against advancing hostile forces."),

    ("Define", "verb", "B1", "/dɪˈfaɪn/", "mendefinisikan arti / menetapkan batas jelas",
     "Menjelaskan makna tepat dari suatu kata; menggariskan batas.", "To state or describe exactly the nature, scope, or meaning of.",
     ["Definition", "Definite", "Definitive"], ["Explain", "Clarify", "Specify", "Characterize", "Delineate"], ["Confuse", "Obscure", "Distort"],
     "Dictionaries define words by providing precise grammatical categories, pronunciations, and contextual meanings.",
     "The national boundary treaty helped define territorial fishing zones along the disputed ocean strait."),

    ("Definite", "adjective", "B1", "/ˈdef.ɪ.nət/", "pasti / jelas tak diragukan / tegas",
     "Jelas dan pasti; bebas dari segala keraguan.", "Clearly stated or decided; not vague or doubtful.",
     ["Definitely", "Definition", "Certain"], ["Certain", "Sure", "Clear-cut", "Specific", "Decisive"], ["Indefinite", "Vague", "Uncertain", "Ambiguous"],
     "The research team has a definite timetable for completing the initial laboratory drug screening.",
     "She gave a definite 'yes' when offered the opportunity to lead the overseas environmental project."),

    ("Delay", "verb", "B1", "/dɪˈleɪ/", "menunda jadwal / memperlambat laju / mengulur waktu",
     "Membuat sesuatu terjadi lebih lambat dari jadwal yang direncanakan.", "To make someone or something late or slow; postpone action.",
     ["Delay", "Delayed", "Postpone"], ["Postpone", "Defer", "Suspend", "Retard", "Hinder"], ["Expedite", "Accelerate", "Hasten", "Advance"],
     "Heavy snowfall and icy runways forced the airline to delay all morning international departures.",
     "Do not delay seeking medical attention if you experience severe sudden chest pain or shortness of breath."),

    ("Deliberate", "adjective", "B2", "/dɪˈlɪb.ər.ət/", "disengaja / penuh pertimbangan matang",
     "Dilakukan dengan sadar dan terencana; tenang penuh kehati-hatian.", "Done consciously and intentionally; careful and unhurried.",
     ["Deliberately", "Deliberation", "Intentional"], ["Intentional", "Planned", "Premeditated", "Calculated", "Thoughtful"], ["Accidental", "Unintentional", "Hasty", "Impulsive"],
     "The author made a deliberate stylistic choice to write the novel entirely in the present tense.",
     "Her slow and deliberate speech gave listeners the impression of deep philosophical wisdom."),

    ("Deliver", "verb", "B1", "/dɪˈlɪv.ər/", "mengantarkan barang / menyampaikan pidato / melahirkan",
     "Membawa barang ke alamat tujuan; menyampaikan ceramah; menepati janji.", "To bring goods to a recipient; launch a speech; fulfill a promise.",
     ["Delivery", "Deliverance", "Transport"], ["Transport", "Distribute", "Present", "Fulfill", "Convey"], ["Withhold", "Retain", "Keep back"],
     "The courier service will deliver the confidential legal documents before five in the afternoon.",
     "The university chancellor stepped up to the podium to deliver an inspiring commencement address."),

    ("Demand", "noun", "B1", "/dɪˈmɑːnd/", "permintaan pasar / tuntutan tegas / desakan",
     "Tuntutan yang harus dipenuhi; kebutuhan pembeli akan barang.", "An insistent and peremptory request; consumer desire for goods.",
     ["Demanding", "Request", "Requirement"], ["Requirement", "Claim", "Request", "Need", "Market desire"], ["Surplus", "Supply", "Offer"],
     "Global demand for electric vehicles has surged dramatically as battery technologies improve.",
     "Labor union delegates presented a formal demand for safer factory operating conditions and fair wages."),

    ("Demonstrate", "verb", "B1", "/ˈdem.ən.streɪt/", "mendemonstrasikan / memperagakan cara kerja / membuktikan",
     "Menunjukkan dengan jelas melalui bukti atau peragaan nyata.", "To clearly show the existence or truth of something by giving proof; show how something works.",
     ["Demonstration", "Demonstrator", "Exhibit"], ["Show", "Prove", "Exhibit", "Display", "Manifest"], ["Conceal", "Hide", "Disprove", "Refute"],
     "The chemistry professor conducted an experiment to demonstrate the chemical reaction between acid and base.",
     "Thousands of peaceful citizens gathered in the city square to demonstrate for civil rights and democratic reforms."),

    ("Deny", "verb", "B1", "/dɪˈnaɪ/", "menyangkal tuduhan / menolak memberi izin",
     "Menyatakan bahwa tuduhan tidak benar; menolak memberikan sesuatu.", "To state that one refuses to admit the truth; refuse to give something requested.",
     ["Denial", "Deniable", "Refuse"], ["Refute", "Disown", "Reject", "Dispute", "Withhold"], ["Admit", "Acknowledge", "Confirm", "Grant"],
     "The corporate spokesperson stepped before cameras to deny all allegations of financial impropriety.",
     "Authoritarian regimes often deny independent journalists access to critical public health records."),

    ("Department", "noun", "A2", "/dɪˈpɑːt.mənt/", "departemen / divisi bagian kantor / jurusan kampus",
     "Divisi khusus dalam organisasi besar, universitas, atau pemerintahan.", "A specialized division of a large organization, government, or university.",
     ["Departmental", "Division", "Section"], ["Division", "Section", "Branch", "Bureau", "Faculty"], ["Whole"],
     "She works as a senior researcher in the university department of biomedical engineering.",
     "The human resources department scheduled quarterly professional training workshops for all staff."),

    ("Depend", "verb", "A2", "/dɪˈpend/", "bergantung pada / mengandalkan pertolongan",
     "Ditentukan oleh kondisi lain; mempercayai bantuan seseorang.", "To be controlled or determined by; rely on with trust.",
     ["Dependent", "Dependence", "Reliable"], ["Rely", "Count on", "Hinge on", "Lean on", "Trust"], ["Distrust", "Independent"],
     "Agricultural crop yields depend heavily on seasonal monsoon rainfall and fertile soil conditions.",
     "Elderly community members often depend on home health aides for daily mobility assistance."),

    ("Depict", "verb", "B2", "/dɪˈpɪkt/", "menggambarkan lukisan / melukiskan watak cerita",
     "Mewakili dalam bentuk lukisan, gambar, atau kata-kata dalam cerita.", "To represent by a drawing, painting, or other art form; portray in words.",
     ["Depiction", "Depicted", "Portray"], ["Portray", "Represent", "Illustrate", "Paint", "Delineate"], ["Distort", "Misrepresent", "Conceal"],
     "Renaissance fresco murals frequently depict classical mythological legends and biblical parables.",
     "The historical novel managed to depict the everyday struggles of working-class families with moving accuracy."),

    ("Deposit", "noun", "B1", "/dɪˈpɒz.ɪt/", "setoran uang / uang muka jaminan / endapan mineral",
     "Uang yang disetor ke bank; uang jaminan; lapisan mineral alami.", "A sum of money placed in a bank; a security payment; a layer of substance.",
     ["Depositor", "Deposit", "Payment"], ["Savings", "Down payment", "Sediment", "Accumulation", "Installment"], ["Withdrawal"],
     "Tenants must pay a security deposit equal to one month's rent before moving into the apartment.",
     "Geologists discovered a rich subterranean deposit of lithium ore in the desert plateau."),

    ("Describe", "verb", "A1", "/dɪˈskraɪb/", "mendeskripsikan / menggambarkan ciri-ciri",
     "Memberikan penjelasan terperinci mengenai rupa atau watak sesuatu.", "To give a detailed account in words of someone or something.",
     ["Description", "Descriptive", "Portray"], ["Portray", "Characterize", "Detail", "Narrate", "Recount"], ["Misrepresent", "Obscure"],
     "Can you describe the visual features of the missing backpack to the airport lost-and-found desk?",
     "Biologists describe newly discovered insect species by cataloging wing morphology and DNA barcodes."),

    ("Description", "noun", "A2", "/dɪˈskrɪp.ʃən/", "deskripsi / uraian gambaran rinci",
     "Uraian lisan atau tulisan yang menggambarkan rincian suatu hal.", "A spoken or written representation of a person, object, or event.",
     ["Describe", "Descriptive", "Account"], ["Account", "Portrayal", "Explanation", "Profile", "Characterization"], ["Concealment"],
     "The job description clearly lists the required educational qualifications and programming language proficiencies.",
     "Police detectives released an eyewitness description of the suspect to the local news media."),

    ("Deserve", "verb", "B1", "/dɪˈzɜːv/", "layak mendapatkan / pantas menerima penghargaan",
     "Pantas memperoleh imbalan atau hukuman karena perbuatan atau mutunya.", "To do something or have qualities worthy of reward, punishment, or attention.",
     ["Deserving", "Deservedly", "Merit"], ["Merit", "Earn", "Warrant", "Rate", "Be entitled to"], ["Forfeit", "Lose"],
     "Athletes who train diligently for years deserve the honor of representing their nation at the Olympics.",
     "Every human being deserves equal dignity, fundamental civil rights, and respectful medical treatment."),

    ("Design", "noun", "A1", "/dɪˈzaɪn/", "desain / rancangan arsitektur / pola gambar",
     "Rencana atau gambar yang dibuat untuk menunjukkan tampilan dan fungsi objek.", "A plan or drawing produced to show the look and function of an object.",
     ["Designer", "Designate", "Pattern"], ["Blueprint", "Plan", "Pattern", "Layout", "Concept"], ["Disorder", "Chaos"],
     "The minimalist design of the smartphone emphasizes intuitive touchscreen navigation and sleek aesthetics.",
     "Architectural design competitions encourage students to submit innovative sustainable housing blueprints."),

    ("Desire", "noun", "B1", "/dɪˈzaɪər/", "hasrat kuat / keinginan mendalam / idaman",
     "Perasaan ingin memiliki atau melakukan sesuatu secara kuat.", "A strong feeling of wanting to have something or wishing for something to happen.",
     ["Desirable", "Desirous", "Wish"], ["Wish", "Craving", "Aspiration", "Longing", "Yearning"], ["Aversion", "Dislike", "Indifference"],
     "She possessed a passionate desire to master the art of classical ballet from a young age.",
     "Educators cultivate students' natural desire for intellectual curiosity through hands-on laboratory experiments."),

    ("Despair", "noun", "B2", "/dɪˈspeər/", "keputusasaan / hilangnya seluruh harapan",
     "Perasaan kehilangan seluruh harapan dan merasa tidak berdaya.", "The complete loss or absence of hope.",
     ["Desperate", "Desperately", "Hopelessness"], ["Hopelessness", "Despondency", "Depression", "Gloom", "Anguish"], ["Hope", "Optimism", "Joy", "Cheer"],
     "In moments of deep personal despair, supportive friends and counselors offer vital emotional solace.",
     "The refugees refused to succumb to despair, clinging to the resilient hope of rebuilding their lives."),

    ("Destroy", "verb", "A2", "/dɪˈstrɔɪ/", "menghancurkan / membinasakan / memusnahkan",
     "Merusak sesuatu hingga hancur berkeping-keping atau tidak berfungsi lagi.", "To end the existence of something by damaging or attacking it.",
     ["Destruction", "Destructive", "Demolish"], ["Demolish", "Ruin", "Wreck", "Devastate", "Annihilate"], ["Construct", "Build", "Create", "Restore"],
     "Wildfires can destroy vast swathes of pine forests and residential neighborhoods in hours.",
     "Misinformation campaigns deliberately aim to destroy public trust in verified scientific institutions."),

    ("Detail", "noun", "A2", "/ˈdiː.teɪl/", "detail / rincian unsur kecil / butir uraian",
     "Unsur atau bagian kecil tersendiri dari suatu objek, cerita, atau rencana.", "An individual feature, fact, or item in a larger whole.",
     ["Detailed", "Detailedly", "Particular"], ["Particular", "Feature", "Specific", "Facet", "Component"], ["Whole", "Generalization"],
     "The artisan hand-carved intricate floral details into the oak wood dining table frame.",
     "Pay close attention to every technical detail when formatting citations according to academic publication guidelines.")
]

print(f"Loaded {len(WORDS_A_D)} words in A-D list")
