#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Oxford 3000 & 5000 - Part 2: Letters E - L (260 words)"""

PART2_WORDS = [
    # E
    ("Eager", "adjective", "B1", "/ˈiː.ɡər/", "sangat bersemangat / antusias / tidak sabar",
     "Sangat menginginkan sesuatu atau sangat bersemangat untuk melakukan tindakan.", "Wanting to do or have something very much; characterized by keen interest.",
     ["Eagerness", "Eagerly", "Keen"], ["Keen", "Enthusiastic", "Avid", "Impatient", "Fervent"], ["Reluctant", "Indifferent", "Apathetic", "Hesitant"],
     "The students were eager to explore the interactive exhibits at the science museum.",
     "Investors were eager to participate in the renewable energy funding round following promising pilot results."),

    ("Earnest", "adjective", "B2", "/ˈɜː.nɪst/", "sungguh-sungguh / tulus / bersungguh hati",
     "Menunjukkan niat yang tulus, serius, dan jujur tanpa kepalsuan.", "Resulting from or showing sincere and intense conviction.",
     ["Earnestly", "Earnestness", "Sincere"], ["Sincere", "Heartfelt", "Grave", "Serious", "Devout"], ["Frivolous", "Insincere", "Flippant", "Casual"],
     "He made an earnest plea to the community council to protect the endangered wetlands.",
     "Her earnest commitment to human rights advocacy earned her deep respect among international delegates."),

    ("Eccentric", "adjective", "B2", "/ɪkˈsen.trɪk/", "eksentrik / aneh tapi unik / ganjil",
     "Memiliki kebiasaan, perilaku, atau penampilan yang tidak lazim namun menarik.", "Unconventional and slightly strange; deviating from standard norms.",
     ["Eccentricity", "Eccentrically", "Quirky"], ["Unconventional", "Quirky", "Odd", "Peculiar", "Bizarre"], ["Conventional", "Ordinary", "Normal", "Standard"],
     "The eccentric inventor filled his workshop with clockwork contraptions and vintage telescopes.",
     "Although considered eccentric by contemporaries, her avant-garde painting techniques influenced modern art deeply."),

    ("Eclipse", "verb", "C1", "/ɪˈklɪps/", "mengaburkan / melampaui / mengungguli / gerhana",
     "Menghalangi cahaya; membuat prestasi orang lain tampak kurang penting karena jauh lebih unggul.", "To obscure light; to surpass or overshadow in importance, reputation, or quality.",
     ["Eclipsing", "Overshadow", "Surpass"], ["Overshadow", "Surpass", "Outshine", "Dominate", "Exceed"], ["Enhance", "Illuminate", "Highlight"],
     "Her stellar athletic performance managed to eclipse all previous national marathon records.",
     "The sudden technological breakthrough threatened to eclipse earlier research models in molecular biology."),

    ("Economical", "adjective", "B1", "/ˌiː.kəˈnɒm.ɪ.kəl/", "hemat / efisien / ekonomis",
     "Menggunakan sedikit uang, waktu, atau sumber daya tanpa pemborosan.", "Giving good value or return in relation to the money, time, or effort expended.",
     ["Economics", "Economize", "Frugal"], ["Frugal", "Thrifty", "Cost-effective", "Prudent", "Resourceful"], ["Wasteful", "Extravagant", "Expensive"],
     "Hybrid compact cars provide an economical transportation option for daily city commuters.",
     "The architect designed an economical heating layout using geothermal insulation to minimize utility bills."),

    ("Edge", "noun", "B1", "/edʒ/", "tepi / pinggiran / keunggulan kompetitif",
     "Bagian paling luar atau pinggir; keunggulan atas pihak lain.", "The outside limit of an object, surface, or area; a competitive advantage.",
     ["Edgy", "Border", "Advantage"], ["Border", "Brink", "Margin", "Perimeter", "Advantage"], ["Center", "Middle", "Disadvantage"],
     "He stood at the edge of the rocky cliff, gazing at the crashing Atlantic ocean waves.",
     "Fluency in three languages gave the young candidate a decisive edge during international job interviews."),

    ("Edible", "adjective", "B2", "/ˈed.ə.bəl/", "dapat dimakan / layak konsumsi",
     "Aman dan cocok untuk dimakan manusia tanpa menimbulkan racun.", "Fit or suitable to be eaten; non-toxic and digestible.",
     ["Eatable", "Inedible", "Consumable"], ["Eatable", "Consumable", "Nourishing", "Digestible"], ["Inedible", "Poisonous", "Toxic"],
     "Foragers must undergo expert botanical training to distinguish edible wild mushrooms from toxic species.",
     "The gourmet pastry chef decorated the wedding cake with delicate edible gold leaf flakes."),

    ("Editorial", "noun", "B2", "/ˌed.ɪˈtɔː.ri.əl/", "tajuk rencana / editorial / opini redaksi",
     "Artikel surat kabar yang menyuarakan pendapat resmi dari dewan redaksi.", "A newspaper article written by or on behalf of an editor that gives an opinion on a topical issue.",
     ["Editor", "Edit", "Op-ed"], ["Opinion piece", "Commentary", "Leading article", "Review"], ["News report", "Factual column"],
     "The weekend newspaper published a fiery editorial advocating for comprehensive municipal transport reforms.",
     "Journalism students analyze classic editorial columns to study techniques of persuasive political writing."),

    ("Efficiency", "noun", "B1", "/ɪˈfɪʃ.ən.si/", "efisiensi / ketepatan guna / kedayagunaan",
     "Kemampuan mencapai hasil terbaik tanpa menyia-nyiakan waktu atau energi.", "The state or quality of being efficient; achieving maximum productivity with minimum wasted effort.",
     ["Efficient", "Efficiently", "Productivity"], ["Productivity", "Competence", "Efficacy", "Streamlining"], ["Inefficiency", "Wastefulness", "Incompetence"],
     "Upgrading to LED light bulbs significantly improved energy efficiency across all university buildings.",
     "Software developers conduct code refactoring sessions to optimize server processing speed and resource efficiency."),

    ("Elaborate", "adjective", "B2", "/ɪˈlæb.ər.ət/", "rumit mendetail / terperinci / dipersiapkan teliti",
     "Melibatkan banyak detail, bagian yang saling terkait, atau persiapan teliti.", "Involving many carefully arranged parts or details; detailed and complicated in design.",
     ["Elaborately", "Elaboration", "Intricate"], ["Intricate", "Detailed", "Complex", "Ornate", "Sophisticated"], ["Simple", "Plain", "Basic", "Rudimentary"],
     "The museum curator unveiled an elaborate scale model of the ancient Roman forum.",
     "Security personnel detected an elaborate counterfeit banking scheme orchestrated by international cybercriminals."),

    ("Elastic", "adjective", "B2", "/ɪˈlæs.tɪk/", "elastis / lentur / kenyal / fleksibel",
     "Mampu kembali ke bentuk semula setelah ditarik; fleksibel beradaptasi.", "Able to resume its normal shape spontaneously after contraction, dilatation, or distortion.",
     ["Elasticity", "Flexibility", "Resilient"], ["Flexible", "Supple", "Pliable", "Springy", "Resilient"], ["Rigid", "Stiff", "Inflexible"],
     "The athlete wore an elastic compression sleeve around her knee to provide joint stability during sprints.",
     "In microeconomics, price elastic demand refers to consumer purchasing habits that shift markedly when prices change."),

    ("Eligible", "adjective", "B2", "/ˈel.ɪ.dʒə.bəl/", "memenuhi syarat / berhak terpilih / layak",
     "Memiliki kualifikasi yang tepat atau memenuhi persyaratan yang ditentukan.", "Having the right to do or obtain something; satisfying the appropriate conditions.",
     ["Eligibility", "Ineligible", "Qualified"], ["Qualified", "Entitled", "Suitable", "Permitted", "Fit"], ["Ineligible", "Disqualified", "Unsuitable"],
     "Undergraduate students with a grade point average above 3.8 are eligible to apply for the prestigious scholarship.",
     "Only registered citizens aged eighteen and older are eligible to cast ballots in the presidential election."),

    ("Eliminate", "verb", "B1", "/ɪˈlɪm.ɪ.neɪt/", "mengeliminasi / menyingkirkan / menghapus tuntas",
     "Menghilangkan atau menyingkirkan sepenuhnya suatu masalah atau hambatan.", "Completely remove or get rid of something unwanted.",
     ["Elimination", "Eliminated", "Remove"], ["Remove", "Eradicate", "Abolish", "Expel", "Extinguish"], ["Introduce", "Retain", "Keep", "Create"],
     "The public health vaccination initiative aims to eliminate indigenous transmission of polio globally.",
     "Regular software updates help eliminate security vulnerabilities and protect users against spyware threats."),

    ("Elusive", "adjective", "C1", "/iˈluː.sɪv/", "sukar ditangkap / sulit dipahami / misterius",
     "Sukar ditemukan, diingat, dipahami, atau ditangkap.", "Difficult to find, catch, achieve, or remember.",
     ["Elude", "Elusiveness", "Evasive"], ["Evasive", "Fugitive", "Subtle", "Inaccessible", "Baffling"], ["Accessible", "Obvious", "Attainable", "Direct"],
     "A definitive cure for the autoimmune disorder remained elusive despite decades of intensive laboratory trials.",
     "The snow leopard is an elusive feline predator that roams the remote rocky peaks of Central Asia."),

    ("Embark", "verb", "B2", "/ɪmˈbɑːk/", "memulai perjalanan baru / menaiki kapal",
     "Menaiki kapal atau pesawat; memulai suatu petualangan atau proyek besar.", "To go on board a ship, aircraft, or vehicle; to start a new journey or venture.",
     ["Embarkation", "Disembark", "Begin"], ["Begin", "Commence", "Launch", "Board", "Undertake"], ["Disembark", "Finish", "Conclude", "Terminate"],
     "After completing her medical degree, she was ready to embark on a career in humanitarian public health.",
     "Passengers were instructed to have their boarding passes ready before they embark on the cross-channel ferry."),

    ("Embarrass", "verb", "B1", "/ɪmˈbær.əs/", "mempermalukan / membuat canggung atau tersipu",
     "Menyebabkan seseorang merasa canggung, malu, atau tidak nyaman di hadapan orang lain.", "To cause someone to feel awkward, self-conscious, or ashamed.",
     ["Embarrassment", "Embarrassing", "Humiliate"], ["Humiliate", "Shame", "Fluster", "Disconcert", "Abash"], ["Honor", "Praise", "Compliment", "Comfort"],
     "Please do not embarrass your younger brother in front of his classmates by sharing old baby photos.",
     "The politician tried to laugh off the humorous teleprompter malfunction without letting it embarrass him on live television."),

    ("Embrace", "verb", "B2", "/ɪmˈbreɪs/", "merangkul / menyambut hangat ide / mendekap",
     "Memeluk seseorang dengan penuh kasih; menerima ide atau perubahan dengan antusias.", "To hold someone closely in one's arms; to accept or support an idea or belief willingly.",
     ["Embracing", "Hug", "Adopt"], ["Hug", "Welcome", "Adopt", "Accept", "Encompass"], ["Reject", "Spurn", "Shun", "Exclude"],
     "Progressive educators encourage school administrators to embrace modern digital learning technologies.",
     "The long-separated siblings ran toward each other on the airport platform and shared a tearful embrace."),

    ("Emerge", "verb", "B1", "/ɪˈmɜːdʒ/", "muncul ke permukaan / timbul / terungkap",
     "Keluar dari tempat tersembunyi; menjadi jelas atau terkenal setelah melalui proses.", "To move out of or away from something and become visible; to become apparent.",
     ["Emergence", "Emergent", "Appear"], ["Appear", "Surface", "Arise", "Materialize", "Emanate"], ["Disappear", "Vanish", "Submerge", "Fade"],
     "The butterfly takes several minutes to dry its delicate wings after it emerges from the protective chrysalis.",
     "Exciting new clinical evidence continues to emerge regarding the cognitive benefits of aerobic exercise."),

    ("Emission", "noun", "B1", "/iˈmɪʃ.ən/", "emisi gas / pancaran zat / pengeluaran limbah",
     "Pelepasan gas, polutan, atau radiasi ke atmosfer atau lingkungan.", "The production and discharge of something, especially gas, heat, or radiation.",
     ["Emit", "Emitter", "Discharge"], ["Discharge", "Release", "Exhalation", "Radiation", "Exhaust"], ["Absorption", "Containment", "Retention"],
     "The international climate conference established binding targets to curb greenhouse gas emissions by 2030.",
     "Automakers are accelerating the transition to electric platforms to achieve zero tailpipe emission standards."),

    ("Emotion", "noun", "A2", "/ɪˈməʊ.ʃən/", "emosi / perasaan hati / getaran jiwa",
     "Perasaan naluriah yang kuat seperti kegembiraan, kesedihan, kemarahan, atau cinta.", "A natural instinctive state of mind deriving from one's circumstances, mood, or relationships.",
     ["Emotional", "Emotionally", "Feeling"], ["Feeling", "Sentiment", "Passion", "Sensation", "Affect"], ["Apathy", "Indifference", "Coldness"],
     "Her voice trembled with deep emotion as she expressed gratitude to the rescue workers who saved her family.",
     "Cognitive behavioral therapy helps individuals understand the interplay between thoughts, behaviors, and emotions."),

    ("Emphasis", "noun", "B2", "/ˈem.fə.sɪs/", "penekanan / titik berat perhatian / aksen",
     "Perhatian khusus atau nilai penting yang diberikan pada suatu gagasan atau bagian kata.", "Special importance, value, or prominence given to something; stress given to a syllable.",
     ["Emphasize", "Emphatic", "Stress"], ["Stress", "Priority", "Weight", "Focus", "Prominence"], ["Understatement", "Neglect", "Indifference"],
     "The new curriculum places strong emphasis on practical problem-solving and computer programming skills.",
     "In English pronunciation, shifting the syllable emphasis can change a word from a noun to a verb."),

    ("Empire", "noun", "B1", "/ˈem.paɪər/", "kekaisaran / imperium / kerajaan besar",
     "Sekelompok wilayah atau bangsa besar yang diperintah oleh seorang kaisar atau kekuasaan tunggal.", "An extensive group of states or countries ruled over by a single monarch or supreme authority.",
     ["Emperor", "Empress", "Imperial"], ["Realm", "Kingdom", "Dominion", "Sovereignty", "Dynasty"], ["Democracy", "Republic"],
     "The Roman Empire expanded across the Mediterranean basin, building paved roads, aqueducts, and legal codes.",
     "The corporate media empire encompassed global television networks, daily broadsheet newspapers, and digital portals."),

    ("Empower", "verb", "B2", "/ɪmˈpaʊ.ər/", "memberdayakan / memberi wewenang kekuasaan",
     "Memberi seseorang kekuasaan, wewenang, atau kepercayaan diri untuk mengendalikan hidupnya.", "To give someone the authority or power to do something; make someone stronger and more confident.",
     ["Empowerment", "Empowered", "Authorize"], ["Authorize", "Enable", "Equip", "Liberate", "Strengthen"], ["Disenfranchise", "Weaken", "Constrain", "Oppress"],
     "Microfinance lending initiatives empower rural women entrepreneurs to establish independent artisan businesses.",
     "The school leadership council was formed to empower students to make meaningful decisions regarding campus activities."),

    ("Enact", "verb", "C1", "/ɪnˈækt/", "memberlakukan undang-undang / memerankan drama",
     "Mengesahkan rancangan menjadi hukum resmi; mementaskan peristiwa di atas panggung.", "To make a bill or other proposal into law; to perform a story or play on stage.",
     ["Enactment", "Legislative", "Pass"], ["Pass", "Legislate", "Establish", "Sanction", "Perform"], ["Repeal", "Revoke", "Abolish", "Cancel"],
     "Parliament moved swiftly to enact comprehensive data privacy protections for online consumers.",
     "History reenactors gather every summer to enact famous decisive battles from the revolutionary war."),

    ("Encounter", "verb", "B1", "/ɪnˈkaʊn.tər/", "menemui masalah / berpapasan / menghadapi kendala",
     "Menghadapi sesuatu secara tak terduga; berpapasan dengan seseorang.", "To unexpectedly experience or be faced with something difficult; to meet someone unexpectedly.",
     ["Encounter", "Meeting", "Confront"], ["Confront", "Face", "Meet", "Run into", "Experience"], ["Avoid", "Evade", "Dodge", "Escape"],
     "Hikers may encounter sudden changes in alpine weather, so packing waterproof gear is mandatory.",
     "During field research in the Amazon basin, the expedition team encountered several undocumented insect species."),

    ("Encourage", "verb", "A2", "/ɪnˈkʌr.ɪdʒ/", "mendorong semangat / memberi motivasi / menganjurkan",
     "Memberikan harapan, keberanian, atau kepercayaan diri kepada seseorang untuk berbuat baik.", "To give support, confidence, or hope to someone; to stimulate the development of an activity.",
     ["Encouragement", "Encouraging", "Motivate"], ["Motivate", "Inspire", "Cheer", "Support", "Promote"], ["Discourage", "Deter", "Dishearten", "Impede"],
     "Teachers should encourage students to ask questions whenever they feel confused about complex topics.",
     "Urban planners encourage cycling by constructing dedicated, illuminated bike lanes across the city center."),

    ("Endeavor", "noun", "B2", "/ɪnˈdev.ər/", "upaya keras / usaha sungguh-sungguh / ikhtiar",
     "Usaha terencana dan sungguh-sungguh yang menuntut kerja keras demi meraih cita-cita.", "An enterprise, undertaking, or strenuous effort directed toward achieving a specific goal.",
     ["Endeavor", "Strive", "Undertaking"], ["Enterprise", "Undertaking", "Effort", "Pursuit", "Venture"], ["Inaction", "Passivity", "Neglect"],
     "Developing reusable space exploration rockets is a remarkable multi-decade scientific endeavor.",
     "We wish you the greatest success and fulfillment in all your future professional endeavors and research."),

    ("Endorse", "verb", "B2", "/ɪnˈdɔːs/", "mendukung resmi / mengesahkan / mengiklankan produk",
     "Menyatakan persetujuan resmi terhadap tokoh/kebijakan; menandatangani cek.", "To declare one's public approval or support of; recommend a product in an advertisement.",
     ["Endorsement", "Endorser", "Approve"], ["Support", "Back", "Sanction", "Approve", "Promote"], ["Oppose", "Reject", "Disapprove", "Denounce"],
     "Several prominent Nobel laureates stepped forward to endorse the international treaty on artificial intelligence safety.",
     "Professional tennis stars sign lucrative sponsorship contracts to endorse footwear and athletic apparel globally."),

    ("Endure", "verb", "B2", "/ɪnˈdʒʊər/", "bertahan menghadapi penderitaan / berlangsung lama",
     "Menanggung masa-masa sulit atau rasa sakit dengan tabah; tetap bertahan melintasi waktu.", "To suffer something painful or difficult patiently; to remain in existence or last.",
     ["Endurance", "Enduring", "Tolerate"], ["Tolerate", "Withstand", "Survive", "Persevere", "Persist"], ["Succumb", "Surrender", "Perish", "Collapse"],
     "Marathon competitors must endure intense physical fatigue during the final miles of the course.",
     "The ancient stone monuments of Borobudur continue to endure through centuries of volcanic ash and tropical rainstorms."),

    ("Energy", "noun", "A2", "/ˈen.ə.dʒi/", "energi / tenaga daya / daya listrik",
     "Kekuatan fisik dan mental untuk beraktivitas; daya tenaga seperti listrik, panas, atau angin.", "The strength and vitality required for sustained activity; power derived from physical resources.",
     ["Energetic", "Energize", "Power"], ["Vigor", "Vitality", "Power", "Force", "Dynamism"], ["Lethargy", "Fatigue", "Weakness", "Inertia"],
     "Children radiate boundless energy when playing outdoors in the warm sunshine during recess.",
     "Renewable solar and wind energy installations are replacing fossil fuels across national electrical grids."),

    ("Enforce", "verb", "B2", "/ɪnˈfɔːs/", "menegakkan hukum / memaksakan kepatuhan aturan",
     "Memastikan bahwa hukum atau peraturan ditaati dan dijalankan dengan tegas.", "To compel observance of or compliance with a law, rule, or obligation.",
     ["Enforcement", "Enforceable", "Implement"], ["Implement", "Administer", "Execute", "Impose", "Apply"], ["Ignore", "Disregard", "Waive", "Repeal"],
     "Traffic police officers use automated radar cameras to enforce highway speed restrictions.",
     "Regulatory authorities inspect food processing facilities regularly to enforce sanitary standards rigorously."),

    ("Engage", "verb", "B2", "/ɪnˈɡeɪdʒ/", "melibatkan diri / memikat perhatian / bertunangan",
     "Berpartisipasi aktif dalam kegiatan; menarik minat seseorang; menyewa jasa.", "To participate or become involved in; attract someone's interest or attention; promise to marry.",
     ["Engagement", "Engaged", "Involve"], ["Participate", "Involve", "Absorb", "Employ", "Enlist"], ["Disengage", "Withdraw", "Ignore", "Bore"],
     "Interactive classroom simulations engage students actively in historical inquiry and debate.",
     "The couple announced their decision to engage after five years of close university companionship."),

    ("Enhance", "verb", "B2", "/ɪnˈhɑːns/", "meningkatkan mutu / memperindah / menambah daya tarik",
     "Meningkatkan kualitas, nilai, atau daya tarik sesuatu menjadi lebih baik.", "To intensify, increase, or further improve the quality, value, or extent of.",
     ["Enhancement", "Enhanced", "Improve"], ["Improve", "Augment", "Elevate", "Boost", "Enrich"], ["Diminish", "Impair", "Degrade", "Lessen"],
     "Adding fresh rosemary and roasted garlic will enhance the rich aroma and flavor of the vegetable soup.",
     "Continuing professional education courses enhance an employee's career advancement prospects significantly."),

    ("Enormous", "adjective", "B1", "/ɪˈnɔː.məs/", "sangat besar / luar biasa dahsyat / masif",
     "Memiliki ukuran, jumlah, atau skala yang luar biasa besar dan spektakuler.", "Very large in size, quantity, or extent; huge and impressive.",
     ["Enormously", "Enormity", "Gigantic"], ["Huge", "Gigantic", "Colossal", "Immense", "Massive"], ["Tiny", "Minute", "Minuscule", "Small"],
     "The construction of the transcontinental railway required an enormous investment of labor and capital.",
     "The blue whale is an enormous marine mammal that can reach lengths of over thirty meters in polar oceans."),

    ("Ensure", "verb", "B1", "/ɪnˈʃɔːr/", "memastikan / menjamin kepastian keselamatan",
     "Melakukan tindakan agar sesuatu pasti terjadi atau aman dari risiko kegagalan.", "To make certain that something will occur or be the case; guarantee.",
     ["Sure", "Assure", "Guarantee"], ["Guarantee", "Secure", "Confirm", "Safeguard", "Assure"], ["Jeopardize", "Endanger", "Neglect"],
     "Inspect all climbing harnesses and ropes thoroughly to ensure complete safety before ascending the cliff.",
     "Public health guidelines are designed to ensure clean drinking water standards for every municipality."),

    ("Enterprise", "noun", "B2", "/ˈen.tə.praɪz/", "perusahaan bisnis / inisiatif usaha / keberanian bertindak",
     "Proyek bisnis atau usaha niaga; keberanian mengambil inisiatif dan risiko baru.", "A project or undertaking, typically one that is difficult; a business or company.",
     ["Enterprising", "Entrepreneur", "Business"], ["Venture", "Business", "Company", "Endeavor", "Initiative"], ["Inaction", "Passivity", "Stagnation"],
     "Launching an independent artisanal roastery was a bold business enterprise for the young entrepreneurs.",
     "The space agency partnered with private technology enterprises to build satellite communication arrays."),

    ("Enthusiasm", "noun", "B1", "/ɪnˈθjuː.zi.æz.əm/", "antusiasme / semangat berkobar / kegairahan",
     "Minat yang sangat besar dan kegembiraan yang tulus terhadap suatu kegiatan.", "Intense and eager enjoyment, interest, or approval for a topic or pursuit.",
     ["Enthusiastic", "Enthusiast", "Zeal"], ["Zeal", "Passion", "Ardor", "Eagerness", "Fervor"], ["Apathy", "Indifference", "Lethargy", "Boredom"],
     "The children participated with boundless enthusiasm in the annual school botanical science fair.",
     "Her genuine enthusiasm for Renaissance classical music was infectious to everyone in the choir."),

    ("Entity", "noun", "C1", "/ˈen.tə.ti/", "entitas / kesatuan mandiri / wujud badan hukum",
     "Sesuatu yang memiliki keberadaan nyata dan mandiri, seperti perusahaan atau institusi.", "A thing with distinct and independent existence; an organization treated as a unit.",
     ["Entities", "Existence", "Unit"], ["Unit", "Organization", "Body", "Institution", "Organism"], ["Nonentity", "Nothingness"],
     "Under commercial law, a registered corporation is treated as a separate legal entity from its founders.",
     "Researchers discovered that the coral reef functions as a single interconnected ecological entity."),

    ("Environment", "noun", "A2", "/ɪnˈvaɪ.rən.mənt/", "lingkungan hidup / alam sekitar / suasana kerja",
     "Kondisi alam sekitar manusia, hewan, dan tumbuhan; situasi tempat seseorang berada.", "The surroundings or conditions in which a person, animal, or plant lives or operates.",
     ["Environmental", "Environmentally", "Surroundings"], ["Surroundings", "Habitat", "Ecosystem", "Atmosphere", "Setting"], ["N/A"],
     "We have a moral and civic responsibility to protect our natural environment from plastic pollution.",
     "A supportive and inclusive workplace environment boosts employee morale and innovative collaboration."),

    ("Envisage", "verb", "C1", "/ɪnˈvɪz.ɪdʒ/", "membayangkan rencana / memproyeksikan masa depan",
     "Membayangkan atau merencanakan sesuatu sebagai kemungkinan yang akan terjadi di masa depan.", "To contemplate or conceive of as a possibility or a desirable future event.",
     ["Vision", "Envision", "Conceive"], ["Envision", "Imagine", "Foresee", "Conceive", "Anticipate"], ["Ignore", "Overlook"],
     "Urban architects envisage a future city powered entirely by zero-emission renewable energy sources.",
     "The development plan envisages the construction of three new university research laboratories by 2030."),

    ("Epidemic", "noun", "B2", "/ˌep.ɪˈdem.ɪk/", "wabah epidemi / penularan penyakit massal",
     "Penyebaran penyakit menular yang meluas secara cepat dalam suatu populasi masyarakat.", "A widespread occurrence of an infectious disease in a community at a particular time.",
     ["Epidemiology", "Pandemic", "Outbreak"], ["Outbreak", "Plague", "Contagion", "Scourge", "Wave"], ["Containment", "Health"],
     "Public health officials implemented rapid quarantine protocols to contain the viral influenza epidemic.",
     "Epidemiologists study statistical transmission vectors to forecast the trajectory of seasonal disease epidemics."),

    ("Equal", "adjective", "A2", "/ˈiː.kwəl/", "setara / sama rata / seimbang nilainya",
     "Sama dalam jumlah, ukuran, nilai, atau status hak sosial.", "Being the same in quantity, size, degree, or value; having identical status, rights, or opportunities.",
     ["Equality", "Equally", "Equate"], ["Identical", "Equivalent", "Uniform", "Even", "Balanced"], ["Unequal", "Different", "Disparate", "Unfair"],
     "All democratic citizens are entitled to equal protection under the law regardless of their background.",
     "Divide the freshly baked apple pie into six equal slices so every guest receives an identical portion."),

    ("Equip", "verb", "B1", "/ɪˈkwɪp/", "memperlengkapi / membekali peralatan / mempersiapkan",
     "Menyediakan peralatan, sarana, atau keahlian yang diperlukan untuk melakukan tugas tertentu.", "To supply with the necessary items for a particular purpose; prepare mentally.",
     ["Equipment", "Equipped", "Furnish"], ["Furnish", "Outfit", "Provide", "Arm", "Supply"], ["Deprive", "Strip", "Divest"],
     "The educational foundation provided funding to equip rural high schools with modern computer labs.",
     "Rigorous university training helps equip medical students with the analytical skills needed in clinical diagnosis."),

    ("Equivalent", "adjective", "B2", "/ɪˈkwɪv.əl.ənt/", "setara / sebanding / bernilai sama persis",
     "Sama nilainya, jumlahnya, maknanya, atau fungsinya dengan sesuatu yang lain.", "Equal in value, amount, function, meaning, or importance.",
     ["Equivalence", "Equivalently", "Comparable"], ["Comparable", "Parallel", "Equal", "Commensurate", "Identical"], ["Different", "Unequal", "Dissimilar", "Incompatible"],
     "One mile is approximately equivalent to one point six zero nine kilometers in metric measurement.",
     "Applicants with an international diploma equivalent to a bachelor's degree may enroll directly in the master's program."),

    ("Eradicate", "verb", "C1", "/ɪˈræd.ɪ.keɪt/", "memberantas habis / membasmi tuntas ke akar",
     "Menghancurkan atau menyingkirkan sesuatu yang buruk hingga tidak bersisa sama sekali.", "To destroy completely; put an end to.",
     ["Eradication", "Uproot", "Eliminate"], ["Eliminate", "Exterminate", "Abolish", "Extirpate", "Uproot"], ["Establish", "Preserve", "Cultivate", "Foster"],
     "Global health initiatives have successfully managed to eradicate smallpox through systematic vaccination.",
     "Agricultural scientists work with farmers to eradicate invasive weed species threatening native crop harvests."),

    ("Essential", "adjective", "B1", "/ɪˈsen.ʃəl/", "sangat penting / mendasar / esensial / mutlak",
     "Sangat diperlukan dan mutlak harus ada untuk mencapai keberhasilan atau kelangsungan hidup.", "Absolutely necessary; extremely important; relating to the fundamental nature of something.",
     ["Essentially", "Essence", "Vital"], ["Vital", "Crucial", "Indispensable", "Fundamental", "Key"], ["Inessential", "Optional", "Superfluous", "Trivial"],
     "Clean drinking water, balanced nutrition, and adequate sleep are essential for physical health.",
     "Clear communication between air traffic controllers and pilots is essential for aviation flight safety.")
]

print(f"Loaded {len(PART2_WORDS)} words in Part 2 list")
