#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Oxford 3000 & 5000 - Part 3: Letters M - R (260 words)"""

PART3_WORDS = [
    # M
    ("Magnificent", "adjective", "B1", "/mæɡˈnɪf.ɪ.sənt/", "luar biasa megah / menawan spektakuler",
     "Sangat indah, megah, atau mengagumkan dalam penampilan dan skala.", "Extremely beautiful, elaborate, or impressive; splendid.",
     ["Magnificence", "Magnificently", "Grand"], ["Grand", "Splendid", "Glorious", "Majestic", "Superb"], ["Modest", "Plain", "Ordinary", "Drab"],
     "The royal ballroom was decorated with magnificent crystal chandeliers and gold-trimmed velvet drapery.",
     "Hikers paused at the summit to gaze upon a magnificent sunset painting the snowcapped peaks in crimson."),

    ("Maintain", "verb", "B1", "/meɪnˈteɪn/", "memelihara / mempertahankan / merawat rutin",
     "Menjaga sesuatu agar tetap dalam kondisi baik; mempertahankan pernyataan.", "To cause or enable a condition or state of affairs to continue; keep in repair.",
     ["Maintenance", "Maintainable", "Preserve"], ["Preserve", "Sustain", "Uphold", "Keep", "Continue"], ["Abandon", "Neglect", "Relinquish", "Cease"],
     "Routine service checks help maintain optimal vehicle engine performance and fuel efficiency.",
     "The defendant continued to maintain his innocence throughout the protracted appellate court hearings."),

    ("Magnitude", "noun", "C1", "/ˈmæɡ.nɪ.tʃuːd/", "besaran / tingkat kekuatan / skala luas",
     "Tingkat kebesaran, ukuran, atau pentingnya suatu peristiwa atau fenomena.", "The great size or extent of something; size or extent of an earthquake.",
     ["Magnify", "Magnification", "Scale"], ["Scale", "Extent", "Dimension", "Immensity", "Significance"], ["Smallness", "Insignificance", "Triviality"],
     "Seismologists recorded an earthquake of magnitude seven point two off the northeastern coastline.",
     "Few people initially grasped the colossal magnitude of the economic crisis as it unfolded globally."),

    ("Malfunction", "noun", "B2", "/ˌmælˈfʌŋk.ʃən/", "gangguan mesin / kegagalan fungsi alat",
     "Kegagalan suatu peralatan mesin atau sistem digital untuk beroperasi dengan benar.", "A failure to function normally or satisfactorily.",
     ["Malfunctioning", "Glitch", "Breakdown"], ["Glitch", "Defect", "Fault", "Failure", "Impairment"], ["Operation", "Function", "Order"],
     "A minor sensor malfunction triggered a warning light on the aircraft cockpit control dashboard.",
     "The automated assembly line paused for twenty minutes while technicians corrected a robotic gripper malfunction."),

    ("Manipulate", "verb", "B2", "/məˈnɪp.jə.leɪt/", "memanipulasi data / mengendalikan alat / memengaruhi licik",
     "Mengendalikan alat mekanis dengan terampil; memengaruhi orang lain demi keuntungan pribadi.", "To handle or control a tool skillfully; influence or control deviously.",
     ["Manipulation", "Manipulative", "Control"], ["Control", "Influence", "Maneuver", "Engineer", "Exploit"], ["Leave alone", "Guide transparently"],
     "Surgeons use robotic micro-instruments to manipulate delicate cardiovascular tissues safely.",
     "Deceptive advertising campaigns attempt to manipulate consumer emotions rather than providing factual data."),

    ("Manufacture", "verb", "B1", "/ˌmæn.jəˈfæk.tʃər/", "memproduksi barang / mempabrikasi produk",
     "Membuat barang dalam jumlah massal menggunakan mesin pabrik.", "To make something on a large scale using machinery; invent or fabricate.",
     ["Manufacturer", "Manufacturing", "Produce"], ["Produce", "Fabricate", "Construct", "Assemble", "Build"], ["Demolish", "Dismantle", "Destroy"],
     "The industrial plant can manufacture five hundred electric batteries every working hour.",
     "Biomedical companies manufacture synthetic insulin under strict sterile laboratory conditions."),

    ("Margin", "noun", "B2", "/ˈmɑː.dʒɪn/", "tepi halaman / margin laba / batas toleransi",
     "Bagian kosong di tepi halaman kertas; batas selisih keuntungan penjualan.", "The edge or border of something; the amount by which a thing is won or falls short.",
     ["Marginal", "Marginalize", "Border"], ["Border", "Edge", "Brink", "Boundary", "Profit"], ["Center", "Core", "Interior"],
     "Students wrote explanatory notes in the wide margins of their printed anatomy textbooks.",
     "The wholesale distributor operated on a narrow profit margin of only three percent per shipment."),

    ("Maturity", "noun", "B2", "/məˈtʃʊə.rə.ti/", "kematangan usia / kedewasaan emosional / jatuh tempo utang",
     "Kondisi matang secara fisik atau mental; saat berakhirnya masa pinjaman.", "The state, fact, or period of being mature; date when a financial note is due.",
     ["Mature", "Immature", "Adulthood"], ["Adulthood", "Wisdom", "Ripeness", "Fullness", "Experience"], ["Immaturity", "Childishness", "Greenness"],
     "Her emotional maturity allowed her to handle workplace disagreements with calm professionalism.",
     "The government treasury bond will reach full financial maturity in ten years from issue date."),

    ("Mechanism", "noun", "B2", "/ˈmek.ə.nɪz.əm/", "mekanisme kerja / susunan roda gigi / cara kerja proses",
     "Sistem bagian yang bekerja bersama dalam mesin; proses cara terjadinya sesuatu.", "A system of parts working together in a machine; a process by which something takes place.",
     ["Mechanize", "Mechanical", "Apparatus"], ["Apparatus", "Device", "System", "Method", "Process"], ["Disorganization", "Chaos"],
     "The antique grandfather clock operates through a precise brass pendulum and escapement mechanism.",
     "Immunologists study the cellular defense mechanism through which white blood cells neutralize pathogens."),

    ("Mediation", "noun", "B2", "/ˌmiː.diˈeɪ.ʃən/", "mediasi / penengahan sengketa damai",
     "Intervensi pihak ketiga netral untuk mendamaikan pertikaian antara dua pihak.", "Intervention in a dispute in order to resolve it; conciliation or arbitration.",
     ["Mediate", "Mediator", "Negotiation"], ["Conciliation", "Arbitration", "Negotiation", "Intervention"], ["Dispute", "Conflict", "Litigation"],
     "Both labor union and corporate leaders agreed to resolve their wage dispute through neutral legal mediation.",
     "Trained community mediation officers help neighbors resolve property boundary disagreements peacefully."),

    # N
    ("Narrative", "noun", "B1", "/ˈnær.ə.tɪv/", "narasi cerita / kisah runut kejadian",
     "Cerita atau uraian terhubung dari rangkaian peristiwa yang terjadi.", "A spoken or written account of connected events; a story.",
     ["Narrate", "Narrator", "Story"], ["Story", "Tale", "Chronicle", "Account", "History"], ["Data point", "Fragment"],
     "The author wove a gripping historical narrative depicting the migration of nineteenth-century settlers.",
     "Public health organizations craft a clear educational narrative to combat vaccine disinformation online."),

    ("Negotiate", "verb", "B1", "/nəˈɡəʊ.ʃi.eɪt/", "bernegosiasi / merundingkan perjanjian dagang",
     "Mendiskusikan sesuatu dengan orang lain demi mencapai kesepakatan bersama.", "To try to reach an agreement or compromise by discussion with others.",
     ["Negotiation", "Negotiator", "Confer"], ["Bargain", "Confer", "Debate", "Settle", "Treat"], ["Dictate", "Demand", "Refuse"],
     "Diplomats gathered in Geneva to negotiate a bilateral ceasefire and humanitarian access corridor.",
     "Prospective employees are encouraged to negotiate salary and flexible telecommuting terms respectfully."),

    ("Neutral", "adjective", "B1", "/ˈnjuː.trəl/", "netral / tidak memihak / ber-pH 7",
     "Tidak mendukung atau memihak salah satu sisi dalam perselisihan; seimbang kimianya.", "Not supporting or helping either side in a conflict; having a pH of 7.",
     ["Neutrality", "Neutralize", "Impartial"], ["Impartial", "Unbiased", "Objective", "Dispassionate", "Nonaligned"], ["Biased", "Partial", "Partisan", "Prejudiced"],
     "Switzerland has maintained a historic foreign policy of armed diplomatic neutrality for centuries.",
     "Pure distilled water at room temperature has a completely neutral pH value of seven."),

    ("Notable", "adjective", "B2", "/ˈnəʊ.tə.bəl/", "patut diperhatikan / terkemuka / menonjol",
     "Pantas mendapat perhatian karena keunggulan, kehebatan, atau keunikannya.", "Worthy of attention or notice; remarkable and distinguished.",
     ["Notably", "Notability", "Remarkable"], ["Remarkable", "Memorable", "Distinguished", "Prominent", "Eminent"], ["Insignificant", "Unremarkable", "Mediocre", "Obscure"],
     "The research paper noted a notable decrease in cardiovascular disease rates among vegetarian populations.",
     "The historic harbor city boasts several notable architectural monuments dating to the seventeenth century."),

    ("Notify", "verb", "B1", "/ˈnəʊ.tɪ.faɪ/", "memberitahukan resmi / mengabari lewat surat/pesan",
     "Memberitahukan suatu informasi atau peristiwa penting secara resmi kepada seseorang.", "To inform someone of something, typically in a formal or official manner.",
     ["Notification", "Notified", "Inform"], ["Inform", "Advise", "Alert", "Apprise", "Warn"], ["Conceal", "Hide", "Withhold"],
     "Please notify the human resources department immediately if your primary residential address changes.",
     "The mobile banking app will notify users instantaneously whenever an online payment transaction occurs."),

    ("Nourish", "verb", "B2", "/ˈnʌr.ɪʃ/", "memberi makan bergizi / memelihara harapan",
     "Menyediakan makanan yang diperlukan untuk pertumbuhan sehat; merawat emosi.", "To provide with the food or other substances necessary for growth, health, and good condition.",
     ["Nourishment", "Nutrient", "Nurture"], ["Nurture", "Feed", "Sustain", "Cherish", "Foster"], ["Starve", "Deprive", "Neglect", "Stunt"],
     "Wholesome organic meals rich in fresh vegetables nourish growing children and support brain development.",
     "Reading inspiring poetry can nourish the soul during stressful periods of life."),

    ("Novelty", "noun", "B2", "/ˈnɒv.əl.ti/", "kebaruan / keunikan baru / barang cenderamata unik",
     "Kualitas baru, segar, dan orisinal; barang unik yang menarik perhatian sesaat.", "The quality of being new, original, or unusual; a small, inexpensive toy or ornament.",
     ["Novel", "Innovate", "Originality"], ["Originality", "Newness", "Freshness", "Innovation", "Uniqueness"], ["Staleness", "Familiarity", "Triteness", "Oldness"],
     "Once the initial novelty of the high-tech kitchen gadget wore off, it remained largely unused on the counter.",
     "Tourists enjoy browsing the seaside souvenir stalls for playful handmade wooden novelties."),

    ("Numerous", "adjective", "B1", "/ˈnjuː.mər.əs/", "sangat banyak / berjumlah melimpah",
     "Berjumlah banyak atau terdiri dari sejumlah besar orang atau benda.", "Great in number; many and abundant.",
     ["Number", "Innumerable", "Many"], ["Many", "Abundant", "Countless", "Plentiful", "Multitudinous"], ["Few", "Scarce", "Sparse", "Rare"],
     "The candidate received numerous congratulatory telegrams from international political leaders.",
     "Researchers conducted numerous laboratory trials to ensure the experimental vaccine had no adverse side effects."),

    # O
    ("Objective", "noun", "B1", "/əbˈdʒek.tɪv/", "tujuan sasaran / objektif capaian",
     "Target atau sasaran yang ingin diraih melalui tindakan nyata.", "A thing aimed at or sought; a goal or target.",
     ["Object", "Objective", "Goal"], ["Goal", "Target", "Purpose", "Aim", "End"], ["Aimlessness", "Disarray"],
     "The primary objective of the public hygiene campaign is to eradicate waterborne bacterial diseases.",
     "Military units must achieve all tactical reconnaissance objectives before dusk."),

    ("Obligation", "noun", "B1", "/ˌɒb.lɪˈɡeɪ.ʃən/", "kewajiban hukum/moral / keharusan mengikat",
     "Tugas atau ikatan hukum dan moral yang wajib dijalankan seseorang.", "An act or course of action to which a person is morally or legally bound.",
     ["Obligate", "Obligatory", "Duty"], ["Duty", "Responsibility", "Commitment", "Requirement", "Bond"], ["Choice", "Option", "Exemption"],
     "Parents have a moral and legal obligation to provide shelter, education, and nutrition for their children.",
     "Citizens fulfill their civic obligation by paying statutory taxes and participating in jury trials."),

    ("Obscure", "adjective", "B2", "/əbˈskjʊər/", "samar-samar / tidak terkenal / sulit dipahami",
     "Tidak jelas terlihat atau dipahami; tidak dikenal banyak orang.", "Not discovered or known about; uncertain; not clearly expressed or easily understood.",
     ["Obscurity", "Obscurely", "Vague"], ["Unclear", "Vague", "Mysterious", "Little-known", "Enigmatic"], ["Famous", "Clear", "Prominent", "Obvious"],
     "The library archives contain thousands of obscure historical manuscripts written by medieval monks.",
     "The philosopher's obscure terminology made the introductory ethics text difficult for beginners to digest."),

    ("Observation", "noun", "B1", "/ˌɒb.zəˈveɪ.ʃən/", "pengamatan / observasi ilmiah / komentar catatan",
     "Tindakan memperhatikan atau memonitor sesuatu secara saksama; catatan pengamatan.", "The action or process of observing something or someone carefully; a remark or statement.",
     ["Observe", "Observer", "Monitoring"], ["Monitoring", "Inspection", "Surveillance", "Scrutiny", "Remark"], ["Inattention", "Neglect", "Overlooking"],
     "Astronomical observation of distant galaxies is conducted using orbital space telescopes.",
     "The attending nurse kept the postoperative cardiac patient under twenty-four-hour clinical observation."),

    ("Obstacle", "noun", "B1", "/ˈɒb.stə.kəl/", "rintangan penghalang / kendala rintangan",
     "Sesuatu yang menghalangi kemajuan atau membuat pencapaian menjadi sulit.", "A thing that blocks one's way or prevents or hinders progress.",
     ["Obstruct", "Obstruction", "Barrier"], ["Barrier", "Hurdle", "Impediment", "Hindrance", "Block"], ["Aid", "Advantage", "Assistance", "Open path"],
     "Lack of financial seed funding was the primary obstacle facing the young technology startup founders.",
     "Fallen boulder rocks created a dangerous obstacle for vehicles navigating the winding mountain canyon road."),

    ("Obtain", "verb", "B1", "/əbˈteɪn/", "memperoleh / mendapatkan surat izin/barang",
     "Mendapatkan kepemilikan atas sesuatu melalui usaha atau permohonan.", "To get, acquire, or secure something.",
     ["Obtainable", "Acquire", "Secure"], ["Acquire", "Secure", "Procure", "Gain", "Attain"], ["Lose", "Forfeit", "Surrender", "Relinquish"],
     "Foreign tourists must obtain a valid entry visa from the embassy before booking flights.",
     "Researchers worked for months to obtain official ethical clearance for their clinical psychology study."),

    ("Obvious", "adjective", "A2", "/ˈɒb.vi.əs/", "jelas nyata / gamblang tak terbantahkan",
     "Mudah dilihat, dikenali, atau dipahami oleh semua orang.", "Easily perceived or understood; clear, self-evident, or apparent.",
     ["Obviously", "Obviousness", "Clear"], ["Evident", "Apparent", "Manifest", "Clear-cut", "Plain"], ["Unclear", "Hidden", "Obscure", "Doubtful"],
     "It was obvious to everyone in the audience that the young violinist had practiced diligently for months.",
     "The most obvious solution to reducing plastic waste is adopting reusable glass and canvas containers."),

    ("Occupation", "noun", "A2", "/ˌɒk.jəˈpeɪ.ʃən/", "pekerjaan profesi / pendudukan wilayah",
     "Pekerjaan atau profesi utama seseorang; pendudukan militer atas wilayah.", "A job or profession; the action, state, or period of occupying a territory.",
     ["Occupy", "Occupant", "Profession"], ["Profession", "Vocation", "Career", "Trade", "Inhabitation"], ["Unemployment", "Idleness", "Vacation"],
     "On the census declaration form, she listed her primary occupation as environmental biomedical researcher.",
     "Historians documented the resilience of local citizens during the wartime foreign military occupation."),

    ("Occurrence", "noun", "B2", "/əˈkʌr.əns/", "kejadian peristiwa / peristiwa kemunculan",
     "Peristiwa atau hal yang terjadi dalam kehidupan sehari-hari.", "An incident or event; the fact or frequency of something happening.",
     ["Occur", "Occurring", "Event"], ["Incident", "Event", "Happenstance", "Phenomenon", "Episode"], ["Nonappearance"],
     "Sudden flash flood occurrences in desert canyon riverbeds can catch hikers completely unprepared.",
     "Minor electrical sparks are a rare occurrence when using modern surge-protected circuit breakers."),

    ("Omission", "noun", "C1", "/əʊˈmɪʃ.ən/", "kelalaian / penghapusan / hal yang terlewatkan",
     "Sesuatu yang tertinggal, terlewatkan, atau sengaja tidak dimasukkan.", "Someone or something that has been left out or excluded; failure to act.",
     ["Omit", "Omitted", "Exclusion"], ["Exclusion", "Oversight", "Deletion", "Elimination", "Skip"], ["Inclusion", "Addition", "Insertion"],
     "The audit team identified a critical omission of depreciation expenses in the balance sheet.",
     "Apologies for the accidental omission of your name from the published conference contributors list."),

    ("Operate", "verb", "B1", "/ˈɒp.ər.eɪt/", "mengoperasikan mesin / menjalankan bisnis / membedah",
     "Menjalankan alat atau mesin; memimpin bisnis; melakukan operasi bedah medis.", "To control the functioning of a machine; manage a business; perform surgical procedure.",
     ["Operation", "Operator", "Operational"], ["Run", "Function", "Manage", "Control", "Perform surgery"], ["Stall", "Halt", "Cease"],
     "Certified heavy equipment drivers operate industrial excavators on urban construction sites.",
     "Surgeons prepared to operate on the patient's fractured femur immediately following the accident."),

    ("Opportunity", "noun", "A2", "/ˌɒp.əˈtʃuː.nə.ti/", "kesempatan emas / peluang baik",
     "Kondisi atau saat yang menguntungkan untuk melakukan sesuatu yang berharga.", "A set of circumstances that makes it possible to do something.",
     ["Opportunistic", "Chance", "Opening"], ["Chance", "Opening", "Occasion", "Possibility", "Break"], ["Obstacle", "Disadvantage", "Misfortune"],
     "Studying abroad on an international exchange fellowship provides an extraordinary opportunity to master new languages.",
     "The economic downturn presented an unexpected investment opportunity for patient value buyers."),

    ("Oppose", "verb", "B1", "/əˈpəʊz/", "menentang kebijakan / melawan rencana",
     "Tidak menyetujui dan secara aktif berusaha menggagalkan suatu ide atau hukum.", "To disagree with and attempt to prevent, especially by argument or voting.",
     ["Opposition", "Opponent", "Opposing"], ["Resist", "Combat", "Contest", "Defy", "Challenge"], ["Support", "Endorse", "Favor", "Advocate"],
     "Environmental organizations unite to oppose industrial coal mining inside national national wildlife reserves.",
     "Several legislators stepped forward to publicly oppose the proposed hike in residential municipal property taxes."),

    ("Option", "noun", "A2", "/ˈɒp.ʃən/", "pilihan / opsi alternatif",
     "Hal yang dapat dipilih dari sejumlah alternatif yang tersedia.", "A thing that is or may be chosen; the freedom or capacity to choose.",
     ["Optional", "Opt", "Choice"], ["Choice", "Alternative", "Preference", "Possibility", "Selection"], ["Mandate", "Requirement", "Coercion"],
     "University students have the option to complete their final degree project via an internship or thesis.",
     "Vegetarian and gluten-free dining options are clearly indicated on the restaurant menu."),

    ("Organize", "verb", "A2", "/ˈɔː.ɡən.aɪz/", "mengatur rapi / mengorganisasi acara",
     "Menata sesuatu secara teratur dan sistematis; merencanakan acara bersama.", "To arrange into a structured whole; make arrangements or preparations for an event.",
     ["Organization", "Organizer", "Systematize"], ["Arrange", "Coordinate", "Order", "Classify", "Systematize"], ["Disorganize", "Disorder", "Scatter", "Disrupt"],
     "Volunteers worked late into the evening to organize donated books into categorized library shelves.",
     "The student committee volunteered to organize a charity musical concert to support local animal shelters."),

    ("Origin", "noun", "B1", "/ˈɒr.ɪ.dʒɪn/", "asal-usul / sumber muasal / pangkal mula",
     "Titik tempat sesuatu bermula, muncul, atau diturunkan.", "The point or place where something begins, arises, or is derived.",
     ["Original", "Originate", "Source"], ["Source", "Root", "Genesis", "Fountainhead", "Beginning"], ["End", "Conclusion", "Termination", "Outcome"],
     "Etymologists study the historical linguistic origin of English words derived from ancient Greek and Latin.",
     "The culinary historian traced the ancient Mediterranean origin of sourdough bread fermentation techniques."),

    ("Outcome", "noun", "B1", "/ˈaʊt.kʌm/", "hasil akhir / capaian dampak dari proses",
     "Hasil atau akibat akhir dari suatu proses, tindakan, atau perundingan.", "The way a thing turns out; a consequence, result, or effect.",
     ["Outcomes", "Result", "Consequence"], ["Result", "Consequence", "Effect", "Aftermath", "Conclusion"], ["Cause", "Origin", "Beginning"],
     "The clinical trial outcome demonstrated significant reductions in patient blood pressure levels.",
     "Negotiators worked tirelessly through the night to achieve a mutually beneficial peace treaty outcome."),

    ("Outstanding", "adjective", "B1", "/ˌaʊtˈstæn.dɪŋ/", "luar biasa menonjol / belum terbayar lunas",
     "Sangat istimewa dan terpuji; tagihan atau tugas yang belum diselesaikan.", "Exceptionally good; not yet paid, resolved, or dealt with.",
     ["Outstandingly", "Exceptional", "Unpaid"], ["Exceptional", "Superb", "Exemplary", "Unpaid", "Unsettled"], ["Mediocre", "Poor", "Paid", "Settled"],
     "The young cellist received a prestigious standing ovation for her outstanding performance of the Bach suite.",
     "Please settle all outstanding library penalty fees before collecting your official graduation diploma."),

    ("Overcome", "verb", "B1", "/ˌəʊ.vəˈkʌm/", "mengatasi rintangan / menaklukkan rasa takut",
     "Berhasil mengatasi atau mengalahkan kesulitan, rasa takut, atau rintangan.", "To succeed in dealing with a problem or difficulty; defeat or overcome emotionally.",
     ["Overcame", "Surmount", "Conquer"], ["Surmount", "Conquer", "Triumph over", "Defeat", "Vanquish"], ["Succumb", "Surrender", "Yield", "Fail"],
     "With dedicated physical therapy and positive grit, the injured athlete was able to overcome all setbacks.",
     "Mindfulness exercises help individuals overcome anxiety and regain inner mental equilibrium."),

    ("Oversee", "verb", "B2", "/ˌəʊ.vəˈsiː/", "mengawasi jalannya proyek / menyelia operasional",
     "Mengawasi orang atau proses untuk memastikan pekerjaan dilakukan dengan benar.", "To supervise a person or work, especially in an official capacity.",
     ["Overseer", "Supervise", "Inspect"], ["Supervise", "Direct", "Manage", "Administer", "Inspect"], ["Neglect", "Ignore", "Overlook"],
     "A senior civil engineer was appointed to oversee construction of the sixty-story skyscraper.",
     "The ethics board was created to oversee clinical laboratory trials involving human gene therapy."),

    # P
    ("Participate", "verb", "A2", "/pɑːˈtɪs.ɪ.peɪt/", "berpartisipasi / ikut serta aktif",
     "Mengambil bagian dalam suatu kegiatan atau acara bersama orang lain.", "To be involved; take part in an event or activity.",
     ["Participation", "Participant", "Join"], ["Join in", "Partake", "Engage", "Share", "Contribute"], ["Abstain", "Withdraw", "Refrain", "Boycott"],
     "High school students are encouraged to participate in community environmental cleanup volunteer days.",
     "Over five hundred delegates from fifty nations gathered to participate in the international climate summit."),

    ("Perceive", "verb", "B2", "/pəˈsiːv/", "mempersepsikan / menangkap kesan lewat indra",
     "Menjadi sadar akan sesuatu melalui indra; memahami atau menafsirkan arti.", "To become aware or conscious of something; come to realize or understand.",
     ["Perception", "Perceptive", "Discern"], ["Discern", "Recognize", "Detect", "Observe", "Comprehend"], ["Overlook", "Ignore", "Misunderstand"],
     "Cats can perceive high-pitched ultrasound squeaks that are completely inaudible to human ears.",
     "Employees perceive transparent corporate leadership as a cornerstone of genuine mutual trust."),

    ("Perception", "noun", "B2", "/pəˈsep.ʃən/", "persepsi / sudut pandang pemahaman / daya tangkap indra",
     "Kemampuan melihat, mendengar, atau menyadari sesuatu; cara memandang hal.", "The ability to see, hear, or become aware of something through the senses; an impression.",
     ["Perceive", "Perceptive", "Viewpoint"], ["Impression", "Viewpoint", "Understanding", "Discernment", "Insight"], ["Blindness", "Ignorance", "Misconception"],
     "Public perception of electric vehicles shifted positively as charging station networks expanded nationwide.",
     "Artists play with optical perspective to alter the viewer's visual perception of three-dimensional depth."),

    ("Persistent", "adjective", "B2", "/pəˈsɪs.tənt/", "gigih pantang menyerah / terus menerus ada",
     "Melanjutkan tindakan secara teguh meskipun menghadapi rintangan; tidak kunjung hilang.", "Continuing firmly in a course of action in spite of difficulty; obstinately recurring.",
     ["Persistently", "Persistence", "Tenacious"], ["Tenacious", "Determined", "Persevering", "Enduring", "Relentless"], ["Giving up", "Transient", "Sporadic", "Yielding"],
     "Through persistent effort and daily practice, she mastered the classical Spanish acoustic guitar.",
     "Consult a physician if you experience a persistent dry cough accompanied by unexplained fatigue."),

    ("Perspective", "noun", "B1", "/pəˈspek.tɪv/", "sudut pandang / perspektif visual / wawasan luas",
     "Cara pandang tertentu terhadap sesuatu; teknik menggambar kedalaman tiga dimensi.", "A particular attitude toward or way of regarding something; a point of view.",
     ["Perspective", "Viewpoint", "Angle"], ["Viewpoint", "Standpoint", "Outlook", "Angle", "Stance"], ["Narrow-mindedness"],
     "Traveling abroad provides young people with an invaluable global perspective on diverse cultures.",
     "Renaissance painters used linear mathematical perspective to create stunning realistic architectural depth."),

    ("Phenomenon", "noun", "B2", "/fəˈnɒm.ɪ.nən/", "fenomena alam / kejadian luar biasa spektakuler",
     "Fakta atau peristiwa yang dapat diamati terjadi di alam semesta; hal luar biasa.", "A fact or situation that is observed to exist or happen; a remarkable person or thing.",
     ["Phenomenal", "Occurrence", "Marvel"], ["Occurrence", "Event", "Marvel", "Wonder", "Manifestation"], ["Normality", "Regularity"],
     "The Aurora Borealis is a dazzling electromagnetic atmospheric phenomenon visible in high northern latitudes.",
     "The sudden viral explosion of the smartphone app was a cultural phenomenon analyzed by marketing scholars."),

    ("Pioneer", "noun", "B2", "/ˌpaɪəˈnɪər/", "pelopor perintis / pemula inovasi jalan",
     "Orang yang pertama kali membuka jalan, meneliti bidang baru, atau menjelajahi wilayah asing.", "A person who is among the first to explore or settle a new country or area; an innovator.",
     ["Pioneering", "Trailblazer", "Innovator"], ["Trailblazer", "Innovator", "Pathfinder", "Founder", "Developer"], ["Follower", "Imitator"],
     "Marie Curie was a scientific pioneer whose groundbreaking research on radioactivity earned two Nobel Prizes.",
     "Early space flight pioneers paved the way for modern orbital research laboratories and interplanetary exploration."),

    ("Plentiful", "adjective", "B1", "/ˈplen.tɪ.fəl/", "berlimpah ruah / sangat banyak tersedia",
     "Tersedia dalam jumlah besar dan berlebih yang mencukupi segala kebutuhan.", "Existing in or yielding great quantities; abundant and copious.",
     ["Plenty", "Plentifully", "Abundant"], ["Abundant", "Copious", "Ample", "Bountiful", "Profuse"], ["Scarce", "Sparse", "Meager", "Rare"],
     "After the seasonal monsoon rains, wild berries and edible mushrooms became plentiful throughout the forest.",
     "The coastal marine reserve offers a plentiful supply of fresh seafood for local fishing villages."),

    ("Potential", "noun", "B1", "/pəˈten.ʃəl/", "potensi / daya kemampuan terpendam",
     "Kemampuan terpendam yang dapat berkembang menjadi kesuksesan di masa depan.", "Latent qualities or abilities that may be developed and lead to future success or usefulness.",
     ["Potentially", "Capability", "Promise"], ["Possibility", "Capacity", "Promise", "Capability", "Aptitude"], ["Impotence", "Incapacity", "Limitation"],
     "The dedicated teacher worked patiently to help every student unlock their full creative potential.",
     "Solar photovoltaic technology holds tremendous untapped potential for decentralized rural electrification."),

    ("Precaution", "noun", "B1", "/prɪˈkɔː.ʃən/", "tindakan pencegahan / langkah antisipasi bahaya",
     "Langkah yang diambil terlebih dahulu untuk mencegah terjadinya bahaya atau kerugian.", "A measure taken in advance to prevent something dangerous, unpleasant, or inconvenient from happening.",
     ["Precautionary", "Safeguard", "Preventative"], ["Safeguard", "Safety measure", "Defense", "Anticipation", "Insurance"], ["Neglect", "Recklessness", "Carelessness"],
     "Wearing heavy thermal gloves and safety goggles is a mandatory precaution when working with liquid nitrogen.",
     "As a health precaution during flu season, wash your hands regularly with soap and warm water."),

    ("Predict", "verb", "B1", "/prɪˈdɪkt/", "memprediksi / meramalkan kejadian masa depan",
     "Menyatakan apa yang akan terjadi di masa depan berdasarkan data atau bukti ilmiah.", "To say or estimate that a specified thing will happen in the future or will be a consequence.",
     ["Prediction", "Predictable", "Forecast"], ["Forecast", "Foresee", "Prophesy", "Anticipate", "Project"], ["Ignore", "Overlook"],
     "Meteorologists use computer simulation models to predict the landfall location of coastal typhoons.",
     "Economists find it difficult to predict short-term stock market fluctuations with absolute certainty."),

    ("Preserve", "verb", "B1", "/prɪˈzɜːv/", "melestarikan alam / mengawetkan makanan / menjaga keaslian",
     "Menjaga sesuatu agar tidak rusak, punah, atau membusuk; mempertahankan tradisi.", "To maintain something in its original or existing state; protect from harm; treat food to prevent decay.",
     ["Preservation", "Preservative", "Conserve"], ["Conserve", "Protect", "Safeguard", "Maintain", "Sustain"], ["Destroy", "Ruin", "Damage", "Neglect"],
     "National park rangers work tirelessly to preserve pristine alpine forests and endangered bear habitats.",
     "Traditional canning and pickling methods preserve seasonal summer vegetables for cold winter consumption."),

    ("Prevail", "verb", "B2", "/prɪˈveɪl/", "menang unggul / lazim berlaku di masyarakat",
     "Terbukti lebih kuat dan akhirnya menang; umum dijumpai dalam suatu kebudayaan.", "To prove more powerful than opposing forces; be victorious; be widespread or current.",
     ["Prevalent", "Prevalence", "Triumph"], ["Triumph", "Dominate", "Overcome", "Predominate", "Reign"], ["Surrender", "Fail", "Yield", "Succumb"],
     "Truth and justice will ultimately prevail over falsehood through diligent legal advocacy.",
     "Warm sunny weather is expected to prevail across the southern coastal peninsula throughout the weekend."),

    ("Primary", "adjective", "B1", "/ˈpraɪ.mər.i/", "utama / primer / paling mendasar / pendidikan dasar",
     "Paling penting atau mendasar; tingkatan awal dalam rangkaian proses.", "Of chief importance; principal; earliest in time or order of development.",
     ["Primarily", "Prime", "Principal"], ["Principal", "Chief", "Main", "Essential", "Fundamental"], ["Secondary", "Minor", "Subordinate", "Peripheral"],
     "Our primary objective this quarter is improving customer satisfaction ratings across all branch locations.",
     "Elementary primary education instills foundational literacy, numeracy, and social cooperation skills."),

    ("Priority", "noun", "B1", "/praɪˈɒr.ə.ti/", "prioritas / hal yang diutamakan pertama",
     "Hal yang dianggap lebih penting daripada yang lain dan harus ditangani terlebih dahulu.", "A thing that is regarded as more important than another and given precedence.",
     ["Prioritize", "Priorities", "Precedence"], ["Precedence", "Preference", "Urgency", "Primary concern"], ["Subordination", "Neglect"],
     "Ensuring workplace safety for all construction personnel is our absolute top priority on the job site.",
     "Emergency dispatchers assign highest priority to ambulances responding to critical cardiac distress calls."),

    ("Promote", "verb", "A2", "/prəˈməʊt/", "mempromosikan jabatan/produk / mendorong kemajuan",
     "Menaikkan posisi jabatan seseorang; mengiklankan barang; mendorong perkembangan.", "To raise someone to a higher position or rank; encourage development; publicize.",
     ["Promotion", "Promotional", "Advance"], ["Advance", "Elevate", "Upgrade", "Publicize", "Endorse"], ["Demote", "Degrade", "Discourage", "Hinder"],
     "The board of directors voted to promote her to senior vice president of global marketing.",
     "Public health initiatives use television ads to promote daily physical exercise and balanced nutrition."),

    ("Propose", "verb", "B1", "/prəˈpəʊz/", "mengusulkan rencana / melamar pernikahan",
     "Mengajukan ide atau rencana untuk dipertimbangkan; mengajak menikah.", "To put forward an idea or plan for consideration; make an offer of marriage.",
     ["Proposal", "Proposition", "Suggest"], ["Suggest", "Recommend", "Offer", "Submit", "Advise"], ["Reject", "Withdraw", "Retract"],
     "Architects will propose a sustainable solar-powered design for the new public high school building.",
     "He chose a scenic cliffside gazebo during the golden sunset to propose marriage to his partner."),

    ("Prosperity", "noun", "B2", "/prɒsˈper.ə.ti/", "kemakmuran / kejayaan finansial / kesejahteraan",
     "Kondisi makmur, sukses secara finansial, dan berkembang subur.", "The state of being prosperous, successful, and flourishing in material terms.",
     ["Prosper", "Prosperous", "Wealth"], ["Wealth", "Affluence", "Abundance", "Success", "Opulence"], ["Poverty", "Hardship", "Destitution", "Failure"],
     "Investment in education and digital infrastructure brought lasting economic prosperity to the region.",
     "The agricultural community celebrated a season of peace, bountiful harvest, and general civic prosperity."),

    ("Pursue", "verb", "B1", "/pəˈsjuː/", "mengejar cita-cita / memburu buronan",
     "Mengikuti seseorang demi menangkapnya; terus berusaha meraih tujuan hidup.", "To follow someone in order to catch or attack them; seek to achieve a goal over time.",
     ["Pursuit", "Pursuer", "Chase"], ["Chase", "Follow", "Seek", "Strive for", "Track"], ["Abandon", "Flee", "Give up", "Relinquish"],
     "She decided to pursue a doctoral degree in renewable energy engineering at Cambridge University.",
     "Police cruisers were dispatched to pursue the stolen sports car along the highway bypass."),

    # Q
    ("Qualified", "adjective", "B1", "/ˈkwɒl.ɪ.faɪd/", "berkualifikasi / memiliki keahlian resmi",
     "Memiliki keterampilan, ijazah, atau pengalaman yang diperlukan untuk tugas tertentu.", "Officially recognized as being trained to perform a particular job; certified.",
     ["Qualify", "Qualification", "Certified"], ["Certified", "Competent", "Eligible", "Capable", "Skilled"], ["Unqualified", "Incompetent", "Ineligible"],
     "Only fully qualified pediatric surgeons are permitted to perform intricate infant surgeries.",
     "The recruitment committee interviewed five highly qualified candidates for the university professorship."),

    ("Quantity", "noun", "A2", "/ˈkwɒn.tə.ti/", "kuantitas / jumlah besaran barang",
     "Jumlah atau banyaknya suatu barang yang dapat dihitung atau diukur.", "An amount or number of something; especially that which can be measured.",
     ["Quantify", "Quantitative", "Amount"], ["Amount", "Number", "Volume", "Bulk", "Sum"], ["Quality", "Paucity"],
     "The bakery orders a massive quantity of organic wheat flour and butter every Monday morning.",
     "In manufacturing, maintaining exceptional quality is just as important as producing high quantity."),

    # R
    ("Radiant", "adjective", "B2", "/ˈreɪ.di.ənt/", "berseri-seri bahagia / memancarkan sinar hangat",
     "Memancarkan cahaya hangat yang terang; tampak sangat gembira dan sehat berseri.", "Shining or glowing brightly; clearly emanating great joy, love, or health.",
     ["Radiate", "Radiance", "Glowing"], ["Glowing", "Shining", "Beaming", "Luminous", "Dazzling"], ["Dull", "Gloomy", "Dim", "Lifeless"],
     "The bride looked radiant in her embroidered lace gown as she walked down the aisle.",
     "The morning sun cast radiant golden rays through the tall stained glass windows of the abbey."),

    ("Rational", "adjective", "B2", "/ˈræʃ.ən.əl/", "rasional / berlandaskan akal sehat logis",
     "Berdasarkan atau sesuai dengan akal budi dan penalaran yang logis.", "Based on or in accordance with reason or logic.",
     ["Rationally", "Rationality", "Logical"], ["Logical", "Sensible", "Reasonable", "Judicious", "Sound"], ["Irrational", "Illogical", "Unreasonable", "Absurd"],
     "Decision makers must maintain a calm, rational perspective when assessing financial market risks.",
     "Philosophers argue that rational inquiry and empirical evidence are foundational to scientific progress."),

    ("Reassure", "verb", "B2", "/ˌriː.əˈʃɔːr/", "menenangkan hati / meyakinkan kembali rasa aman",
     "Menghilangkan keraguan atau rasa takut seseorang dengan kata-kata menenangkan.", "To say or do something to remove the doubts or fears of someone.",
     ["Reassurance", "Reassuring", "Comfort"], ["Comfort", "Encourage", "Console", "Heartened", "Soothe"], ["Alarm", "Frighten", "Intimidate", "Dishearten"],
     "The flight attendant spoke with calm authority to reassure passengers during moderate air turbulence.",
     "The doctor's comprehensive test review helped reassure the anxious patient that the surgery had succeeded."),

    ("Recognition", "noun", "B1", "/ˌrek.əɡˈnɪʃ.ən/", "pengakuan prestasi / pengenalan wajah",
     "Pengakuan atas pencapaian atau kontribusi seseorang; proses mengenali wajah/suara.", "Identification of someone from previous knowledge; appreciation or acclaim for achievement.",
     ["Recognize", "Recognizable", "Acknowledgment"], ["Acknowledgment", "Appreciation", "Acclaim", "Identification"], ["Unawareness", "Ignorance", "Disregard"],
     "She received international recognition and a gold medal for her pioneering biomedical cancer research.",
     "Modern smartphones utilize biometric facial recognition algorithms to unlock screens securely."),

    ("Recommend", "verb", "A2", "/ˌrek.əˈmend/", "merekomendasikan / menyarankan pilihan terbaik",
     "Menyarankan seseorang atau sesuatu sebagai yang terbaik untuk dipilih.", "To put forward someone or something with approval as being suitable for a purpose.",
     ["Recommendation", "Recommended", "Suggest"], ["Suggest", "Advise", "Propose", "Endorse", "Advocate"], ["Disapprove", "Warn against", "Discourage"],
     "I highly recommend reading this environmental economics book before writing your term paper.",
     "Physicians recommend at least thirty minutes of moderate aerobic exercise every single day."),

    ("Reconcile", "verb", "C1", "/ˈrek.ən.saɪl/", "mendamaikan pertikaian / mencocokkan laporan kas",
     "Mengembalikan hubungan harmonis yang retak; mencocokkan data keuangan agar seimbang.", "To restore friendly relations between; make one view or belief compatible with another.",
     ["Reconciliation", "Reconciled", "Harmonize"], ["Harmonize", "Reunite", "Pacify", "Adjust", "Balance"], ["Alienate", "Estrange", "Divide", "Dispute"],
     "Diplomats worked for months to reconcile the long-standing territorial disputes between both nations.",
     "Accountants must reconcile monthly bank statements with internal ledger records to catch discrepancies."),

    ("Recover", "verb", "B1", "/rɪˈkʌv.ər/", "pulih dari sakit / menemukan kembali barang hilang",
     "Kembali sehat setelah sakit; mendapatkan kembali benda yang sempat hilang.", "To return to a normal state of health, mind, or strength; find or regain possession of.",
     ["Recovery", "Recovered", "Recuperate"], ["Recuperate", "Heal", "Regain", "Retrieve", "Reclaim"], ["Deteriorate", "Worsen", "Lose", "Relapse"],
     "It took several restful weeks for the athlete to fully recover from the knee ligament surgery.",
     "Divers were deployed to the ocean trench to recover the downed aircraft's black box recorder."),

    ("Refine", "verb", "B2", "/rɪˈfaɪn/", "memurnikan zat / menyempurnakan tulisan/keahlian",
     "Menghilangkan kotoran dari bahan mentah; menyempurnakan keahlian atau tulisan.", "To remove impurities or unwanted elements from; improve by making small changes.",
     ["Refinement", "Refined", "Purify"], ["Purify", "Polish", "Perfect", "Hone", "Improve"], ["Contaminate", "Pollute", "Roughen"],
     "Industrial processing facilities refine raw petroleum into gasoline, diesel, and aviation kerosene.",
     "Writers continually edit and refine their draft chapters to enhance lyrical flow and dramatic tension."),

    ("Reflect", "verb", "B1", "/rɪˈflekt/", "memantulkan cahaya / merenungkan pengalaman / mencerminkan",
     "Memantulkan cahaya atau suara; berpikir mendalam mengenai suatu kejadian; menggambarkan.", "To throw back heat, light, or sound without absorbing it; think deeply about something.",
     ["Reflection", "Reflective", "Mirror"], ["Mirror", "Echo", "Ponder", "Contemplate", "Meditate"], ["Absorb", "Disregard", "Ignore"],
     "The calm alpine mountain lake was still enough to reflect the snowcapped peaks like a silver mirror.",
     "Take time at the end of each busy week to reflect on personal accomplishments and future goals."),

    ("Refuge", "noun", "B2", "/ˈref.juːdʒ/", "tempat perlindungan suaka / suaka margasatwa",
     "Tempat aman yang memberikan perlindungan dari bahaya atau cuaca buruk.", "A condition of being safe or sheltered from pursuit, danger, or trouble; a safe place.",
     ["Refugee", "Sanctuary", "Haven"], ["Sanctuary", "Haven", "Shelter", "Asylum", "Retreat"], ["Peril", "Danger", "Exposure"],
     "The ancient stone monastery served as a peaceful refuge for travelers caught in the blizzard.",
     "Wildlife conservationists established a thousand-hectare coastal refuge for endangered migratory waterfowl."),

    ("Regulate", "verb", "B2", "/ˈreɡ.jə.leɪt/", "mengatur laju / meregulasi standar hukum",
     "Mengendalikan atau memelihara laju kecepatan atau suhu; membuat aturan resmi.", "To control or maintain the rate or speed of a machine or process; control by rules.",
     ["Regulation", "Regulatory", "Control"], ["Control", "Govern", "Adjust", "Standardize", "Supervise"], ["Disorder", "Deregulate", "Neglect"],
     "The internal thermostat helps regulate the temperature inside the biological incubation chamber.",
     "Government financial agencies regulate commercial banks to prevent reckless speculative lending practices."),

    ("Reinforce", "verb", "B2", "/ˌriː.ɪnˈfɔːs/", "memperkuat struktur beton / memperkokoh keyakinan",
     "Memperkuat dengan menambah bahan penopang; memperteguh argumen atau perilaku.", "To strengthen or support an existing structure or army with additional material or personnel.",
     ["Reinforcement", "Reinforced", "Strengthen"], ["Strengthen", "Fortify", "Bolster", "Support", "Underpin"], ["Weaken", "Undermine", "Impair", "Subvert"],
     "Structural engineers used high-tensile steel cables to reinforce the suspension bridge towers against typhoons.",
     "Praising positive student cooperation helps reinforce good classroom social habits effectively."),

    ("Relevant", "adjective", "B1", "/ˈrel.ə.vənt/", "relevan / berkaitan erat / sesuai konteks",
     "Berkaitan erat dan bermakna dengan topik atau masalah yang sedang dibahas.", "Closely connected or appropriate to the matter at hand.",
     ["Relevance", "Relevantly", "Pertinent"], ["Pertinent", "Applicable", "Germane", "Appropriate", "Fitting"], ["Irrelevant", "Inapplicable", "Extraneous"],
     "Please ensure all cited references in your literature review are directly relevant to the core thesis topic.",
     "Candidates should highlight relevant job experience on their resume when applying for management roles."),

    ("Relieve", "verb", "B1", "/rɪˈliːv/", "meredakan rasa sakit / meringankan beban",
     "Mengurangi rasa sakit atau kekhawatiran; menggantikan petugas jaga.", "To reduce or remove pain, distress, or anxiety; take over from someone on duty.",
     ["Relief", "Relieved", "Alleviate"], ["Alleviate", "Assuage", "Soothe", "Mitigate", "Ease"], ["Aggravate", "Intensify", "Worsen", "Increase"],
     "Applying a cold ice compress will help relieve pain and reduce swelling around the sprained ankle.",
     "A fresh security shift arrived at midnight to relieve the fatigued guards stationed at the harbor gate."),

    ("Remarkable", "adjective", "B1", "/rɪˈmɑː.kə.bəl/", "luar biasa mengagumkan / patut dicatat",
     "Layak mendapat perhatian karena kehebatan, keunikan, atau prestasinya.", "Worthy of attention; striking, extraordinary, or exceptional.",
     ["Remarkably", "Remark", "Extraordinary"], ["Extraordinary", "Exceptional", "Outstanding", "Notable", "Impressive"], ["Ordinary", "Average", "Unremarkable", "Common"],
     "The young pianist demonstrated a remarkable ability to memorize complex concertos after one hearing.",
     "The island boasts a remarkable diversity of endemic bird species found nowhere else on earth."),

    ("Remedy", "noun", "B2", "/ˈrem.ə.di/", "obat penawar / solusi jalan keluar masalah",
     "Obat atau pengobatan untuk penyakit; sarana untuk memperbaiki situasi buruk.", "A medicine or treatment for a disease or injury; a means of counteracting or solving a problem.",
     ["Remedial", "Remediate", "Cure"], ["Cure", "Treatment", "Solution", "Antidote", "Restorative"], ["Poison", "Affliction", "Damage"],
     "Warm herbal ginger tea with raw wildflower honey is a traditional home remedy for a sore throat.",
     "Legal experts proposed structural regulatory reforms as the only effective remedy for market corruption."),

    ("Renovate", "verb", "B2", "/ˈren.ə.veɪt/", "merenovasi / memugar gedung kuno / memperbarui",
     "Memperbaiki dan memperbarui gedung atau ruangan agar kembali dalam kondisi bagus.", "To restore a building or thing to a good state of repair.",
     ["Renovation", "Renovated", "Restore"], ["Restore", "Refurbish", "Revamp", "Modernize", "Rehabilitate"], ["Demolish", "Destroy", "Neglect", "Ruin"],
     "The municipal council voted to allocate funding to renovate the historic city library and clock tower.",
     "The young couple spent six months renovating their 1920s craftsman bungalow kitchen and wood floors."),

    ("Reputation", "noun", "B1", "/ˌrep.jəˈteɪ.ʃən/", "reputasi nama baik / citra kehormatan",
     "Pendapat umum atau keyakinan masyarakat mengenai seseorang atau organisasi.", "The beliefs or opinions that are generally held about someone or something.",
     ["Reputable", "Disrepute", "Prestige"], ["Prestige", "Standing", "Stature", "Renown", "Fame"], ["Infamy", "Disrepute", "Dishonor"],
     "The university medical school has earned an international reputation for cutting-edge genomic research.",
     "Maintaining impeccable professional integrity is essential for preserving an artisan's brand reputation."),

    ("Resilience", "noun", "B2", "/rɪˈzɪl.jəns/", "daya lenting ketangguhan / ketabahan bangkit",
     "Kemampuan untuk pulih dengan cepat dari kesulitan, krisis, atau trauma.", "The capacity to recover quickly from difficulties; toughness and elasticity.",
     ["Resilient", "Resiliently", "Elasticity"], ["Toughness", "Fortitude", "Endurance", "Flexibility", "Tenacity"], ["Fragility", "Vulnerability", "Weakness"],
     "The community displayed inspiring psychological resilience as they rebuilt homes following the flood.",
     "Ecologists study the ecological resilience of mangrove coastlines in dissipating tidal storm surges."),

    ("Resolution", "noun", "B2", "/ˌrez.əˈluː.ʃən/", "resolusi tekad bulat / resolusi layar monitor / penyelesaian",
     "Keputusan teguh untuk melakukan sesuatu; resolusi ketajaman gambar; penyelesaian sengketa.", "A firm decision to do or not to do something; clarity of an image; solution to a conflict.",
     ["Resolve", "Resolute", "Decision"], ["Decision", "Determination", "Settlement", "Clarity", "Verdict"], ["Indecision", "Hesitation", "Dispute"],
     "Her New Year's resolution was to read fifty classic literature masterpieces and exercise daily.",
     "The new 4K television display provides crystal-clear visual resolution and vivid color fidelity."),

    ("Resource", "noun", "A2", "/rɪˈzɔːs/", "sumber daya alam/dana / sarana pendukung",
     "Pasokan uang, bahan, staf, atau aset yang dapat dimanfaatkan untuk beroperasi.", "A stock or supply of money, materials, staff, and other assets that can be drawn on.",
     ["Resourceful", "Resourcefulness", "Asset"], ["Asset", "Supply", "Reserve", "Material", "Means"], ["Debt", "Depletion", "Shortage"],
     "Clean drinking water is the most vital natural resource requiring sustainable global conservation.",
     "The university library offers extensive digital resources including academic journals and eBooks."),

    ("Restore", "verb", "B1", "/rɪˈstɔːr/", "memulihkan kondisi / merestorasi lukisan kuno",
     "Mengembalikan sesuatu ke kondisi aslinya yang baik atau ke posisi sebelumnya.", "To bring back a situation or feeling that existed before; repair or renovate a building or artwork.",
     ["Restoration", "Restorative", "Rehabilitate"], ["Rehabilitate", "Reinstate", "Revive", "Renew", "Refurbish"], ["Destroy", "Abolish", "Ruin", "Damage"],
     "Conservators used delicate surgical tools to restore the faded colors of the Renaissance fresco painting.",
     "After twelve hours of emergency line repair, power technicians managed to restore electricity to the township."),

    ("Reveal", "verb", "B1", "/rɪˈviːl/", "mengungkapkan rahasia / menyingkap tabir",
     "Membuat sesuatu yang sebelumnya rahasia atau tersembunyi menjadi diketahui publik.", "To make previously unknown or secret information known to others; expose.",
     ["Revelation", "Revealing", "Disclose"], ["Disclose", "Unveil", "Expose", "Uncover", "Divulge"], ["Conceal", "Hide", "Cover", "Suppress"],
     "Archaeological digs along the Nile riverbank continue to reveal ancient bronze relics and hieroglyphic inscriptions.",
     "The investigative documentary will reveal new evidence concerning the offshore corporate financial scandal."),

    ("Revolution", "noun", "B1", "/ˌrev.əˈluː.ʃən/", "revolusi perubahan besar / putaran orbit",
     "Perubahan mendasar dan dramatis dalam tatanan sosial, teknologi, atau politik; putaran penuh.", "A forcible overthrow of a government or social order; a dramatic change; one complete circular turn.",
     ["Revolutionary", "Revolutionize", "Upheaval"], ["Upheaval", "Transformation", "Rebellion", "Rotation", "Turn"], ["Stagnation", "Stability"],
     "The industrial revolution transformed agrarian societies into mechanized, urban manufacturing economies.",
     "The Earth takes three hundred sixty-five days to complete one full orbital revolution around the sun."),

    ("Rigid", "adjective", "B2", "/ˈrɪdʒ.ɪd/", "kaku tidak lentur / kaku ketat aturannya",
     "Keras dan tidak dapat ditekuk tanpa patah; sangat ketat dan tidak fleksibel.", "Unable to bend or be forced out of shape; not able to be changed or adapted.",
     ["Rigidly", "Rigidity", "Inflexible"], ["Inflexible", "Stiff", "Unbending", "Strict", "Rigorous"], ["Flexible", "Supple", "Pliable", "Elastic"],
     "Cast iron pipes are extremely strong but somewhat rigid, making them brittle under intense seismic strain.",
     "The school enforced a rigid dress code that required all students to wear tailored navy blazers."),

    ("Robust", "adjective", "B2", "/rəʊˈbʌst/", "kokoh kuat berenergi / tangguh tahan uji",
     "Kuat dan sehat penuh stamina; dirancang tahan banting menghadapi tekanan berat.", "Strong and healthy; vigorous; sturdy in construction or design.",
     ["Robustly", "Robustness", "Sturdy"], ["Sturdy", "Vigorous", "Resilient", "Tough", "Sound"], ["Fragile", "Weak", "Frail", "Feeble"],
     "The rugged mountaineering boots are built from robust waterproof leather with reinforced rubber soles.",
     "Software architects engineered a robust server architecture capable of handling millions of concurrent users.")
]

print(f"Loaded {len(PART3_WORDS)} words for Part 3")
