#!/usr/bin/env python3
"""
Generator for Part 1 (A to D) Oxford 3000 & 5000 Vocabulary Entries.
Generates comprehensive DictionaryEntry records in TypeScript format.
"""
import json
import os

WORDS_A_D = [
    # --- Letter A ---
    ("Abbreviate", "verb", "B2", "/əˈbriː.vi.eɪt/", "menyingkat / memendekkan kata",
     "Membuat kata atau frasa menjadi lebih pendek dengan menghilangkan beberapa huruf.",
     "To make a word or phrase shorter by omitting letters or syllables.",
     ["Abbreviation", "Abridge", "Shorten"], ["Shorten", "Condense", "Truncate", "Contract"], ["Expand", "Lengthen", "Extend"],
     "In medical reports, clinicians frequently abbreviate complex anatomical terms.",
     "When taking rapid lecture notes, students often abbreviate recurring terminology to keep pace with the speaker."),

    ("Abbreviation", "noun", "B1", "/əˌbriː.viˈeɪ.ʃən/", "singkatan / kependekan kata",
     "Bentuk pendek dari sebuah kata atau frasa yang mewakili bentuk aslinya.",
     "A shortened form of a word or phrase used in place of the whole.",
     ["Acronym", "Initialism", "Contraction"], ["Acronym", "Contraction", "Shortening", "Code"], ["Full form", "Elaboration", "Expansion"],
     "'NASA' is a globally recognized abbreviation for the National Aeronautics and Space Administration.",
     "Academic style manuals require writers to define each abbreviation in parentheses the first time it appears in a manuscript."),

    ("Abide", "verb", "B2", "/əˈbaɪd/", "mematuhi / mentaati / tinggal",
     "Menerima atau mematuhi aturan, keputusan, atau instruksi yang berlaku; bertahan tinggal.",
     "To accept, follow, or endure a rule, decision, or condition without objection.",
     ["Abiding", "Compliance", "Adhere"], ["Comply", "Obey", "Follow", "Conform", "Endure"], ["Disobey", "Violate", "Flout", "Defy"],
     "All registered athletes must strictly abide by international anti-doping regulations.",
     "Citizens who respect the democratic process agree to abide by judicial rulings, even when they disagree with specific outcomes."),

    ("Abnormal", "adjective", "B2", "/æbˈnɔː.məl/", "abnormal / tidak normal / menyimpang",
     "Berbeda secara signifikan dari apa yang lazim, wajar, atau diharapkan.",
     "Deviating noticeably from what is normal, standard, or expected.",
     ["Anomaly", "Deviation", "Irregularity"], ["Unusual", "Atypical", "Irregular", "Anomalous"], ["Normal", "Typical", "Regular", "Standard"],
     "The pediatrician noticed an abnormal heart rhythm during the routine checkup.",
     "Meteorologists warned that the abnormal rise in coastal sea surface temperatures could trigger stronger typhoon formations."),

    ("Aboard", "adverb", "B1", "/əˈbɔːd/", "di atas kapal / naik pesawat / di kendaraan",
     "Berada di dalam atau menaiki kapal laut, pesawat terbang, kereta api, atau bus.",
     "On or into a ship, train, aircraft, or other transport vehicle.",
     ["Board", "Embark", "Onboard"], ["Onboard", "Embarked", "Inside"], ["Ashore", "Off"],
     "The flight attendants cordially welcomed all passengers aboard the transatlantic flight.",
     "Once all cargo and crew members were safely aboard, the exploration vessel departed the harbor into open waters."),

    ("Abolition", "noun", "C1", "/ˌæb.əˈlɪʃ.ən/", "penghapusan resmi / peniadaan hukum",
     "Tindakan resmi menghentikan atau menghapuskan hukum, institusi, atau praktik sosial.",
     "The official ending or legal annulment of a law, system, or institution.",
     ["Abolish", "Repeal", "Annulment"], ["Annulment", "Repeal", "Elimination", "Revocation"], ["Establishment", "Institution", "Enactment"],
     "The abolition of child labor marked a triumphant milestone in humanitarian legal history.",
     "Nineteenth-century activists dedicated their entire lives to securing the universal abolition of human bondage and servitude."),

    ("Abrupt", "adjective", "B2", "/əˈbrʌpt/", "tiba-tiba / mendadak / kasar",
     "Terjadi secara sangat mendadak tanpa peringatan; bersikap terburu-buru dan agak kasar.",
     "Sudden and unexpected, often in an unpleasant or brusque manner.",
     ["Abruptly", "Sudden", "Sharp"], ["Sudden", "Precipitous", "Unexpected", "Sharp", "Curt"], ["Gradual", "Smooth", "Gentle", "Expected"],
     "The lively discussion came to an abrupt halt when the emergency siren sounded.",
     "Commuters were startled by the train driver's abrupt application of emergency brakes on the curved track."),

    ("Absolute", "adjective", "B1", "/ˈæb.sə.luːt/", "mutlak / pasti / tanpa syarat",
     "Lengkap, bulat, tanpa keraguan atau batasan apapun; independen dan tidak bersyarat.",
     "Complete, total, and not limited by restrictions or conditions.",
     ["Absolutely", "Absoluteness", "Certainty"], ["Total", "Complete", "Unconditional", "Definitive"], ["Relative", "Partial", "Conditional", "Limited"],
     "The constitutional monarch does not possess absolute political authority.",
     "Scientific investigators require absolute honesty and empirical rigor when presenting clinical trial data to peer reviewers."),

    ("Absorb", "verb", "B1", "/əbˈzɔːb/", "menyerap cairan / mencerna ilmu / mendalami",
     "Mengambil atau menyedot cairan, energi, atau panas; memahami pengetahuan secara mendalam.",
     "To take in or soak up liquid, energy, or information thoroughly.",
     ["Absorption", "Absorbent", "Imbibe"], ["Soak up", "Assimilate", "Imbibe", "Incorporate", "Digest"], ["Emit", "Discharge", "Release", "Exude"],
     "Porous sponge materials absorb spilled liquids in a matter of seconds.",
     "During intensive language immersion programs, learners absorb grammatical patterns intuitively by listening to native dialogue daily."),

    ("Abstain", "verb", "C1", "/æbˈsteɪn/", "menahan diri / memilih golput / berpantang",
     "Secara sadar menolak atau menahan diri untuk tidak melakukan sesuatu atau tidak memberikan suara.",
     "To choose deliberately not to do or consume something, or not to cast a vote.",
     ["Abstinence", "Refrain", "Forbear"], ["Refrain", "Desist", "Withhold", "Avoid"], ["Indulge", "Participate", "Engage", "Consume"],
     "Several committee delegates chose to abstain from voting on the controversial resolution.",
     "Health professionals advise patients with cardiovascular conditions to abstain from smoking and excessive sodium intake."),

    ("Abstract", "adjective", "B2", "/ˈæb.strækt/", "abstrak / bersifat konseptual",
     "Berkaitan dengan gagasan murni atau konsep pikiran, bukan benda berwujud nyata.",
     "Existing in thought or as an idea but having no physical or concrete existence.",
     ["Abstraction", "Abstractly", "Concept"], ["Theoretical", "Conceptual", "Intangible", "Philosophical"], ["Concrete", "Physical", "Tangible", "Material"],
     "Truth, justice, and liberty are profound abstract concepts that shape human society.",
     "Young mathematics students often struggle with abstract algebraic notation before applying it to concrete real-world word problems."),

    ("Abundance", "noun", "B2", "/əˈbʌn.dəns/", "kelimpahan / jumlah yang sangat berlimpah",
     "Kuantitas atau pasokan yang sangat besar dan lebih dari cukup.",
     "A very large quantity or plentiful supply of something.",
     ["Abundant", "Abundantly", "Profusion"], ["Profusion", "Plenitude", "Surplus", "Wealth", "Opulence"], ["Scarcity", "Shortage", "Dearth", "Lack"],
     "The fertile volcanic river valley provided an abundance of organic harvest.",
     "Marine biologists observed an extraordinary abundance of coral reef species in the newly designated marine sanctuary."),

    ("Abuse", "verb", "B2", "/əˈbjuːz/", "menyalahgunakan / menganiaya / memaki",
     "Menggunakan sesuatu secara salah untuk niat buruk; memperlakukan manusia/hewan secara kejam.",
     "To use something improperly or excessively; to treat a person or animal with cruelty.",
     ["Abusive", "Abuser", "Misuse"], ["Misuse", "Exploit", "Mistreat", "Maltreat"], ["Respect", "Protect", "Cherish", "Uphold"],
     "Elected officials who abuse their public authority must face rigorous judicial accountability.",
     "Nonprofit animal shelters rescue domesticated pets from neglectful owners who abuse them through confinement or malnutrition."),

    ("Academic", "adjective", "B1", "/ˌæk.əˈdem.ɪk/", "akademis / ilmiah / keilmuan",
     "Berkaitan dengan pendidikan tinggi, riset ilmiah, sekolah, atau universitas.",
     "Relating to schools, colleges, scholarly research, or higher education.",
     ["Academy", "Academically", "Academia"], ["Scholarly", "Educational", "Intellectual", "Pedagogical"], ["Practical", "Vocational", "Nonacademic"],
     "She attained remarkable academic achievements during her postgraduate studies in astrophysics.",
     "The university publishes an esteemed academic journal featuring peer-reviewed investigations into renewable solar cell chemistry."),

    ("Accede", "verb", "C1", "/əkˈsiːd/", "menyetujui tuntutan / naik tahta",
     "Menyetujui suatu permintaan, perjanjian, atau bergabung dalam konvensi resmi.",
     "To agree to a demand, request, or treaty; to assume an office or position.",
     ["Accession", "Consent", "Yield"], ["Consent", "Concede", "Assent", "Agree", "Comply"], ["Refuse", "Reject", "Decline", "Oppose"],
     "The government finally agreed to accede to the terms of the international climate treaty.",
     "After prolonged negotiations between union leaders and corporate management, the board decided to accede to the pension requests."),

    ("Accelerate", "verb", "B2", "/əkˈsel.ə.reɪt/", "mempercepat laju / meningkatkan akselerasi",
     "Meningkatkan kecepatan gerakan, laju proses, atau tempo terjadinya peristiwa.",
     "To increase the speed or rate of something; to cause to happen sooner.",
     ["Acceleration", "Accelerator", "Speed"], ["Hasten", "Expedite", "Quicken", "Spur", "Boost"], ["Decelerate", "Slow down", "Delay", "Hinder"],
     "Electric vehicles accelerate with remarkable smoothness compared to gasoline engines.",
     "Modern artificial intelligence algorithms accelerate drug discovery by simulating chemical molecule bindings in seconds rather than months."),

    ("Accent", "noun", "B1", "/ˈæk.sənt/", "aksen / logat kedaerahan / penekanan nada",
     "Cara pengucapan bahasa yang khas dari wilayah, kelompok sosial, atau bangsa tertentu.",
     "A distinctive pronunciation of a language associated with a particular region or country.",
     ["Accentuate", "Dialect", "Intonation"], ["Dialect", "Pronunciation", "Inflection", "Cadence"], ["Monotone"],
     "She speaks English with exceptional fluency and a mild French accent.",
     "Linguists analyze regional accent variations to trace historical migration routes of early settlers across the continent."),

    ("Acceptable", "adjective", "B1", "/əkˈsep.tə.bəl/", "dapat diterima / memadai / patut",
     "Cukup baik untuk disetujui atau dianggap memuaskan sesuai standar yang berlaku.",
     "Able to be agreed upon; suitable, adequate, or satisfactory in standard.",
     ["Accept", "Acceptance", "Acceptably"], ["Satisfactory", "Tolerable", "Permissible", "Adequate", "Decent"], ["Unacceptable", "Intolerable", "Unsuitable"],
     "A minor delay of ten minutes is considered acceptable during stormy weather conditions.",
     "Food safety inspectors verify that bacterial colony counts remain within strictly acceptable microbiological limits."),

    ("Access", "noun", "B1", "/ˈæk.ses/", "akses / jalan masuk / hak memanfaatkan",
     "Kesempatan, hak, atau sarana untuk mendekati, memasuki, atau menggunakan sesuatu.",
     "The means or opportunity to enter, approach, or make use of something.",
     ["Accessible", "Accessibility", "Inaccessible"], ["Admission", "Entry", "Approach", "Availability", "Ingress"], ["Bar", "Restriction", "Blockade", "Denial"],
     "Every student in remote rural schools deserves equal access to digital library resources.",
     "The newly renovated subway station provides barrier-free wheelchair access from street level directly down to the boarding platform."),

    ("Accessible", "adjective", "B2", "/əkˈses.ə.bəl/", "mudah diakses / terjangkau / ramah pengguna",
     "Dapat dicapai, dimasuki, dipahami, atau diperoleh dengan mudah oleh semua orang.",
     "Easy to approach, reach, enter, obtain, or understand.",
     ["Access", "Accessibility", "Inaccessible"], ["Reachable", "Attainable", "Approachable", "User-friendly"], ["Inaccessible", "Unreachable", "Obscure", "Impassable"],
     "The professor explained complex quantum theories in an accessible, engaging manner.",
     "Public buildings must construct ramps and install wide doorways to make facilities accessible for individuals with mobility disabilities."),

    ("Accident", "noun", "A2", "/ˈæk.sɪ.dənt/", "kecelakaan / insiden tak terduga",
     "Peristiwa malang atau tak terduga yang sering kali menyebabkan kerusakan atau cedera.",
     "An unfortunate incident that happens unexpectedly and unintentionally, causing damage.",
     ["Accidental", "Accidentally", "Mishap"], ["Mishap", "Collision", "Casualty", "Calamity", "Incident"], ["Plan", "Calculation", "Design", "Intention"],
     "He wore a sturdy helmet which protected his head during the cycling accident.",
     "Workplace safety training programs aim to eliminate hazard blind spots and prevent industrial accident occurrences in factories."),

    ("Accidental", "adjective", "B2", "/ˌæk.sɪˈden.təl/", "tidak sengaja / terjadi secara kebetulan",
     "Terjadi tanpa niat atau rencana yang telah dirancang sebelumnya; karena kebetulan.",
     "Happening by chance or unintentionally without deliberate foresight.",
     ["Accident", "Accidentally", "Coincidence"], ["Unintentional", "Inadvertent", "Fortuitous", "Chance", "Casual"], ["Deliberate", "Intentional", "Planned", "Premeditated"],
     "Alexander Fleming made the accidental discovery of penicillin from contaminated culture dishes.",
     "The author clarified that any resemblance of fictional characters to living persons was purely accidental and unintentional."),

    ("Acclaim", "noun", "C1", "/əˈkleɪm/", "pujian meriah / sanjungan publik",
     "Pujian dan sambutan hangat penuh kekaguman dari masyarakat atau kritikus.",
     "Enthusiastic and public praise, approval, or celebration.",
     ["Acclaimed", "Praise", "Applause"], ["Praise", "Commendation", "Applause", "Tribute", "Enthusiasm"], ["Condemnation", "Criticism", "Censure", "Derision"],
     "The young pianist won international acclaim after performing Chopin's concertos flawlessly.",
     "Her debut historical novel received widespread critical acclaim for its meticulous archival research and vivid emotional depth."),

    ("Accommodate", "verb", "B2", "/əˈkɒm.ə.deɪt/", "menampung / menyediakan akomodasi / menyesuaikan",
     "Menyediakan tempat tinggal atau ruang yang cukup; menyesuaikan diri dengan kebutuhan.",
     "To provide lodging or sufficient space for; to adapt or make adjustments for someone.",
     ["Accommodation", "Accommodating", "Housing"], ["House", "Lodge", "Shelter", "Adapt", "Adjust", "Fit"], ["Reject", "Turn away", "Inconvenience"],
     "The modern convention center can accommodate more than eight thousand attendees.",
     "Universities often adjust lecture schedules to accommodate students who work part-time jobs to finance their tuition."),

    ("Accomplish", "verb", "B1", "/əˈkʌm.plɪʃ/", "menyelesaikan dengan sukses / mencapai target",
     "Berhasil menyelesaikan tugas, tujuan, atau impian melalui usaha dan ketekunan.",
     "To achieve or complete something successfully through effort, skill, or perseverance.",
     ["Accomplishment", "Accomplished", "Achieve"], ["Achieve", "Fulfill", "Execute", "Attain", "Realize"], ["Fail", "Abandon", "Forfeit", "Neglect"],
     "You can accomplish remarkable life goals by staying dedicated to daily deliberate practice.",
     "The multidisciplinary engineering team worked around the clock to accomplish the bridge construction project ahead of deadline."),

    ("Accord", "noun", "B2", "/əˈkɔːd/", "kesepakatan resmi / perjanjian / keharmonisan",
     "Persetujuan resmi atau traktat antara negara atau kelompok; keharmonisan pendapat.",
     "An official agreement, treaty, or harmonious concurrence between parties.",
     ["Accordance", "According", "Consensus"], ["Pact", "Treaty", "Agreement", "Consensus", "Harmony"], ["Discord", "Disagreement", "Conflict", "Dispute"],
     "Diplomats gathered in Geneva to sign a landmark bilateral peace accord.",
     "Both trading nations reached an amicable accord that eliminated restrictive tariffs on essential agricultural imports."),

    ("Account", "noun", "A2", "/əˈkaʊnt/", "rekening bank / akun / uraian penjelasan",
     "Catatan keuangan di bank; profil layanan digital; atau laporan narasi tentang suatu peristiwa.",
     "A financial arrangement with a bank; a digital profile; or a descriptive report of events.",
     ["Accountable", "Accountant", "Accounting"], ["Report", "Description", "Narrative", "Ledger", "Profile"], ["Concealment", "Suppression"],
     "She opened a high-yield savings account to build an emergency fund.",
     "The surviving eyewitness provided police detectives with a detailed first-hand account of the downtown bank robbery."),

    ("Accountable", "adjective", "B2", "/əˈkaʊn.tə.bəl/", "bertanggung jawab / wajib mempertanggungjawabkan",
     "Wajib menjelaskan atau menanggung konsekuensi atas tindakan dan keputusan yang diambil.",
     "Required or expected to justify actions or decisions; responsible for outcomes.",
     ["Accountability", "Account", "Responsible"], ["Responsible", "Answerable", "Liable", "Culpable"], ["Unaccountable", "Irresponsible", "Exempt", "Blameless"],
     "Government leaders must remain accountable to the public through transparent audits.",
     "Corporate governance frameworks ensure that board executives are held strictly accountable for shareholder value and ethical practices."),

    ("Accumulate", "verb", "B2", "/əˈkjuː.mjə.leɪt/", "mengumpulkan / menimbun / terakumulasi bertambah",
     "Mengumpulkan atau menambah jumlah sesuatu secara bertahap dalam kurun waktu tertentu.",
     "To gather or acquire an increasing quantity or number over a period of time.",
     ["Accumulation", "Cumulative", "Amass"], ["Amass", "Gather", "Collect", "Build up", "Hoard"], ["Disperse", "Scatter", "Dissipate", "Deplete"],
     "Dust and archived folders accumulate rapidly inside neglected office storage closets.",
     "Long-term index fund investors accumulate substantial compound interest over decades of consistent monthly contributions."),

    ("Accurate", "adjective", "B1", "/ˈæk.jə.rət/", "akurat / tepat / cermat tanpa keliru",
     "Benar dalam setiap rincian; bebas dari kekeliruan atau kesalahan faktual.",
     "Correct in all details; conforming exactly to truth or standard measurements.",
     ["Accuracy", "Accurately", "Inaccurate"], ["Precise", "Exact", "Correct", "Flawless", "True"], ["Inaccurate", "Incorrect", "Erroneous", "Faulty"],
     "Laboratory technicians must record accurate measurements to ensure valid experimental findings.",
     "Historians cross-reference multiple primary sources to construct an accurate narrative of ancient archaeological discoveries."),

    ("Accuse", "verb", "B1", "/əˈkjuːz/", "menuduh / mendakwa kesalahan seseorang",
     "Menyatakan bahwa seseorang telah melakukan kejahatan, pelanggaran, atau tindakan tercela.",
     "To claim that someone has done something illegal, wrong, or dishonest.",
     ["Accusation", "Accuser", "Accused"], ["Charge", "Indict", "Blame", "Implicate", "Censure"], ["Defend", "Exonerate", "Absolve", "Acquit"],
     "You should never accuse a colleague of misconduct without solid verifiable evidence.",
     "The public prosecutor stood up before the jury to accuse the corporate executive of intentional securities fraud."),

    ("Accustomed", "adjective", "B2", "/əˈkʌs.təmd/", "terbiasa / lazim dengan suatu keadaan",
     "Sudah akrab dan merasa wajar dengan suatu kebiasaan, lingkungan, atau kondisi.",
     "Customary, usual, or having become familiar with something through repeated exposure.",
     ["Accustom", "Custom", "Habituated"], ["Habituated", "Used to", "Familiar", "Inured"], ["Unaccustomed", "Unfamiliar", "Unused"],
     "Living in Oslo for five years made her accustomed to sub-zero winter temperatures.",
     "Athletes become accustomed to rigorous physical training regimens through steady incremental conditioning."),

    ("Achieve", "verb", "A2", "/əˈtʃiːv/", "mencapai / meraih prestasi / mewujudkan cita-cita",
     "Berhasil memperoleh hasil yang diinginkan berkat kerja keras dan keterampilan.",
     "To reach a desired objective, milestone, or standard through effort and skill.",
     ["Achievement", "Achiever", "Achievable"], ["Attain", "Accomplish", "Realize", "Fulfill", "Gain"], ["Fail", "Forfeit", "Miss", "Lose"],
     "She worked tirelessly to achieve her childhood aspiration of becoming a cardiac surgeon.",
     "Developing countries strive to achieve universal primary education and sustainable economic independence through civic investment."),

    ("Achievement", "noun", "B1", "/əˈtʃiːv.mənt/", "prestasi / pencapaian gemilang / keberhasilan",
     "Sesuatu yang berhasil diraih dengan hebat melalui usaha, tekad, atau keberanian.",
     "A notable thing done successfully with effort, skill, dedication, or courage.",
     ["Achieve", "Achiever", "Triumph"], ["Feat", "Triumph", "Accomplishment", "Success", "Exploit"], ["Failure", "Defeat", "Loss", "Collapse"],
     "Earning a doctoral fellowship in computational linguistics was her greatest academic achievement.",
     "The team celebrated the monumental achievement of mapping the complete genetic sequence of the endangered plant species."),

    ("Acknowledge", "verb", "B2", "/əkˈnɒl.ɪdʒ/", "mengakui / menyatakan apresiasi / membalas",
     "Menerima atau mengakui keberadaan, kebenaran, atau kontribusi seseorang secara resmi.",
     "To accept or admit the truth, existence, or importance of someone or something.",
     ["Acknowledgment", "Acknowledged", "Recognize"], ["Admit", "Recognize", "Grant", "Concede", "Validate"], ["Deny", "Disown", "Ignore", "Reject"],
     "The managing director was quick to acknowledge the engineering team's exceptional dedication.",
     "Academic authors always acknowledge research grants and peer reviewers in the introductory section of their publications."),

    ("Acoustic", "adjective", "B2", "/əˈkuː.stɪk/", "akustik / berkaitan dengan bunyi dan pendengaran",
     "Berkaitan dengan suara, indera pendengaran, atau instrumen musik non-elektronik.",
     "Relating to sound, auditory perception, or non-electrical musical instruments.",
     ["Acoustics", "Acoustically", "Auditory"], ["Auditory", "Sonic", "Sound", "Hearing"], ["Silent", "Inaudible", "Visual"],
     "The singer performed an intimate acoustic version of her classic folk ballad.",
     "Architects incorporated perforated wall panels to enhance the acoustic clarity of the university concert hall."),

    ("Acquire", "verb", "B2", "/əˈkwaɪər/", "memperoleh / mendapatkan / menguasai keahlian",
     "Membeli atau mendapatkan kepemilikan aset; menguasai pengetahuan atau keterampilan baru.",
     "To buy or obtain an asset; to learn or develop a skill, habit, or quality.",
     ["Acquisition", "Acquired", "Obtain"], ["Obtain", "Procure", "Gain", "Attain", "Master"], ["Lose", "Forfeit", "Relinquish", "Surrender"],
     "Children acquire complex grammatical structures naturally through daily social conversations.",
     "The technology conglomerate moved swiftly to acquire several promising cybersecurity startups to bolster its cloud infrastructure."),

    ("Acquisition", "noun", "B2", "/ˌæk.wɪˈzɪʃ.ən/", "akuisisi / perolehan barang / pembelian aset",
     "Tindakan memperoleh aset, perusahaan, atau kepemilikan barang; keterampilan yang diperoleh.",
     "The act of acquiring or buying something; an asset or valuable item gained.",
     ["Acquire", "Acquired", "Procurement"], ["Procurement", "Purchase", "Gain", "Addition", "Takeover"], ["Disposal", "Sale", "Divestment", "Loss"],
     "The museum celebrated the rare acquisition of an authentic 17th-century Renaissance portrait.",
     "Early childhood language acquisition progresses rapidly between the ages of two and five through parental engagement."),

    ("Activate", "verb", "B1", "/ˈæk.tɪ.veɪt/", "mengaktifkan / menghidupkan fungsi",
     "Menjadikan sesuatu berfungsi, berjalan, atau beroperasi secara aktif.",
     "To make something active, operational, or capable of functioning.",
     ["Activation", "Active", "Activator"], ["Trigger", "Enable", "Initiate", "Turn on", "Energize"], ["Deactivate", "Disable", "Turn off", "Halt"],
     "You must scan the authentication QR code to activate your digital bank wallet.",
     "Sensors embedded along the hallway automatically activate energy-efficient LED lighting when movement is detected at night."),

    ("Acute", "adjective", "B2", "/əˈkjuːt/", "akut / parah / tajam / peka sekali",
     "Sangat parah, mendesak, atau kritis; memiliki indera pengamatan yang sangat tajam.",
     "Experienced to a severe or intense degree; having a keen perceptive ability.",
     ["Acutely", "Acuteness", "Sharp"], ["Severe", "Critical", "Sharp", "Intense", "Keen"], ["Mild", "Chronic", "Dull", "Blunt"],
     "The patient was admitted to the emergency ward suffering from acute appendicitis.",
     "Dogs possess an acute sense of olfactory detection, enabling them to locate trapped earthquake survivors beneath rubble."),

    ("Adapt", "verb", "B1", "/əˈdæpt/", "menyesuaikan diri / mengadaptasi karya",
     "Mengubah perilaku atau struktur agar cocok dengan kondisi baru; menggubah buku ke film.",
     "To change or adjust to suit new conditions; to modify a work for a new medium.",
     ["Adaptation", "Adaptable", "Adaptive"], ["Adjust", "Modify", "Accommodate", "Conform", "Tailor"], ["Resist", "Clash", "Remain rigid"],
     "Polar bears have specialized physical traits that allow them to adapt to arctic tundra climates.",
     "The acclaimed playwright decided to adapt the best-selling historical biography into a compelling three-act Broadway drama."),

    ("Adequate", "adjective", "B1", "/ˈæd.ə.kwət/", "memadai / cukup memenuhi syarat",
     "Cukup dalam kuantitas atau kualitas untuk memenuhi kebutuhan atau tujuan tertentu.",
     "Satisfactory or acceptable in quality or quantity to meet a specified requirement.",
     ["Adequacy", "Adequately", "Inadequate"], ["Sufficient", "Enough", "Ample", "Satisfactory", "Competent"], ["Inadequate", "Insufficient", "Deficient", "Lacking"],
     "Make sure you get adequate sleep each night before taking strenuous university examinations.",
     "The humanitarian agency established water purification plants to ensure an adequate supply of potable drinking water for refugees."),

    ("Adhere", "verb", "B2", "/ədˈhɪər/", "menempel erat / mematuhi prinsip/aturan",
     "Melekat kuat pada permukaan; tetap setia dan patuh pada pedoman atau keyakinan.",
     "To stick firmly to a surface; to follow or uphold a rule, standard, or principle faithfully.",
     ["Adherence", "Adhesive", "Adherent"], ["Stick", "Cling", "Comply", "Follow", "Uphold"], ["Detach", "Separate", "Violate", "Flout"],
     "All medical personnel must strictly adhere to sterile hygiene protocols in operating theaters.",
     "The waterproof adhesive label will adhere securely to glass and metal surfaces even in freezing conditions."),

    ("Adjacent", "adjective", "B2", "/əˈdʒeɪ.sənt/", "bersebelahan / berdampingan / berdekatan",
     "Berada tepat di sebelah atau sangat dekat tanpa ada pemisah yang jauh.",
     "Next to, adjoining, or neighboring something with a shared boundary.",
     ["Adjacency", "Neighboring", "Contiguous"], ["Neighboring", "Adjoining", "Contiguous", "Bordering", "Next"], ["Distant", "Remote", "Far", "Separate"],
     "Our biology research laboratory is located adjacent to the university greenhouse.",
     "The hotel offers luxurious family suites with adjacent interconnecting bedrooms for convenience."),

    ("Admire", "verb", "A2", "/ədˈmaɪər/", "mengagumi / memuji kebaikan seseorang",
     "Menaruh rasa hormat, takjub, dan apresiasi tinggi terhadap seseorang atau karyanya.",
     "To regard someone or something with deep respect, wonder, approval, or affection.",
     ["Admiration", "Admirable", "Admirer"], ["Respect", "Appreciate", "Esteem", "Praise", "Revere"], ["Despise", "Disdain", "Scorn", "Criticize"],
     "I truly admire her unwavering perseverance in overcoming physical adversity.",
     "Art enthusiasts from across the globe gather at the gallery to admire masterworks painted during the Renaissance era."),

    ("Adopt", "verb", "B1", "/əˈdɒpt/", "mengadopsi anak / menerapkan kebijakan/metode",
     "Mengambil anak orang lain menjadi anak sah; menerima dan mulai menggunakan metode baru.",
     "To legally take another's child as one's own; to choose to take up a method or idea.",
     ["Adoption", "Adoptive", "Adopted"], ["Embrace", "Implement", "Assume", "Take on", "Foster"], ["Reject", "Abandon", "Discard", "Repudiate"],
     "The company decided to adopt agile project management methods to streamline product releases.",
     "After years of contemplation, the loving couple decided to adopt a child from a local orphanage."),

    ("Advocate", "verb", "B2", "/ˈæd.və.keɪt/", "menganjurkan / membela hak / menyuarakan",
     "Mendukung, membela, atau merekomendasikan suatu gagasan atau kebijakan secara terbuka.",
     "To publicly recommend, support, or speak in favor of a particular policy or cause.",
     ["Advocacy", "Advocate", "Proponent"], ["Champion", "Support", "Promote", "Espouse", "Endorse"], ["Oppose", "Condemn", "Denounce", "Discourage"],
     "Environmental scientists strongly advocate for immediate transition toward renewable solar energy.",
     "Civil rights lawyers tirelessly advocate for legal reforms that protect vulnerable marginalized populations."),

    ("Aesthetic", "adjective", "B2", "/esˈθet.ɪk/", "estetis / bernilai keindahan / artistik",
     "Berkaitan dengan keindahan alam atau seni; memiliki apresiasi terhadap unsur seni visual.",
     "Concerned with beauty, art, or the appreciation of artistic elegance.",
     ["Aesthetics", "Aesthetically", "Artistic"], ["Artistic", "Harmonious", "Beautiful", "Tasteful", "Refined"], ["Ugly", "Unattractive", "Grotesque", "Crude"],
     "The minimalist cafe was designed with a warm, natural aesthetic combining wood and stone.",
     "Modern architecture harmonizes structural engineering resilience with compelling aesthetic elegance."),

    ("Afford", "verb", "A2", "/əˈfɔːd/", "mampu membeli / menyanggupi biaya/waktu",
     "Memiliki cukup uang atau waktu luang untuk melakukan atau membeli sesuatu.",
     "To have enough money or time to be able to buy or do something without hardship.",
     ["Affordable", "Affordability", "Cost"], ["Bear", "Manage", "Sustain", "Provide", "Furnish"], ["Lack funds", "Forgo", "Cannot bear"],
     "With her new promotion, she can finally afford to buy a modest suburban apartment.",
     "Busy university students often feel they cannot afford to waste a single hour during examination revision weeks."),

    ("Affordable", "adjective", "B1", "/əˈfɔː.də.bəl/", "terjangkau / ramah di kantong",
     "Memiliki harga yang wajar sehingga dapat dibeli oleh kebanyakan orang tanpa beban berat.",
     "Reasonably priced and within the financial means of ordinary people.",
     ["Afford", "Affordability", "Inexpensive"], ["Inexpensive", "Reasonable", "Economical", "Budget-friendly"], ["Expensive", "Costly", "Exorbitant", "Pricy"],
     "The municipal government launched an initiative to construct affordable housing for nurses and teachers.",
     "Renewable solar panels have become significantly more affordable due to mass production breakthroughs."),

    ("Aggressive", "adjective", "B1", "/əˈɡres.ɪv/", "agresif / giat menyerang / bertekad kuat",
     "Cenderung menyerang atau bersikap konfrontatif; sangat tegas dan giat mengejar target bisnis.",
     "Ready or likely to attack or confront; behaving with forceful determination in pursuing goals.",
     ["Aggression", "Aggressively", "Aggressor"], ["Combative", "Hostile", "Assertive", "Forceful", "Fierce"], ["Peaceful", "Passive", "Gentle", "Timid"],
     "Predatory wolves become aggressive when defending their newborn cubs against intruders.",
     "The digital marketing startup adopted an aggressive outreach campaign to capture regional market share."),

    ("Agitate", "verb", "C1", "/ˈædʒ.ɪ.teɪt/", "menggelisahkan / menghasut / mengaduk cairan",
     "Membuat cemas atau gelisah; menggerakkan massa demi tuntutan politik; mengocok cairan.",
     "To make someone troubled or nervous; to campaign vigorously for political change; to stir.",
     ["Agitation", "Agitator", "Disturb"], ["Disturb", "Fluster", "Perturb", "Stir", "Rouse"], ["Calm", "Soothe", "Pacify", "Quiet"],
     "Unexpected flight cancellations agitate stranded airport passengers during holiday seasons.",
     "Factory workers began to agitate for safer working conditions and fair hourly overtime compensation."),

    ("Alarming", "adjective", "B2", "/əˈlɑː.mɪŋ/", "mengkhawatirkan / mencemaskan / genting",
     "Menimbulkan rasa takut, cemas, atau kekhawatiran yang mendalam.",
     "Causing worry, distress, or apprehension; dangerously urgent.",
     ["Alarm", "Alarmed", "Worrying"], ["Frightening", "Disturbing", "Shocking", "Worrisome", "Dire"], ["Reassuring", "Calming", "Comforting", "Soothing"],
     "The rapid deforestation rate along tropical watersheds is truly alarming for climatologists.",
     "Doctors reported an alarming spike in respiratory infections following severe seasonal smog events."),

    ("Allocate", "verb", "B2", "/ˈæl.ə.keɪt/", "mengalokasikan / membagikan jatah anggaran",
     "Menetapkan atau membagikan sumber daya, dana, atau waktu untuk tujuan tertentu.",
     "To distribute resources, funds, or duties for a specific predetermined purpose.",
     ["Allocation", "Allotted", "Distribute"], ["Assign", "Distribute", "Allot", "Earmark", "Apportion"], ["Withhold", "Retain", "Keep back", "Deny"],
     "The city council voted to allocate ten million dollars to reconstruct aging public bridges.",
     "Project managers must allocate sufficient time buffers to accommodate unexpected software testing bottlenecks."),

    ("Alter", "verb", "B2", "/ˈɒl.tər/", "mengubah / memodifikasi sedikit",
     "Membuat perubahan kecil namun signifikan pada bentuk, sifat, atau pakaian.",
     "To change or cause to change in character, composition, or appearance partially.",
     ["Alteration", "Alternate", "Modify"], ["Modify", "Adjust", "Transform", "Vary", "Revise"], ["Maintain", "Preserve", "Keep constant", "Retain"],
     "He took the tailored wool suit to the tailor to alter the trouser hemline.",
     "Sudden shifts in consumer dietary preferences alter food manufacturing supply chains worldwide."),

    ("Ambiguous", "adjective", "B2", "/æmˈbɪɡ.ju.əs/", "ambigu / bermakna ganda / tidak jelas",
     "Dapat dipahami dalam lebih dari satu cara; maknanya kabur atau membingungkan.",
     "Open to more than one interpretation; having a double or uncertain meaning.",
     ["Ambiguity", "Ambiguously", "Unclear"], ["Equivocal", "Vague", "Obscure", "Unclear", "Doubtful"], ["Clear", "Explicit", "Unambiguous", "Definite"],
     "The contract clause was worded in an ambiguous way that led to legal dispute between the parties.",
     "Philosophers avoid ambiguous terminology to ensure their ethical treatises can be reasoned with absolute clarity."),

    ("Ambition", "noun", "B1", "/æmˈbɪʃ.ən/", "ambisi / cita-cita besar / tekad maju",
     "Keinginan kuat dan tekad membara untuk meraih kesuksesan, jabatan, atau prestasi besar.",
     "A strong desire and determination to achieve success, power, or honor.",
     ["Ambitious", "Ambitiously", "Aspiration"], ["Aspiration", "Goal", "Drive", "Endeavor", "Objective"], ["Apathy", "Laziness", "Indifference"],
     "Her childhood ambition was to conduct astronomical research at the European Space Agency.",
     "Unchecked political ambition without moral integrity often leads leaders into severe ethical compromise."),

    ("Amend", "verb", "C1", "/əˈmend/", "mengamandemen / memperbaiki pasal/dokumen",
     "Mengubah secara resmi bunyi naskah undang-undang atau perjanjian untuk memperbaikinya.",
     "To make minor changes to a text, law, or legislative bill to improve or update it.",
     ["Amendment", "Amends", "Revise"], ["Revise", "Modify", "Correct", "Rectify", "Alter"], ["Worsen", "Harm", "Ruin", "Repeal"],
     "Lawmakers convened a special parliamentary session to amend the national data privacy law.",
     "The committee agreed to amend the charter clauses to guarantee equitable voting rights for all members."),

    ("Ample", "adjective", "B2", "/ˈæm.pəl/", "cukup leluasa / berlimpah luas / lapang",
     "Lebih dari cukup dalam hal ruang, waktu, atau pasokan kebutuhan.",
     "Enough or more than enough; plentiful and spacious.",
     ["Amply", "Ampleness", "Plentiful"], ["Plentiful", "Abundant", "Spacious", "Generous", "Sufficient"], ["Meager", "Scarce", "Cramped", "Insufficient"],
     "There is ample parking space available behind the new metropolitan shopping center.",
     "The thesis defense committee granted the candidate ample time to elaborate on her statistical methodology."),

    ("Analyze", "verb", "B1", "/ˈæn.əl.aɪz/", "menganalisis / membedah data secara mendalam",
     "Memeriksa sesuatu secara metodis dan terperinci untuk memahami struktur atau polanya.",
     "To examine methodically and in detail the constitution or structure of something.",
     ["Analysis", "Analyst", "Analytical"], ["Examine", "Investigate", "Evaluate", "Scrutinize", "Study"], ["Synthesize", "Assemble", "Ignore", "Overlook"],
     "Data scientists analyze millions of server log entries to detect suspicious cyber threats.",
     "Economists analyze inflationary trends over consecutive quarters before formulating benchmark interest rate adjustments."),

    ("Anchor", "noun", "B2", "/ˈæŋ.kər/", "jangkar kapal / penyiar utama / penopang kokoh",
     "Alat berat penahan kapal di laut; pembawa berita televisi utama; tumpuan andalan.",
     "A heavy metal device cast into water to moor a vessel; a reliable main presenter or pillar.",
     ["Anchorage", "Anchored", "Moor"], ["Moor", "Support", "Mainstay", "Presenter", "Pillar"], ["Drifter", "Unstable element"],
     "The ship dropped anchor in the sheltered bay during the severe tropical storm.",
     "She served as the trusted evening news anchor for over three decades on national public television."),

    ("Ancient", "adjective", "A2", "/ˈeɪn.ʃənt/", "kuno / zaman purbakala / antik",
     "Berasal dari masa lampau ribuan tahun yang lalu; sangat tua dalam sejarah peradaban.",
     "Belonging to the very distant past and no longer in existence.",
     ["Antiquity", "Antique", "Archaic"], ["Archaic", "Antique", "Historic", "Primeval", "Timeworn"], ["Modern", "Contemporary", "Recent", "New"],
     "Archaeologists unearthed ancient clay tablets inscribed with Mesopotamian cuneiform script.",
     "The ancient stone pyramids of Giza continue to evoke profound awe and architectural admiration."),

    ("Anticipate", "verb", "B2", "/ænˈtɪs.ɪ.peɪt/", "mengantisipasi / menduga sebelum terjadi",
     "Memperkirakan kemungkinan peristiwa di masa depan dan mempersiapkan langkah menghadapinya.",
     "To foresee, expect, or predict a future event and take action in readiness.",
     ["Anticipation", "Anticipatory", "Foresee"], ["Foresee", "Expect", "Predict", "Await", "Prepare for"], ["Ignore", "Doubt", "Overlook", "Neglect"],
     "Meteorologists anticipate heavy monsoon rains across northern agricultural plains this weekend.",
     "Seasoned chess grandmasters anticipate their opponent's defensive moves six turns in advance."),

    ("Anxious", "adjective", "B1", "/ˈæŋk.ʃəs/", "cemas / waswas / gelisah penuh kekhawatiran",
     "Merasa gelisah, takut, atau tidak tenang tentang kejadian yang tidak pasti.",
     "Experiencing worry, unease, or nervousness about an imminent event or uncertain outcome.",
     ["Anxiety", "Anxiously", "Anxiousness"], ["Apprehensive", "Worried", "Nervous", "Uneasy", "Fearful"], ["Calm", "Relaxed", "Confident", "Serene"],
     "She felt understandably anxious while waiting for the surgical biopsy laboratory results.",
     "High school seniors often feel anxious during the final week before college admission notifications are published."),

    ("Apparent", "adjective", "B2", "/əˈpær.ənt/", "tampak jelas / nyata kelihatan / kasat mata",
     "Mudah dilihat atau dipahami; terlihat nyata di permukaan meskipun mungkin perlu diteliti lagi.",
     "Clearly visible or understood; obvious; seeming rather than real.",
     ["Apparently", "Appearance", "Obvious"], ["Obvious", "Evident", "Manifest", "Conspicuous", "Distinct"], ["Hidden", "Obscure", "Doubtful", "Unclear"],
     "It became immediately apparent that the electrical generator had suffered fatal water damage.",
     "Her genuine passion for marine conservation was apparent in every lecture she delivered across campuses."),

    ("Applaud", "verb", "B2", "/əˈplɔːd/", "bertepuk tangan / memuji keberhasilan",
     "Menepukkan kedua tangan sebagai tanda kagum; menyambut baik suatu keputusan bijak.",
     "To show approval or praise by clapping the hands; to praise enthusiastically.",
     ["Applause", "Applaudable", "Acclaim"], ["Clap", "Cheer", "Commend", "Praise", "Acclaim"], ["Boo", "Jeer", "Hiss", "Condemn", "Censure"],
     "The enthusiastic audience stood up to applaud the symphony orchestra after the finale.",
     "Consumer advocacy groups applaud the government's decisive move to cap predatory interest rates on payday loans."),

    ("Applause", "noun", "B1", "/əˈplɔːz/", "tepuk tangan riuh / sambutan apresiasi",
     "Suara tepukan tangan meriah dari kerumunan penonton untuk menunjukkan kekaguman.",
     "Approval or praise expressed by clapping hands in unison.",
     ["Applaud", "Clapping", "Ovation"], ["Clapping", "Ovation", "Cheering", "Acclamation", "Praise"], ["Jeering", "Boos", "Hissing", "Silence"],
     "A deafening burst of applause filled the auditorium when the Nobel laureate stepped on stage.",
     "The charismatic stage actor bowed gracefully to acknowledge the thunderous standing applause of the theatergoers."),

    ("Appreciate", "verb", "B1", "/əˈpriː.ʃi.eɪt/", "mengapresiasi / menghargai / bertambah nilainya",
     "Menyadari nilai baik seseorang atau sesuatu; bersyukur; mengalami kenaikan harga aset.",
     "To recognize the full worth or quality of something; to rise in economic value.",
     ["Appreciation", "Appreciative", "Appreciable"], ["Value", "Treasure", "Esteem", "Acknowledge", "Gain value"], ["Undervalue", "Depreciate", "Disregard", "Degrade"],
     "I deeply appreciate all the generous mentorship you provided during my internship term.",
     "Real estate properties in well-connected transit districts tend to appreciate steadily over economic cycles."),

    ("Apprehensive", "adjective", "C1", "/ˌæp.rɪˈhen.sɪv/", "waswas / diliputi kekhawatiran / cemas",
     "Merasa cemas atau takut bahwa sesuatu yang buruk atau tidak menyenangkan akan terjadi.",
     "Anxious or fearful that something bad, difficult, or unpleasant will happen.",
     ["Apprehension", "Apprehensively", "Fearful"], ["Uneasy", "Anxious", "Worried", "Nervous", "Hesitant"], ["Confident", "Assured", "Unconcerned", "Tranquil"],
     "She felt apprehensive about moving alone to a foreign metropolis where she spoke no local tongue.",
     "Patients awaiting complex orthopedic surgeries are naturally apprehensive regarding postoperative recovery timelines."),

    ("Arbitrary", "adjective", "B2", "/ˈɑː.bɪ.trər.i/", "sewenang-wenang / acak tanpa alasan jelas",
     "Didasarkan pada kemauan pribadi semata atau pilihan acak, bukan pada hukum atau logika.",
     "Based on random choice or personal whim, rather than any reason or legal principle.",
     ["Arbitrarily", "Arbitrariness", "Random"], ["Capricious", "Random", "Discretionary", "Dictatorial", "Unreasonable"], ["Rational", "Reasoned", "Systematic", "Just", "Consistent"],
     "The company imposed an arbitrary dress code policy that sparked discontent among creative staff.",
     "Constitutional democracies establish independent courts to shield citizens from arbitrary detention and lawless decrees."),

    ("Articulate", "adjective", "C1", "/ɑːˈtɪk.jə.lət/", "fasih berbicara / runtut menyampaikan pikiran",
     "Mampu mengekspresikan gagasan dan emosi dengan jelas, fasih, dan runtut.",
     "Able to express thoughts and ideas clearly, fluently, and effectively in speech or writing.",
     ["Articulately", "Articulation", "Eloquent"], ["Eloquent", "Lucid", "Fluent", "Coherent", "Expressive"], ["Inarticulate", "Tongue-tied", "Muffled", "Incoherent"],
     "She gave an articulate and persuasive keynote presentation on urban green spaces.",
     "A diplomat must remain remarkably articulate even when navigating tense multilateral treaty renegotiations."),

    ("Artificial", "adjective", "A2", "/ˌɑː.tɪˈfɪʃ.əl/", "buatan / tiruan / sintetis / artifisial",
     "Dibuat oleh manusia sebagai tiruan dari benda alami; tidak asli.",
     "Made or produced by human beings rather than occurring naturally.",
     ["Artificially", "Artificiality", "Synthetic"], ["Synthetic", "Man-made", "Imitation", "Fabricated", "Simulated"], ["Natural", "Genuine", "Authentic", "Real"],
     "Artificial intelligence systems process vast natural language corpora to translate languages accurately.",
     "The football pitch was covered in durable artificial turf to withstand heavy rain throughout the winter season."),

    ("Aspire", "verb", "B2", "/əˈspaɪər/", "bercita-cita tinggi / mendambakan pencapaian",
     "Mengarahkan harapan dan usaha kuat untuk meraih kedudukan atau tujuan mulia.",
     "To direct one's hopes, ambition, or strong desire toward achieving something great.",
     ["Aspiration", "Aspiring", "Ambition"], ["Aim", "Desire", "Seek", "Strive", "Yearn"], ["Despair", "Surrender", "Give up"],
     "Many young medical students aspire to work for Doctors Without Borders in humanitarian crisis zones.",
     "Emerging entrepreneurs aspire to create environmentally circular products that eliminate single-use plastic waste entirely."),

    ("Assert", "verb", "B2", "/əˈsɜːt/", "menegaskan / menyatakan dengan tegas / menuntut hak",
     "Menyatakan suatu fakta atau keyakinan secara kuat dan percaya diri; menegakkan wewenang.",
     "To state a fact or belief confidently and forcefully; to cause others to recognize authority.",
     ["Assertion", "Assertive", "Assertiveness"], ["Declare", "Maintain", "Affirm", "Insist", "Contend"], ["Deny", "Retract", "Conceal", "Disclaim"],
     "The defense attorney stood to assert her client's constitutional right to a speedy trial.",
     "When working in multidisciplinary teams, professionals must learn to assert their domain expertise respectfully."),

    ("Assess", "verb", "B2", "/əˈses/", "menilai / menakar kualitas / menaksir nilai",
     "Mengevaluasi atau memperkirakan sifat, kemampuan, kondisi, atau nilai moneter sesuatu.",
     "To evaluate or estimate the nature, ability, quality, or financial value of something.",
     ["Assessment", "Assessor", "Assessable"], ["Evaluate", "Appraise", "Judge", "Estimate", "Gauge"], ["Ignore", "Neglect", "Overlook"],
     "Teachers use formative quizzes to assess students' comprehension of weekly physics lectures.",
     "Insurance adjusters arrived at the flood-damaged farm to assess structural losses to grain silos and tractors."),

    ("Assessment", "noun", "B2", "/əˈses.mənt/", "penilaian / evaluasi menyeluruh / taksiran",
     "Proses menimbang dan mengukur mutu, kinerja, atau kelayakan suatu hal secara teliti.",
     "The evaluation or estimation of the nature, quality, or ability of someone or something.",
     ["Assess", "Assessor", "Appraisal"], ["Evaluation", "Appraisal", "Analysis", "Review", "Judgment"], ["Neglect", "Ignorance"],
     "The comprehensive environmental impact assessment must be completed before dam construction commences.",
     "Continuous classroom assessment provides educators with actionable diagnostic feedback on student learning gaps."),

    ("Asset", "noun", "B2", "/ˈæs.et/", "aset berharga / modal utama / kekayaan",
     "Benda bernilai ekonomis yang dimiliki; orang atau sifat berguna yang menjadi keunggulan.",
     "A useful or valuable quality, person, or piece of property owned by an entity.",
     ["Assets", "Resource", "Wealth"], ["Property", "Resource", "Advantage", "Holding", "Treasure"], ["Liability", "Disadvantage", "Debt", "Burden"],
     "Her multilingual fluency proved to be an invaluable asset during international trade negotiations.",
     "Accounting audits catalog all fixed and liquid corporate assets to ensure compliance with securities transparency laws."),

    ("Assign", "verb", "B1", "/əˈsaɪn/", "menugaskan / membebankan tugas / menetapkan",
     "Memberikan pekerjaan atau tanggung jawab tertentu kepada seseorang; menetapkan nilai.",
     "To allocate a job, task, or duty to someone; to designate for a specific purpose.",
     ["Assignment", "Assignee", "Allocate"], ["Allot", "Designate", "Appoint", "Delegate", "Task"], ["Withdraw", "Revoke", "Withhold"],
     "The professor will assign weekly research essays to sharpen students' critical thinking skills.",
     "Project managers assign technical tasks according to individual team members' specialized engineering strengths."),

    ("Assignment", "noun", "B1", "/əˈsaɪn.mənt/", "tugas kuliah/kerja / penugasan resmi",
     "Pekerjaan atau kewajiban yang diberikan kepada seseorang sebagai bagian dari studi atau profesi.",
     "A piece of work or duty allocated to someone as part of a job or course of study.",
     ["Assign", "Assignee", "Task"], ["Task", "Duty", "Mission", "Project", "Homework"], ["Discharge", "Freedom"],
     "Make sure to submit your chemistry lab assignment before midnight via the digital student portal.",
     "The overseas investigative journalism assignment required the reporter to spend six months embedded in refugee camps."),

    ("Assist", "verb", "B1", "/əˈsɪst/", "membantu / menolong / mendampingi",
     "Memberikan bantuan atau dukungan berupa tenaga, pemikiran, atau fasilitas kepada orang lain.",
     "To help someone typically by doing a share of the work or providing guidance.",
     ["Assistance", "Assistant", "Aid"], ["Help", "Aid", "Support", "Back", "Facilitate"], ["Hinder", "Obstruct", "Impede", "Block"],
     "Paramedics arrived immediately to assist the injured survivors of the highway accident.",
     "Advanced robotic surgical arms assist experienced orthopedic doctors during delicate joint replacement operations."),

    ("Assistance", "noun", "B1", "/əˈsɪs.təns/", "bantuan / uluran pertolongan / subsidi",
     "Tindakan menolong seseorang atau penyediaan sarana yang meringankan beban pekerjaan.",
     "The provision of money, resources, or effort to help someone accomplish a task.",
     ["Assist", "Assistant", "Aid"], ["Help", "Aid", "Support", "Relief", "Backing"], ["Hindrance", "Obstruction", "Impediment"],
     "The international community pledged emergency humanitarian assistance following the devastating cyclone.",
     "Low-income university students can apply for financial assistance programs to cover textbook and lodging expenses."),

    ("Associate", "verb", "B2", "/əˈsəʊ.si.eɪt/", "mengaitkan / menghubungkan pikiran / bergaul",
     "Menghubungkan satu hal dengan hal lain dalam ingatan; bergaul atau bermitra kerja.",
     "To connect someone or something in one's mind with something else; to partner with.",
     ["Association", "Associated", "Ally"], ["Connect", "Link", "Relate", "Partner", "Affiliate"], ["Dissociate", "Separate", "Disconnect", "Alienate"],
     "Most people associate the fragrant scent of lavender with calmness and peaceful slumber.",
     "Scientists associate chronic sleep deprivation with elevated risks of metabolic and cardiovascular dysfunctions."),

    ("Association", "noun", "B2", "/əˌsəʊ.siˈeɪ.ʃən/", "asosiasi / perkumpulan resmi / hubungan asosiatif",
     "Kelompok orang yang berserikat untuk tujuan bersama; hubungan mental antara konsep.",
     "An organized group of people with a common purpose; a mental connection between concepts.",
     ["Associate", "Affiliation", "Society"], ["Organization", "Society", "Union", "Alliance", "League"], ["Dissociation", "Disorganization", "Separation"],
     "She was elected president of the National Medical Association for her healthcare advocacy.",
     "Psychologists use word association experiments to uncover subconscious cognitive responses in clinical patients."),

    ("Assume", "verb", "B1", "/əˈsjuːm/", "mengasumsikan / menduga tanpa bukti / memikul jabatan",
     "Menganggap sesuatu benar tanpa memiliki bukti pasti; mengambil alih tanggung jawab/peran.",
     "To suppose to be the case without proof; to take on a responsibility, role, or position.",
     ["Assumption", "Assumed", "Presume"], ["Presume", "Suppose", "Take for granted", "Undertake", "Adopt"], ["Know", "Prove", "Relinquish", "Deny"],
     "Do not simply assume that everyone understands technical jargon without clarifying definitions.",
     "The newly appointed chief executive officer will assume official corporate duties beginning next Monday."),

    ("Assumption", "noun", "B2", "/əˈsʌmp.ʃən/", "asumsi / anggapan dasar / praduga",
     "Sesuatu yang diterima sebagai kebenaran tanpa perlu pembuktian langsung.",
     "A thing that is accepted as true or certain to happen, without concrete proof.",
     ["Assume", "Presumption", "Hypothesis"], ["Presumption", "Supposition", "Hypothesis", "Premise", "Belief"], ["Fact", "Certainty", "Proof", "Reality"],
     "The economic forecast was based on the optimistic assumption that fuel prices would stabilize.",
     "Researchers must state every theoretical assumption explicitly to ensure other scientists can reproduce experimental findings."),

    ("Astonish", "verb", "B2", "/əˈstɒn.ɪʃ/", "mengejutkan / membuat takjub terperangah",
     "Membuat seseorang sangat terkejut, kagum, atau terpukau dengan peristiwa luar biasa.",
     "To surprise or impress someone greatly; to strike with sudden wonder.",
     ["Astonishing", "Astonishment", "Astound"], ["Astound", "Amaze", "Surprise", "Stun", "Flabbergast"], ["Expect", "Bore", "Leave unimpressed"],
     "Her extraordinary vocal range never fails to astonish audiences at the grand opera hall.",
     "Astronomers discover cosmic deep-space phenomena that consistently astonish the international scientific community."),

    ("Atheist", "noun", "C1", "/ˈeɪ.θi.ɪst/", "ateis / orang yang tidak memercayai tuhan",
     "Seseorang yang tidak mempercayai atau menolak keberadaan Tuhan atau dewa-dewa.",
     "A person who disbelieves or lacks belief in the existence of God or gods.",
     ["Atheism", "Atheistic", "Secular"], ["Nonbeliever", "Skeptic", "Secularist", "Freethinker"], ["Theist", "Believer", "Devotee"],
     "As an atheist, he approached moral philosophy from a purely secular humanist perspective.",
     "The comparative religion forum invited theist and atheist scholars to debate the metaphysical foundation of human rights."),

    ("Atmosphere", "noun", "B1", "/ˈæt.məs.fɪər/", "atmosfer / lapisan udara bumi / suasana tempat",
     "Lapisan gas yang menyelimuti planet; suasana emosional atau suasana hati suatu tempat.",
     "The envelope of gases surrounding the earth; the pervading tone or mood of a place.",
     ["Atmospheric", "Ambiance", "Climate"], ["Air", "Sky", "Ambiance", "Mood", "Aura"], ["Vacuum", "Void"],
     "Greenhouse gases trap thermal radiation within Earth's atmosphere, accelerating global warming.",
     "The warm candlelit interior and soft acoustic jazz created a cozy, inviting dining atmosphere."),

    ("Attack", "verb", "A2", "/əˈtæk/", "menyerang / menggempur musuh / mengkritik tajam",
     "Mengambil tindakan kekerasan agresif terhadap seseorang; mengkritik secara pedas.",
     "To take aggressive action against a place, enemy, or person; to criticize severely.",
     ["Attacker", "Attack", "Assault"], ["Assault", "Assail", "Strike", "Charge", "Criticize"], ["Defend", "Protect", "Shield", "Praise"],
     "Cybercriminals continuously attempt to attack banking databases with ransomware scripts.",
     "Military historians analyzed the strategic planning behind the early morning amphibious beach attack."),

    ("Attain", "verb", "B2", "/əˈteɪn/", "mencapai / meraih tingkat keberhasilan",
     "Berhasil mencapai suatu tujuan, kematangan, atau tingkat kemahiran melalui usaha.",
     "To succeed in achieving, reaching, or getting to a specified level, goal, or status.",
     ["Attainment", "Attainable", "Achieve"], ["Achieve", "Accomplish", "Reach", "Acquire", "Fulfill"], ["Fail", "Miss", "Lose", "Forfeit"],
     "With rigorous training and dietary discipline, the weightlifter managed to attain peak fitness.",
     "Developing economies implement structural tax reforms to attain long-term fiscal solvency and investment stability."),

    ("Attempt", "noun", "B1", "/əˈtempt/", "upaya / percobaan melakukan sesuatu",
     "Tindakan berusaha melakukan atau menyelesaikan sesuatu yang sering kali menantang.",
     "An act of trying to achieve or do something, especially something difficult.",
     ["Attempt", "Trial", "Endeavor"], ["Effort", "Endeavor", "Try", "Venture", "Bid"], ["Inaction", "Passivity", "Surrender"],
     "Her first attempt to run a full marathon was cut short due to an unfortunate ankle sprain.",
     "Engineers launched a second attempt to drill through the granite mountain bedrock after upgrading turbine cutter heads."),

    ("Attend", "verb", "A2", "/əˈtend/", "menghadiri acara / merawat pasien / menyimak",
     "Hadir di suatu pertemuan atau kelas; memperhatikan dengan seksama; merawat orang sakit.",
     "To be present at an event, meeting, or function; to look after someone; pay attention.",
     ["Attendance", "Attendant", "Attention"], ["Present", "Go to", "Visit", "Care for", "Serve"], ["Miss", "Skip", "Abscond", "Neglect"],
     "Over three hundred international delegates will attend the clean energy conference.",
     "Specialist pediatric nurses attend to premature infants inside the neonatal intensive care ward."),

    ("Attendance", "noun", "B1", "/əˈten.dəns/", "kehadiran / jumlah orang yang hadir",
     "Tindakan hadir di sekolah atau acara; total jumlah peserta yang datang.",
     "The action or state of attending an event or institution; the number of people present.",
     ["Attend", "Attendant", "Presence"], ["Presence", "Turnout", "Audience", "Enrollment"], ["Absence", "Nonattendance", "Truancy"],
     "School administrators reward students who achieve one hundred percent class attendance.",
     "Record-breaking attendance was recorded at the annual botanical garden tulip festival this spring."),

    ("Attitude", "noun", "B1", "/ˈæt.ɪ.tjuːd/", "sikap mental / pandangan hidup / tingkah laku",
     "Cara berpikir atau merasakan yang menetap tentang seseorang atau sesuatu, yang tercermin dalam perilaku.",
     "A settled way of thinking or feeling about someone or something, typically reflected in behavior.",
     ["Attitudinal", "Mindset", "Outlook"], ["Mindset", "Outlook", "Perspective", "Stance", "Disposition"], ["Apathy", "Indifference"],
     "Maintaining a resilient, constructive attitude helps individuals overcome career setbacks.",
     "Customer service representatives are trained to display an empathetic and patient attitude toward upset clients."),

    ("Attract", "verb", "B1", "/əˈtrækt/", "menarik minat / memikat perhatian / menarik magnet",
     "Menyebabkan orang atau benda datang mendekat; memikat rasa kagum atau ketertarikan.",
     "To cause someone or something to come to a place or want to participate; draw by physical force.",
     ["Attraction", "Attractive", "Allure"], ["Draw", "Allure", "Captivate", "Entice", "Lure"], ["Repel", "Deter", "Disgust", "Repulse"],
     "Bright floral colors and sweet nectar attract honeybees and butterflies to garden blossoms.",
     "The city's low corporate tax rates and vibrant cultural scene attract tech entrepreneurs from around the globe."),

    ("Attractive", "adjective", "A2", "/əˈtræk.tɪv/", "menarik / rupawan / memikat hati / menggiurkan",
     "Menyenangkan untuk dipandang; memiliki kualitas yang memikat atau menguntungkan.",
     "Pleasing or appealing to look at; possessing qualities that arouse interest or enthusiasm.",
     ["Attract", "Attractiveness", "Attractively"], ["Appealing", "Charming", "Alluring", "Good-looking", "Enticing"], ["Ugly", "Unattractive", "Repulsive", "Unappealing"],
     "The investment fund offers an attractive annual dividend yield to conservative retirement savers.",
     "The historic waterfront promenade features attractive cobblestone pathways illuminated by vintage wrought-iron lamps."),

    ("Attribute", "verb", "B2", "/əˈtrɪb.juːt/", "menghubungkan sebab / menganggap berasal dari",
     "Menganggap suatu hasil atau karya sebagai akibat dari penyebab atau sosok tertentu.",
     "To regard something as being caused by, created by, or belonging to a specific entity.",
     ["Attribution", "Attributable", "Trait"], ["Ascribe", "Credit", "Assign", "Impute", "Trace"], ["Disassociate", "Disconnect"],
     "Doctors attribute her remarkable recovery to early clinical diagnosis and disciplined physical therapy.",
     "Literary historians attribute the anonymous renaissance sonnet manuscript to an apprentice of William Shakespeare."),

    ("Authentic", "adjective", "B2", "/ɔːˈθen.tɪk/", "otentik / asli / bukan tiruan / terpercaya",
     "Berasal dari sumber yang sah dan asli; tidak dibuat-buat atau dipalsukan.",
     "Of undisputed origin and genuine authenticity; not a copy or imitation.",
     ["Authenticate", "Authenticity", "Authentically"], ["Genuine", "Real", "Original", "Legitimate", "Bona fide"], ["Fake", "Counterfeit", "Fraudulent", "Spurious"],
     "The museum curator confirmed that the oil painting was an authentic work by Rembrandt.",
     "To experience authentic Italian cuisine, travelers explore small family-owned trattorias in countryside villages."),

    ("Author", "noun", "A2", "/ˈɔː.θər/", "penulis / pengarang buku / pencetus karya",
     "Orang yang menulis buku, artikel, atau naskah; penggagas suatu gagasan orisinal.",
     "A writer of a book, article, or document; the originator or creator of an idea.",
     ["Authority", "Authorize", "Authorship"], ["Writer", "Novelist", "Creator", "Originator", "Essayist"], ["Reader", "Audience"],
     "The acclaimed author spent five years living in the Amazon basin to research her newest environmental novel.",
     "Scholarly articles list each contributing author alongside their corresponding university departmental affiliation."),

    ("Authority", "noun", "B1", "/ɔːˈθɒr.ə.ti/", "otoritas / wewenang resmi / pakar terkemuka",
     "Kekuasaan atau hak resmi untuk memerintah dan mengambil keputusan; pakar dalam bidangnya.",
     "The power or right to give orders, make decisions, and enforce obedience; an expert.",
     ["Authorize", "Authoritative", "Authoritarian"], ["Power", "Jurisdiction", "Command", "Expert", "Dominion"], ["Subordination", "Powerlessness", "Weakness"],
     "Only the municipal aviation authority can grant flight permits over restricted urban airspace.",
     "The professor is widely recognized as a foremost international authority on renewable geothermal thermodynamics."),

    ("Automatic", "adjective", "A2", "/ˌɔː.təˈmæt.ɪk/", "otomatis / bekerja sendiri tanpa bantuan manual",
     "Bekerja atau bergerak sendiri dengan mekanisme mandiri tanpa campur tangan manusia langsung.",
     "Operating by itself with little or no direct human control; done spontaneously without thought.",
     ["Automatically", "Automation", "Automate"], ["Mechanized", "Automated", "Spontaneous", "Involuntary", "Self-acting"], ["Manual", "Hand-operated", "Deliberate"],
     "Modern commercial airliners feature sophisticated automatic pilot navigation systems for long flights.",
     "The sliding glass doors at the hospital entrance operate on automatic infrared motion sensors."),

    ("Automate", "verb", "B2", "/ˈɔː.tə.meɪt/", "mengotomatiskan / mengotomasi proses kerja",
     "Mengubah sistem kerja manual menjadi beroperasi secara mandiri menggunakan mesin atau komputer.",
     "To convert a process or facility to largely automatic operation through technology.",
     ["Automation", "Automatic", "Automated"], ["Mechanize", "Computerize", "Systematize", "Digitize"], ["Manualize", "Operate by hand"],
     "Manufacturing facilities automate automobile assembly lines using high-precision robotic arms.",
     "Software developers write automated test scripts to verify backend database endpoints before rolling out production updates."),

    ("Autonomy", "noun", "C1", "/ɔːˈtɒn.ə.mi/", "otonomi / kemandirian / hak menentukan nasib sendiri",
     "Hak atau kondisi berpemerintahan sendiri atau kebebasan pribadi untuk mengambil keputusan mandiri.",
     "The right or condition of self-government; freedom from external control or influence.",
     ["Autonomous", "Autonomously", "Independence"], ["Independence", "Self-determination", "Freedom", "Sovereignty"], ["Dependence", "Subjugation", "Control", "Subjection"],
     "The university grants individual academic departments substantial budgetary and curriculum autonomy.",
     "Autonomous underwater research drones possess the computational autonomy to map seafloor trenches without surface cables."),

    ("Available", "adjective", "A2", "/əˈveɪ.lə.bəl/", "tersedia / dapat diperoleh / ada waktu luang",
     "Siap digunakan atau dibeli; seseorang yang sedang bebas dan tidak sibuk.",
     "Able to be used or obtained; at someone's disposal; free to meet or talk.",
     ["Availability", "Avail", "Unavailable"], ["Accessible", "Obtainable", "Ready", "Free", "Vacant"], ["Unavailable", "Inaccessible", "Occupied", "Busy"],
     "Fresh drinking water and emergency rations were made immediately available to storm victims.",
     "The clinical counselor has several appointment slots available on Thursday afternoon for student stress consultations."),

    ("Avenue", "noun", "B1", "/ˈæv.ə.njuː/", "jalan raya rindang / jalur peluang / saluran solusi",
     "Jalan raya lebar yang sering kali diapit pepohonan; jalan atau sarana untuk mencapai tujuan.",
     "A broad road in a town or city, typically tree-lined; a way of approaching or achieving something.",
     ["Boulevard", "Street", "Path"], ["Boulevard", "Thoroughfare", "Path", "Route", "Channel"], ["Dead end", "Cul-de-sac"],
     "Fifth Avenue in New York is world-famous for its luxury fashion boutiques and grand architecture.",
     "Diplomats explored every peaceful diplomatic avenue to defuse border tensions before sanctions were formalized."),

    ("Aware", "adjective", "A2", "/əˈweər/", "sadar / mengetahui / menyadari situasi",
     "Mengetahui atau menyadari keberadaan suatu fakta, kondisi, atau bahaya.",
     "Having knowledge or perception of a situation, fact, or feeling.",
     ["Awareness", "Unaware", "Conscious"], ["Conscious", "Mindful", "Cognizant", "Informed", "Sensible"], ["Unaware", "Oblivious", "Ignorant", "Unconscious"],
     "Drivers must remain constantly aware of pedestrians crossing at unmonitored street corners.",
     "Public health campaigns ensure that citizens are fully aware of early symptom warning signs for tick-borne diseases."),

    ("Awareness", "noun", "B1", "/əˈweə.nəs/", "kesadaran / pemahaman publik / kepekaan",
     "Pengetahuan atau pemahaman tentang suatu situasi, isu sosial, atau bahaya.",
     "Knowledge or perception of a situation or fact; concern about and well-informed interest in an issue.",
     ["Aware", "Unaware", "Mindfulness"], ["Consciousness", "Recognition", "Mindfulness", "Perception", "Insight"], ["Ignorance", "Oblivion", "Unawareness"],
     "The nationwide campaign raised public awareness about the catastrophic impact of plastic pollution in oceans.",
     "Cultivating emotional self-awareness helps professionals navigate stressful workplace confrontations with composure."),

    ("Awkward", "adjective", "B1", "/ˈɔː.kwəd/", "canggung / kikuk / kikuk / serba salah",
     "Menimbulkan rasa malu atau serba salah; tidak lincah dalam gerakan fisik; canggung digunakan.",
     "Causing embarrassment or inconvenience; uncomfortable; lacking grace in physical movement.",
     ["Awkwardly", "Awkwardness", "Clumsy"], ["Clumsy", "Embarrassing", "Uncomfortable", "Ungainly", "Inconvenient"], ["Graceful", "Smooth", "Comfortable", "Adroit"],
     "There was an awkward silence in the boardroom after the treasurer questioned the CEO's bonus.",
     "Learning to ice skate feels awkward at first, but ankle balance improves steadily with hours of practice."),

    # --- Letter B ---
    ("Background", "noun", "A2", "/ˈbæk.ɡraʊnd/", "latar belakang / riwayat hidup / latar visual",
     "Riwayat pendidikan atau keluarga seseorang; bagian pemandangan di belakang objek utama.",
     "A person's origin, education, and experience; the area behind the main subject in a scene.",
     ["Backdrop", "Setting", "Heritage"], ["Backdrop", "Heritage", "Upbringing", "Setting", "Context"], ["Foreground", "Front"],
     "The candidates come from diverse cultural and professional backgrounds across Southeast Asia.",
     "In photographic portraiture, a softly blurred natural foliage background highlights the subject's facial expressions."),

    ("Balance", "noun", "B1", "/ˈbæl.əns/", "keseimbangan / saldo rekening / kesetimbangan",
     "Kondisi di mana unsur-unsur berada dalam proporsi yang setara; sisa uang di rekening bank.",
     "An even distribution of weight or forces; remaining funds in an account.",
     ["Balanced", "Imbalance", "Equilibrium"], ["Equilibrium", "Symmetry", "Stability", "Poise", "Remainder"], ["Imbalance", "Instability", "Asymmetry"],
     "Maintaining a healthy balance between demanding professional responsibilities and restful family life is essential.",
     "Before making a large debit card purchase, check your checking account balance on the mobile banking application."),

    ("Ban", "verb", "B1", "/bæn/", "melarang resmi / mencekal / memblokir",
     "Melarang suatu tindakan, buku, barang, atau kegiatan secara hukum atau ketetapan resmi.",
     "To officially or legally prohibit something from being done, sold, or used.",
     ["Prohibition", "Banned", "Outlaw"], ["Prohibit", "Forbid", "Bar", "Outlaw", "Disallow"], ["Permit", "Allow", "Authorize", "Legalize"],
     "The municipal government enacted an ordinance to ban single-use plastic grocery bags.",
     "International sporting federations voted to ban performance-enhancing anabolic substances across all competitive athletics."),

    ("Barrier", "noun", "B2", "/ˈbær.i.ər/", "rintangan / pembatas fisik / kendala penghalang",
     "Pagar atau benda yang menghalangi pergerakan; hambatan sosial atau bahasa yang menyulitkan komunikasi.",
     "A fence or obstacle that prevents movement or access; a circumstance that impedes progress.",
     ["Barricade", "Obstacle", "Hurdle"], ["Obstacle", "Hurdle", "Barricade", "Impediment", "Blockade"], ["Openway", "Access", "Aid", "Passage"],
     "Language differences should never act as a permanent barrier to collaborative humanitarian teamwork.",
     "Civil engineers constructed concrete sea barriers along the harbor promenade to deflect powerful storm surge waves."),

    ("Basic", "adjective", "A1", "/ˈbeɪ.sɪk/", "dasar / mendasar / pokok / elementer",
     "Membentuk fondasi utama atau bagian yang paling esensial; bersifat sederhana.",
     "Forming an essential foundation or starting point; fundamental and simple.",
     ["Basically", "Basics", "Base"], ["Fundamental", "Essential", "Primary", "Elementary", "Core"], ["Advanced", "Complex", "Secondary", "Elaborate"],
     "Every citizen should have guaranteed access to basic healthcare, clean water, and nutritional food.",
     "The introductory computer science course begins with basic logic gates before advancing to algorithmic complexity."),

    ("Behavior", "noun", "A2", "/bɪˈheɪ.vjər/", "perilaku / tingkah laku / kelakuan",
     "Cara seseorang atau hewan bertindak atau bersikap terhadap lingkungan dan orang lain.",
     "The way in which one acts or conducts oneself, especially toward others.",
     ["Behave", "Behavioral", "Conduct"], ["Conduct", "Demeanor", "Actions", "Deportment", "Manner"], ["Immobility", "Inaction"],
     "Parents reward positive social behavior to encourage kindness and cooperation in young siblings.",
     "Primatologists observe chimpanzee group behavior in wild sanctuaries to understand early hominid social hierarchies."),

    ("Belief", "noun", "B1", "/bɪˈliːf/", "keyakinan / kepercayaan / asas pandangan",
     "Sesuatu yang diyakini sebagai kebenaran; iman keagamaan atau prinsip hidup yang dipegang teguh.",
     "An acceptance that a statement is true or that something exists; trust, faith, or confidence.",
     ["Believe", "Believer", "Unbelief"], ["Conviction", "Faith", "Credo", "Tenet", "Trust"], ["Disbelief", "Skepticism", "Doubt", "Distrust"],
     "She holds a steadfast belief in the power of public education to transform impoverished communities.",
     "Freedom of religious belief and conscience is enshrined as an inviolable right in international human rights declarations."),

    ("Beneficial", "adjective", "B2", "/ˌben.ɪˈfɪʃ.əl/", "bermanfaat / berfaedah / menguntungkan",
     "Menghasilkan hasil yang baik, positif, atau membawa keuntungan bagi kesehatan/kemajuan.",
     "Resulting in good; favorable or advantageous to health, well-being, or success.",
     ["Benefit", "Beneficially", "Advantageous"], ["Advantageous", "Favorable", "Helpful", "Lucrative", "Valuable"], ["Detrimental", "Harmful", "Damaging", "Disadvantageous"],
     "Regular aerobic exercise is exceptionally beneficial for maintaining cardiovascular and mental wellness.",
     "Planting nitrogen-fixing clover between seasonal crop cycles is highly beneficial for restoring depleted soil nutrients."),

    ("Benefit", "noun", "A2", "/ˈben.ɪ.fɪt/", "manfaat / faedah / tunjangan kesejahteraan",
     "Keuntungan yang diperoleh dari sesuatu; tunjangan kesehatan atau dana bantuan finansial.",
     "An advantage or profit gained from something; a payment made by employer or state.",
     ["Beneficial", "Beneficiary", "Advantage"], ["Advantage", "Perk", "Profit", "Gain", "Assistance"], ["Disadvantage", "Drawback", "Detriment", "Loss"],
     "One major benefit of remote telecommuting is saving hours previously spent in congested highway traffic.",
     "The full-time corporate employment package includes comprehensive dental and optical healthcare benefits."),

    ("Betray", "verb", "B2", "/bɪˈtreɪ/", "mengkhianati / membocorkan rahasia / mengecewakan",
     "Mengingkari kesetiaan atau kepercayaan seseorang; membocorkan rahasia ke pihak lawan.",
     "To expose one's country or a person to danger by treacherous disloyalty; reveal secrets.",
     ["Betrayal", "Betrayer", "Treacherous"], ["Deceive", "Double-cross", "Expose", "Disclose", "Let down"], ["Defend", "Protect", "Support", "Remain loyal"],
     "He refused to betray his close comrades even when threatened with severe punitive sanctions.",
     "Unreliable encrypted password storage protocols can betray sensitive user credentials to malicious online eavesdroppers."),

    ("Bias", "noun", "B2", "/ˈbaɪ.əs/", "bias / keberpihakan / prasangka subjektif",
     "Kecenderungan untuk mendukung atau menolak suatu hal secara tidak adil dan berat sebelah.",
     "Prejudice in favor of or against one thing, person, or group compared with another, usually unfairly.",
     ["Biased", "Unbiased", "Prejudice"], ["Prejudice", "Partiality", "Partisanship", "Favoritism", "Slant"], ["Impartiality", "Fairness", "Neutrality", "Objectivity"],
     "Journalists must strive to eliminate personal political bias when reporting controversial election debates.",
     "Machine learning algorithms can inadvertently absorb human historical bias present in unfiltered training datasets."),

    ("Bizarre", "adjective", "B2", "/bɪˈzɑːr/", "ganjil / aneh sekali / tidak lazim",
     "Sangat aneh atau tidak biasa dalam penampilan, gaya, atau kejadian.",
     "Very strange, unusual, or striking in appearance or effect.",
     ["Bizarrely", "Bizarreness", "Eccentric"], ["Strange", "Peculiar", "Odd", "Eccentric", "Weird"], ["Normal", "Ordinary", "Typical", "Conventional"],
     "Deep-sea oceanographers discovered a bizarre bioluminescent creature thriving near volcanic hydrothermal vents.",
     "The thriller movie featured a bizarre plot twist that left audiences debating its hidden symbolism for weeks."),

    ("Blanket", "noun", "A2", "/ˈblæŋ.kɪt/", "selimut hangat / hamparan penutup tebal",
     "Kain tebal penutup badan saat tidur agar hangat; lapisan tebal yang menyelimuti area.",
     "A large piece of woolen or thick fabric used for warmth; a thick covering layer.",
     ["Covering", "Layer", "Quilt"], ["Quilt", "Coverlet", "Layer", "Canopy", "Shroud"], ["Exposed ground"],
     "The rescue volunteers distributed warm wool blankets to families displaced by the winter blizzard.",
     "A thick blanket of early morning fog drifted across the mountain pine valleys, reducing road visibility."),

    ("Bleak", "adjective", "C1", "/bliːk/", "suram / gersang / tanpa harapan membahagiakan",
     "Gersang dan dingin tak terlindung; tanpa prospek cerah atau masa depan yang membahagiakan.",
     "Lacking vegetation and exposed to the elements; offering little or no hope for future success.",
     ["Bleakness", "Bleakly", "Desolate"], ["Grim", "Desolate", "Dismal", "Gloomy", "Hopeless"], ["Bright", "Promising", "Hopeful", "Cheerful"],
     "The economic outlook for the coal-mining town appeared bleak following factory closures.",
     "Explorers trekked across the bleak Arctic tundra where biting sub-zero winds whipped uninterrupted across icy plains."),

    ("Blessing", "noun", "B1", "/ˈbles.ɪŋ/", "berkah / restu / anugerah keberuntungan",
     "Doa memohon perlindungan ilahi; anugerah yang mendatangkan kebahagiaan atau keselamatan.",
     "A prayer asking for divine favor and protection; a beneficial thing that brings happiness.",
     ["Bless", "Blessed", "Grace"], ["Benediction", "Grace", "Boon", "Gift", "Favor"], ["Curse", "Bane", "Affliction", "Damnation"],
     "The arrival of monsoon rains was a true blessing for drought-stricken farming communities.",
     "Before embarking on her overseas university studies, she sought the heartfelt blessing of her grandparents."),

    ("Blockade", "noun", "C1", "/blɒkˈeɪd/", "blokade / pengepungan jalur masuk / rintangan",
     "Tindakan menutup atau mengepung pelabuhan atau wilayah untuk mencegah masuknya pasokan.",
     "An act of sealing off a place to prevent goods or people from entering or leaving.",
     ["Block", "Besiege", "Embargo"], ["Siege", "Embargo", "Barricade", "Obstruction", "Quarantine"], ["Opening", "Access", "Free passage"],
     "The naval fleet enforced a strict maritime blockade around the disputed territorial straits.",
     "Protesting transport workers formed a peaceful road blockade outside the shipping terminal to demand wage parity."),

    ("Boast", "verb", "B2", "/bəʊst/", "membanggakan / menyombongkan / memiliki keunggulan",
     "Berbicara dengan rasa bangga berlebihan tentang pencapaian diri; memiliki fitur hebat.",
     "To talk with excessive pride and self-satisfaction about oneself; to possess a proud feature.",
     ["Boastful", "Boasting", "Brag"], ["Brag", "Crow", "Flaunt", "Possess", "Show off"], ["Belittle", "Deprecate", "Hide", "Understate"],
     "The newly opened five-star resort can boast panoramic ocean views from every guest balcony.",
     "True champions let their athletic performance speak for itself rather than boast about past victories on social media."),

    ("Bold", "adjective", "B1", "/bəʊld/", "berani / tegas / mencolok / huruf tebal",
     "Tidak takut mengambil risiko; percaya diri dan tegas; bentuk huruf cetak tebal.",
     "Showing an ability to take risks; confident, courageous, and visually prominent.",
     ["Boldly", "Boldness", "Courageous"], ["Courageous", "Daring", "Audacious", "Brazen", "Vivid"], ["Timid", "Cowardly", "Faint", "Hesitant"],
     "She made a bold entrepreneurial decision to quit her corporate job and launch a solar startup.",
     "Key headings in the technical documentation are styled in bold typography to enhance readability."),

    ("Bond", "noun", "B1", "/bɒnd/", "ikatan batin / obligasi keuangan / ikatan kimia",
     "Hubungan emosional atau sosial yang erat antarmanusia; surat utang; gaya tarik antaratom.",
     "A strong connection between people; a financial debt security; a chemical attraction holding atoms.",
     ["Bonding", "Bonded", "Attachment"], ["Tie", "Attachment", "Alliance", "Affinity", "Obligation"], ["Severance", "Separation", "Rift", "Alienation"],
     "A shared passion for wildlife preservation forged an unbreakable bond between the two naturalists.",
     "Conservative pension funds invest a substantial percentage of capital in sovereign government bonds."),

    ("Boost", "verb", "B1", "/buːst/", "mendorong naik / meningkatkan / mendongkrak",
     "Membantu memajukan, menaikkan, atau memperbaiki performa, moral, atau ekonomi.",
     "To help or encourage something to increase, improve, or become more successful.",
     ["Booster", "Boost", "Uplift"], ["Enhance", "Elevate", "Amplify", "Augment", "Strengthen"], ["Decrease", "Diminish", "Dampen", "Impair"],
     "Eating a nutritious Mediterranean diet rich in leafy greens helps boost immune system resilience.",
     "The central bank lowered benchmark lending rates to boost consumer spending and stimulate business hiring."),

    ("Boundary", "noun", "B2", "/ˈbaʊn.dər.i/", "batas wilayah / garis batas / batas toleransi",
     "Garis yang menandai batas suatu bidang tanah, wilayah negara, atau batasan perilaku pribadi.",
     "A line that marks the limits of an area; a dividing line; limits of acceptable behavior.",
     ["Bound", "Boundaries", "Border"], ["Border", "Frontier", "Perimeter", "Limit", "Demarcation"], ["Interior", "Center", "Unlimited space"],
     "Surveyors used satellite laser telemetry to verify the exact boundary between the neighboring farms.",
     "Establishing healthy personal boundaries at work prevents occupational burnout and preserves evening family time."),

    ("Bravery", "noun", "B1", "/ˈbreɪ.vər.i/", "keberanian / ketabahan hati menghadapi bahaya",
     "Sikap berani dan pantang menyerah saat menghadapi rasa sakit, marabahaya, atau kesulitan.",
     "Courageous behavior or character when facing danger, adversity, or fear.",
     ["Brave", "Bravely", "Courage"], ["Courage", "Valor", "Fortitude", "Gallantry", "Pluck"], ["Cowardice", "Timidity", "Fearfulness"],
     "The rookie firefighter was awarded a medal of honor for extraordinary bravery during the rescue.",
     "Historical records commemorate the bravery of peaceful suffragettes who marched despite police intimidation."),

    ("Breakthrough", "noun", "B2", "/ˈbreɪk.θruː/", "terobosan besar / penemuan revolusioner",
     "Kemajuan atau penemuan mendadak yang sangat penting dan mengatasi rintangan lama.",
     "A sudden, dramatic, and important development, discovery, or achievement.",
     ["Break", "Advance", "Discovery"], ["Discovery", "Advance", "Innovation", "Triumph", "Leap"], ["Setback", "Impasse", "Stagnation", "Failure"],
     "Oncology researchers announced a major scientific breakthrough in targeted cancer immunotherapy.",
     "The invention of the transistor was the technological breakthrough that enabled the modern digital computing revolution."),

    ("Breed", "verb", "B2", "/briːd/", "berkembang biak / mengembangbiakkan / memicu",
     "Menghasilkan keturunan pada hewan/tumbuhan; memelihara hewan; memicu timbulnya hal buruk.",
     "To mate and produce offspring; to rear animals; to cause something to happen or spread.",
     ["Breeding", "Breeder", "Offspring"], ["Reproduce", "Propagate", "Cultivate", "Engender", "Spawn"], ["Extinguish", "Suppress", "Halt"],
     "Endangered sea turtles return to their natal beaches every few years to breed and lay eggs.",
     "Unregulated industrial pollution and stagnant puddles breed disease-carrying mosquito larvae during wet months."),

    ("Brief", "adjective", "A2", "/briːf/", "singkat / ringkas / tidak memakan waktu lama",
     "Berlangsung hanya dalam waktu yang pendek; menggunakan sedikit kata-kata namun jelas.",
     "Of short duration; concise and not lasting a long time in speech or text.",
     ["Briefly", "Briefing", "Brevity"], ["Concise", "Short", "Succinct", "Fleeting", "Terse"], ["Long", "Prolonged", "Protracted", "Verbose"],
     "The military commander held a brief tactical briefing before deploying the search helicopter.",
     "After a brief coffee pause, the delegates resumed negotiating terms of the multilateral climate accord."),

    ("Brilliant", "adjective", "A2", "/ˈbrɪl.jənt/", "cemerlang / sangat cerdas / berkilau terang",
     "Sangat luar biasa cerdas atau berbakat; memancarkan cahaya yang sangat terang berkilauan.",
     "Exceptionally clever, talented, or impressive; shining brightly with intense light.",
     ["Brilliantly", "Brilliance", "Luminous"], ["Intelligent", "Ingenious", "Dazzling", "Luminous", "Superb"], ["Dull", "Stupid", "Dim", "Mediocre"],
     "The young theoretical physicist proposed a brilliant mathematical framework to reconcile quantum mechanics.",
     "The nighttime sky over the Chilean high desert offered a brilliant, unobstructed view of the Milky Way galaxy."),

    ("Broad", "adjective", "B1", "/brɔːd/", "luas / lebar / mencakup banyak aspek umum",
     "Memiliki ukuran lebar dari sisi ke sisi yang besar; mencakup berbagai macam topik umum.",
     "Having an ample distance from side to side; wide; covering a large scope of subjects.",
     ["Broadly", "Broaden", "Width"], ["Wide", "Spacious", "Extensive", "Comprehensive", "Sweeping"], ["Narrow", "Restricted", "Limited", "Specific"],
     "The university curriculum offers a broad foundational overview of both arts and empirical sciences.",
     "The presidential candidate enjoyed broad electoral support spanning working-class suburbs and urban districts."),

    ("Broaden", "verb", "B2", "/ˈbrɔː.dən/", "memperluas / menambah wawasan / memperlebar",
     "Membuat sesuatu menjadi lebih lebar atau mencakup lingkup yang lebih luas.",
     "To make or become larger in width, scope, perspective, or variety.",
     ["Broad", "Broadly", "Expand"], ["Expand", "Enlarge", "Widen", "Diversify", "Extend"], ["Narrow", "Constrict", "Limit", "Restrict"],
     "Living abroad for an exchange semester helps students broaden their cultural horizons and empathy.",
     "The software enterprise decided to broaden its product catalog to include cloud analytics tools for healthcare."),

    ("Budget", "noun", "A2", "/ˈbʌdʒ.ɪt/", "anggaran belanja / bujet keuangan",
     "Perkiraan rencana pendapatan dan pengeluaran uang untuk jangka waktu tertentu.",
     "An estimate of income and expenditure for a set period of time.",
     ["Budgetary", "Budgeted", "Fiscal"], ["Allocation", "Funds", "Allowance", "Finances", "Estimate"], ["Extravagance", "Debt"],
     "Families draft a monthly household budget to track grocery expenses and prioritize debt repayments.",
     "The finance ministry submitted the national fiscal budget proposal to parliament for legislative scrutiny."),

    ("Bulk", "noun", "B2", "/bʌlk/", "sebagian besar / volume besar / curah",
     "Ukuran atau volume yang sangat besar; bagian terbesar atau mayoritas dari sesuatu.",
     "The greater part or mass of something; large in size, volume, or unpackaged quantity.",
     ["Bulky", "Mass", "Volume"], ["Majority", "Mass", "Larger part", "Volume", "Mainstream"], ["Minority", "Small fraction", "Portion"],
     "The bulk of our company revenue is generated through annual cloud software subscriptions.",
     "Purchasing raw organic oats in bulk quantities significantly reduces single-use plastic packaging waste."),

    ("Burden", "noun", "B2", "/ˈbɜː.dən/", "beban berat / tanggungan moral / kesulitan",
     "Beban fisik yang berat untuk dipikul; tugas sulit atau tanggung jawab emosional yang menekan.",
     "A heavy load that is carried; a heavy duty, responsibility, or emotional worry.",
     ["Burdensome", "Unburden", "Load"], ["Load", "Weight", "Encumbrance", "Strain", "Affliction"], ["Relief", "Benefit", "Advantage", "Solace"],
     "Excessive student loan debt imposes a crushing financial burden upon young university graduates.",
     "Caring for an ailing family member requires community support systems so caregivers do not bear the burden alone.")
]

print(f"Loaded {len(WORDS_A_D)} words for Part 1 (A-D)")
