#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generates rich Oxford 3000/5000 dictionary entries for Letters E - L (Part 2)
Guarantees 260 distinct headwords with complete linguistic data.
"""

# Tuple structure:
# (word, partOfSpeech, level, phonetic, indonesianTranslation,
#  definition_id, definition_en, similarWords, synonyms, antonyms,
#  sentenceExample, paragraphExample)

EXTRA_EL_WORDS = [
    # E words
    ("Eager", "adjective", "B1", "/ˈiː.ɡər/", "sangat berhasrat / antusias penuh semangat",
     "Sangat menginginkan sesuatu atau sangat tertarik untuk melakukan sesuatu.",
     "Wanting very much to do or have something, especially something interesting or enjoyable.",
     ["Eagerness", "Eagerly", "Keen"], ["Keen", "Enthusiastic", "Avid", "Desirous", "Zealous"], ["Indifferent", "Apathetic", "Reluctant"],
     "The students were eager to participate in the environmental science workshop.",
     "She arrived early at the airport, eager to welcome her family after years abroad."),

    ("Earnest", "adjective", "B2", "/ˈɜː.nɪst/", "sungguh-sungguh / tulus dan beritikad baik",
     "Menunjukkan ketulusan yang mendalam dan niat yang serius tanpa kepura-puraan.",
     "Resulting from or showing sincere and intense conviction; serious in intention.",
     ["Earnestly", "Earnestness", "Sincere"], ["Sincere", "Genuine", "Solemn", "Heartfelt", "Devoted"], ["Frivolous", "Insincere", "Trivial", "Joking"],
     "He made an earnest plea to the board for immediate community safety funding.",
     "Her earnest commitment to human rights earned her international respect and awards."),

    ("Earthquake", "noun", "A2", "/ˈɜːθ.kweɪk/", "gempa bumi / getaran tektonik",
     "Guncangan tiba-tiba dan keras pada permukaan bumi akibat pergerakan kerak tektonik.",
     "A sudden and violent shaking of the ground, sometimes causing great destruction.",
     ["Seismic", "Tremor", "Quake"], ["Tremor", "Seism", "Shock", "Quake", "Convulsion"], ["Stability", "Stillness"],
     "The modern skyscrapers were designed to withstand a major magnitude earthquake.",
     "Rescue teams quickly mobilized after an earthquake struck the mountainous province."),

    ("Eccentric", "adjective", "B2", "/ɪkˈsen.trɪk/", "nyentrik / aneh tapi menarik / tidak lazim",
     "Memiliki perilaku, kebiasaan, atau penampilan yang unik dan berbeda dari norma umum.",
     "Unconventional and slightly strange, but often in an amusing or charismatic way.",
     ["Eccentricity", "Eccentrically", "Odd"], ["Odd", "Quirky", "Unconventional", "Peculiar", "Bizarre"], ["Conventional", "Normal", "Ordinary", "Typical"],
     "The eccentric inventor filled his workshop with clockwork automata and steam devices.",
     "Her eccentric artistic style made her gallery exhibitions immensely popular among critics."),

    ("Eclipse", "noun", "B2", "/ɪˈklɪps/", "gerhana matahari atau bulan / penggelapan",
     "Peristiwa astronomi ketika suatu benda langit terhalang oleh bayangan benda lain.",
     "An obscuring of the light from one celestial body by the passage of another between it.",
     ["Solar eclipse", "Lunar eclipse", "Obscurity"], ["Obscuration", "Blocking", "Occultation", "Shadowing", "Darkening"], ["Illumination", "Brightness"],
     "Thousands gathered with protective glasses to witness the total solar eclipse.",
     "The sudden scientific breakthrough caused an eclipse of older theoretical models."),

    ("Ecological", "adjective", "B2", "/ˌiː.kəˈlɒdʒ.ɪ.kəl/", "ekologis / berhubungan dengan alam lingkungan",
     "Berkaitan dengan interaksi antara organisme hidup dan lingkungan sekitarnya.",
     "Relating to or concerned with the relation of living organisms to one another and surroundings.",
     ["Ecology", "Ecologist", "Ecologically"], ["Environmental", "Biological", "Natural", "Green", "Organic"], ["Artificial", "Synthetic", "Polluting"],
     "The wetlands reserve plays an essential ecological role in filtering coastal waters.",
     "Conservationists warn against the long-term ecological impact of unregulated deforestation."),

    ("Economical", "adjective", "B1", "/ˌiː.kəˈnɒm.ɪ.kəl/", "hemat biaya / efisien pemakaiannya",
     "Menggunakan sedikit uang, bahan bakar, atau sumber daya untuk mencapai tujuan.",
     "Giving good value or return in relation to the money, time, or energy spent; thrifty.",
     ["Economy", "Economize", "Economically"], ["Thrifty", "Frugal", "Cost-effective", "Inexpensive", "Efficient"], ["Extravagant", "Wasteful", "Expensive"],
     "Hybrid compact cars provide an economical solution for daily metropolitan commuters.",
     "Cooking balanced meals at home is both healthy and highly economical for students."),

    ("Economics", "noun", "B1", "/ˌiː.kəˈnɒm.ɪks/", "ilmu ekonomi / sistem perekonomian",
     "Cabang ilmu sosial yang mempelajari produksi, distribusi, dan konsumsi barang serta jasa.",
     "The branch of knowledge concerned with the production, consumption, and transfer of wealth.",
     ["Economic", "Economist", "Economy"], ["Finance", "Commerce", "Trade", "Wealth management", "Fiscal science"], ["N/A"],
     "She decided to major in international economics to understand global market dynamics.",
     "Behavioral economics explores how psychological biases influence consumer purchasing decisions."),

    ("Economist", "noun", "B2", "/ɪˈkɒn.ə.mɪst/", "pakar ekonomi / ekonom profesional",
     "Ahli yang mempelajari dan menganalisis tren moneter, fiskal, dan dinamika pasar.",
     "An expert in economics, especially one who analyzes economic trends and policies.",
     ["Economics", "Economic", "Analyst"], ["Financial analyst", "Statistician", "Fiscal expert", "Policy adviser"], ["Layman"],
     "The chief economist predicted steady inflation stabilization over the upcoming fiscal quarters.",
     "Leading economists convened at the global summit to address international trade imbalances."),

    ("Economy", "noun", "A2", "/ɪˈkɒn.ə.mi/", "perekonomian negara / pengelolaan keuangan",
     "Sistem produksi, perdagangan, dan peredaran uang di suatu wilayah atau negara.",
     "The wealth and resources of a country or region, especially in terms of production and goods.",
     ["Economic", "Economical", "Market"], ["Financial system", "Marketplace", "Commerce", "Trade", "Wealth"], ["Bankruptcy"],
     "Tourism contributes significantly to the national economy and creates local employment.",
     "The transition toward a circular green economy reduces industrial waste and carbon footprints."),

    ("Edge", "noun", "A2", "/edʒ/", "tepi pinggiran / keunggulan kompetitif",
     "Bagian terluar dari suatu benda; keuntungan atau keunggulan atas pesaing.",
     "The outside limit of an object, area, or surface; an advantage over others.",
     ["Edgy", "Border", "Advantage"], ["Border", "Perimeter", "Rim", "Advantage", "Upper hand"], ["Center", "Middle", "Disadvantage"],
     "She walked carefully along the grassy edge of the steep ocean cliff.",
     "Fluent bilingual communication skills gave the candidate a decisive competitive edge."),

    ("Edible", "adjective", "B2", "/ˈed.ə.bəl/", "dapat dimakan / aman dikonsumsi",
     "Layak, aman, dan pantas untuk dimakan tanpa membahayakan kesehatan manusia.",
     "Fit or suitable to be eaten by humans; non-toxic and nutritious.",
     ["Inedible", "Eat", "Comestible"], ["Eatable", "Comestible", "Palatable", "Wholesome", "Safe"], ["Inedible", "Poisonous", "Toxic", "Harmful"],
     "Botanists identified several varieties of wild edible mushrooms in the pine forest.",
     "Cake decorators crafted delicate flowers from edible colored sugar paste."),

    ("Edition", "noun", "A2", "/ɪˈdɪʃ.ən/", "edisi buku atau majalah / versi cetakan",
     "Bentuk khusus dari buku, surat kabar, atau siaran yang dipublikasikan.",
     "A particular form or version of a published text or broadcast.",
     ["Editor", "Edit", "Issue"], ["Issue", "Version", "Release", "Volume", "Publication"], ["Manuscript"],
     "The updated digital edition of the encyclopedia includes interactive video diagrams.",
     "A rare first edition copy of Shakespeare's sonnets was auctioned in London."),

    ("Editor", "noun", "A2", "/ˈed.ɪ.tər/", "penyunting naskah / redaktur media",
     "Orang yang bertugas memeriksa, memperbaiki, dan menyusun teks sebelum dipublikasikan.",
     "A person who is in charge of and determines the final content of a newspaper, magazine, or book.",
     ["Editorial", "Edit", "Editing"], ["Redactor", "Proofreader", "Compiler", "Journalist", "Director"], ["Writer", "Author"],
     "The senior editor reviewed the manuscript and suggested stylistic adjustments for clarity.",
     "Newspaper editors ensure all published news reports adhere to strict factual accuracy."),

    ("Editorial", "noun", "B2", "/ˌed.ɪˈtɔː.ri.əl/", "tajuk rencana / artikel opini redaksi",
     "Artikel surat kabar yang menyuarakan sikap atau pendapat resmi dewan redaksi.",
     "A newspaper article written by or on behalf of an editor that gives an opinion on an issue.",
     ["Editor", "Op-ed", "Commentary"], ["Leading article", "Leader", "Commentary", "Opinion piece", "Critique"], ["News report"],
     "The Sunday editorial called for increased public funding for vocational technology colleges.",
     "Readers debated the controversial points raised in the newspaper's front-page editorial."),

    ("Educate", "verb", "A2", "/ˈedʒ.u.keɪt/", "mendidik / memberi pengajaran intelektual",
     "Memberikan bimbingan intelektual, moral, dan keterampilan kepada seseorang.",
     "Give intellectual, moral, and social instruction to someone, typically at a school.",
     ["Education", "Educated", "Educator"], ["Instruct", "Teach", "School", "Train", "Tutor"], ["Misinform", "Neglect", "Misguide"],
     "Nonprofit organizations work to educate rural communities about preventative healthcare.",
     "Parents and teachers partner together to educate children about environmental responsibility."),

    ("Educated", "adjective", "A2", "/ˈedʒ.u.keɪ.tɪd/", "berpendidikan / berwawasan luas terpelajar",
     "Memiliki pengetahuan yang luas melalui jalur pendidikan formal atau pembelajaran mandiri.",
     "Having been educated; displaying culture and scholarly knowledge.",
     ["Educate", "Education", "Learned"], ["Learned", "Scholarly", "Literate", "Knowledgeable", "Cultured"], ["Uneducated", "Illiterate", "Ignorant"],
     "An educated workforce is vital for driving technological innovation and economic growth.",
     "She made an educated assessment of the financial risks associated with the venture."),

    ("Education", "noun", "A1", "/ˌedʒ.uˈkeɪ.ʃən/", "pendidikan / proses belajar mengajar",
     "Proses menerima atau memberikan instruksi sistematis, terutama di sekolah atau universitas.",
     "The process of receiving or giving systematic instruction, especially at a school or university.",
     ["Educational", "Educate", "Educator"], ["Schooling", "Instruction", "Tuition", "Pedagogy", "Learning"], ["Ignorance", "Illiteracy"],
     "Higher education opens pathways to specialized careers and critical reasoning skills.",
     "Universal access to quality primary education remains a fundamental human right."),

    ("Educational", "adjective", "A2", "/ˌedʒ.uˈkeɪ.ʃən.əl/", "bersifat mendidik / bernilai edukatif",
     "Dirancang untuk memberikan pengetahuan dan pembelajaran yang bermanfaat.",
     "Relating to the provision of education; providing useful knowledge.",
     ["Education", "Educate", "Instructive"], ["Instructive", "Informative", "Enlightening", "Pedagogical", "Didactic"], ["Uninformative", "Misleading"],
     "The natural history museum offers interactive educational programs for school children.",
     "Documentary films provide both educational value and compelling artistic storytelling."),

    ("Educator", "noun", "B2", "/ˈedʒ.u.keɪ.tər/", "pendidik / guru / tenaga pengajar",
     "Orang yang berprofesi memberikan pendidikan atau pengajaran kepada siswa.",
     "A person who provides instruction or education; a teacher or administrator.",
     ["Educate", "Education", "Teacher"], ["Teacher", "Instructor", "Tutor", "Professor", "Mentor"], ["Student", "Pupil", "Learner"],
     "Innovative educators integrate digital simulation tools to make science concepts tangible.",
     "The annual conference celebrates outstanding educators who inspire youth in underprivileged districts."),

    ("Effect", "noun", "A2", "/ɪˈfekt/", "efek dampak / akibat yang ditimbulkan",
     "Perubahan yang merupakan hasil atau konsekuensi dari suatu tindakan atau sebab.",
     "A change which is a result or consequence of an action or other cause.",
     ["Effective", "Effectively", "Outcome"], ["Outcome", "Result", "Consequence", "Impact", "Repercussion"], ["Cause", "Origin", "Source"],
     "The medication had an immediate calming effect on the patient's acute allergic reaction.",
     "Scientists study the cumulative environmental effects of greenhouse gas emissions."),

    ("Effective", "adjective", "B1", "/ɪˈfek.tɪv/", "efektif / berhasil menghasilkan dampak nyata",
     "Mampu mencapai hasil yang diinginkan dengan tepat sasaran dan memuaskan.",
     "Successful in producing a desired or intended result; operative and functional.",
     ["Effectiveness", "Effectively", "Potent"], ["Productive", "Successful", "Potent", "Constructive", "Efficacious"], ["Ineffective", "Futile", "Useless"],
     "Regular cardiovascular exercise is an effective preventive measure against heart disease.",
     "The new workplace policy proved effective in boosting team morale and reducing turnover."),

    ("Effectively", "adverb", "B1", "/ɪˈfek.tɪv.li/", "secara efektif / dengan hasil nyata",
     "Dengan cara yang berhasil mewujudkan tujuan yang diinginkan secara tepat.",
     "In such a manner as to produce a desired result; virtually or in practice.",
     ["Effective", "Effectiveness", "Successfully"], ["Successfully", "Efficiently", "Productively", "Virtually", "Practically"], ["Ineffectively", "Poorly"],
     "The leadership team communicated the project goals effectively to all company departments.",
     "By reorganizing the warehouse layout, staff effectively halved package retrieval times."),

    ("Efficiency", "noun", "B2", "/ɪˈfɪʃ.ən.si/", "efisiensi / ketepatan daya guna tanpa boros",
     "Kemampuan untuk mencapai hasil maksimal dengan meminimalkan waktu, tenaga, atau biaya.",
     "The state or quality of being efficient; achieving maximum productivity with minimum wasted effort.",
     ["Efficient", "Efficiently", "Productivity"], ["Productivity", "Competence", "Efficacy", "Economy", "Streamlining"], ["Inefficiency", "Wastefulness", "Incompetence"],
     "Modern aerodynamic car engineering enhances fuel efficiency and reduces emissions.",
     "Cloud automation improved the operational efficiency of the hospital logistics network."),

    ("Efficient", "adjective", "B1", "/ɪˈfɪʃ.ənt/", "efisien / berdaya guna tinggi tanpa boros",
     "Mampu bekerja dengan cepat, tepat, dan tanpa membuang-buang sumber daya.",
     "Achieving maximum productivity with minimum wasted effort or expense.",
     ["Efficiently", "Efficiency", "Effective"], ["Productive", "Competent", "Streamlined", "Cost-effective", "Proficient"], ["Inefficient", "Wasteful", "Slow"],
     "LED light bulbs are far more energy-efficient than traditional incandescent lighting.",
     "The software firm developed an efficient database indexing algorithm for large datasets."),

    ("Efficiently", "adverb", "B1", "/ɪˈfɪʃ.ənt.li/", "secara efisien / dengan daya guna optimal",
     "Dengan cara yang menghemat waktu, tenaga, dan biaya sambil tetap mencapai hasil prima.",
     "In a well-organized and competent way; without wasting time or resources.",
     ["Efficient", "Efficiency", "Smoothly"], ["Smoothly", "Competently", "Productively", "Skillfully", "Speedily"], ["Inefficiently", "Wastefully", "Clumsily"],
     "The automated sorting line processes thousands of postal packages efficiently each hour.",
     "She organized her study schedule efficiently to prepare for the licensing examinations."),

    ("Effort", "noun", "A1", "/ˈef.ət/", "upaya keras / pengerahan daya dan tenaga",
     "Pengerahan tenaga fisik atau mental secara sungguh-sungguh untuk menyelesaikan tugas.",
     "A vigorous or determined attempt; physical or mental energy needed to do something.",
     ["Effortless", "Effortlessly", "Endeavor"], ["Endeavor", "Striving", "Exertion", "Attempt", "Trial"], ["Inaction", "Sloth", "Idleness"],
     "Achieving fluency in a second language requires consistent daily effort and immersion.",
     "The community made a united effort to restore the public park after the storm."),

    ("Effortless", "adjective", "B2", "/ˈef.ət.ləs/", "tanpa susah payah / tampak sangat mudah",
     "Membutuhkan sedikit atau tanpa usaha yang tampak; tampak sangat lancar dan anggun.",
     "Requiring no physical or mental exertion; achieved with ease.",
     ["Effortlessly", "Effortlessness", "Easy"], ["Easy", "Graceful", "Smooth", "Painless", "Unforced"], ["Strenuous", "Difficult", "Laborious", "Arduous"],
     "The Olympic figure skater executed a series of difficult jumps with effortless grace.",
     "His natural musical ear made learning new piano melodies seem completely effortless."),

    ("Effortlessly", "adverb", "B2", "/ˈef.ət.ləs.li/", "dengan sangat mudah / tanpa kesulitan",
     "Dengan cara yang tampak mengalir alami tanpa memerlukan tenaga besar.",
     "In a manner that requires no physical or mental exertion, such as with grace and ease.",
     ["Effortless", "Easily", "Smoothly"], ["Easily", "Gracefully", "Smoothly", "Fluidly", "Naturally"], ["Laboriously", "Strenuously", "With difficulty"],
     "The dolphin glided effortlessly through the calm turquoise waters of the lagoon.",
     "She answered the interviewer's complex theoretical questions effortlessly and articulately."),

    ("Elaborate", "adjective", "B2", "/ɪˈlæb.ər.ət/", "rumit mendetail / terperinci kaya hiasan",
     "Dikerjakan dengan perhatian mendalam terhadap setiap detail kecil; sangat terperinci.",
     "Involving many carefully arranged parts or details; detailed and complicated in design.",
     ["Elaboration", "Elaborately", "Intricate"], ["Intricate", "Detailed", "Complex", "Ornate", "Sophisticated"], ["Simple", "Plain", "Basic", "Rudimentary"],
     "The palace ceiling was decorated with elaborate baroque frescoes and gold leaf.",
     "The research team developed an elaborate simulation model to forecast weather patterns."),

    ("Elaborate", "verb", "B2", "/ɪˈlæb.ə.reɪt/", "menjelaskan terperinci / menguraikan mendalam",
     "Mengembangkan atau menyajikan penjelasan dengan menambahkan lebih banyak rincian penting.",
     "Develop or present a theory, policy, or system in further detail.",
     ["Elaboration", "Expand", "Clarify"], ["Expand", "Amplify", "Detail", "Explicate", "Flesh out"], ["Simplify", "Summarize", "Abridge"],
     "The professor asked the candidate to elaborate on the methodology used in the study.",
     "During the press conference, the finance minister elaborated on the proposed tax reforms."),

    ("Elastic", "adjective", "B2", "/ɪˈlæs.tɪk/", "elastis kenyal / fleksibel dapat kembali ke bentuk asal",
     "Mampu kembali ke bentuk aslinya setelah ditarik atau ditekan; lentur beradaptasi.",
     "Able to resume its normal shape spontaneously after contraction, dilatation, or distortion.",
     ["Elasticity", "Elastically", "Flexible"], ["Flexible", "Pliant", "Resilient", "Stretchable", "Supple"], ["Rigid", "Stiff", "Inflexible", "Brittle"],
     "The athletic fabric contains elastic fibers that provide flexibility during workouts.",
     "Economists observed that consumer demand for luxury goods is highly price elastic."),

    ("Elasticity", "noun", "C1", "/ˌel.æˈstɪs.ə.ti/", "elastisitas / kelenturan daya lentur",
     "Sifat bahan yang memungkinkannya memanjang atau berubah bentuk lalu kembali utuh.",
     "The ability of an object or material to resume its normal shape after being stretched or compressed.",
     ["Elastic", "Flexibility", "Resilience"], ["Resilience", "Flexibility", "Springiness", "Suppleness", "Give"], ["Rigidity", "Stiffness", "Inelasticity"],
     "Natural rubber retains its elasticity even under cold winter outdoor temperatures.",
     "Price elasticity of demand measures how consumer purchasing reacts to price changes."),

    ("Elated", "adjective", "C1", "/iˈleɪ.tɪd/", "sangat gembira / bersuka cita meluap-luap",
     "Merasa luar biasa bahagia dan bangga atas keberhasilan atau kabar baik yang besar.",
     "Ecstatically happy; in high spirits and filled with delightful celebration.",
     ["Elation", "Elatedly", "Overjoyed"], ["Overjoyed", "Exhilarated", "Ecstatic", "Thrilled", "Euphoric"], ["Depressed", "Miserable", "Downcast", "Dejected"],
     "The young scientist felt elated when her research paper was accepted by Nature.",
     "The entire stadium was elated as the hometown team scored the winning goal in overtime."),

    ("Elation", "noun", "C1", "/iˈleɪ.ʃən/", "kegembiraan luar biasa / rasa sukacita mendalam",
     "Perasaan kebahagiaan, kegembiraan, dan kebanggaan yang meluap-luap.",
     "Great happiness and exhilaration; state of overwhelming joy.",
     ["Elated", "Joy", "Exhilaration"], ["Exhilaration", "Ecstasy", "Euphoria", "Jubilation", "Rapture"], ["Despair", "Depression", "Gloom", "Melancholy"],
     "A wave of elation swept through the mission control room as the rover landed safely on Mars.",
     "She experienced profound elation upon crossing the marathon finish line after months of training."),

    ("Elderly", "adjective", "A2", "/ˈel.dəl.i/", "lanjut usia / kaum lansia berumur",
     "Berada pada tahap usia lanjut dalam siklus hidup manusia; sopan untuk orang tua.",
     "Of a person, polite word for old; past middle age.",
     ["Elder", "Eldest", "Senior"], ["Senior", "Aged", "Older", "Venerable", "Mature"], ["Young", "Youthful", "Juvenile"],
     "The municipal community center offers gentle yoga and art classes for elderly residents.",
     "Volunteers deliver warm nutritious meals to homebound elderly citizens every weekend."),

    ("Elect", "verb", "A2", "/iˈlekt/", "memilih secara demokratis / mengangkat lewat suara",
     "Memilih seseorang untuk memegang jabatan publik atau posisi kepemimpinan melalui pemilu.",
     "Choose someone to hold public office or some other position by voting.",
     ["Election", "Electoral", "Vote"], ["Vote in", "Choose", "Appoint", "Designate", "Select"], ["Reject", "Dismiss", "Depose"],
     "Citizens queued patiently at neighborhood voting stations to elect their town mayor.",
     "The university faculty met to elect a new academic dean for the sciences division."),

    ("Election", "noun", "A2", "/iˈlek.ʃən/", "pemilihan umum / pemungutan suara resmi",
     "Proses pemungutan suara formal untuk menentukan pemegang jabatan kepemimpinan.",
     "A formal and organized choice by vote of a person for a political office or other position.",
     ["Electoral", "Electorate", "Poll"], ["Poll", "Ballot", "Voting", "Referendum", "Plebiscite"], ["Appointment"],
     "International election observers confirmed that the national voting was fair and transparent.",
     "Campaign volunteers distributed pamphlets explaining candidate platforms ahead of the election."),

    ("Electric", "adjective", "A2", "/iˈlek.trɪk/", "bertenaga listrik / sangat menggetarkan suasana",
     "Menggunakan atau digerakkan oleh tenaga listrik; penuh sensasi yang mendebarkan.",
     "Of, worked by, or charged with electricity; exciting and thrilling.",
     ["Electrical", "Electricity", "Electrify"], ["Powered", "Charged", "Thrilling", "Dynamic", "Electrifying"], ["Mechanical", "Manual", "Dull"],
     "The city expanded its fleet of clean electric buses to reduce urban air pollution.",
     "The atmosphere in the concert arena was electric as the band took the stage."),

    ("Electrical", "adjective", "A2", "/iˈlek.trɪ.kəl/", "kelistrikan / berkaitan dengan sirkuit listrik",
     "Berhubungan dengan pembangkitan, transmisi, atau penggunaan daya listrik dan sirkuit.",
     "Concerned with, operating by, or producing electricity.",
     ["Electric", "Electricity", "Electronic"], ["Power", "Current-related", "Electrified", "Galvanic"], ["Non-electrical"],
     "Certified electrical engineers inspected the wiring of the commercial high-rise.",
     "Keep all electrical appliances away from wet surfaces to prevent accidental shocks."),

    ("Electricity", "noun", "A2", "/ɪˌlekˈtrɪs.ə.ti/", "tenaga listrik / energi arus listrik",
     "Bentuk energi yang dihasilkan dari keberadaan dan pergerakan partikel bermuatan.",
     "A form of energy resulting from the existence of charged particles, such as electrons.",
     ["Electric", "Electrify", "Power"], ["Power", "Current", "Energy", "Voltage", "Charge"], ["Darkness"],
     "Rooftop solar photovoltaic panels generate clean electricity for the community school.",
     "Storm winds temporarily knocked down regional transmission lines, cutting electricity to the valley."),

    ("Electrify", "verb", "B2", "/iˈlek.trɪ.faɪ/", "mengaliri listrik / menggemparkan penonton",
     "Mengisi atau mengaliri sesuatu dengan listrik; membuat seseorang sangat bersemangat.",
     "Charge with electricity; excite someone enormously and arouse intense interest.",
     ["Electrification", "Electric", "Excite"], ["Excite", "Thrill", "Galvanize", "Stimulate", "Energize"], ["Bore", "Dampen", "Depress"],
     "The national railway project plans to electrify five hundred kilometers of commuter track.",
     "Her passionate violin solo electrified the audience, prompting an immediate standing ovation."),

    ("Electronic", "adjective", "A2", "/ɪˌlekˈtrɒn.ɪk/", "elektronik / berbasis mikroprosesor digital",
     "Memiliki atau menggunakan komponen mikrochip, semikonduktor, dan sirkuit digital.",
     "Having or operating with components such as microchips and transistors that control current.",
     ["Electronics", "Electronically", "Digital"], ["Digital", "Automated", "Cyber", "Computerized", "Microprocessor"], ["Analog", "Manual", "Mechanical"],
     "Modern automobiles incorporate dozens of electronic control units to optimize safety.",
     "University students access course syllabi and submit essays through an electronic portal."),

    ("Electronics", "noun", "B1", "/ɪˌlekˈtrɒn.ɪks/", "ilmu elektronika / perangkat elektronik",
     "Cabang fisika dan teknologi yang berhubungan dengan sirkuit terpadu dan perangkat.",
     "The branch of physics and technology concerned with the design of circuits using microchips.",
     ["Electronic", "Semiconductor", "Hardware"], ["Hardware", "Gadgets", "Devices", "Circuitry", "Microchips"], ["Mechanicals"],
     "Consumer electronics recycling programs prevent toxic heavy metals from entering landfills.",
     "Japan and South Korea are world leaders in advanced semiconductor and electronics manufacturing."),

    ("Elegant", "adjective", "B1", "/ˈel.ɪ.ɡənt/", "anggun menawan / rapi berkelas / luwes",
     "Menyenangkan secara estetika, anggun dalam gerakan, dan bernilai seni tinggi.",
     "Pleasingly graceful and stylish in appearance or manner; ingeniously simple.",
     ["Elegance", "Elegantly", "Graceful"], ["Graceful", "Stylish", "Refined", "Chic", "Sophisticated"], ["Clumsy", "Crude", "Gaudy", "Inartistic"],
     "The ballroom dancers moved across the floor in elegant synchronization with the waltz.",
     "Mathematicians admire Euler's formula for its concise and elegant representation of constants."),

    ("Element", "noun", "B1", "/ˈel.ɪ.mənt/", "elemen unsur pokok / komponen pembentuk",
     "Bagian mendasar yang esensial dari suatu kesatuan; zat kimia murni yang tak terbagi.",
     "An essential or characteristic part of something abstract; a primary chemical substance.",
     ["Elemental", "Elementary", "Component"], ["Component", "Constituent", "Factor", "Ingredient", "Basis"], ["Whole", "Aggregate", "Compound"],
     "Mutual respect is a fundamental element of any long-lasting personal friendship.",
     "Hydrogen and oxygen are chemical elements that chemically bond to form water molecules."),

    ("Elementary", "adjective", "A2", "/ˌel.ɪˈmen.tər.i/", "tingkat dasar / mendasar pemula",
     "Berkaitan dengan hal-hal pokok dan paling awal dari suatu mata pelajaran.",
     "Relating to the basic elements of a subject; rudimentary and straightforward.",
     ["Element", "Basic", "Fundamental"], ["Basic", "Fundamental", "Primary", "Rudimentary", "Introductory"], ["Advanced", "Complex", "Sophisticated"],
     "The course introduces students to elementary principles of organic chemistry.",
     "Elementary school teachers nurture curiosity and foundational reading skills in young learners."),

    ("Elevate", "verb", "B2", "/ˈel.ɪ.veɪt/", "mengangkat posisi / menaikkan derajat",
     "Menaikkan ke posisi yang lebih tinggi secara fisik atau meningkatkan status martabat.",
     "Raise or lift to a higher position; raise to a more important or higher level.",
     ["Elevation", "Elevator", "Elevated"], ["Raise", "Lift", "Hoist", "Promote", "Exalt"], ["Lower", "Demote", "Degrade", "Depress"],
     "Using high-quality natural ingredients will elevate the flavor profile of any home recipe.",
     "The company board voted to elevate the senior researcher to the position of vice president."),

    ("Elevation", "noun", "B2", "/ˌel.ɪˈveɪ.ʃən/", "ketinggian tempat / pengangkatan derajat",
     "Tinggi suatu tempat di atas permukaan laut; kenaikan jabatan atau status.",
     "Height above a given level, especially sea level; the action or fact of elevating.",
     ["Elevate", "Elevated", "Altitude"], ["Altitude", "Height", "Prominence", "Promotion", "Loftiness"], ["Depression", "Depth", "Demotion"],
     "The mountain observatory sits at an elevation of three thousand meters above sea level.",
     "His elevation to department director reflected years of dedication and peer recognition."),

    ("Elevator", "noun", "A2", "/ˈel.ɪ.veɪ.tər/", "lift penumpang / ruang pengangkut bertingkat",
     "Kompartemen mekanis berdaya listrik untuk menaikkan dan menurunkan orang antarlantai.",
     "A platform or compartment housed in a shaft for raising and lowering people or things.",
     ["Elevate", "Lift", "Hoist"], ["Lift", "Hoist", "Escalator", "Dumbwaiter"], ["Stairs"],
     "Please take the express elevator on the left to reach the rooftop observation restaurant.",
     "The hotel modernized its heritage elevator with smooth whisper-quiet electric motors."),

    ("Eligible", "adjective", "B2", "/ˈel.ɪ.dʒə.bəl/", "memenuhi syarat / berhak terpilih",
     "Memiliki kualifikasi atau memenuhi persyaratan yang ditetapkan untuk suatu hal.",
     "Having the right to do or obtain something; satisfying the appropriate conditions.",
     ["Eligibility", "Ineligible", "Qualified"], ["Qualified", "Entitled", "Suitable", "Fit", "Acceptable"], ["Ineligible", "Unqualified", "Disqualified"],
     "Graduates with top academic honors are eligible to apply for prestigious international fellowships.",
     "Only registered citizens aged eighteen and above are eligible to vote in national elections."),

    ("Eliminate", "verb", "B1", "/iˈlɪm.ɪ.neɪt/", "meniadakan / menghapus tuntas / menyingkirkan",
     "Menghilangkan atau menyingkirkan sepenuhnya sesuatu yang tidak diinginkan.",
     "Completely remove or get rid of something; expel or exclude from consideration.",
     ["Elimination", "Eliminator", "Eradicate"], ["Eradicate", "Remove", "Abolish", "Expel", "Discard"], ["Retain", "Include", "Preserve", "Adopt"],
     "Adopting digital workflows helps companies eliminate unnecessary paper consumption.",
     "The health campaign aims to eliminate preventable infectious diseases through widespread vaccination.")
]

print("Extra EL dataset created with", len(EXTRA_EL_WORDS), "words.")
