#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Full remainder dataset for Oxford MR (Part 3) and SZ (Part 4).
"""

REMAINDER_MR = [
    ("Quaint", "adjective", "B2", "/kweɪnt/", "unik kuno menarik / memikat bersahaja",
     "Menarik atau tidak biasa karena kuno, bersahaja, atau bergaya masa lalu.",
     "Attractively unusual or old-fashioned in character or appearance.",
     ["Quaintly", "Picturesque", "Charming"], ["Picturesque", "Charming", "Old-world", "Vintage", "Idyllic"], ["Modern", "Ugly", "Conventional"],
     "The travelers stayed at a quaint seaside cottage with thatched roofs and stone fireplaces.",
     "Cobblestone streets and quaint pastry shops give the historic village an enchanting atmosphere."),

    ("Qualify", "verb", "B1", "/ˈkwɒl.ɪ.faɪ/", "memenuhi kualifikasi / berhak lolos",
     "Memenuhi syarat atau kriteria yang dibutuhkan; lulus standar sertifikasi profesional.",
     "Be entitled to a particular benefit or privilege by fulfilling necessary conditions.",
     ["Qualification", "Qualified", "Certify"], ["Certify", "Authorize", "Fit", "Pass", "Graduate"], ["Disqualify", "Fail", "Incapacitate"],
     "Applicants must pass the professional examination to qualify as registered architects.",
     "The national football team qualified for the continental championship tournament after winning the playoffs."),

    ("Qualitative", "adjective", "B2", "/ˈkwɒl.ɪ.tə.tɪv/", "kualitatif / berdasarkan mutu dan karakteristik",
     "Berkaitan dengan atau diukur berdasarkan kualitas atau karakteristik daripada kuantitas.",
     "Relating to, measuring, or measured by the quality of something rather than its quantity.",
     ["Quality", "Qualitatively", "Descriptive"], ["Descriptive", "Subjective", "Character-based", "Evaluative"], ["Quantitative", "Numerical"],
     "The sociology study combined quantitative statistical surveys with in-depth qualitative interviews.",
     "Qualitative customer feedback provided actionable insights into product usability."),

    ("Quantum", "noun", "B2", "/ˈkwɒn.təm/", "kuantum fisika / lompatan perubahan besar",
     "Jumlah diskrit energi atom; peningkatan atau kemajuan besar yang mendasar.",
     "A discrete quantity of energy proportional in magnitude to the frequency of the radiation; significant advance.",
     ["Quantum leap", "Atomic", "Discrete"], ["Unit", "Portion", "Leap", "Advance", "Breakthrough"], ["Continuous"],
     "Quantum computing harnesses the strange principles of superposition to solve complex equations.",
     "The invention of the microchip represented a quantum leap forward in telecommunications technology."),

    ("Quench", "verb", "B2", "/kwentʃ/", "memuaskan dahaga / memadamkan api bara",
     "Memuaskan rasa haus dengan minum; memadamkan api atau keinginan yang membara.",
     "Satisfy one's thirst by drinking; extinguish a fire or flame.",
     ["Thirst-quenching", "Extinguish", "Sate"], ["Sate", "Slake", "Satisfy", "Extinguish", "Douse"], ["Ignite", "Inflame", "Dehydrate"],
     "Fresh cold coconut water is the best drink to quench your thirst on a hot tropical afternoon.",
     "Firefighters worked tirelessly through the night to quench the lingering forest blaze."),

    ("Query", "noun", "B1", "/ˈkwɪə.ri/", "pertanyaan pencarian / kueri pencarian data",
     "Pertanyaan, terutama yang mengungkapkan keraguan atau meminta informasi tambahan.",
     "A question, especially one expressing doubt or requesting information.",
     ["Inquiry", "Question", "Interrogate"], ["Inquiry", "Question", "Doubt", "Search", "Interrogation"], ["Answer", "Reply", "Resolution"],
     "The helpdesk support team responds promptly to every customer query via email.",
     "Database administrators optimize SQL queries to retrieve records from millions of rows in milliseconds."),

    ("Quest", "noun", "B2", "/kwest/", "pencarian mulia / penjelajahan demi tujuan luhur",
     "Pencarian atau penjelajahan yang panjang dan penuh tantangan untuk menemukan sesuatu yang berharga.",
     "A long or arduous search for something; an adventurous expedition in stories.",
     ["Inquest", "Pursuit", "Expedition"], ["Pursuit", "Expedition", "Search", "Mission", "Endeavor"], ["Inaction", "Abandonment"],
     "The medical research institute launched a global quest to develop a universal influenza vaccine.",
     "Legendary folklore tells of knights embarking on an epic quest to find the Holy Grail."),

    ("Quota", "noun", "B2", "/ˈkwəʊ.tə/", "kuota jatah / batas alokasi kuantitas",
     "Jumlah atau bagian proporsional tetap yang dialokasikan atau diwajibkan untuk dipenuhi.",
     "A limited or fixed number or amount of people or things, in particular under official rules.",
     ["Allocation", "Share", "Allotment"], ["Allocation", "Share", "Allotment", "Cap", "Allowance"], ["Limitless"],
     "International environmental treaties establish strict annual fishing quotas to prevent depletion.",
     "The sales division exceeded its quarterly performance quota ahead of schedule."),

    ("Quote", "verb", "A2", "/kwəʊt/", "mengutip perkataan / menyebutkan penawaran harga",
     "Mengulang perkataan atau tulisan orang lain secara persis; menyebutkan estimasi biaya.",
     "Repeat or copy out a group of words from a text or speech; give an estimated price for a job.",
     ["Quotation", "Quote", "Cite"], ["Cite", "Extract", "Recite", "Estimate", "State"], ["Misquote", "Plagiarize"],
     "The valedictorian began her graduation speech with an inspiring quote from Nelson Mandela.",
     "The roofing contractor quoted a reasonable price estimate for repairing the storm damage."),

    ("Radiant", "adjective", "B2", "/ˈreɪ.di.ənt/", "berseri-seri cerah / memancarkan pendar cahaya",
     "Memancarkan cahaya atau kehangatan; wajah yang berseri-seri penuh kebahagiaan.",
     "Shining or glowing brightly; emitting heat or light; displaying immense joy.",
     ["Radiance", "Radiate", "Glowing"], ["Glowing", "Beaming", "Luminous", "Dazzling", "Joyful"], ["Dull", "Gloomy", "Dim", "Sad"],
     "The bride looked radiant as she walked down the aisle surrounded by flowers and family.",
     "Solar panels convert the sun's radiant energy directly into clean household electricity."),

    ("Radical", "adjective", "B2", "/ˈræd.ɪ.kəl/", "radikal mendasar / perubahan revolusioner",
     "Mempengaruhi hakikat mendasar dari sesuatu; menganjurkan perubahan politik atau sosial yang menyeluruh.",
     "Relating to or affecting the fundamental nature of something; far-reaching or thorough.",
     ["Radically", "Radicalism", "Fundamental"], ["Fundamental", "Drastic", "Revolutionary", "Sweeping", "Profound"], ["Conservative", "Moderate", "Superficial", "Mild"],
     "The architecture firm proposed a radical redesign of urban spaces centered around public parks.",
     "Transitioning to a zero-carbon economy requires radical innovations in green transport and manufacturing."),

    ("Rational", "adjective", "B2", "/ˈræʃ.ən.əl/", "rasional logis / berdasarkan akal sehat sehat",
     "Berdasarkan atau sesuai dengan akal budi atau logika; mampu berpikir secara jernih.",
     "Based on or in accordance with reason or logic; able to think clearly and make good decisions.",
     ["Rationality", "Rationally", "Logical"], ["Logical", "Reasonable", "Sensible", "Lucid", "Sound"], ["Irrational", "Illogical", "Absurd", "Emotional"],
     "In times of unexpected financial market volatility, investors must make calm and rational decisions.",
     "Scientists seek rational, empirically verified explanations for natural phenomena."),

    ("Realistic", "adjective", "B1", "/ˌrɪəˈlɪs.tɪk/", "realistis masuk akal / sesuai kenyataan hidup",
     "Memiliki atau menunjukkan pandangan yang bijaksana dan praktis tentang kenyataan hidup.",
     "Having or showing a sensible and practical idea of what can be achieved or expected.",
     ["Realism", "Realistically", "Pragmatic"], ["Pragmatic", "Feasible", "Plausible", "Lifelike", "Authentic"], ["Unrealistic", "Idealistic", "Fanciful", "Impractical"],
     "Set realistic daily study goals so that you maintain consistent progress without burnout.",
     "The cinematic special effects created a remarkably realistic visual simulation of outer space."),

    ("Reassure", "verb", "B2", "/ˌriː.əˈʃɔːr/", "menenangkan hati / meyakinkan agar tidak cemas",
     "Mengatakan atau melakukan sesuatu untuk menghilangkan rasa takut dan keraguan seseorang.",
     "Say or do something to remove the doubts and fears of someone; restore confidence.",
     ["Reassurance", "Reassuring", "Comfort"], ["Comfort", "Console", "Hearten", "Encourage", "Soothe"], ["Alarm", "Unnerve", "Terrify", "Dismay"],
     "The pediatrician spoke gently to reassure the worried parents about their child's recovery.",
     "Airline cabin crew reassured passengers during temporary turbulent atmospheric crosswinds."),

    ("Rebel", "noun", "B1", "/ˈreb.əl/", "pemberontak pembangkang / pejuang perlawanan",
     "Seseorang yang bangkit melawan otoritas atau menolak konvensi sosial yang berlaku.",
     "A person who rises in opposition or armed resistance against an established government or ruler.",
     ["Rebellion", "Rebellious", "Insurgent"], ["Insurgent", "Dissident", "Mutineer", "Revolutionary", "Maverick"], ["Loyalist", "Conformist"],
     "Historical records recount how rebels fought to overthrow feudal tyranny and establish civil rights.",
     "In modern teenage psychology, a healthy desire for self-identity can sometimes look like a rebel attitude."),

    ("Rebuke", "verb", "C1", "/rɪˈbjuːk/", "menegur keras / mencela kesalahan tajam",
     "Menyatakan celaan atau ketidaksetujuan yang tajam terhadap tindakan seseorang.",
     "Express sharp disapproval or criticism of someone because of their behavior or actions.",
     ["Rebuke", "Reprimand", "Chide"], ["Reprimand", "Scold", "Chide", "Admonish", "Censure"], ["Praise", "Applaud", "Commend"],
     "The ethics committee did not hesitate to rebuke the executive for misleading public shareholders.",
     "The mentor rebuked the apprentice gently, reminding him of safety rules in the metal workshop."),

    ("Recede", "verb", "B2", "/rɪˈsiːd/", "menyurut mundur / menjauh perlahan ke belakang",
     "Bergerak mundur atau menjauh dari suatu posisi sebelumnya; surutnya air banjir.",
     "Go or move back or further away from a previous position; diminish or lessen.",
     ["Recession", "Retreat", "Withdraw"], ["Retreat", "Withdraw", "Subside", "Ebb", "Diminish"], ["Advance", "Approach", "Surge", "Rise"],
     "Floodwaters began to recede slowly as sunny dry weather returned across the river basin.",
     "The distant mountain shoreline receded as the passenger ferry steamed into open waters."),

    ("Recognize", "verb", "A2", "/ˈrek.əɡ.naɪz/", "mengenali / mengakui secara resmi prestasi",
     "Mengidentifikasi seseorang atau sesuatu yang telah diketahui sebelumnya; menghargai jasa.",
     "Identify someone or something from having encountered them before; acknowledge officially.",
     ["Recognition", "Recognizable", "Acknowledge"], ["Acknowledge", "Identify", "Appreciate", "Honor", "Spot"], ["Ignore", "Overlook", "Disregard"],
     "I could immediately recognize her warm melodic laughter across the crowded banquet room.",
     "The international committee gathered to recognize outstanding humanitarian volunteers with medals."),

    ("Reconcile", "verb", "B2", "/ˈrek.ən.saɪl/", "mendamaikan / menyelaraskan dua hal yang bertolak",
     "Memulihkan hubungan persahabatan; membuat dua gagasan atau catatan keuangan selaras.",
     "Restore friendly relations between; make one account or idea consistent with another.",
     ["Reconciliation", "Harmonize", "Unite"], ["Harmonize", "Pacify", "Attune", "Settle", "Resolve"], ["Alienate", "Estrange", "Divide"],
     "Diplomats worked patiently for months to reconcile the opposing political factions.",
     "Accountants reconcile monthly bank ledger entries with incoming sales invoices to ensure accuracy."),

    ("Recover", "verb", "A2", "/rɪˈkʌv.ər/", "sembuh pulih / menemukan kembali barang hilang",
     "Kembali ke kondisi kesehatan yang normal setelah sakit; mendapatkan kembali apa yang hilang.",
     "Return to a normal state of health, mind, or strength; find or regain possession of.",
     ["Recovery", "Recoverable", "Heal"], ["Heal", "Recuperate", "Mend", "Regain", "Retrieve"], ["Deteriorate", "Lose", "Worsen"],
     "With proper rest and hydration, the athlete made a swift and complete recovery from the sprain.",
     "Divers managed to recover the ancient bronze amphora from the shipwreck off the Mediterranean coast."),

    ("Recruit", "verb", "B2", "/rɪˈkruːt/", "merekrut anggota baru / menghimpun tenaga kerja",
     "Mendaftarkan seseorang ke dalam angkatan bersenjata atau mempekerjakan karyawan baru.",
     "Enlist someone in the armed forces; recruit new personnel for an organization or enterprise.",
     ["Recruitment", "Recruiter", "Enlist"], ["Enlist", "Hire", "Draft", "Engage", "Sign up"], ["Dismiss", "Discharge", "Fire"],
     "The engineering technology firm plans to recruit top computer science graduates from local universities.",
     "Community volunteer organizations actively recruit enthusiastic members to support food banks."),

    ("Rectify", "verb", "C1", "/ˈrek.tɪ.faɪ/", "membetulkan / meluruskan kesalahan menjadi benar",
     "Memperbaiki sesuatu yang salah atau mengembalikan situasi ke kondisi yang tepat.",
     "Put right; correct an error or deficiency in a system, text, or procedure.",
     ["Rectification", "Correct", "Ambit"], ["Correct", "Amend", "Remedy", "Repair", "Right"], ["Damage", "Worsen", "Corrupt"],
     "The software firm worked quickly to rectify the security vulnerability with a software patch.",
     "Management took immediate corrective action to rectify unfair salary disparities across teams."),

    ("Redundant", "adjective", "B2", "/rɪˈdʌn.dənt/", "berlebihan mubazir / diberhentikan dari kerja",
     "Tidak lagi dibutuhkan atau berguna; lebih dari apa yang diperlukan; diberhentikan kerja karena efisiensi.",
     "Not or no longer needed or useful; superfluous; dismissed from employment due to lack of need.",
     ["Redundancy", "Superfluous", "Excess"], ["Superfluous", "Excess", "Surplus", "Unneeded", "Spare"], ["Essential", "Necessary", "Indispensable"],
     "Automated digital workflows rendered several manual data entry filing positions redundant.",
     "The editor removed redundant paragraphs from the manuscript to enhance narrative flow."),

    ("Refine", "verb", "B2", "/rɪˈfaɪn/", "memurnikan / menyempurnakan kualitas keterampilan",
     "Menghilangkan kotoran atau zat asing; memperbaiki kualitas agar lebih sempurna dan elegan.",
     "Remove impurities or unwanted elements from; improve something by making small changes.",
     ["Refinement", "Refinery", "Purify"], ["Purify", "Perfect", "Hone", "Polish", "Cultivate"], ["Corrupt", "Degrade", "Pollute"],
     "Petrochemical plants refine crude petroleum into gasoline, diesel, and aviation kerosene.",
     "Writers continually refine their manuscript drafts to achieve crystal-clear prose and pacing."),

    ("Reflect", "verb", "B1", "/rɪˈflekt/", "memantulkan cahaya / merenungkan pelajaran hidup",
     "Memantulkan cahaya atau panas; memikirkan kembali peristiwa masa lalu dengan mendalam.",
     "Throw back heat, light, or sound without absorbing it; think deeply or carefully about.",
     ["Reflection", "Reflective", "Mirror"], ["Mirror", "Echo", "Contemplate", "Meditate", "Ponder"], ["Absorb", "Disregard"],
     "The calm mountain lake reflected the snow-capped alpine peaks with crystalline clarity.",
     "Journaling each evening helps individuals reflect on their personal growth and achievements."),

    ("Reform", "verb", "B2", "/rɪˈfɔːm/", "mereformasi / memperbarui sistem menjadi lebih adil",
     "Melakukan perubahan mendasar untuk memperbaiki institusi, undang-undang, atau perilaku.",
     "Make changes in something, typically a social, political, or economic institution, to improve it.",
     ["Reformation", "Reformer", "Overhaul"], ["Overhaul", "Improve", "Revamp", "Reorganize", "Transform"], ["Worsen", "Maintain", "Corrupt"],
     "The ministry announced ambitious plans to reform the national public education curriculum.",
     "Legal scholars advocated to reform outdated court procedures and guarantee faster trials."),

    ("Refrain", "verb", "B2", "/rɪˈfreɪn/", "menahan diri / berpantang melakukan sesuatu",
     "Menghentikan diri sendiri dari melakukan sesuatu, terutama yang menyenangkan atau menggoda.",
     "Stop oneself from doing something; avoid or abstain from an action.",
     ["Abstain", "Forbear", "Desist"], ["Abstain", "Desist", "Withhold", "Avoid", "Forbear"], ["Indulge", "Persist", "Continue"],
     "Passengers are politely requested to refrain from smoking in all airport terminals.",
     "She decided to refrain from commenting during the heated political discussion among colleagues."),

    ("Refuge", "noun", "B2", "/ˈref.juːdʒ/", "suaka perlindungan / tempat berteduh dari bahaya",
     "Keadaan terlindung atau tempat yang aman dari bahaya atau kesulitan hidup.",
     "A condition of being safe or sheltered from pursuit, danger, or trouble; a safe haven.",
     ["Refugee", "Sanctuary", "Shelter"], ["Sanctuary", "Haven", "Shelter", "Asylum", "Retreat"], ["Danger", "Exposure", "Peril"],
     "The mountain cabin served as a warm refuge for hikers caught in the sudden winter blizzard.",
     "The coastal mangrove wetlands provide a protected natural refuge for endangered sea turtles."),

    ("Refute", "verb", "C1", "/rɪˈfjuːt/", "membantah menyanggah / membuktikan kekeliruan",
     "Membuktikan bahwa suatu pernyataan atau teori salah atau keliru dengan bukti nyata.",
     "Prove a statement or theory to be wrong or false; disprove with evidence.",
     ["Refutation", "Disprove", "Rebut"], ["Disprove", "Rebut", "Counter", "Contradict", "Invalidate"], ["Confirm", "Validate", "Support", "Prove"],
     "The research scientist presented empirical experimental data to refute the opposing hypothesis.",
     "The defense attorney produced timestamped security video to refute the false allegations."),

    ("Reiterate", "verb", "C1", "/riːˈɪt.ər.eɪt/", "menegaskan kembali / mengulang pernyataan",
     "Mengatakan sesuatu sekali lagi atau berulang kali untuk kejelasan atau penekanan.",
     "Say something again or a number of times, typically for emphasis or clarity.",
     ["Reiteration", "Repeat", "Restate"], ["Repeat", "Restate", "Emphasize", "Echo", "Recapitulate"], ["Retract", "Withdraw"],
     "The health minister reiterated the importance of regular handwashing and vaccination.",
     "Let me reiterate that all student research submissions must adhere to academic honesty codes."),

    ("Rejoice", "verb", "B2", "/rɪˈdʒɔɪs/", "bersukacita riang / bersuka ria merayakan",
     "Merasakan atau menunjukkan kegembiraan yang besar dan sukacita yang tulus.",
     "Feel or show great joy or delight; celebrate with happiness.",
     ["Rejoicing", "Joyful", "Celebrate"], ["Celebrate", "Exult", "Triumph", "Glory", "Cheer"], ["Mourn", "Grieve", "Lament", "Weep"],
     "Citizens rejoiced in the city square as the historic peace treaty was officially signed.",
     "The entire family gathered to rejoice on the occasion of their grandmother's centenary birthday.")
]

print("Remainder MR dataset ready:", len(REMAINDER_MR))
