#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Rich supplemental Oxford words for MR (Part 3) and SZ (Part 4).
"""

SUPPLEMENTAL_MR = [
    ("Magnify", "verb", "B2", "/ˈmæɡ.nɪ.faɪ/", "memperbesar tampilan / membesarkan masalah",
     "Membuat sesuatu tampak lebih besar dari ukuran aslinya; memperbesar skala dampak.",
     "Make something appear larger than it is, especially with a lens or microscope; exaggerate.",
     ["Magnification", "Magnifier", "Enlarge"], ["Enlarge", "Amplify", "Augment", "Exaggerate", "Intensify"], ["Minimize", "Reduce", "Diminish", "Shrink"],
     "A scanning electron microscope can magnify biological specimens thousands of times.",
     "Sensationalist media outlets often magnify minor political disagreements into national crises."),

    ("Mandatory", "adjective", "B2", "/ˈmæn.də.tər.i/", "wajib mutlak / diharuskan oleh peraturan",
     "Diharuskan oleh undang-undang atau peraturan; tidak bersifat opsional.",
     "Required by law or rules; compulsory and obligatory.",
     ["Mandate", "Obligatory", "Compulsory"], ["Compulsory", "Obligatory", "Required", "Requisite", "Involuntary"], ["Optional", "Voluntary", "Discretionary"],
     "Wearing safety helmets is mandatory for all construction personnel on site.",
     "The university introduced mandatory ethics modules for all incoming medical students."),

    ("Maneuver", "noun", "B2", "/məˈnuː.vər/", "manuver taktis / gerakan terampil terkendali",
     "Gerakan yang direncanakan secara terampil untuk mencapai tujuan atau menghindari rintangan.",
     "A movement or series of moves requiring skill and care; a carefully planned scheme.",
     ["Maneuverable", "Tactic", "Operation"], ["Tactic", "Operation", "Ploy", "Strategy", "Movement"], ["Inaction", "Stagnation"],
     "The fighter pilot executed a daring aerial maneuver to evade the simulated threat.",
     "Through skillful diplomatic maneuvers, the ambassador secured an amicable trade treaty."),

    ("Mankind", "noun", "B1", "/mænˈkaɪnd/", "umat manusia / seluruh peradaban insani",
     "Seluruh spesies manusia yang hidup di bumi dipandang sebagai satu kesatuan utuh.",
     "The human race considered collectively; all human beings.",
     ["Humanity", "Human race", "Society"], ["Humanity", "Human race", "People", "Homo sapiens", "Mortals"], ["Inanimate"],
     "The preservation of natural biodiversity is an urgent shared responsibility for all mankind.",
     "Landing astronauts on the moon was hailed as a monumental leap for mankind."),

    ("Manuscript", "noun", "B2", "/ˈmæn.jə.skrɪpt/", "naskah tulisan tangan / draf asli buku",
     "Buku, dokumen, atau komposisi musik yang ditulis tangan atau diketik sebelum diterbitkan.",
     "A book, document, or piece of music written by hand rather than typed or printed.",
     ["Script", "Draft", "Text"], ["Draft", "Text", "Document", "Autograph", "Codex"], ["Printed copy"],
     "Archaeologists discovered ancient biblical manuscripts preserved inside sealed clay jars.",
     "The novelist submitted her completed fantasy manuscript to the London publishing house."),

    ("Marginal", "adjective", "B2", "/ˈmɑː.dʒɪ.nəl/", "marjinal / kecil di batas pinggiran / tak signifikan",
     "Berada di tepi atau batas; sangat kecil atau tidak terlalu penting.",
     "Of secondary or minor importance; not central; situated at the edge or margin.",
     ["Marginalize", "Marginally", "Minor"], ["Minor", "Insignificant", "Borderline", "Peripheral", "Negligible"], ["Central", "Significant", "Major", "Crucial"],
     "The minor price increase had only a marginal impact on overall consumer demand.",
     "Public welfare programs aim to empower marginal communities through vocational job training."),

    ("Marine", "adjective", "B1", "/məˈriːn/", "kelautan / berhubungan dengan biota laut samudera",
     "Berkaitan dengan laut, samudera, dan organisme yang hidup di dalamnya.",
     "Relating to or found in the sea; nautical and maritime.",
     ["Maritime", "Oceanic", "Aquatic"], ["Oceanic", "Maritime", "Nautical", "Aquatic", "Seafaring"], ["Terrestrial", "Land-based"],
     "Marine biologists discovered vibrant deep-sea coral reefs near the volcanic hydrothermal vent.",
     "Pollution from microplastics poses a severe long-term threat to global marine life."),

    ("Marital", "adjective", "B2", "/ˈmær.ɪ.təl/", "perkawinan / berhubungan dengan ikatan pernikahan",
     "Berkaitan dengan pernikahan atau hubungan suami istri yang sah.",
     "Relating to marriage or the formal relationship of a married couple.",
     ["Marriage", "Matrimonial", "Conjugal"], ["Matrimonial", "Conjugal", "Nuptial", "Spousal", "Wedded"], ["Single", "Unmarried"],
     "The family counseling center assists couples in resolving marital communication conflicts.",
     "The legal contract clearly outlined marital property division in the event of separation."),

    ("Massive", "adjective", "B1", "/ˈmæs.ɪv/", "sangat besar masif / kokoh berukuran raksasa",
     "Berukuran sangat besar, berat, dan kokoh; berlangsung dalam skala yang luas.",
     "Large and heavy or solid; exceptionally large, ambitious, or severe.",
     ["Massively", "Huge", "Gigantic"], ["Gigantic", "Huge", "Enormous", "Colossal", "Monumental"], ["Tiny", "Slight", "Miniature", "Fragile"],
     "The medieval fortress was protected by massive granite walls and iron-reinforced gates.",
     "The government announced a massive multi-billion-dollar infrastructure revitalization plan."),

    ("Masterpiece", "noun", "B2", "/ˈmɑː.stə.piːs/", "mahakarya / karya seni puncak bernilai agung",
     "Karya seni, sastra, atau musik yang dibuat dengan keterampilan luar biasa tinggi.",
     "A work of outstanding artistry, skill, or workmanship; supreme creation.",
     ["Magnum opus", "Classic", "Triumph"], ["Magnum opus", "Tour de force", "Classic", "Triumph", "Monument"], ["Mediocrity", "Failure"],
     "Leonardo da Vinci's Mona Lisa is celebrated globally as an immortal renaissance masterpiece.",
     "Critics praised the director's latest film as a cinematic masterpiece of storytelling and lighting."),

    ("Maternal", "adjective", "B2", "/məˈtɜː.nəl/", "keibuan / berkaitan dengan sifat naluri ibu",
     "Berkaitan dengan ibu; menunjukkan kasih sayang dan perlindungan layaknya seorang ibu.",
     "Relating to a mother, especially during pregnancy or shortly after childbirth; motherly.",
     ["Maternity", "Motherly", "Paternal"], ["Motherly", "Affectionate", "Protective", "Nurturing", "Warm"], ["Paternal", "Cold", "Aloof"],
     "The mother bear exhibited fierce maternal instincts when protecting her playful cubs.",
     "Maternal healthcare clinics provide essential nutrition and prenatal checkups for expecting mothers."),

    ("Maximize", "verb", "B2", "/ˈmæk.sɪ.maɪz/", "memaksimalkan / memanfaatkan potensi tertinggi",
     "Meningkatkan atau memanfaatkan sesuatu hingga mencapai potensi atau kapasitas tertinggi.",
     "Make as large or great as possible; make the best use of.",
     ["Maximum", "Maximal", "Optimize"], ["Optimize", "Boost", "Increase", "Expand", "Leverage"], ["Minimize", "Curtail", "Diminish", "Reduce"],
     "Farmers use precision irrigation drip systems to maximize crop yield while conserving water.",
     "Students should organize daily study schedules to maximize cognitive retention and focus."),

    ("Meager", "adjective", "C1", "/ˈmiː.ɡər/", "sangat sedikit / serba minim pas-pasan",
     "Berjumlah sedikit, berkualitas rendah, atau tidak mencukupi kebutuhan dasar.",
     "Lacking in quantity or quality; lean, thin, or scanty.",
     ["Meagerness", "Scanty", "Sparse"], ["Scanty", "Sparse", "Inadequate", "Deficient", "Paltry"], ["Abundant", "Plentiful", "Generous", "Copious"],
     "The nomadic refugees survived in the harsh desert on meager rations of dry flatbread and water.",
     "Her meager starting salary forced her to budget every monthly household expense meticulously."),

    ("Mediate", "verb", "B2", "/ˈmiː.di.eɪt/", "menengahi / mendamaikan pihak yang bersengketa",
     "Campur tangan di antara orang atau kelompok untuk menyelesaikan perselisihan secara damai.",
     "Intervene between people in a dispute in order to bring about an agreement or reconciliation.",
     ["Mediation", "Mediator", "Arbitrate"], ["Arbitrate", "Intercede", "Reconcile", "Negotiate", "Moderate"], ["Instigate", "Aggravate", "Provoke"],
     "A neutral international envoy was chosen to mediate bilateral peace talks between the neighbors.",
     "Trained workplace counselors help mediate interpersonal disputes among office employees."),

    ("Meditate", "verb", "B2", "/ˈmed.ɪ.teɪt/", "bermeditasi / merenungkan batin dengan hening",
     "Memusatkan pikiran dalam keheningan untuk ketenangan batin atau tujuan spiritual.",
     "Focus one's mind for a period of time in silence for religious or relaxation purposes.",
     ["Meditation", "Meditative", "Reflect"], ["Contemplate", "Reflect", "Ponder", "Ruminate", "Deliberate"], ["Distract", "Overthink"],
     "She likes to meditate in the tranquil flower garden for twenty minutes every morning.",
     "Mindfulness coaches teach students how to meditate to relieve exam anxiety and enhance focus."),

    ("Medieval", "adjective", "B1", "/ˌmed.iˈiː.vəl/", "abad pertengahan / bergaya zaman feudal kuno",
     "Berkaitan dengan Zaman Pertengahan dalam sejarah Eropa (sekitar abad ke-5 hingga ke-15).",
     "Relating to the Middle Ages; ancient or antiquated in style.",
     ["Middle Ages", "Feudal", "Gothic"], ["Middle-aged", "Gothic", "Feudal", "Archaic", "Antique"], ["Modern", "Contemporary", "Futuristic"],
     "Tourists marveled at the towering stone ramparts of the preserved medieval French castle.",
     "Historians study medieval illuminated manuscripts to understand monastic scholarship."),

    ("Melancholy", "noun", "B2", "/ˈmel.əŋ.kɒl.i/", "kemurungan syahdu / kesedihan puitis mendalam",
     "Perasaan sedih yang mendalam, tenang, dan berlangsung lama tanpa sebab yang jelas.",
     "A feeling of pensive sadness, typically with no obvious cause.",
     ["Melancholic", "Sadness", "Sorrow"], ["Sadness", "Gloom", "Despondency", "Sorrow", "Wistfulness"], ["Cheerfulness", "Joy", "Exuberance"],
     "A gentle sense of melancholy washed over him as he listened to the rainy cello sonata.",
     "Autumn sunsets often evoke a wistful melancholy as deciduous leaves fall to the ground."),

    ("Memorable", "adjective", "B1", "/ˈmem.ər.ə.bəl/", "mengesankan / patut dikenang sepanjang masa",
     "Sangat luar biasa, menarik, atau penting sehingga mudah diingat selamanya.",
     "Easily remembered, especially because of being special, unusual, or remarkable.",
     ["Memorial", "Memory", "Unforgettable"], ["Unforgettable", "Notable", "Remarkable", "Historic", "Momentous"], ["Forgettable", "Unremarkable", "Ordinary"],
     "The family safari trip through the Serengeti wildlife reserve was a memorable experience.",
     "She delivered a memorable commencement speech that inspired thousands of young graduates."),

    ("Menace", "noun", "B2", "/ˈmen.ɪs/", "ancaman berbahaya / pengganggu ketertiban",
     "Seseorang atau sesuatu yang dapat membahayakan, merugikan, atau menimbulkan bahaya besar.",
     "A person or thing that is likely to cause harm; a threat or danger.",
     ["Menacing", "Threat", "Peril"], ["Threat", "Peril", "Danger", "Hazard", "Terror"], ["Safety", "Guardian", "Blessing"],
     "Unregulated plastic dumping in coastal waterways poses an ecological menace to marine life.",
     "The reckless drunk driver was condemned by the judge as a menace to public safety."),

    ("Merge", "verb", "B2", "/mɜːdʒ/", "menggabungkan diri / melebur menjadi satu kesatuan",
     "Menyatukan atau menyatu secara bertahap sehingga membentuk satu kesatuan tunggal.",
     "Combine or cause to combine to form a single entity; blend smoothly.",
     ["Merger", "Fusion", "Blend"], ["Combine", "Unite", "Blend", "Fuse", "Amalgamate"], ["Separate", "Divide", "Split", "Disconnect"],
     "The two telecommunication giants voted to merge into a single multinational provider.",
     "Two mountain streams merge at the bottom of the rocky gorge to form a rushing river."),

    ("Metallic", "adjective", "B1", "/məˈtæl.ɪk/", "bersifat logam / berkilau seperti metal",
     "Terbuat dari logam, menyerupai logam, atau memiliki kilau dan bunyi berdenting metal.",
     "Relating to or resembling metal; having the reflective sheen or sharp sound of metal.",
     ["Metal", "Metallurgy", "Lustrous"], ["Lustrous", "Gleaming", "Tinkling", "Hard", "Reflective"], ["Dull", "Matte", "Organic"],
     "The sports car was painted in a sleek metallic cobalt blue that glittered in sunlight.",
     "A sharp metallic click indicated that the heavy vault security lock had engaged."),

    ("Methodology", "noun", "B2", "/ˌmeθ.əˈdɒl.ə.dʒi/", "metodologi riset / kerangka sistematis penelitian",
     "Sistem metode, aturan, dan prinsip yang digunakan dalam suatu disiplin ilmu atau riset.",
     "A system of methods used in a particular area of study or activity.",
     ["Method", "Methodological", "Framework"], ["Framework", "Approach", "Procedure", "Technique", "Paradigm"], ["Chaos", "Haphazardness"],
     "The doctoral dissertation includes a rigorous chapter evaluating the quantitative research methodology.",
     "Agile project management offers a flexible development methodology for modern software firms."),

    ("Metric", "noun", "B2", "/ˈmet.rɪk/", "tolok ukur metrik / standar pengukuran data",
     "Sistem pengukuran matematis; parameter standar yang digunakan untuk mengukur kinerja.",
     "A system or standard of measurement; a set of figures or statistics that measure results.",
     ["Metrics", "Measurement", "Benchmark"], ["Benchmark", "Standard", "Index", "Parameter", "Criterion"], ["Guesswork"],
     "Customer retention rate is a crucial business metric for assessing subscription software growth.",
     "Most countries across the globe have adopted the scientific metric system of units."),

    ("Miniature", "adjective", "B2", "/ˈmɪn.ə.tʃər/", "miniatur mungil / versi berskala sangat kecil",
     "Sangat kecil; dibuat dalam bentuk atau skala yang jauh lebih kecil dari ukuran aslinya.",
     "Representing or being a smaller version of something; very small of its kind.",
     ["Minify", "Tiny", "Micro"], ["Tiny", "Small-scale", "Diminutive", "Pocket-sized", "Micro"], ["Gigantic", "Full-sized", "Colossal"],
     "The museum exhibited a delicate miniature replica of eighteenth-century Paris architecture.",
     "Bonsai masters cultivate beautiful miniature cedar trees in ceramic clay planters."),

    ("Minimize", "verb", "B2", "/ˈmɪn.ɪ.maɪz/", "meminimalkan dampak / menekan sekecil mungkin",
     "Mengurangi sesuatu hingga ke tingkat sekecil atau serendah mungkin.",
     "Reduce something, especially something unwanted, to the smallest possible amount or degree.",
     ["Minimum", "Minimal", "Curtail"], ["Reduce", "Curtail", "Lessen", "Diminish", "Downplay"], ["Maximize", "Increase", "Expand", "Exaggerate"],
     "Engineers designed aerodynamic winglets to minimize drag and reduce jet fuel consumption.",
     "Proper defensive driving techniques help minimize the probability of highway collisions."),

    ("Miracle", "noun", "B1", "/ˈmɪr.ə.kəl/", "mukjizat keajaiban / peristiwa luar biasa",
     "Peristiwa luar biasa yang mengagumkan dan tidak dapat dijelaskan oleh hukum alam biasa.",
     "A remarkable event or development that brings very welcome consequences and evokes wonder.",
     ["Miraculous", "Miraculously", "Wonder"], ["Wonder", "Marvel", "Prodigy", "Phenomenon", "Blessing"], ["Catastrophe", "Disaster"],
     "It was a medical miracle that the injured mountain climber survived the freezing avalanche.",
     "The rapid economic revival of post-war cities is celebrated as a modernization miracle."),

    ("Mitigate", "verb", "C1", "/ˈmɪt.ɪ.ɡeɪt/", "memitigasi / meredakan keparahan dampak",
     "Membuat sesuatu menjadi tidak terlalu buruk, keras, menyakitkan, atau berbahaya.",
     "Make something bad less severe, serious, or painful; alleviate or moderate.",
     ["Mitigation", "Unmitigated", "Alleviate"], ["Alleviate", "Moderate", "Lessen", "Ease", "Soften"], ["Aggravate", "Exacerbate", "Intensify", "Worsen"],
     "Planting mangrove forests along coastal shores helps mitigate typhoon wave surge damage.",
     "Prompt administration of antivenom will mitigate the toxic effects of snake bites."),

    ("Mobile", "adjective", "A2", "/ˈməʊ.baɪl/", "bergerak lincah / mudah berpindah tempat",
     "Mampu bergerak atau digerakkan dengan bebas dan mudah dari satu tempat ke tempat lain.",
     "Able to move or be moved freely or easily; relating to mobile phones or computing.",
     ["Mobility", "Mobilize", "Movable"], ["Movable", "Portable", "Flexible", "Roaming", "Adaptable"], ["Immobile", "Static", "Stationary", "Fixed"],
     "The government dispatched mobile medical clinics to deliver vaccines to remote mountain hamlets.",
     "Smartphones have transformed modern communication into a truly mobile and instant experience."),

    ("Modernize", "verb", "B2", "/ˈmɒd.ən.aɪz/", "memodernisasi / memperbarui sesuai zaman",
     "Mengadaptasi atau melengkapi sesuatu dengan perlengkapan atau gagasan masa kini.",
     "Adapt something to modern needs or habits, typically by installing modern equipment.",
     ["Modernization", "Modern", "Upgrade"], ["Upgrade", "Update", "Renovate", "Streamline", "Overhaul"], ["Outdate", "Regress"],
     "The port authority invested heavily to modernize container cranes and automated berths.",
     "Many traditional factories need to modernize their production lines with robotics."),

    ("Modest", "adjective", "B1", "/ˈmɒd.ɪst/", "rendah hati bersahaja / berukuran sedang wajar",
     "Tidak menyombongkan diri; berukuran atau bernilai sedang dan tidak berlebihan.",
     "Unassuming in the estimation of one's abilities; relatively moderate or limited in scale.",
     ["Modesty", "Modestly", "Humble"], ["Humble", "Unassuming", "Moderate", "Reasonable", "Simple"], ["Arrogant", "Boastful", "Excessive", "Extravagant"],
     "Despite winning the international Nobel prize, the geneticist remained humble and modest.",
     "The family lives in a modest wooden bungalow near the scenic lakeside forest."),

    ("Moisture", "noun", "B1", "/ˈmɔɪs.tʃər/", "kelembapan air / kadar uap air",
     "Air atau cairan lain yang tersebar dalam jumlah kecil sebagai uap atau embun.",
     "Water or other liquid diffused in a small quantity as vapor, within a solid, or on a surface.",
     ["Moist", "Moisturize", "Dampness"], ["Dampness", "Humidity", "Wetness", "Dew", "Condensation"], ["Dryness", "Aridity", "Dehydration"],
     "Tropical rainforest soil retains rich moisture beneath its thick canopy of fallen leaves.",
     "Apply natural aloe vera cream to restore natural moisture to dry and sunburned skin."),

    ("Momentum", "noun", "B2", "/məˈmen.təm/", "momentum dorongan laju / percepatan gerak",
     "Kekuatan atau daya dorong yang diperoleh dari pergerakan atau perkembangan pesat.",
     "The quantity of motion of a moving body; the impetus gained by a developing process.",
     ["Momentous", "Impetus", "Thrust"], ["Impetus", "Thrust", "Drive", "Velocity", "Energy"], ["Inertia", "Stagnation", "Stall"],
     "The grassroots environmental campaign gained unstoppable momentum across major university campuses.",
     "As the roller coaster sped down the steep rail slope, it gathered tremendous kinetic momentum."),

    ("Monarch", "noun", "B2", "/ˈmɒn.ək/", "raja ratu bermahkota / penguasa monarki",
     "Kepala negara yang berdaulat, seperti raja, ratu, atau kaisar, terutama seumur hidup.",
     "A sovereign head of state, especially a king, queen, or emperor.",
     ["Monarchy", "Monarchical", "Sovereign"], ["Sovereign", "Ruler", "King", "Queen", "Emperor"], ["Subject", "Citizen"],
     "The constitutional monarch represented the nation at formal diplomatic state banquets.",
     "Orange monarch butterflies migrate thousands of miles south every autumn to avoid winter cold."),

    ("Monopoly", "noun", "B2", "/məˈnɒp.əl.i/", "monopoli pasar / penguasaan tunggal mutlak",
     "Penguasaan eksklusif atas pasokan atau perdagangan komoditas atau layanan tertentu.",
     "The exclusive possession or control of the supply of or trade in a commodity or service.",
     ["Monopolize", "Monopolistic", "Cartel"], ["Cartel", "Dominance", "Corner", "Exclusive control"], ["Free market", "Competition"],
     "Antitrust regulatory commissions prevent any single tech corporation from establishing a harmful monopoly.",
     "The state railway maintained a national monopoly on intercity passenger rail transport for decades."),

    ("Monotonous", "adjective", "B2", "/məˈnɒt.ən.əs/", "monoton menjemukan / berulang membosankan",
     "Membosankan karena berulang-ulang tanpa variasi nada, warna, atau aktivitas.",
     "Dull, tedious, and repetitious; lacking in variety and interest.",
     ["Monotony", "Monotonously", "Tedious"], ["Tedious", "Boring", "Repetitive", "Dull", "Unvarying"], ["Exciting", "Varied", "Dynamic", "Lively"],
     "Assembly line packaging tasks can become mentally exhausting and monotonous over long shifts.",
     "The speaker delivered the lecture in a monotonous drone that put several attendees to sleep."),

    ("Monumental", "adjective", "B2", "/ˌmɒn.jəˈmen.təl/", "monumental agung / berskala raksasa bersejarah",
     "Sangat besar, megah, dan memiliki nilai sejarah atau kepentingan abadi.",
     "Great in importance, extent, or size; monumental in historical significance.",
     ["Monument", "Monumentally", "Epic"], ["Epic", "Colossal", "Historic", "Magnificent", "Immense"], ["Insignificant", "Minor", "Trivial"],
     "Building the Panama Canal was a monumental feat of civil engineering and human perseverance.",
     "The peace treaty marked a monumental step toward regional stability and economic prosperity."),

    ("Motivate", "verb", "B1", "/ˈməʊ.tɪ.veɪt/", "memotivasi / membakar gairah semangat",
     "Memberikan alasan, dorongan, atau antusiasme kepada seseorang untuk bertindak.",
     "Provide someone with a reason for doing something; stimulate interest or enthusiasm.",
     ["Motivation", "Motivational", "Inspire"], ["Inspire", "Encourage", "Drive", "Stimulate", "Incentivize"], ["Demotivate", "Discourage", "Deter"],
     "Inspiring athletic coaches know how to motivate players even after difficult tournament losses.",
     "Intrinsic curiosity about the universe motivates astrophysicists to spend nights analyzing stellar data."),

    ("Mourn", "verb", "B2", "/mɔːn/", "berkabung meratap / berduka cita atas kepergian",
     "Merasakan atau menunjukkan kesedihan mendalam atas kematian atau kehilangan seseorang.",
     "Feel or show deep sorrow or regret for someone, especially someone who has died.",
     ["Mourner", "Mournful", "Grieve"], ["Grieve", "Lament", "Weep", "Sorrow", "Bereave"], ["Rejoice", "Celebrate", "Cheer"],
     "The nation gathered in quiet solemnity to mourn the passing of its beloved founding leader.",
     "Flags flew at half-mast across the capital as thousands mourned the fallen disaster responders."),

    ("Multitude", "noun", "B2", "/ˈmʌl.tɪ.tjuːd/", "khalayak ramai / jumlah besar melimpah",
     "Jumlah orang atau benda yang sangat banyak; kerumunan besar orang.",
     "A large number of people or things; a great crowd.",
     ["Multitudinous", "Multiply", "Crowd"], ["Crowd", "Throng", "Mass", "Host", "Plethora"], ["Few", "Handful", "Scarcity"],
     "The pristine coral reef supports a colorful multitude of tropical fish and crustaceans.",
     "A enthusiastic multitude of supporters gathered outside the auditorium to greet the candidate."),

    ("Mundane", "adjective", "B2", "/mʌnˈdeɪn/", "biasa membosankan / urusan duniawi rutin",
     "Berkaitan dengan rutinitas sehari-hari yang biasa dan kurang menarik; duniawi.",
     "Lacking interest or excitement; dull; of this earthly world rather than heavenly.",
     ["Mundanely", "Everyday", "Routine"], ["Everyday", "Ordinary", "Routine", "Commonplace", "Workaday"], ["Extraordinary", "Exciting", "Exotic", "Heavenly"],
     "He found joy in performing mundane household chores like folding laundry and sweeping leaves.",
     "Scientific breakthroughs often require thousands of hours of mundane laboratory record-keeping."),

    ("Mural", "noun", "B1", "/ˈmjʊə.rəl/", "lukisan dinding mural / karya seni tembok kota",
     "Karya seni lukis yang diaplikasikan langsung pada dinding, tembok, atau langit-langit.",
     "A piece of artwork painted or applied directly on a wall, ceiling or other permanent surface.",
     ["Fresco", "Wall painting", "Graffiti"], ["Fresco", "Wall painting", "Artwork"], ["Canvas"],
     "Local youth transformed the neglected alleyway with a vibrant mural depicting rainforest flora.",
     "The historic community hall features colorful cultural murals celebrating agricultural heritage."),

    ("Mutate", "verb", "B2", "/mjuːˈteɪt/", "bermutasi / berubah sifat genetik",
     "Mengalami perubahan bentuk, sifat alami, atau struktur genetik sel secara biologis.",
     "Undergo or cause to undergo a change in form, character, or genetic structure.",
     ["Mutation", "Mutant", "Transform"], ["Transform", "Evolve", "Alter", "Metamorphose", "Change"], ["Remain", "Stabilize"],
     "Viruses can rapidly mutate over time, requiring researchers to develop updated vaccines.",
     "Under radiation exposure, single-celled organisms can mutate into novel genetic strains."),

    ("Naive", "adjective", "B2", "/naɪˈiːv/", "naif polos / kurang pengalaman dan mudah percaya",
     "Menunjukkan kurangnya pengalaman, kebijaksanaan, atau penilaian matang; terlalu lugu.",
     "Showing a lack of experience, wisdom, or judgment; innocent and unsophisticated.",
     ["Naivety", "Naively", "Gullible"], ["Gullible", "Innocent", "Trusting", "Artless", "Ingenuous"], ["Sophisticated", "Shrewd", "Cynical", "Worldly"],
     "It was naive of him to believe that complex international trade pacts could be signed overnight.",
     "Her naive honesty and childlike openness won the affection of cynical colleagues."),

    ("Narrative", "noun", "B2", "/ˈnær.ə.tɪv/", "narasi cerita / kisah runut alur peristiwa",
     "Cerita atau kisah tertulis maupun lisan yang menyajikan rangkaian peristiwa saling terhubung.",
     "A spoken or written account of connected events; a story.",
     ["Narrate", "Narrator", "Story"], ["Story", "Account", "Chronicle", "Tale", "Relating"], ["Fact sheet"],
     "The documentary weaves an emotional narrative about the survival of orphaned African elephants.",
     "Controlling the public media narrative is a key objective during modern political campaigns."),

    ("Native", "adjective", "B1", "/ˈneɪ.tɪv/", "asli pribumi / tumbuhan hewan khas lokal",
     "Berasal atau lahir di suatu tempat tertentu; spesies asli habitat alami.",
     "Associated with the place or circumstance of one's birth; indigenous to an area.",
     ["Natively", "Nativity", "Indigenous"], ["Indigenous", "Endemic", "Local", "Aboriginal", "Inborn"], ["Alien", "Foreign", "Exotic", "Non-native"],
     "The rare Komodo dragon is native exclusively to a few eastern islands of Indonesia.",
     "She spoke her native language with authentic regional intonation and natural fluency."),

    ("Nautical", "adjective", "B2", "/ˈnɔː.tɪ.kəl/", "bahari nautika / berhubungan dengan pelayaran kapal",
     "Berkaitan dengan pelaut, navigasi kapal laut, atau kehidupan di atas samudera.",
     "Of or concerning sailors, ships, or navigation on water; maritime.",
     ["Naval", "Maritime", "Marine"], ["Maritime", "Marine", "Naval", "Oceanic", "Seafaring"], ["Aviation", "Land-based"],
     "The museum displayed antique brass compasses and historical nautical charts from colonial trade.",
     "Navigators measure marine distance in nautical miles rather than standard terrestrial kilometers."),

    ("Navigate", "verb", "B2", "/ˈnæv.ɪ.ɡeɪt/", "menavigasi / memandu arah perjalanan",
     "Merencanakan dan mengarahkan rute kapal, pesawat, kendaraan, atau situs digital.",
     "Plan and direct the route or course of a ship, aircraft, or other form of transportation.",
     ["Navigation", "Navigator", "Steer"], ["Steer", "Pilot", "Guide", "Direct", "Maneuver"], ["Get lost", "Drift"],
     "Ancient Polynesian seafarers used bright constellation stars to navigate across the Pacific.",
     "The mobile application allows drivers to navigate congested city traffic using real-time GPS."),

    ("Nebulous", "adjective", "C1", "/ˈneb.jə.ləs/", "kabur remang-remang / tidak jelas berbentuk",
     "Dalam bentuk awan atau kabut; tidak jelas, samar, atau tidak terdefinisikan dengan baik.",
     "In the form of a cloud or haze; hazy; vague, indistinct, or ill-defined.",
     ["Nebula", "Vague", "Hazy"], ["Hazy", "Vague", "Indistinct", "Cloudy", "Formless"], ["Clear", "Distinct", "Precise", "Sharp"],
     "His startup business plan was criticized for presenting vague and nebulous revenue projections.",
     "Telescopes captured images of a nebulous interstellar gas cloud giving birth to infant stars."),

    ("Negate", "verb", "C1", "/nɪˈɡeɪt/", "meniadakan / membatalkan keabsahan efek",
     "Membatalkan keberadaan, kebenaran, atau efek positif dari sesuatu; menyangkal.",
     "Nullify; make ineffective; deny the existence of.",
     ["Negation", "Negative", "Nullify"], ["Nullify", "Invalidate", "Cancel", "Neutralize", "Undo"], ["Confirm", "Validate", "Support", "Enforce"],
     "Failing to submit the signed disclosure will negate all terms agreed in the contract.",
     "Wearing heavy wet clothing can negate the insulation benefits of wool during winter treks."),

    ("Neutral", "adjective", "B1", "/ˈnjuː.trəl/", "netral tidak memihak / warna pastel kalem",
     "Tidak mendukung atau membantu pihak mana pun dalam konflik; warna yang tidak mencolok.",
     "Not supporting or helping either side in a conflict or disagreement; impartial.",
     ["Neutrality", "Neutralize", "Impartial"], ["Impartial", "Unbiased", "Objective", "Dispassionate", "Non-aligned"], ["Biased", "Partisan", "Prejudiced"],
     "Switzerland has maintained a famous policy of armed neutral diplomacy for centuries.",
     "Interior designers used neutral tones like beige and slate gray to create a serene living room."),

    ("Nocturnal", "adjective", "B2", "/nɒkˈtɜː.nəl/", "nokturnal aktif malam / hidup di malam hari",
     "Terjadi, aktif, atau mekar pada malam hari bukan di siang hari.",
     "Done, occurring, or active at night rather than in daylight.",
     ["Nightly", "Diurnal", "Night"], ["Nightly", "Nighttime", "Night-active", "Dark-dwelling"], ["Diurnal", "Daytime"],
     "Owls, bats, and leopards are classic nocturnal predators that hunt under the cover of darkness.",
     "The nocturnal bloom of the queen of the night cactus emits a sweet fragrance after dusk."),

    ("Nominate", "verb", "B2", "/ˈnɒm.ɪ.neɪt/", "mencalonkan / mengusulkan kandidat resmi",
     "Mengajukan nama seseorang secara resmi untuk jabatan, penghargaan, atau pemilu.",
     "Propose or formally enter as a candidate for election or for an honor or award.",
     ["Nomination", "Nominee", "Propose"], ["Propose", "Put forward", "Recommend", "Designate", "Name"], ["Withdraw", "Reject", "Dismiss"],
     "The academy voted to nominate the environmental scientist for the prestigious international prize.",
     "Delegates gathered at the national convention to nominate their presidential party candidate."),

    ("Nostalgia", "noun", "B2", "/nɒsˈtæl.dʒə/", "nostalgia / rasa rindu hangat pada masa lalu",
     "Perasaan rindu yang hangat dan manis-getir terhadap masa lalu atau tanah kelahiran.",
     "A sentimental longing or wistful affection for the past, typically for a period with happy memories.",
     ["Nostalgic", "Nostalgically", "Reminiscence"], ["Reminiscence", "Wistfulness", "Yearning", "Longing", "Sentimentality"], ["Indifference"],
     "Flipping through old black-and-white family photograph albums filled her with warm nostalgia.",
     "The retro video arcade restaurant attracts millennials seeking a dose of childhood nostalgia."),

    ("Novelty", "noun", "B2", "/ˈnɒv.əl.ti/", "kebaruan / sesuatu yang unik dan segar",
     "Kualitas menjadi baru, orisinal, atau belum pernah ada sebelumnya; barang unik kecil.",
     "The quality of being new, original, or unusual; a small and inexpensive toy or ornament.",
     ["Novel", "Innovate", "Originality"], ["Originality", "Newness", "Innovation", "Curiosity", "Freshness"], ["Familiarity", "Tiredness", "Antiquity"],
     "The novelty of working remotely from a beach villa wore off after weeks of poor internet.",
     "Souvenir gift shops sell colorful novelty keychains and postcards to visiting tourists."),

    ("Nuance", "noun", "B2", "/ˈnjuː.ɑːns/", "nuansa selera / perbedaan makna yang sangat halus",
     "Perbedaan yang sangat halus atau variasi kecil dalam makna, nada, warna, atau perasaan.",
     "A subtle difference in or shade of meaning, expression, or sound.",
     ["Nuanced", "Subtlety", "Shade"], ["Subtlety", "Shade", "Gradation", "Distinction", "Refinement"], ["Bluntness", "Crudeness"],
     "Skilled literary translators capture the delicate nuances of poetry across different languages.",
     "The diplomat listened attentively to every verbal nuance during the tense treaty deliberations."),

    ("Nurture", "verb", "B2", "/ˈnɜː.tʃər/", "mengasuh merawat / memelihara pertumbuhan bakat",
     "Merawat, membesarkan, dan mendorong perkembangan seseorang atau sesuatu dengan penuh kasih.",
     "Care for and encourage the growth or development of someone or something.",
     ["Nurture", "Cultivate", "Foster"], ["Foster", "Cultivate", "Cherish", "Nourish", "Sustain"], ["Neglect", "Abandon", "Stifle", "Suppress"],
     "Dedicated music teachers help nurture raw young talent into accomplished concert pianists.",
     "A supportive family environment nurtures self-confidence and emotional resilience in adolescents.")
]

print("Supplemental MR dataset ready:", len(SUPPLEMENTAL_MR), "entries.")
