#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Precise Fill-in to hit exactly 260 items for MR and 260 items for SZ.
"""

MR_FILLIN = [
    ("Nourish", "verb", "B2", "/ˈnʌr.ɪʃ/", "menutrisi / memberi makan bergizi dan merawat",
     "Memberi makanan atau zat yang diperlukan untuk pertumbuhan, kesehatan, dan kehidupan.",
     "Provide with the food or other substances necessary for growth, health, and good condition.",
     ["Nourishment", "Nutrient", "Feed"], ["Feed", "Sustain", "Nurture", "Cherish", "Foster"], ["Starve", "Deprive", "Neglect"],
     "Rich organic compost nourishes the garden soil and encourages vigorous tomato growth.",
     "Reading inspiring literature helps nourish the imagination and creative intellect."),

    ("Novel", "adjective", "B2", "/ˈnɒv.əl/", "kebaruan unik / belum pernah ada sebelumnya",
     "Baru dan berbeda dari apa pun yang pernah ada atau dikenal sebelumnya; orisinal.",
     "Interestingly new or unusual; original in concept, style, or method.",
     ["Novelty", "Innovate", "Original"], ["Original", "Fresh", "Unconventional", "Innovative", "Unique"], ["Traditional", "Familiar", "Commonplace", "Tired"],
     "The startup proposed a novel approach to recycling marine plastics into building bricks.",
     "Scientists synthesized a novel organic compound that absorbs solar thermal energy efficiently."),

    ("Nucleus", "noun", "B2", "/ˈnjuː.kli.əs/", "inti sel / pusat pengendali utama",
     "Pusat positif atom; bagian inti sel organisme; kelompok sentral yang memimpin kegiatan.",
     "The central and most important part of an object, movement, or group; atomic core.",
     ["Nuclear", "Core", "Center"], ["Core", "Center", "Heart", "Kernel", "Focus"], ["Periphery", "Edge", "Margin"],
     "The biological cell nucleus contains chromosomes that carry hereditary DNA instructions.",
     "A small nucleus of dedicated civic volunteers launched the city-wide community garden network."),

    ("Nutrient", "noun", "B1", "/ˈnjuː.tri.ənt/", "zat gizi nutrisi / unsur hara penyubur",
     "Zat yang memberikan makanan penting bagi pertumbuhan dan pemeliharaan kehidupan.",
     "A substance that provides nourishment essential for the maintenance of life and for growth.",
     ["Nutrition", "Nutritious", "Nourish"], ["Nourishment", "Sustenance", "Food", "Mineral", "Vitamin"], ["Toxin", "Poison"],
     "Fresh leafy vegetables are rich in essential vitamins, minerals, and dietary nutrients.",
     "Healthy river deltas supply vital nutrients to coastal coral reefs and mangrove wetlands."),

    ("Oblivious", "adjective", "B2", "/əˈblɪv.i.əs/", "tidak menyadari sama sekali / lalai tak acuh",
     "Sama sekali tidak sadar atau tidak memperhatikan apa yang sedang terjadi di sekitarnya.",
     "Not aware of or not concerned about what is happening around one.",
     ["Oblivion", "Unaware", "Heedless"], ["Unaware", "Heedless", "Unmindful", "Ignorant", "Blind"], ["Aware", "Conscious", "Alert", "Mindful"],
     "Deeply absorbed in reading her book, she was completely oblivious to the pouring rain outside.",
     "The tourist walked across the busy bicycle lane oblivious to the ringing warning bells."),

    ("Obtain", "verb", "A2", "/əbˈteɪn/", "memperoleh / mendapatkan sesuatu dengan berusaha",
     "Mendapatkan, memperoleh, atau meraih kepemilikan atas sesuatu melalui usaha terencana.",
     "Get, acquire, or secure something, especially through effort or planning.",
     ["Obtainable", "Acquire", "Procure"], ["Acquire", "Procure", "Secure", "Gain", "Attain"], ["Lose", "Forfeit", "Surrender"],
     "International travelers must obtain an entry visa before arriving at the border checkpoint.",
     "She worked diligently throughout the academic term to obtain the top scholastic marks."),

    ("Occur", "verb", "A2", "/əˈkɜːr/", "terjadi berlangsung / terlintas dalam benak pikiran",
     "Terjadi atau berlangsung sebagai peristiwa nyata; muncul dalam pikiran seseorang.",
     "Happen; take place; come to mind as an idea or realization.",
     ["Occurrence", "Happen", "Transpire"], ["Happen", "Transpire", "Befall", "Materialize", "Crop up"], ["Cease"],
     "Total solar eclipses occur when the Moon passes directly between the Earth and the Sun.",
     "It suddenly occurred to him that he had forgotten to turn off the laboratory ovens."),

    ("Offend", "verb", "B1", "/əˈfend/", "menyinggung perasaan / melanggar norma kesopanan",
     "Menyebabkan seseorang merasa terluka atau kesal karena kata-kata yang tidak sopan.",
     "Cause someone to feel hurt, angry, or upset, typically by hurtful speech or action.",
     ["Offensive", "Offense", "Insult"], ["Insult", "Slight", "Displease", "Anger", "Affront"], ["Please", "Delight", "Compliment", "Honor"],
     "He was careful in his diplomatic speech so as not to offend the visiting foreign delegates.",
     "Humorous satire should challenge societal ideas without intending to offend individual feelings."),

    ("Omen", "noun", "B2", "/ˈəʊ.mən/", "pertanda firasat / isyarat masa depan",
     "Peristiwa yang dianggap sebagai tanda atau pertanda dari sesuatu yang baik atau buruk di masa depan.",
     "An event regarded as a portent of good or evil to come.",
     ["Ominous", "Portent", "Sign"], ["Portent", "Sign", "Augury", "Foreshadowing", "Harbinger"], ["Fact"],
     "In ancient maritime lore, sighting a flock of albatrosses was viewed as a fortunate omen.",
     "The sudden sharp drop in barometric pressure was a clear weather omen of an approaching gale."),

    ("Onset", "noun", "B2", "/ˈɒn.set/", "permulaan awal / saat timbulnya gejala",
     "Awal mula dimulainya sesuatu, terutama sesuatu yang tidak menyenangkan seperti penyakit atau badai.",
     "The beginning of something, especially something unpleasant like illness or winter.",
     ["Start", "Inception", "Dawn"], ["Beginning", "Start", "Inception", "Dawn", "Outset"], ["Conclusion", "End", "Termination"],
     "Early medical intervention can delay the onset of chronic age-related cognitive symptoms.",
     "The sudden onset of freezing winter blizzards caught the mountain village unprepared."),

    ("Operate", "verb", "A2", "/ˈɒp.ər.eɪt/", "mengoperasikan mesin / melakukan pembedahan medis",
     "Mengendalikan fungsi mesin atau proses bisnis; melakukan operasi bedah pada pasien.",
     "Control the functioning of a machine or process; perform a surgical operation.",
     ["Operation", "Operator", "Run"], ["Run", "Control", "Manage", "Function", "Execute"], ["Stall", "Break down"],
     "Technicians operate heavy industrial cranes with precision joysticks from the control cabin.",
     "Surgeons operate on complex cardiovascular conditions using minimally invasive techniques."),

    ("Oppose", "verb", "B1", "/əˈpəʊz/", "menentang melawan / menyuarakan ketidaksetujuan",
     "Tidak menyetujui dan berusaha mencegah atau melawan seseorang atau suatu kebijakan.",
     "Disapprove of and attempt to prevent, especially by argument or collective action.",
     ["Opposition", "Opponent", "Resist"], ["Resist", "Combat", "Contest", "Challenge", "Defy"], ["Support", "Endorse", "Advocate", "Favor"],
     "Environmental groups united to oppose the construction of the open-pit coal mine.",
     "The senator announced she would vigorously oppose the proposed public transit budget cuts."),

    ("Opt", "verb", "B1", "/ɒpt/", "memilih memutuskan / mengambil opsi tertentu",
     "Membuat pilihan dari sejumlah alternatif yang tersedia.",
     "Make a choice from a range of possibilities.",
     ["Option", "Optional", "Choose"], ["Choose", "Select", "Decide on", "Elect", "Pick"], ["Reject", "Decline"],
     "Many daily commuters opt for electric bicycles to avoid metropolitan traffic congestion.",
     "Students can opt to study either organic chemistry or molecular genetics this semester."),

    ("Origin", "noun", "A2", "/ˈɒr.ɪ.dʒɪn/", "asal-usul muasal / titik mula kelahiran",
     "Tempat atau situasi di mana sesuatu bermula atau berasal.",
     "The point or place where something begins, arises, or is derived.",
     ["Original", "Originate", "Source"], ["Source", "Root", "Beginning", "Derivation", "Genesis"], ["Destination", "Ending"],
     "Linguists trace the historical origin of romance languages back to spoken Latin dialects.",
     "The artisan proudly certified the geographical origin of the single-estate arabica coffee."),

    ("Outweigh", "verb", "B2", "/ˌaʊtˈweɪ/", "lebih berbobot / melampaui bobot kepentingan",
     "Lebih besar, lebih berbobot, atau lebih penting nilainya daripada sesuatu yang lain.",
     "Be heavier, greater, or more significant than something else.",
     ["Surpass", "Exceed", "Overtop"], ["Exceed", "Surpass", "Overbalance", "Eclipse", "Overshadow"], ["Fall short of"],
     "The long-term environmental benefits of solar energy far outweigh the initial setup costs.",
     "The advantages of studying abroad outweigh the temporary challenges of cultural adjustment."),

    ("Overwhelm", "verb", "B2", "/ˌəʊ.vəˈwelm/", "membanjiri menguasai / membuat kewalahan hebat",
     "Membuat seseorang merasa kewalahan secara emosional; membanjiri dengan jumlah besar.",
     "Have a strong emotional effect on; defeat completely with overwhelming force; inundate.",
     ["Overwhelming", "Overwhelmed", "Inundate"], ["Inundate", "Submerge", "Engulf", "Overpower", "Crush"], ["Underwhelm", "Spare"],
     "Generous donations from across the country overwhelmed the disaster relief center with supplies.",
     "The sheer beauty of the vast star-filled desert night overwhelmed the travelers with wonder."),

    ("Plentiful", "adjective", "B1", "/ˈplen.tɪ.fəl/", "berlimpah ruah / tersedia dalam jumlah banyak",
     "Ada atau tersedia dalam jumlah yang sangat banyak dan mencukupi kebutuhan.",
     "Existing in or yielding great quantities; abundant.",
     ["Plenty", "Abundant", "Copious"], ["Abundant", "Copious", "Ample", "Bountiful", "Profuse"], ["Scarce", "Sparse", "Meager", "Inadequate"],
     "Fresh organic fruits and crisp vegetables are plentiful in the summer countryside markets.",
     "The river basin provides plentiful freshwater for both irrigation agriculture and wildlife."),

    ("Plunge", "verb", "B2", "/plʌndʒ/", "terjun menyelam / anjlok drastis ke bawah",
     "Melompat atau terjun ke dalam air; turun dengan sangat cepat dan tajam.",
     "Jump or dive quickly and energetically; fall suddenly and steeply.",
     ["Plunging", "Dive", "Drop"], ["Dive", "Drop", "Plummet", "Descend", "Submerge"], ["Ascend", "Rise", "Soar", "Climb"],
     "Adventurous swimmers plunged into the crystal-clear cool waters of the natural quarry pool.",
     "Global crude oil prices plunged following unexpected surplus production reports."),

    ("Polar", "adjective", "B1", "/ˈpəʊ.lər/", "kutub es / berlawanan bertolak belakang",
     "Berkaitan dengan kutub bumi utara atau selatan; dua hal yang saling bertolak belakang.",
     "Relating to the North or South Pole; directly opposite in character or tendency.",
     ["Polarity", "Polarize", "Arctic"], ["Arctic", "Antarctic", "Glacial", "Opposite", "Antithetical"], ["Equatorial", "Tropical", "Identical"],
     "Polar bears possess thick insulating fat and dense fur to survive arctic winter freezes.",
     "The two political parties held polar views on environmental carbon taxation legislation."),

    ("Polish", "verb", "B1", "/ˈpɒl.ɪʃ/", "mengilapkan / menyempurnakan tulisan atau pidato",
     "Membuat permukaan berkilau dengan menggosok; memperbaiki karya agar sempurna tanpa cacat.",
     "Make the surface of something smooth and shiny by rubbing it; refine or improve prose.",
     ["Polished", "Luster", "Shine"], ["Shine", "Buff", "Smooth", "Refine", "Hone"], ["Tarnish", "Dull", "Roughen"],
     "The woodcrafter used natural beeswax to polish the handmade teak dining table.",
     "Take an extra hour to polish your final graduation speech before presenting it on stage."),

    ("Praise", "verb", "B1", "/preɪz/", "memuji sanjung / menyatakan kekaguman tulus",
     "Menyatakan persetujuan, rasa hormat, atau kekaguman yang hangat atas prestasi seseorang.",
     "Express warm approval or admiration of someone or something; worship God.",
     ["Praiseworthy", "Applaud", "Commend"], ["Commend", "Applaud", "Laud", "Extol", "Celebrate"], ["Criticize", "Blame", "Condemn", "Censure"],
     "The principal gathered the school to praise the students for their national robotics championship.",
     "Critics praised the director's debut documentary for its emotional honesty and cinematography."),

    ("Preach", "verb", "B2", "/priːtʃ/", "berkhotbah / menyampaikan wejangan moral",
     "Menyampaikan khotbah keagamaan; mengadvokasi atau menasihatkan perilaku moral tertentu.",
     "Deliver a sermon or religious address; earnestly advocate a belief or course of action.",
     ["Preacher", "Sermon", "Advocate"], ["Sermonize", "Proclaim", "Advocate", "Exhort", "Evangelize"], ["Dissuade"],
     "The philosopher traveled from city to city to preach the virtues of tolerance and peace.",
     "Environmental educators preach the urgent necessity of reducing single-use plastic waste."),

    ("Predict", "verb", "B1", "/prɪˈdɪkt/", "memprediksi / memperkirakan masa depan secara ilmiah",
     "Menyatakan atau memperkirakan bahwa suatu peristiwa akan terjadi di masa depan.",
     "Say or estimate that a specified thing will happen in the future or will be a consequence.",
     ["Prediction", "Predictable", "Forecast"], ["Forecast", "Foresee", "Prophesy", "Project", "Anticipate"], ["Recall", "Review"],
     "Meteorologists use satellite atmospheric models to predict seasonal monsoon rainfall patterns.",
     "It is difficult to predict exactly how artificial intelligence will reshape global employment."),

    ("Prevent", "verb", "A2", "/prɪˈvent/", "mencegah menghalangi / menjaga agar tidak terjadi",
     "Menjaga agar sesuatu yang buruk tidak terjadi atau menghalangi seseorang bertindak.",
     "Keep something from happening or arising; stop someone from doing something.",
     ["Prevention", "Preventive", "Stop"], ["Stop", "Avert", "Hinder", "Block", "Forestall"], ["Allow", "Permit", "Facilitate", "Cause"],
     "Regular physical exercise and healthy nutrition help prevent chronic metabolic conditions.",
     "Safety guardrails along mountain highway curves prevent vehicles from skidding off cliffs.")
]

SZ_FILLIN = [
    ("Wholesome", "adjective", "B2", "/ˈhəʊl.səm/", "sehat bergizi / baik bagi jasmani dan rohani",
     "Kondusif bagi kesehatan fisik dan moral yang baik; bergizi dan murni alami.",
     "Conducive to or suggestive of good health and physical well-being; moral and uplifting.",
     ["Healthful", "Nutritious", "Moral"], ["Nutritious", "Healthful", "Nourishing", "Innocent", "Pure"], ["Unwholesome", "Harmful", "Toxic", "Corrupt"],
     "The farmhouse kitchen served wholesome hearty vegetable stews with fresh whole-wheat bread.",
     "The animated family film told a wholesome story about friendship, honesty, and bravery."),

    ("Wholesale", "adjective", "B2", "/ˈhəʊl.seɪl/", "grosir kulakan / skala besar menyeluruh",
     "Penjualan barang dalam jumlah besar dengan harga lebih murah; perubahan besar-besaran.",
     "The selling of goods in large quantities to be retailed by others; extensive in scale.",
     ["Retail", "Bulk", "Mass"], ["Bulk", "Comprehensive", "Sweeping", "Indiscriminate", "Mass"], ["Retail", "Selective", "Partial"],
     "The agricultural cooperative sells fresh organic grain at wholesale prices to city markets.",
     "The company underwent wholesale restructuring to adapt to changing digital commerce trends."),

    ("Wicked", "adjective", "B2", "/ˈwɪk.ɪd/", "jahat keji / nakal penuh tipu muslihat",
     "Sangat buruk secara moral atau berniat jahat; perbuatan yang kejam dan licik.",
     "Evil or morally wrong; playfully mischievous; delightfully excellent in slang.",
     ["Wickedness", "Evil", "Sinful"], ["Evil", "Sinful", "Vicious", "Malicious", "Nefarious"], ["Virtuous", "Good", "Righteous", "Innocent"],
     "Folk fairy tales often depict brave young protagonists overcoming wicked sorcerers.",
     "The corrupt politician engaged in wicked schemes to embezzle public educational funds."),

    ("Wield", "verb", "B2", "/wiːld/", "memegang memegang senjata / menggunakan pengaruh kekuasaan",
     "Memegang dan menggunakan senjata atau alat dengan terampil; menggunakan kekuasaan besar.",
     "Hold and use a weapon or tool; have and be able to use power or influence.",
     ["Wielding", "Brandish", "Exercise"], ["Brandish", "Exercise", "Exert", "Employ", "Command"], ["Drop", "Relinquish", "Surrender"],
     "The legendary blacksmith knew how to wield heavy iron hammers with rhythmic precision.",
     "Chief executive officers wield significant influence over corporate sustainability strategies."),

    ("Windfall", "noun", "C1", "/ˈwɪnd.fɔːl/", "durian runtuh / rezeki nomplok tak terduga",
     "Keuntungan finansial atau buah rezeki yang didapat secara mendadak tanpa diduga sebelumnya.",
     "A piece of unexpected good fortune, typically one that involves receiving a large amount of money.",
     ["Bonanza", "Jackpot", "Godsend"], ["Bonanza", "Godsend", "Jackpot", "Boon", "Stroke of luck"], ["Loss", "Misfortune"],
     "The tech startup founders enjoyed a massive financial windfall when the firm was acquired.",
     "The small coastal town used its lottery tax windfall to build a state-of-the-art public library."),

    ("Winsome", "adjective", "C1", "/ˈwɪn.səm/", "menawan hati / manis memikat bersahaja",
     "Menarik atau memikat dengan cara yang manis, polos, dan menyenangkan hati.",
     "Attractive or appealing in appearance or character in a sweet, engaging way.",
     ["Charming", "Winning", "Engaging"], ["Charming", "Appealing", "Engaging", "Delightful", "Endearing"], ["Unattractive", "Repulsive", "Aloof"],
     "The child gave a winsome smile that immediately melted her grandfather's stern demeanor.",
     "Her winsome storytelling style captivated listeners of all ages around the evening campfire."),

    ("Wisecrack", "noun", "B2", "/ˈwaɪz.kræk/", "lelucon jenaka / celetukan cerdas lucu",
     "Pernyataan atau lelucon jenaka yang dilontarkan dengan cepat dan cerdik.",
     "A clever, witty, or sardonic remark or joke.",
     ["Quip", "Jest", "Joke"], ["Quip", "Jest", "Gag", "Witticism", "Punt"], ["Serious comment"],
     "The movie comic relief character kept the audience laughing with well-timed wisecracks.",
     "Try not to make sarcastic wisecracks during serious professional safety briefings."),

    ("Withhold", "verb", "B2", "/wɪðˈhəʊld/", "menahan menolak memberi / merahasiakan informasi",
     "Menolak memberikan sesuatu yang diminta atau diperlukan; merahasiakan fakta penting.",
     "Refuse to give something that is due to or is desired by another; suppress information.",
     ["Withholding", "Retain", "Suppress"], ["Retain", "Deduct", "Suppress", "Conceal", "Hold back"], ["Release", "Disclose", "Provide", "Grant"],
     "The human rights report urged the military to not withhold vital humanitarian supplies.",
     "Employers are legally obligated to withhold income tax contributions from monthly employee wages."),

    ("Woodland", "noun", "B1", "/ˈwʊd.lənd/", "hutan lindung kayu / kawasan rimbun pepohonan",
     "Kawasan tanah yang ditumbuhi banyak pohon dan semak belukar alami.",
     "Land covered with trees, typically smaller than a forest.",
     ["Forest", "Woods", "Grove"], ["Woods", "Forest", "Grove", "Timberland", "Copse"], ["Meadow", "Prairie", "Desert"],
     "Ancient oak woodlands provide essential habitats for owls, deer, and rare woodland flowers.",
     "A peaceful walking trail winds gently through the shaded pine woodland behind the town."),

    ("Wound", "noun", "B1", "/wuːnd/", "luka fisik cedera / sakit hati mendalam",
     "Cedera pada jaringan tubuh yang disebabkan oleh goresan, tusukan, atau benturan keras; sakit hati.",
     "An injury to living tissue caused by a cut, blow, or other impact; deep emotional hurt.",
     ["Wounded", "Injury", "Lesion"], ["Injury", "Lesion", "Cut", "Gash", "Trauma"], ["Healing", "Remedy"],
     "The paramedic applied sterile bandages and antiseptic ointment to treat the arm wound.",
     "Time and compassionate support from loved ones help heal the deep emotional wounds of loss."),

    ("Wreckage", "noun", "B2", "/ˈrek.ɪdʒ/", "puing reruntuhan / sisa bangkai kehancuran",
     "Sisa-sisa dari sesuatu yang telah hancur atau rusak parah, seperti pesawat atau kapal karam.",
     "The remains of something that has been badly damaged or destroyed.",
     ["Wreck", "Debris", "Flotsam"], ["Debris", "Rubble", "Flotsam", "Ruins", "Remains"], ["Creation"],
     "Search and rescue teams combed through the coastal wreckage of the capsized fishing boat.",
     "Engineers inspected the structural wreckage of the bridge after the massive flood receded."),

    ("Yielding", "adjective", "B2", "/ˈjiːl.dɪŋ/", "lentur empuk / patuh penurut",
     "Mudah ditekan atau ditekuk; bersedia mematuhi atau berkompromi tanpa perlawanan keras.",
     "Giving way under pressure; soft or flexible; compliant and submissive.",
     ["Yield", "Pliant", "Compliant"], ["Pliant", "Flexible", "Supple", "Soft", "Compliant"], ["Rigid", "Hard", "Obstinate", "Inflexible"],
     "The sofa was filled with yielding down feathers that made reading for hours immensely comfortable.",
     "A wise diplomatic negotiator balances firm principles with a yielding and empathetic posture."),

    ("Yonder", "adverb", "B2", "/ˈjɒn.dər/", "di sebelah sana / di kejauhan sana tampak",
     "Di atau menunjuk ke tempat yang ada di sana di kejauhan yang masih tampak oleh mata.",
     "At some distance in that direction over there; situated in the specified place.",
     ["Over there", "Distant", "Farther"], ["Over there", "Afar", "Away", "Distant", "Beyond"], ["Here", "Near", "Close by"],
     "Look at yonder snow-covered mountain peak gleaming brilliantly in the morning sun.",
     "The ancient stone lighthouse stands on yonder high sea cliff guarding the bay harbor."),

    ("Youthful", "adjective", "B1", "/ˈjuːθ.fəl/", "berjiwa muda / segar bertenaga khas remaja",
     "Memiliki kualitas fisik, vitalitas, atau penampilan yang khas dari orang muda.",
     "Young or seeming young; energetic and fresh in appearance or character.",
     ["Youth", "Youthfulness", "Juvenile"], ["Young", "Juvenile", "Sprightly", "Fresh", "Vibrant"], ["Elderly", "Aged", "Old", "Senile"],
     "Regular exercise and a joyful mindset helped the seventy-year-old grandmother retain youthful energy.",
     "The company's marketing campaign adopted a fresh, colorful, and youthful aesthetic."),

    ("Yearlong", "adjective", "B2", "/ˈjɪə.lɒŋ/", "berlangsung setahun penuh / sepanjang masa tahunan",
     "Berlangsung atau berlanjut selama periode satu tahun penuh tanpa henti.",
     "Lasting throughout an entire year.",
     ["Annual", "Perennial", "Continuous"], ["Annual", "Year-round", "Yearly", "Continuous", "Sustained"], ["Short-lived", "Temporary"],
     "She completed a rigorous yearlong research fellowship at the botanical research institute.",
     "The museum celebrated its centenary with a yearlong series of historical art exhibitions."),

    ("Yield", "verb", "A2", "/jiːld/", "menyerahkan jalan / menghasilkan produksi",
     "Memberikan prioritas kepada kendaraan lain di jalan; menghasilkan produk tanaman pangan.",
     "Give way to traffic; produce or generate agricultural or industrial goods.",
     ["Yielding", "Produce", "Surrender"], ["Produce", "Generate", "Harvest", "Concede", "Relinquish"], ["Resist", "Withhold"],
     "Drivers must yield to pedestrians at all marked street crossings in school zones.",
     "High-yield drought-tolerant wheat crops ensure food security during dry summer seasons."),

    ("Zealot", "noun", "C1", "/ˈzel.ət/", "fanatikus ekstrem / pembela membabi buta",
     "Seseorang yang fanatik dan tak kenal kompromi dalam mengejar cita-cita agama atau politik.",
     "A person who is fanatical and uncompromising in pursuit of their religious or political ideals.",
     ["Zeal", "Fanatic", "Extremist"], ["Fanatic", "Extremist", "Militant", "Radical", "Diehard"], ["Moderate", "Centrist", "Pacifist"],
     "Political zealots often refuse to listen to evidence that contradicts their dogmatic beliefs.",
     "True leadership requires pragmatic diplomacy rather than unyielding zealot posturing."),

    ("Zenith", "noun", "B2", "/ˈzen.ɪθ/", "puncak kejayaan / titik tertinggi di cakrawala",
     "Titik tertinggi yang dicapai oleh benda langit di atas pengamat; puncak keberhasilan hidup.",
     "The time at which something is most powerful or successful; the highest point reached by a celestial body.",
     ["Apex", "Pinnacle", "Crest"], ["Apex", "Pinnacle", "Peak", "Acme", "Summit"], ["Nadir", "Base", "Bottom"],
     "At noon on the summer solstice, the sun reaches its highest zenith in the northern sky.",
     "The empire reached the magnificent zenith of its cultural and scientific influence in antiquity."),

    ("Zest", "noun", "B2", "/zest/", "gairah semangat hidup / parutan kulit jeruk aromatik",
     "Antusiasme dan semangat yang besar untuk menikmati hidup; kulit luar buah sitrus beraroma harum.",
     "Great enthusiasm and energy; the outer colored part of the peel of citrus fruit used for flavoring.",
     ["Zesty", "Gusto", "Enthusiasm"], ["Gusto", "Enthusiasm", "Eagerness", "Relish", "Flavor"], ["Apathy", "Lethargy", "Blandness"],
     "She lived every day with infectious optimism and an admirable zest for outdoor adventure.",
     "Grate the fresh zest of an organic lemon into the pancake batter for a delightful citrus flavor."),

    ("Zigzag", "noun", "B1", "/ˈzɪɡ.zæɡ/", "kelok-kelok zig-zag / pola garis berliku tajam",
     "Garis atau lintasan yang memiliki belokan tajam berulang dari satu sisi ke sisi lain secara bergantian.",
     "A line or course having abrupt alternate right and left turns.",
     ["Winding", "Meander", "Serpentine"], ["Meander", "Crook", "Curve", "Bend", "Twist"], ["Straight line"],
     "The narrow mountain hiking trail ascended the steep cliff face in a series of sharp zigzags.",
     "Traditional handwoven tribal textiles feature intricate geometric zigzag border patterns."),

    ("Zodiac", "noun", "B2", "/ˈzəʊ.di.æk/", "zodiak rasi bintang / sabuk edar astronomi",
     "Sabuk langit imajiner yang mencakup jalur matahari, bulan, dan planet-planet utama; rasi bintang.",
     "A belt of the heavens within which the sun, moon, and principal planets remain divided into signs.",
     ["Astrology", "Constellation", "Horoscope"], ["Constellation", "Horoscope", "Sign", "Astrology", "Heavens"], ["N/A"],
     "Ancient Babylonian astronomers divided the celestial zodiac into twelve equal seasonal signs.",
     "The ceiling of the antique planetarium was decorated with gold-embossed zodiac constellations."),

    ("Zone", "noun", "A2", "/zəʊn/", "zona kawasan wilayah / peruntukan tata ruang",
     "Kawasan atau daerah yang memiliki batasan atau karakteristik tertentu untuk tujuan khusus.",
     "An area or stretch of land having a particular characteristic, purpose, or use.",
     ["Zoning", "Sector", "Region"], ["Region", "Area", "Sector", "District", "Belt"], ["Whole"],
     "The city municipality established a pedestrian-only zone in the historic downtown market square.",
     "Marine biologists designated the coral reef as a strictly protected no-fishing conservation zone."),

    ("Zoology", "noun", "B1", "/zuˈɒl.ə.dʒi/", "ilmu zoologi / ilmu pengetahuan biologi hewan",
     "Cabang ilmu biologi yang mempelajari struktur, fisiologi, klasifikasi, dan perilaku hewan.",
     "The scientific study of the behavior, structure, physiology, classification, and distribution of animals.",
     ["Zoologist", "Zoological", "Biology"], ["Faunal science", "Animal biology", "Natural history", "Biology"], ["Botany"],
     "Students enrolled in the university's zoology department conduct field research on Komodo dragons.",
     "The natural history museum exhibits interactive dioramas detailing evolutionary zoology.")
]

print("Fill-in datasets ready: MR=", len(MR_FILLIN), "SZ=", len(SZ_FILLIN))
