#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Rich supplemental Oxford lexicon for MR and SZ.
"""

MR_ADDITIONAL = [
    ("Oblige", "verb", "B2", "/əˈblaɪdʒ/", "mewajibkan / berbuat baik melayani",
     "Membuat seseorang terikat secara hukum atau moral untuk melakukan sesuatu; membantu.",
     "Make someone legally or morally bound to an action; do a favor for.",
     ["Obligation", "Obligatory", "Compel"], ["Compel", "Bind", "Require", "Accommodate", "Indebt"], ["Release", "Free", "Disoblige"],
     "Contractual terms oblige both companies to safeguard user confidentiality.",
     "The hotel concierge was happy to oblige by booking theater tickets for the guests."),

    ("Obscure", "adjective", "B2", "/əbˈskjʊər/", "samar tidak jelas / kurang dikenal",
     "Tidak diketahui oleh banyak orang; sulit dilihat atau dipahami secara jelas.",
     "Not discovered or known about; uncertain; not clearly expressed or easily understood.",
     ["Obscurity", "Obscurely", "Vague"], ["Vague", "Cryptic", "Unclear", "Lesser-known", "Enigmatic"], ["Famous", "Clear", "Obvious", "Renowned"],
     "The scholar spent years translating an obscure medieval manuscript from a monastery.",
     "Dense morning sea fog obscured the distant coastal lighthouses from approaching ships."),

    ("Obsolete", "adjective", "B2", "/ˌɒb.səˈliːt/", "usang kuno / tidak dipakai lagi",
     "Tidak lagi diproduksi atau digunakan; ketinggalan zaman karena ada teknologi baru.",
     "No longer produced or used; out of date.",
     ["Obsolescence", "Outdated", "Archaic"], ["Outdated", "Antiquated", "Archaic", "Superseded", "Defunct"], ["Modern", "Current", "Contemporary", "State-of-the-art"],
     "Floppy disks and dial-up modems quickly became obsolete with the rise of broadband internet.",
     "Technological disruption can render traditional manual manufacturing workflows obsolete."),

    ("Oasis", "noun", "B1", "/əʊˈeɪ.sɪs/", "oase mata air gurun / tempat perlindungan nyaman",
     "Kawasan subur di tengah padang pasir yang memiliki sumber air; tempat teduh di tengah hiruk-pikuk.",
     "A fertile spot in a desert, where water is found; a pleasant or peaceful place in a busy setting.",
     ["Sanctuary", "Haven", "Refuge"], ["Sanctuary", "Haven", "Refuge", "Spring", "Retreat"], ["Desert", "Wasteland"],
     "Caravans rested beneath date palm trees beside a crystal-clear desert oasis.",
     "The shaded rooftop garden is a peaceful green oasis in the heart of the noisy city."),

    ("Oath", "noun", "B2", "/əʊθ/", "sumpah khidmat / janji suci setia",
     "Pernyataan khidmat yang mengatasnamakan Tuhan atau hal suci untuk bersaksi jujur.",
     "A solemn promise, often invoking a divine witness, regarding one's future action or truthfulness.",
     ["Swear", "Pledge", "Vow"], ["Pledge", "Vow", "Promise", "Affidavit", "Covenant"], ["Betrayal", "Perjury"],
     "The newly appointed supreme court justice took a solemn constitutional oath of office.",
     "Witnesses in a courtroom are placed under legal oath to speak the whole truth."),

    ("Obedient", "adjective", "B1", "/əˈbiː.di.ənt/", "patuh taat / penurut terhadap aturan",
     "Patuh dan bersedia menjalankan perintah atau mematuhi aturan otoritas.",
     "Complying or willing to comply with orders or requests; submissive to authority.",
     ["Obedience", "Obediently", "Compliant"], ["Compliant", "Dutiful", "Submissive", "Docile", "Deferential"], ["Disobedient", "Rebellious", "Defiant", "Insubordinate"],
     "Well-trained search dogs are obedient to hand signals and voice commands during rescue missions.",
     "The students were quiet and obedient while the guest professor delivered the keynote lecture."),

    ("Obese", "adjective", "B2", "/əʊˈbiːs/", "kegemukan obesitas / berlebih berat badan ekstrem",
     "Sangat gemuk dalam tingkat yang membahayakan kesehatan jasmani.",
     "Grossly fat or overweight in a way that is dangerous to health.",
     ["Obesity", "Overweight", "Corpulent"], ["Overweight", "Corpulent", "Fleshy", "Stout", "Portly"], ["Slender", "Lean", "Skinny", "Emaciated"],
     "Public health initiatives encourage balanced nutrition to prevent children from becoming obese.",
     "A sedentary lifestyle combined with sugary fast food increases the risk of being clinically obese."),

    ("Occupy", "verb", "B1", "/ˈɒk.jə.paɪ/", "menempati ruang / menyibukkan diri",
     "Tinggal di suatu tempat; mengisi ruang, waktu, atau jabatan tertentu.",
     "Reside or have one's place of business in; fill or take up a space or time.",
     ["Occupant", "Occupation", "Inhabit"], ["Inhabit", "Dwell in", "Take up", "Engage", "Fill"], ["Vacate", "Abandon", "Leave"],
     "The international design consultancy occupies the top three floors of the glass tower.",
     "Solving chess puzzles helped occupy his active mind during the long train journey."),

    ("Ominous", "adjective", "B2", "/ˈɒm.ɪ.nəs/", "pertanda buruk / menyeramkan mengancam",
     "Memberi kesan bahwa sesuatu yang buruk atau berbahaya akan segera terjadi.",
     "Giving the impression that something bad or unpleasant is going to happen; threatening.",
     ["Omen", "Ominously", "Threatening"], ["Threatening", "Foreboding", "Sinister", "Menacing", "Portentous"], ["Auspicious", "Promising", "Encouraging", "Bright"],
     "Dark ominous storm clouds gathered rapidly over the ocean horizon before the gale.",
     "The sudden eerie silence in the forest was viewed as an ominous warning by the trackers."),

    ("Omit", "verb", "B2", "/əʊˈmɪt/", "menghilangkan / melewatkan tanpa sengaja atau sengaja",
     "Meninggalkan atau tidak menyertakan seseorang atau sesuatu dalam daftar atau rencana.",
     "Leave out or exclude someone or something, either intentionally or forgetfully.",
     ["Omission", "Exclude", "Skip"], ["Exclude", "Skip", "Leave out", "Drop", "Bypass"], ["Include", "Insert", "Add", "Incorporate"],
     "Be careful not to omit any important tax documentation when filing your annual return.",
     "The abridged version of the epic novel omitted several secondary character subplots."),

    ("Opaque", "adjective", "B2", "/əʊˈpeɪk/", "buram tidak tembus cahaya / sulit dipahami",
     "Tidak tembus pandang atau tidak membiarkan cahaya lewat; tidak jelas atau sulit dimengerti.",
     "Not able to be seen through; not transparent; hard or impossible to understand.",
     ["Opacity", "Opaquely", "Cloudy"], ["Cloudy", "Muddy", "Nontransparent", "Obscure", "Impenetrable"], ["Transparent", "Translucent", "Clear", "Lucid"],
     "Frosted glass bathroom windows are opaque to preserve personal privacy while letting light in.",
     "Critics complained that the company's financial accounting methods were deliberately opaque."),

    ("Optimum", "adjective", "B2", "/ˈɒp.tɪ.məm/", "paling optimal / kondisi terbaik paling menguntungkan",
     "Kondisi atau tingkat yang paling menguntungkan, efektif, atau memuaskan.",
     "Most conducive to a favorable outcome; best or most effective.",
     ["Optimize", "Optimally", "Prime"], ["Optimal", "Prime", "Ideal", "Peak", "Best"], ["Pessimal", "Worst", "Poorest"],
     "Plant nurseries maintain optimum humidity and temperature levels for seedling germination.",
     "Regular aerobic workouts combined with sufficient sleep create optimum physical performance."),

    ("Opulent", "adjective", "C1", "/ˈɒp.jə.lənt/", "sangat kaya megah / mewah berlimpah harta",
     "Menampilkan kekayaan dan kemewahan yang luar biasa berlimpah; berhias mewah.",
     "Ostentatiously rich and luxurious or lavish; wealthy.",
     ["Opulence", "Opulently", "Lavish"], ["Lavish", "Sumptuous", "Luxurious", "Affluent", "Grand"], ["Poor", "Impoverished", "Spartan", "Destitute"],
     "The sultan's palace was decorated with opulent crystal chandeliers and silk carpets.",
     "Guests enjoyed an opulent banquet featuring rare culinary delicacies from across five continents."),

    ("Ordinary", "adjective", "A2", "/ˈɔː.dən.ri/", "biasa lumrah / tidak istimewa sederhana",
     "Sesuai dengan apa yang lazim terjadi; tidak memiliki keistimewaan khusus.",
     "With no special or distinctive features; normal and customary.",
     ["Extraordinary", "Ordinarily", "Common"], ["Common", "Normal", "Usual", "Standard", "Everyday"], ["Extraordinary", "Special", "Exceptional", "Unusual"],
     "It was an ordinary weekday morning with commuters rushing to catch the suburban train.",
     "Under ordinary circumstances, the bank transfer takes one business day to settle."),

    ("Organic", "adjective", "B1", "/ɔːˈɡæn.ɪk/", "organik alami / bebas zat kimia buatan",
     "Dihasilkan tanpa pupuk atau pestisida kimia buatan; berkaitan dengan makhluk hidup.",
     "Produced without the use of chemical fertilizers, pesticides, or artificial agents.",
     ["Organism", "Organically", "Natural"], ["Natural", "Biological", "Pure", "Chemical-free", "Holistic"], ["Synthetic", "Artificial", "Inorganic"],
     "Organic farm markets sell fresh vegetables, heritage honey, and free-range eggs.",
     "The startup experienced rapid organic growth through glowing word-of-mouth recommendations."),

    ("Orient", "verb", "B2", "/ˈɔː.ri.ənt/", "mengarahkan hadap / menyesuaikan diri dengan situasi",
     "Menyelaraskan atau memposisikan sesuatu ke arah tertentu; membiasakan diri dengan lingkungan.",
     "Align or position something relative to the points of a compass or other specified positions.",
     ["Orientation", "Oriented", "Align"], ["Align", "Position", "Direct", "Familiarize", "Adjust"], ["Disorient", "Confuse", "Mislead"],
     "Modern eco-architects orient building windows to harness natural sunlight and cross breezes.",
     "The university organized a campus tour to help orient international freshmen to their new home."),

    ("Oscillate", "verb", "C1", "/ˈɒs.ɪ.leɪt/", "berosilasi berayun / bimbang bolak-balik",
     "Bergerak bolak-balik pada kecepatan teratur; bimbang di antara dua pendapat atau perasaan.",
     "Move or swing back and forth at a regular speed; waver between opinions.",
     ["Oscillation", "Oscillator", "Swing"], ["Swing", "Vibrate", "Waver", "Fluctuate", "Sway"], ["Stabilize", "Steady", "Remain fixed"],
     "A grandfather clock pendulum oscillates with precise harmonic rhythm every single second.",
     "The undecided voter oscillated between the two candidates until election morning."),

    ("Outline", "noun", "B1", "/ˈaʊt.laɪn/", "garis besar ikhtisar / sketsa kerangka acuan",
     "Gambaran umum yang hanya memuat poin-poin utama tanpa rincian mendalam; garis tepi.",
     "A line or set of lines enclosing or indicating the shape of something; a general sketch or summary.",
     ["Outline", "Summary", "Draft"], ["Summary", "Synopsis", "Draft", "Framework", "Contour"], ["Detail", "Expansion"],
     "The student prepared a structured outline before writing the final sociology research thesis.",
     "The sharp silhouette outline of the mountain range was visible against the twilight sky."),

    ("Outlook", "noun", "B2", "/ˈaʊt.lʊk/", "pandangan masa depan / sikap mental wawasan",
     "Sikap atau pandangan seseorang terhadap kehidupan; prospek perkiraan masa depan.",
     "A person's point of view or general attitude to life; the prospect for the future.",
     ["Prospect", "Viewpoint", "Forecast"], ["Prospect", "Viewpoint", "Perspective", "Forecast", "Attitude"], ["Hindsight"],
     "Maintaining a positive and resilient mental outlook helps individuals overcome adversity.",
     "Economic analysts gave a promising outlook for renewable green energy sector investments."),

    ("Output", "noun", "B2", "/ˈaʊt.pʊt/", "hasil keluaran / kapasitas produksi barang",
     "Jumlah barang, daya, atau informasi yang dihasilkan oleh mesin, pabrik, atau orang.",
     "The amount of something produced by a person, machine, or industry; generated data.",
     ["Produce", "Yield", "Capacity"], ["Yield", "Production", "Harvest", "Product", "Result"], ["Input", "Intake"],
     "The automotive manufacturing plant increased its daily output to five hundred vehicles.",
     "Programmers debugged the code after noticing unexpected numerical output on the console."),

    ("Outrage", "noun", "B2", "/ˈaʊt.reɪdʒ/", "kemarahan publik yang dahsyat / kebiadaban",
     "Rasa marah dan tersinggung yang amat sangat akibat tindakan yang kejam atau tidak adil.",
     "An extremely strong reaction of anger, shock, or indignation; a fierce offence.",
     ["Outrageous", "Fury", "Indignation"], ["Indignation", "Fury", "Wrath", "Anger", "Shock"], ["Satisfaction", "Delight", "Approval"],
     "The unprovoked environmental pollution scandal sparked fierce public outrage across the province.",
     "Citizens voiced their shared outrage at the corruption revelations during peaceful protests."),

    ("Outset", "noun", "B2", "/ˈaʊt.set/", "permulaan awal / sejak langkah mula",
     "Titik awal atau saat dimulainya suatu proses, perjalanan, atau proyek.",
     "The start or beginning of something.",
     ["Beginning", "Inception", "Start"], ["Start", "Beginning", "Inception", "Dawn", "Commencement"], ["Conclusion", "End", "Finish", "Termination"],
     "From the outset of the research project, the scientists prioritized rigorous ethical protocols.",
     "It was clear from the outset that the ambitious software startup would face intense competition."),

    ("Outward", "adjective", "B2", "/ˈaʊt.wəd/", "arah luar / tampilan luar tampak permukaan",
     "Mengarah ke luar; berkaitan dengan penampilan luar yang terlihat oleh orang lain.",
     "Directed on or situated on the outside; relating to the external appearance of something.",
     ["Outwardly", "External", "Surface"], ["External", "Exterior", "Surface", "Superficial", "Apparent"], ["Inward", "Internal", "Interior", "Hidden"],
     "Despite her outward composure, she was deeply nervous before taking the podium.",
     "The airline operates daily outward flights from London to major Asian capitals."),

    ("Overt", "adjective", "C1", "/ˈəʊ.vɜːt/", "terang-terangan terbuka / tanpa disembunyikan",
     "Dilakukan atau ditunjukkan secara terbuka dan gamblang; tidak tersembunyi atau rahasia.",
     "Done or shown openly; plainly apparent; not secret or hidden.",
     ["Overtly", "Open", "Blatant"], ["Open", "Blatant", "Explicit", "Undisguised", "Manifest"], ["Covert", "Secret", "Hidden", "Stealthy"],
     "The corrupt executive engaged in overt violations of corporate conflict-of-interest policies.",
     "Diplomats condemned the overt military aggression along the contested international border."),

    ("Pacifist", "noun", "B2", "/ˈpæs.ɪ.fɪst/", "pasifis / pencinta damai penentang perang",
     "Seseorang yang meyakini bahwa perang dan kekerasan adalah salah dan tidak dapat dibenarkan.",
     "A person who believes that war and violence are unjustifiable under any circumstances.",
     ["Pacifism", "Peaceable", "Dove"], ["Peacemaker", "Dove", "Conscientious objector", "Nonviolent person"], ["Warmonger", "Militarist", "Hawk"],
     "As a devoted lifelong pacifist, he actively organized nonviolent humanitarian peace marches.",
     "Pacifists advocate for diplomatic dialogue and mutual compromise to resolve international border disputes."),

    ("Pamphlet", "noun", "B1", "/ˈpæm.flət/", "selebaran pamflet / brosur informasi ringkas",
     "Buku kecil tanpa sampul tebal yang berisi informasi atau argumen tentang satu topik.",
     "A small booklet or leaflet containing information or arguments about a single subject.",
     ["Leaflet", "Brochure", "Booklet"], ["Leaflet", "Brochure", "Booklet", "Flyer", "Tract"], ["Tome", "Hardcover"],
     "Health clinic volunteers distributed informational pamphlets on childhood immunization schedules.",
     "The historic political pamphlet helped rally citizens around democratic rights and liberty."),

    ("Parable", "noun", "B2", "/ˈpær.ə.bəl/", "cerita perumpamaan / kisah ibarat bermakna moral",
     "Cerita sederhana yang digunakan untuk mengilustrasikan pelajaran moral atau spiritual.",
     "A simple story used to illustrate a moral or spiritual lesson, as told by philosophers.",
     ["Allegory", "Fable", "Moral tale"], ["Allegory", "Fable", "Lesson", "Apologue", "Metaphor"], ["History", "Chronicle"],
     "The philosopher shared a timeless parable about the dangers of excessive human greed.",
     "Children listened intently to the village elder's wise parable about honesty and forest conservation."),

    ("Paradox", "noun", "B2", "/ˈpær.ə.dɒks/", "paradoks / pernyataan kontradiktif tapi benar",
     "Pernyataan atau situasi yang tampak kontradiktif namun pada kenyataannya mengandung kebenaran.",
     "A seemingly absurd or self-contradictory statement or proposition that when investigated may prove true.",
     ["Paradoxical", "Paradoxically", "Enigma"], ["Enigma", "Contradiction", "Puzzle", "Irony", "Mystery"], ["Truism", "Simplicity"],
     "It is a modern technological paradox that hyper-connected social media can increase feelings of loneliness.",
     "The water-diamond paradox explores why essential water is cheap while ornamental diamonds are expensive."),

    ("Paralyze", "verb", "B2", "/ˈpær.ə.laɪz/", "melumpuhkan total / menghentikan kemampuan gerak",
     "Menyebabkan seseorang atau sesuatu kehilangan kemampuan untuk bergerak atau berfungsi.",
     "Cause a person or part of the body to become partly or wholly incapable of movement; incapacitate.",
     ["Paralysis", "Paralyzed", "Incapacitate"], ["Incapacitate", "Immobilize", "Disable", "Freeze", "Stun"], ["Mobilize", "Activate", "Energize", "Animate"],
     "A sudden heavy blizzard paralyzed public transportation and air traffic across the capital city.",
     "Venom from certain tropical sea cone snails can paralyze small prey fish instantly."),

    ("Parameter", "noun", "B2", "/pəˈræm.ɪ.tər/", "parameter acuan / batasan standar ketentuan",
     "Faktor atau batas numerik atau terukur yang menentukan cara sesuatu dijalankan.",
     "A numerical or other measurable factor forming one of a set that defines a system or sets conditions.",
     ["Parametric", "Boundary", "Criterion"], ["Boundary", "Criterion", "Specification", "Framework", "Limit"], ["Arbitrariness"],
     "The clinical trial established strict parameters for selecting eligible patient volunteers.",
     "Software developers set network security parameters to block unauthorized server access attempts."),

    ("Paramount", "adjective", "C1", "/ˈpær.ə.maʊnt/", "terpenting utama / berperingkat paling luhur",
     "Lebih penting daripada segala hal lain; memiliki otoritas atau derajat tertinggi.",
     "More important than anything else; supreme in rank or significance.",
     ["Supreme", "Prime", "Chief"], ["Supreme", "Chief", "Prime", "Foremost", "Predominant"], ["Minor", "Secondary", "Subordinate", "Trivial"],
     "In pediatric medicine, the physical safety and emotional comfort of the child are paramount.",
     "Maintaining national cybersecurity resilience is a matter of paramount national importance."),

    ("Paraphrase", "verb", "B2", "/ˈpær.ə.freɪz/", "memparafrasakan / menguraikan dengan kata sendiri",
     "Menyatakan kembali isi teks atau ucapan orang lain dengan susunan kata-kata sendiri.",
     "Express the meaning of a writer or speaker using different words, especially to achieve clarity.",
     ["Paraphrase", "Reword", "Restate"], ["Reword", "Restate", "Rephrase", "Summarize", "Translate"], ["Quote directly", "Plagiarize"],
     "Students were instructed to paraphrase academic sources carefully and provide proper citations.",
     "The journalist paraphrased the minister's lengthy press speech into three clear summary bullet points."),

    ("Pardon", "noun", "B1", "/ˈpɑː.dən/", "pengampunan resmi / maaf keringanan hukuman",
     "Tindakan memaafkan kesalahan; pengampunan resmi dari kepala negara terhadap narapidana.",
     "The action of forgiving or being forgiven for an error or offence; an official executive amnesty.",
     ["Pardonable", "Forgiveness", "Amnesty"], ["Amnesty", "Forgiveness", "Absolution", "Reprieve", "Exoneration"], ["Punishment", "Condemnation", "Sentence"],
     "The president granted a humanitarian pardon to several elderly nonviolent prisoners.",
     "Beg your pardon, could you please repeat the last flight boarding announcement?"),

    ("Particle", "noun", "B2", "/ˈpɑː.tɪ.kəl/", "partikel renik / butiran zat sangat halus",
     "Bagian atau butiran benda yang sangat kecil sekali; partikel atomik dalam fisika.",
     "A minute portion of matter; the least possible amount; subatomic entity.",
     ["Particulate", "Speck", "Fragment"], ["Speck", "Atom", "Molecule", "Granule", "Fragment"], ["Mass", "Chunk", "Whole"],
     "Air filtration purifiers trap microscopic dust particles, pollen, and pet allergens.",
     "Subatomic physicists smash particles together inside giant underground particle accelerators."),

    ("Partisan", "adjective", "C1", "/ˌpɑː.tɪˈzæn/", "fanatik partisan / berpihak secara berat sebelah",
     "Berpihak secara membabi buta atau sangat fanatik pada satu partai politik atau golongan.",
     "Prejudiced in favor of a particular cause or political party.",
     ["Partisanship", "Bipartisan", "Biased"], ["Biased", "Prejudiced", "One-sided", "Factional", "Sectarian"], ["Impartial", "Neutral", "Bipartisan", "Objective"],
     "The newspaper editorial maintained an objective tone, avoiding heated partisan political rhetoric.",
     "Bipartisan legislative compromise is required to pass long-term national budget bills."),

    ("Passion", "noun", "A2", "/ˈpæʃ.ən/", "gairah membara / minat mendalam penuh cinta",
     "Perasaan antusiasme yang sangat kuat dan intens terhadap suatu kegiatan atau cita-cita.",
     "Strong and barely controllable emotion; an intense enthusiasm or desire for something.",
     ["Passionate", "Passionately", "Ardor"], ["Ardor", "Zeal", "Enthusiasm", "Fervor", "Devotion"], ["Apathy", "Indifference", "Coldness"],
     "Her lifelong passion for marine biology inspired her to establish ocean conservation sanctuaries.",
     "Playing classical violin requires both rigorous technical discipline and heartfelt emotional passion."),

    ("Passive", "adjective", "B2", "/ˈpæs.ɪv/", "pasif tanpa perlawanan / menerima tanpa bertindak",
     "Menerima apa yang terjadi tanpa aktif berbuat atau memberi respons perlawanan.",
     "Accepting or allowing what happens or what others do, without active response or resistance.",
     ["Passively", "Passivity", "Submissive"], ["Submissive", "Inactive", "Compliant", "Unresisting", "Dormant"], ["Active", "Dynamic", "Proactive", "Resistant"],
     "Passive solar house designs absorb and store thermal heat naturally through south-facing windows.",
     "Citizens are encouraged to participate actively in town hall discussions rather than remain passive."),

    ("Pastor", "noun", "B2", "/ˈpɑː.stər/", "pendeta gembala umat / pemimpin rohani",
     "Pemimpin rohani atau pelayan gereja yang membimbing jemaat dalam kegiatan keagamaan.",
     "A minister in charge of a Christian church or congregation.",
     ["Pastoral", "Clergy", "Minister"], ["Minister", "Clergyman", "Priest", "Preacher", "Shepherd"], ["Layperson"],
     "The parish pastor offered comforting words and counseling to grieving neighborhood families.",
     "Pastoral care programs at the school provide emotional and spiritual support for students."),

    ("Patent", "noun", "B2", "/ˈpeɪ.tənt/", "paten hak cipta penemuan / hak monopoli cipta",
     "Hak eksklusif yang diberikan oleh pemerintah kepada penemu atas ciptaan barunya.",
     "A government authority or licence conferring a right or title for a set period to exclude others.",
     ["Patentable", "Patented", "Copyright"], ["Copyright", "License", "Privilege", "Proprietary right"], ["Public domain"],
     "The biotech startup registered an international patent for its novel cancer diagnostic tool.",
     "Engineers filed a patent application protecting their revolutionary lithium battery cooling system."),

    ("Paternal", "adjective", "B2", "/pəˈtɜː.nəl/", "kebapaan / berasal dari garis keturunan ayah",
     "Berkaitan dengan seorang ayah; menunjukkan sifat pelindung seorang bapak.",
     "Of or appropriate to a father; related through the father's side of the family.",
     ["Paternity", "Fatherly", "Maternal"], ["Fatherly", "Patrilineal", "Protective", "Patriarchal"], ["Maternal", "Motherly"],
     "He inherited his mechanical aptitude and artistic flair from his paternal grandfather.",
     "The caring mentor offered wise paternal guidance to the young apprentice entering the guild."),

    ("Pathway", "noun", "B1", "/ˈpɑːθ.weɪ/", "jalur lintasan / alur jenjang karier",
     "Jalan setapak kecil untuk berjalan kaki; alur langkah bertahap menuju pencapaian tujuan.",
     "A track that constitutes or serves as a path; a sequence of actions that achieves a result.",
     ["Path", "Route", "Track"], ["Path", "Track", "Route", "Avenue", "Trajectory"], ["Dead end"],
     "A scenic stone pathway leads hikers through ancient mossy cedar forests to the waterfall.",
     "Vocational education creates accessible career pathways for youth entering specialized industries."),

    ("Patience", "noun", "A2", "/ˈpeɪ.ʃəns/", "kesabaran / ketabahan menanti dengan tenang",
     "Kemampuan untuk menahan kesulitan, penundaan, atau provokasi tanpa menjadi marah.",
     "The capacity to accept or tolerate delay, trouble, or suffering without getting angry or upset.",
     ["Patient", "Patiently", "Tolerance"], ["Tolerance", "Forbearance", "Fortitude", "Composure", "Endurance"], ["Impatience", "Irritability", "Agitation"],
     "Teaching young children how to read requires immense patience, creativity, and empathy.",
     "With patience and consistent daily practice, she mastered the complex classical piano sonata."),

    ("Patriot", "noun", "B2", "/ˈpeɪ.tri.ət/", "patriot pejuang bangsa / pembela tanah air",
     "Seseorang yang sangat mencintai dan siap membela tanah airnya dengan setia.",
     "A person who vigorously supports their country and is prepared to defend it against enemies.",
     ["Patriotic", "Patriotism", "Nationalist"], ["Nationalist", "Loyalist", "Defender", "Statesman"], ["Traitor", "Betrayer"],
     "Historic monuments honor the brave patriots who sacrificed their lives for national independence.",
     "True patriots contribute to their country through civic participation, honesty, and community service."),

    ("Pattern", "noun", "A2", "/ˈpæt.ən/", "pola keteraturan / motif corak hiasan",
     "Susunan bentuk, garis, atau kejadian yang berulang secara teratur dan dapat diprediksi.",
     "A repeated decorative design; a regular and intelligible form or sequence discernible in the way.",
     ["Patterned", "Design", "Template"], ["Design", "Motif", "Template", "Sequence", "Structure"], ["Chaos", "Randomness", "Disorder"],
     "Traditional Indonesian batik fabrics feature intricate cultural motifs and geometric patterns.",
     "Meteorologists analyze long-term atmospheric pressure patterns to forecast seasonal monsoon rain."),

    ("Peasant", "noun", "B1", "/ˈpez.ənt/", "petani desa / kaum jelata pedesaan",
     "Petani kecil tradisional atau buruh tani pemilik lahan sempit di pedesaan.",
     "A poor farmer of low social status who owns or rents a small piece of land for cultivation.",
     ["Peasantry", "Rustic", "Farmer"], ["Farmer", "Rustic", "Agriculturalist", "Villager", "Tiller"], ["Noble", "Aristocrat", "Lord"],
     "Medieval feudal lords collected heavy grain taxes from impoverished peasant communities.",
     "The folk museum showcases the wooden tools and handwoven garments crafted by historic peasants.")
]

print("MR Additional dataset ready:", len(MR_ADDITIONAL), "entries.")
