#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Rich additional Oxford words for MR (46+ words) and SZ (90+ words).
"""

MR_FINAL_SUPPLEMENT = [
    ("Magnificent", "adjective", "B1", "/mæɡˈnɪf.ɪ.sənt/", "sangat megah luar biasa / agung mempesona",
     "Sangat indah, luas, atau mengesankan; menampilkan kemegahan dan keagungan luar biasa.",
     "Extremely beautiful, elaborate, or impressive; grand.",
     ["Magnificence", "Grand", "Superb"], ["Grand", "Superb", "Splendid", "Majestic", "Glorious"], ["Modest", "Drab", "Ugly", "Poor"],
     "The royal palace features magnificent marble halls and manicured fountains.",
     "From the alpine summit, we admired a magnificent panoramic view of the golden sunrise."),

    ("Magnitude", "noun", "B2", "/ˈmæɡ.nɪ.tjuːd/", "besaran magnitudo / skala kepentingan besar",
     "Ukuran atau luas yang sangat besar dari sesuatu; skala numerik kekuatan gempa bumi.",
     "The great size or extent of something; size, quantity, or magnitude of an earthquake.",
     ["Magnify", "Scale", "Extent"], ["Scale", "Extent", "Dimension", "Immensity", "Significance"], ["Smallness", "Insignificance"],
     "Government emergency planners underestimated the catastrophic magnitude of the tsunami.",
     "The seismograph registered an earthquake with a magnitude of 7.2 off the southern coast."),

    ("Majestic", "adjective", "B2", "/məˈdʒes.tɪk/", "agung berwibawa / megah memesona",
     "Menunjukkan keagungan, martabat, atau keindahan yang mengesankan.",
     "Having or showing impressive beauty or scale; royal and stately.",
     ["Majesty", "Stateliness", "Imperial"], ["Imperial", "Royal", "Stately", "Imposing", "Noble"], ["Humble", "Modest", "Lowly"],
     "The majestic snow-capped peaks of Mount Rainier rose high above the pine valleys.",
     "A majestic golden eagle soared effortlessly on warm thermal updrafts above the canyon."),

    ("Malice", "noun", "C1", "/ˈmæl.ɪs/", "niat jahat dengki / kedengkian penuh permusuhan",
     "Keinginan untuk menyakiti atau menyebabkan penderitaan pada orang lain; itikad buruk.",
     "The desire to harm someone; ill will; malicious intent.",
     ["Malicious", "Maliciously", "Spite"], ["Spite", "Spitefulness", "Malevolence", "Grudge", "Animosity"], ["Goodwill", "Benevolence", "Kindness", "Amity"],
     "The court found no evidence of criminal malice in the unfortunate laboratory accident.",
     "She spoke without malice, offering constructive criticism to help her colleague improve."),

    ("Mammoth", "adjective", "B2", "/ˈmæm.əθ/", "raksasa sangat besar / tugas berskala kolosal",
     "Sangat besar dan membutuhkan usaha luar biasa; gajah purba berbulu zaman es.",
     "Huge; gigantic; an extinct prehistoric elephant with long curved tusks.",
     ["Colossal", "Gigantic", "Immense"], ["Gigantic", "Colossal", "Monumental", "Enormous", "Vast"], ["Tiny", "Miniature", "Microscopic"],
     "Rebuilding the national railway network was a mammoth engineering undertaking.",
     "The museum displayed a remarkably preserved fossilized woolly mammoth skeleton."),

    ("Manifest", "verb", "B2", "/ˈmæn.ɪ.fest/", "memanifestasikan / memperlihatkan wujud nyata",
     "Menunjukkan atau memperlihatkan sesuatu secara jelas melalui tanda atau tindakan nyata.",
     "Display or show a quality or feeling by one's acts or appearance; demonstrate.",
     ["Manifestation", "Manifesto", "Evident"], ["Demonstrate", "Exhibit", "Display", "Reveal", "Express"], ["Conceal", "Hide", "Mask", "Suppress"],
     "Chronic psychological stress can manifest physically as headaches and muscle tension.",
     "Her passion for environmental stewardship manifested in her tree-planting campaigns."),

    ("Manipulate", "verb", "B2", "/məˈnɪp.jə.leɪt/", "memanipulasi / mengendalikan secara terampil atau licik",
     "Menangani atau mengendalikan sesuatu dengan terampil; mempengaruhi orang lain secara licik.",
     "Handle or control a tool, mechanism, or data in a skillful manner; influence unfairly.",
     ["Manipulation", "Manipulative", "Influence"], ["Control", "Handle", "Maneuver", "Steer", "Exploit"], ["Mismanage", "Leave alone"],
     "Skilled surgeons use robotic arms to manipulate delicate surgical instruments precisely.",
     "Sensationalist headlines seek to manipulate public emotions and boost article clicks."),

    ("Mankind", "noun", "B1", "/mænˈkaɪnd/", "seluruh umat manusia / peradaban insani",
     "Seluruh spesies manusia yang mendiami bumi secara kolektif.",
     "The human race considered collectively; human beings as a whole.",
     ["Humanity", "Human race", "Mortals"], ["Humanity", "Humankind", "People", "Society", "Mortals"], ["Alien", "Inanimate"],
     "Scientific discoveries in clean energy will benefit the long-term future of all mankind.",
     "Preserving global biodiversity is a vital responsibility shared by all mankind."),

    ("Manual", "noun", "B1", "/ˈmæn.ju.əl/", "buku panduan manual / petunjuk pengoperasian",
     "Buku kecil yang memberikan petunjuk penggunaan mesin atau prosedur; dilakukan dengan tangan.",
     "A book of instructions, especially for operating a machine or learning a subject; of or done with hands.",
     ["Manually", "Handbook", "Guide"], ["Handbook", "Guide", "Instructions", "Companion", "Tutorial"], ["Automatic"],
     "Please read the user manual carefully before assembling the electric bicycle.",
     "Manual craftsmanship adds unique authentic charm to traditional hand-carved wooden furniture."),

    ("Margin", "noun", "B1", "/ˈmɑː.dʒɪn/", "tepi margin halaman / batas selisih keuntungan",
     "Tepi atau batas kosong di sekeliling halaman; batas perbedaan waktu, suara, atau keuntungan.",
     "The edge or border of something; the amount by which a thing is won or falls short.",
     ["Marginal", "Border", "Leeway"], ["Border", "Edge", "Boundary", "Periphery", "Leeway"], ["Center", "Core"],
     "The editor left helpful constructive comments in the wide side margins of the manuscript.",
     "The legislative bill passed the parliament by a narrow margin of just five votes."),

    ("Marvel", "noun", "B2", "/ˈmɑː.vəl/", "keajaiban menakjubkan / hal yang mempesona",
     "Sesuatu atau seseorang yang menimbulkan kekaguman dan keheranan yang luar biasa.",
     "A wonderful or astonishing person or thing; cause for wonder.",
     ["Marvelous", "Wonder", "Prodigy"], ["Wonder", "Miracle", "Prodigy", "Spectacle", "Phenomenon"], ["Commonplace", "Bore"],
     "The ancient stone pyramids of Giza are an architectural marvel of human engineering.",
     "We marvel at the intricate navigational instincts that guide migrating Arctic terns."),

    ("Masculine", "adjective", "B2", "/ˈmæs.kjə.lɪn/", "maskulin kejantanan / berwatak khas pria",
     "Memiliki kualitas atau penampilan yang secara tradisional dikaitkan dengan pria.",
     "Having qualities or appearance traditionally associated with men; manly.",
     ["Masculinity", "Manly", "Virile"], ["Manly", "Virile", "Robust", "Muscular", "Stalwart"], ["Feminine", "Delicate", "Effeminate"],
     "Traditional tailoring emphasizes structured shoulders and clean lines for a masculine silhouette.",
     "Modern psychology encourages men to express empathy alongside traditional masculine resilience."),

    ("Mastery", "noun", "B2", "/ˈmɑː.stər.i/", "penguasaan mahir / keahlian puncak dalam bidang",
     "Keterampilan atau pengetahuan yang komprehensif dan mendalam tentang suatu subjek atau seni.",
     "Comprehensive knowledge or skill in a particular subject or activity; control.",
     ["Master", "Masterpiece", "Expertise"], ["Expertise", "Proficiency", "Command", "Skill", "Fluency"], ["Incompetence", "Ignorance", "Clumsiness"],
     "Achieving complete mastery over the classical concert harp requires decades of disciplined practice.",
     "Her linguistic mastery of five languages made her an indispensable diplomatic translator."),

    ("Maturity", "noun", "B2", "/məˈtʃʊə.rə.ti/", "kedewasaan batin / kematangan usia atau obligasi",
     "Kondisi, fakta, atau periode menjadi matang atau dewasa; tanggal jatuh tempo keuangan.",
     "The state, fact, or period of being mature; wisdom and emotional stability.",
     ["Mature", "Maturational", "Adulthood"], ["Adulthood", "Wisdom", "Sophistication", "Fullness", "Ripeness"], ["Immaturity", "Childishness", "Greenness"],
     "She handled the difficult team disagreement with admirable emotional maturity and grace.",
     "The government treasury bond will reach its financial maturity in ten years with compound interest."),

    ("Medal", "noun", "A2", "/ˈmed.əl/", "medali tanda jasa / piagam penghargaan logam",
     "Kepingan logam bundar berukir yang diberikan sebagai penghargaan atas prestasi militer atau olahraga.",
     "A metal disc typically bearing an inscription or design, given as an award for bravery or sport.",
     ["Medalist", "Medallion", "Decoration"], ["Award", "Decoration", "Badge", "Trophy", "Honor"], ["Penalty"],
     "The Olympic sprinter proudly wore the gold medal around his neck on the championship podium.",
     "Brave military paramedics were awarded medals of honor for rescuing wounded soldiers under fire."),

    ("Medium", "noun", "B1", "/ˈmiː.di.əm/", "perantara media / sarana penyampai pesan",
     "Sarana atau saluran yang digunakan untuk berkomunikasi, mengekspresikan seni, atau menyimpan data.",
     "An agency or means of doing something; a material or form used by an artist.",
     ["Media", "Instrument", "Vehicle"], ["Vehicle", "Channel", "Instrument", "Mode", "Agency"], ["N/A"],
     "Watercolor paint on textured cotton paper is an expressive medium for landscape illustration.",
     "Podcasts have emerged as a popular digital medium for in-depth investigative journalism."),

    ("Mellow", "adjective", "B2", "/ˈmel.əʊ/", "lembut matang / ramah bersahabat dan tenang",
     "Matang dan manis rasanya; ramah, tenang, dan rileks karena usia atau pengalaman.",
     "Pleasantly smooth or soft in sound, taste, or color; relaxed and good-humored.",
     ["Mellowness", "Smooth", "Gentle"], ["Smooth", "Gentle", "Warm", "Harmonious", "Rich"], ["Harsh", "Sour", "Sharp", "Strident"],
     "The cellist produced a mellow, resonant tone that filled the intimate chamber hall.",
     "With age, the fiery debater became more mellow, listening patiently to opposing viewpoints."),

    ("Melody", "noun", "A2", "/ˈmel.ə.di/", "melodi nada / untaian irama lagu yang merdu",
     "Rangkaian nada musik yang disusun dalam urutan berirama dan enak didengar telinga.",
     "A sequence of single notes that is musically satisfying; a tune.",
     ["Melodic", "Melodious", "Tune"], ["Tune", "Theme", "Air", "Song", "Motif"], ["Discord", "Noise"],
     "The acoustic guitarist played a gentle, haunting melody that brought tears to the listeners.",
     "Children easily memorize educational rhymes set to a catchy, upbeat musical melody."),

    ("Mentality", "noun", "B2", "/menˈtæl.ə.ti/", "pola pikir / mentalitas kepribadian",
     "Sikap mental, pola pikir, atau watak umum seseorang atau suatu kelompok masyarakat.",
     "The characteristic attitude, mind-set, or way of thinking of a person or group.",
     ["Mental", "Mindset", "Outlook"], ["Mindset", "Outlook", "Psychology", "Attitude", "Disposition"], ["Physicality"],
     "Developing a growth mentality helps students view academic mistakes as valuable learning steps.",
     "The coach fostered a resilient team mentality focused on mutual encouragement and perseverance."),

    ("Mercy", "noun", "B2", "/ˈmɜː.si/", "belas kasihan / pengampunan penuh welas asih",
     "Welas asih atau pengampunan yang ditunjukkan kepada seseorang yang pantas dihukum.",
     "Compassion or forgiveness shown towards someone whom it is within one's power to punish or harm.",
     ["Merciful", "Merciless", "Compassion"], ["Compassion", "Pity", "Leniency", "Clemency", "Grace"], ["Cruelty", "Harshness", "Ruthlessness", "Vengeance"],
     "The defeated general pleaded for mercy for the captured civilian population of the city.",
     "Humanitarian aid organizations provide mercy and medical assistance to refugees in crisis."),

    ("Merit", "noun", "B2", "/ˈmer.ɪt/", "kebaikan mutu jasa / kelayakan atas prestasi",
     "Kualitas menjadi sangat baik atau patut dipuji; keunggulan dan kepantasan yang berhak dihargai.",
     "The quality of being particularly good or worthy, especially so as to deserve praise or reward.",
     ["Meritorious", "Meritocracy", "Worth"], ["Worth", "Value", "Excellence", "Credit", "Virtue"], ["Demerit", "Fault", "Flaw", "Defect"],
     "University scholarships are awarded based purely on academic merit and leadership potential.",
     "The committee judged each architectural proposal strictly on its technical and economic merits."),

    ("Metaphor", "noun", "B2", "/ˈmet.ə.fər/", "metafora kiasan / majas perbandingan langsung",
     "Gaya bahasa kiasan di mana sebuah kata diterapkan pada objek atau tindakan yang bukan harfiah.",
     "A figure of speech in which a word or phrase is applied to an object or action to which it is not literally applicable.",
     ["Metaphorical", "Allegory", "Analogy"], ["Analogy", "Allegory", "Symbol", "Image", "Simile"], ["Literalness"],
     "The poet used the stormy sea as a dramatic metaphor for human emotional turmoil and grief.",
     "Time is a thief is a classic literary metaphor illustrating the swift and silent passage of years."),

    ("Metropolis", "noun", "B2", "/məˈtrɒp.əl.ɪs/", "metropolis kota raya / pusat peradaban megapolitan",
     "Kota yang sangat besar, sibuk, dan penting sebagai pusat ekonomi atau budaya negara.",
     "The capital or chief city of a country or region; a very large and densely populated city.",
     ["Metropolitan", "City", "Megacity"], ["Megacity", "Capital", "Municipality", "Center", "Hub"], ["Village", "Hamlet"],
     "Tokyo is a sprawling modern metropolis renowned for ultra-fast bullet trains and rich culture.",
     "Young creatives migrate from rural towns to the metropolis seeking dynamic career opportunities."),

    ("Midst", "noun", "B2", "/mɪdst/", "tengah-tengah / di antara pusaran keadaan",
     "Bagian tengah atau titik pusat dari sesuatu; berada di tengah-tengah peristiwa sibuk.",
     "The middle point or part; situated in the middle of a group of people or things.",
     ["Middle", "Center", "Heart"], ["Middle", "Center", "Heart", "Core", "Thick"], ["Edge", "Periphery", "Margin"],
     "Even in the midst of a heavy monsoon storm, the postal couriers delivered packages reliably.",
     "She maintained quiet inner composure even while working in the midst of chaotic stock markets."),

    ("Migrate", "verb", "B1", "/maɪˈɡreɪt/", "bermigrasi / berpindah tempat musiman",
     "Berpindah dari satu wilayah atau habitat ke wilayah lain, terutama sesuai musim.",
     "Move from one region or habitat to another according to the seasons; relocate.",
     ["Migration", "Migratory", "Relocate"], ["Relocate", "Move", "Journey", "Trek", "Emigrate"], ["Stay", "Remain", "Settle"],
     "Humpback whales migrate thousands of miles each winter from polar feeding grounds to warm seas.",
     "Software engineers help migrate legacy database records to modern cloud infrastructure."),

    ("Milestone", "noun", "B2", "/ˈmaɪl.stəʊn/", "tonggak sejarah / pencapaian penting dalam proses",
     "Peristiwa, pencapaian, atau tahap yang sangat penting dalam perkembangan seseorang atau proyek.",
     "A significant stage or event in the development of something; a marker of progress.",
     ["Landmark", "Turning point", "Breakthrough"], ["Landmark", "Turning point", "Breakthrough", "Bench-mark", "Event"], ["Stagnation"],
     "Passing the bar exam was a monumental milestone in her journey to becoming a human rights lawyer.",
     "The space exploration agency celebrated the milestone of landing a robotic rover on Mars."),

    ("Mimic", "verb", "B2", "/ˈmɪm.ɪk/", "menirukan gerak / meniru suara atau ciri khas",
     "Meniru suara, tingkah laku, atau penampilan seseorang atau binatang dengan tepat.",
     "Imitate someone or their actions or words, especially in order to entertain or ridicule.",
     ["Mimicry", "Imitate", "Ape"], ["Imitate", "Ape", "Emulate", "Echo", "Mirror"], ["Differ", "Oppose"],
     "Parrots and lyrebirds can mimic complex human speech and musical melodies with stunning precision.",
     "Biomimetic engineers design aircraft wings that mimic the aerodynamic curve of falcon feathers."),

    ("Miraculous", "adjective", "B2", "/mɪˈræk.jə.ləs/", "ajaib luar biasa / seperti mukjizat selamat",
     "Terjadi seperti mukjizat; sangat luar biasa mengagumkan dan tidak dapat dijelaskan secara biasa.",
     "Occurring through divine or supernatural intervention; remarkable and bringing welcome relief.",
     ["Miracle", "Wonder", "Extraordinary"], ["Extraordinary", "Astonishing", "Wondrous", "Supernatural", "Incredible"], ["Ordinary", "Natural", "Common"],
     "The lost mountain climbers made a miraculous survival after four freezing nights in the cave.",
     "Advancements in surgical robotics have led to miraculous recoveries in pediatric neurology."),

    ("Misfortune", "noun", "B2", "/ˌmɪsˈfɔː.tʃuːn/", "kemalangan nasib buruk / kesialan musibah",
     "Nasib buruk atau kondisi malang; peristiwa menyedihkan yang mendatangkan kerugian.",
     "Bad luck; an unfortunate condition or event; adversity.",
     ["Unfortunate", "Adversity", "Hardship"], ["Adversity", "Hardship", "Mishap", "Calamity", "Affliction"], ["Luck", "Fortune", "Prosperity", "Blessing"],
     "The community showed great empathy and solidarity to help neighbors overcome sudden misfortune.",
     "He bore his financial misfortunes with quiet dignity and persevered to rebuild his enterprise."),

    ("Mislead", "verb", "B2", "/ˌmɪsˈliːd/", "menyesatkan informasi / memberi petunjuk keliru",
     "Menyebabkan seseorang memiliki pendapat atau keyakinan yang salah dengan sengaja atau tidak.",
     "Cause someone to have a wrong idea or impression about someone or something.",
     ["Misleading", "Deceive", "Delude"], ["Deceive", "Delude", "Misguide", "Beguile", "Fool"], ["Guide", "Inform", "Enlighten", "Direct"],
     "Consumer protection agencies penalize companies that mislead buyers with false advertising.",
     "Do not let temporary emotional impulses mislead you into making rash long-term decisions."),

    ("Mobile", "noun", "A2", "/ˈməʊ.baɪl/", "telepon seluler / gantungan hiasan berayun",
     "Perangkat telepon nirkabel genggam; karya seni gantung berayun yang digerakkan oleh arus udara.",
     "A cellular mobile phone; a decorative sculpture with parts that move in current of air.",
     ["Cell phone", "Handset", "Smartphone"], ["Handset", "Cellular", "Smartphone", "Sculpture"], ["Landline"],
     "Modern smartphones serve as versatile mobile computers connecting people across continents.",
     "The nursery was decorated with a colorful mobile of wooden stars and crescent moons."),

    ("Model", "noun", "A1", "/ˈmɒd.əl/", "model teladan / miniatur purwarupa contoh",
     "Representasi tiga dimensi dari orang atau benda; contoh ideal yang patut ditiru dan dijadikan panutan.",
     "A three-dimensional representation of a person or thing; an example to be imitated.",
     ["Modelling", "Prototype", "Exemplar"], ["Prototype", "Exemplar", "Pattern", "Archetype", "Miniature"], ["Original"],
     "The architect presented a wooden scale model of the proposed public art library building.",
     "She is a model student whose dedication, curiosity, and kindness inspire all her classmates."),

    ("Moderate", "verb", "B2", "/ˈmɒd.ər.eɪt/", "memoderasi diskusi / meredakan ketegangan",
     "Menjadi penengah dalam debat atau diskusi; mengurangi intensitas atau keparahan sesuatu.",
     "Make or become less extreme, intense, or violent; preside over a formal debate or forum.",
     ["Moderator", "Moderation", "Tone down"], ["Tone down", "Mitigate", "Temper", "Soothe", "Chair"], ["Intensify", "Aggravate", "Inflame"],
     "A neutral academic was invited to moderate the lively televised presidential debate.",
     "Taking short brisk walks helped moderate his elevated resting blood pressure over time."),

    ("Modest", "noun", "B1", "/ˈmɒd.ɪst/", "kesederhanaan santun / kerendahan hati bersahaja",
     "Sifat bersahaja dan tidak menyombongkan diri atas kelebihan atau kekayaan yang dimiliki.",
     "The quality of being unassuming in the estimation of one's abilities; simplicity.",
     ["Modesty", "Humility", "Simplicity"], ["Humility", "Simplicity", "Reserve", "Unpretentiousness"], ["Vanity", "Arrogance", "Pride"],
     "Despite receiving international accolades, the scientist accepted honors with graceful modest poise.",
     "The family lived in a modest wooden chalet overlooking the sparkling alpine lake."),

    ("Modify", "verb", "B2", "/ˈmɒd.ɪ.faɪ/", "memodifikasi / mengubah sedikit untuk menyempurnakan",
     "Mengubah sesuatu secara parsial untuk meningkatkan kecocokan atau efektivitasnya.",
     "Make partial or minor changes to something, typically so as to improve it or make it more suitable.",
     ["Modification", "Modifier", "Adjust"], ["Adjust", "Adapt", "Alter", "Tweak", "Revise"], ["Leave unchanged", "Preserve"],
     "Engineers had to modify the aircraft wing structure to improve fuel efficiency at cruising speed.",
     "The teacher agreed to modify the exam schedule to accommodate students participating in sports."),

    ("Moist", "adjective", "B1", "/mɔɪst/", "lembap basah sedikit / segar berair lembut",
     "Sedikit basah atau mengandung cairan halus; tidak kering dan segar teksturnya.",
     "Slightly wet; damp; containing moisture.",
     ["Moisture", "Moisturize", "Damp"], ["Damp", "Humid", "Juicy", "Dewy", "Supple"], ["Dry", "Arid", "Parched", "Dehydrated"],
     "The chocolate fudge cake was rich, flavorful, and delightfully moist inside.",
     "Rich organic potting soil should be kept pleasantly moist but not waterlogged for seedlings."),

    ("Mournful", "adjective", "B2", "/ˈmɔːn.fəl/", "penuh duka pilu / menyayat hati sedih",
     "Merasakan, mengungkapkan, atau menimbulkan rasa sedih dan duka cita mendalam.",
     "Feeling, expressing, or inducing sadness, grief, or sorrow; lugubrious.",
     ["Mourn", "Mournfully", "Sorrowful"], ["Sorrowful", "Doleful", "Plaintive", "Woeful", "Melancholy"], ["Joyful", "Cheerful", "Exuberant", "Upbeat"],
     "The cello played a mournful solo melody that captured the tragic narrative of the opera.",
     "A mournful silence descended upon the town square as the funeral procession passed."),

    ("Movement", "noun", "A2", "/ˈmuːv.mənt/", "gerakan perpindahan / pergerakan aksi sosial",
     "Tindakan berpindah tempat atau posisi; kelompok orang yang bersatu demi tujuan sosial.",
     "An act of changing physical location or position; a campaign undertaken by people toward an objective.",
     ["Move", "Movable", "Campaign"], ["Motion", "Gesture", "Drive", "Campaign", "Crusade"], ["Inaction", "Stagnation"],
     "The delicate mechanical movement of the Swiss wristwatch keeps precise time without batteries.",
     "The global youth climate movement advocates for immediate transition to renewable energy.")
]

print("MR Final Supplement ready:", len(MR_FINAL_SUPPLEMENT))
