#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Rich additional Oxford words for SZ (Part 4) to surpass 260 words.
"""

SZ_EXTRA_PART3 = [
    ("Veteran", "noun", "B1", "/ˈvet.ər.ən/", "veteran pejuang / pakar berpengalaman lama",
     "Seseorang yang memiliki pengalaman panjang dalam bidang atau kegiatan tertentu; purnawirawan.",
     "A person who has had long experience in a particular field; a former member of the armed forces.",
     ["Seasoned", "Experienced", "Old hand"], ["Old hand", "Master", "Expert", "Ex-soldier", "Doyen"], ["Novice", "Rookie", "Beginner", "Trainee"],
     "The aerospace engineering team was led by a thirty-year industry veteran who mentored young staff.",
     "Annual national ceremonies honor military veterans who defended the country during wartime."),

    ("Vex", "verb", "C1", "/veks/", "menjengkelkan / membuat gusar frustrasi",
     "Membuat seseorang merasa jengkel, frustrasi, atau khawatir, terutama dengan hal-hal sepele.",
     "Make someone feel annoyed, frustrated, or worried, especially with trivial matters.",
     ["Vexation", "Vexed", "Annoy"], ["Annoy", "Irritate", "Pique", "Nettle", "Frustrate"], ["Soothe", "Please", "Mollify", "Calm"],
     "Confusing traffic signs continue to vex daily commuters navigating the newly built ring road.",
     "The unresolved tax calculation error vexed the accountant until she found the missing invoice."),

    ("Vibrant", "adjective", "B2", "/ˈvaɪ.brənt/", "penuh daya hidup / bersemangat semarak",
     "Penuh dengan energi, vitalitas, dan semangat ceria; warna yang kuat berkilau.",
     "Full of energy and enthusiasm; bright and striking in visual appearance.",
     ["Vibrancy", "Vibrantly", "Lively"], ["Lively", "Dynamic", "Energetic", "Effervescent", "Vivid"], ["Lifeless", "Dull", "Drab"],
     "The historic district has a vibrant creative arts community with weekend craft markets.",
     "She wore a vibrant emerald green silk dress to the opening night gala."),

    ("Vicinity", "noun", "B2", "/vɪˈsɪn.ə.ti/", "sekitarnya / kawasan lingkungan terdekat",
     "Daerah atau kawasan di dekat atau di sekeliling suatu tempat tertentu.",
     "The area near or surrounding a particular place; proximity in relationship or space.",
     ["Proximity", "Surroundings", "Locality"], ["Neighborhood", "Locality", "Proximity", "Precinct", "Surroundings"], ["Distance", "Remoteness"],
     "There are several charming family-owned cafes in the immediate vicinity of the museum.",
     "Police searched the immediate forest vicinity for the missing hikers before dusk."),

    ("Vicious", "adjective", "B2", "/ˈvɪʃ.əs/", "kejam ganas / penuh niat jahat beracun",
     "Sengaja bertindak kejam atau penuh kekerasan; siklus buruk yang memperparah diri sendiri.",
     "Deliberately cruel or violent; of an animal, wild and dangerous to people.",
     ["Viciously", "Cruel", "Ferocious"], ["Cruel", "Ferocious", "Malevolent", "Brutal", "Spiteful"], ["Gentle", "Kind", "Benevolent", "Mild"],
     "Education and vocational training help break the vicious cycle of generational poverty.",
     "The guard dog gave a vicious snarl as the midnight intruder approached the perimeter fence."),

    ("Victor", "noun", "B1", "/ˈvɪk.tər/", "pemenang juara / peraih kejayaan kemenangan",
     "Seseorang yang mengalahkan lawan dalam pertempuran, perlombaan, atau kompetisi.",
     "A person who defeats an enemy or opponent in a battle, game, or other competition.",
     ["Victorious", "Victory", "Champion"], ["Champion", "Winner", "Conqueror", "Hero", "Master"], ["Loser", "Defeated", "Vanquished"],
     "The Olympic marathon victor crossed the finish line to thunderous applause from the stadium crowd.",
     "History books remember the compassionate victors who offered terms of honor to the defeated."),

    ("Vigor", "noun", "B2", "/ˈvɪɡ.ər/", "daya tenaga / kekuatan vitalitas tubuh dan pikiran",
     "Kekuatan fisik, kesehatan prima, dan energi yang melimpah; ketegasan dalam tindakan.",
     "Physical strength and good health; effort, energy, and enthusiasm.",
     ["Vigorous", "Vigorously", "Energy"], ["Energy", "Vitality", "Dynamism", "Stamina", "Robustness"], ["Lethargy", "Weakness", "Frailty", "Fatigue"],
     "Regular cardiovascular exercise and sound sleep restore youthfulness and physical vigor.",
     "The campaign team tackled the neighborhood door-to-door outreach with renewed vigor and enthusiasm."),

    ("Violate", "verb", "B2", "/ˈvaɪ.ə.leɪt/", "melanggar norma / menodai kesucian aturan",
     "Melanggar atau bertindak melawan aturan, undang-undang, perjanjian, atau tempat suci.",
     "Break or fail to comply with a rule or formal agreement; treat a sacred place with disrespect.",
     ["Violation", "Violator", "Breach"], ["Breach", "Infringe", "Transgress", "Defile", "Desecrate"], ["Obey", "Respect", "Uphold", "Honor"],
     "Industrial factories that violate clean air emissions standards face severe regulatory fines.",
     "Trespassing on private wildlife reserves violates environmental conservation statutes."),

    ("Virtue", "noun", "B2", "/ˈvɜː.tʃuː/", "kebajikan luhur / kebaikan moral budi pekerti",
     "Perilaku yang menunjukkan standar moral yang tinggi; kebiasaan berbuat baik yang terpuji.",
     "Behavior showing high moral standards; a good or useful quality of a thing.",
     ["Virtuous", "Morality", "Goodness"], ["Goodness", "Morality", "Integrity", "Righteousness", "Honesty"], ["Vice", "Iniquity", "Sin", "Depravity"],
     "Patience and compassion are timeless human virtues celebrated in philosophical traditions.",
     "By virtue of her extensive international experience, she was appointed chief trade negotiator."),

    ("Vocation", "noun", "B2", "/vəʊˈkeɪ.ʃən/", "panggilan jiwa / profesi pekerjaan sejati",
     "Perasaan kuat tentang kesesuaian untuk karier atau pekerjaan tertentu; profesi keahlian.",
     "A strong feeling of suitability for a particular career or occupation; a trade or profession.",
     ["Vocational", "Calling", "Career"], ["Calling", "Profession", "Career", "Trade", "Occupation"], ["Hobby", "Pastime"],
     "For many dedicated doctors and nurses, pediatric healthcare is a profound lifelong vocation.",
     "Vocational training institutes equip young apprentices with hands-on carpentry and culinary skills."),

    ("Vow", "noun", "B2", "/vaʊ/", "ikrar sumpah janji / komitmen suci teguh",
     "Janji khidmat yang dibuat kepada diri sendiri, orang lain, atau Tuhan untuk melakukan sesuatu.",
     "A solemn promise, pledge, or personal commitment.",
     ["Vowed", "Pledge", "Oath"], ["Pledge", "Oath", "Promise", "Affidavit", "Covenant"], ["Betrayal"],
     "The bride and groom exchanged heartfelt personal wedding vows in front of family and friends.",
     "The environmental activist made a private vow to protect the ancient redwood forest grove."),

    ("Voyage", "noun", "B1", "/ˈvɔɪ.ɪdʒ/", "pelayaran samudera / penjelajahan bahari panjang",
     "Perjalanan jauh ke tempat yang jauh, terutama melalui laut samudera atau luar angkasa.",
     "A long journey involving travel by sea or in space.",
     ["Voyager", "Journey", "Expedition"], ["Expedition", "Journey", "Cruise", "Passage", "Pilgrimage"], ["Stay", "Stationary"],
     "Early Polynesian navigators embarked on daring ocean voyages across thousands of miles of Pacific swells.",
     "The spacecraft completed its historic decade-long voyage to photograph the outer dwarf planets."),

    ("Wander", "verb", "B1", "/ˈwɒn.dər/", "berkelana mengembara / berjalan santai tanpa arah",
     "Berjalan atau bergerak santai tanpa arah atau tujuan yang pasti; pikiran yang melayang.",
     "Walk or move in a leisurely, casual, or aimless way; move away from a path or subject.",
     ["Wanderer", "Wandering", "Roam"], ["Roam", "Rove", "Meander", "Stroll", "Drift"], ["Stay", "Direct", "Focus"],
     "Tourists love to wander through the cobbled narrow alleys of the historic Italian quarter.",
     "During the long lecture, his mind began to wander to the upcoming weekend fishing trip."),

    ("Wardrobe", "noun", "A2", "/ˈwɔː.drəʊb/", "lemari pakaian / koleksi busana pribadi",
     "Lemari besar tempat menggantung pakaian; seluruh pakaian yang dimiliki seseorang.",
     "A large, tall cupboard in which clothes may be hung or stored; a person's entire collection of clothes.",
     ["Closet", "Apparel", "Garments"], ["Closet", "Cupboard", "Attire", "Apparel", "Garments"], ["N/A"],
     "She organized her bedroom wardrobe by grouping seasonal coats, silk blouses, and formal dresses.",
     "A versatile capsule wardrobe consists of high-quality timeless staples that pair easily."),

    ("Warehouse", "noun", "B1", "/ˈweə.haʊs/", "gudang penyimpanan / depo logistik barang",
     "Bangunan besar tempat barang mentah atau manufaktur disimpan sebelum didistribusikan.",
     "A large building where raw materials or manufactured goods may be stored prior to distribution.",
     ["Storage", "Depot", "Repository"], ["Depot", "Repository", "Storehouse", "Stockroom", "Logistics center"], ["Showroom"],
     "Automated robotic forklifts transport pallet boxes across the e-commerce fulfillment warehouse.",
     "The historic riverfront brick warehouse was renovated into stylish open-plan artist lofts."),

    ("Warrant", "noun", "B2", "/ˈwɒr.ənt/", "surat perintah resmi / alasan pembenaran sah",
     "Dokumen resmi yang dikeluarkan oleh pengadilan atau otoritas yang memberi wewenang hukum.",
     "A document issued by a legal or government official authorizing police to make an arrest or search.",
     ["Warranted", "Guarantee", "Authorization"], ["Authorization", "Mandate", "Permit", "License", "Sanction"], ["Prohibition"],
     "Police officers obtained a judicial search warrant before entering the suspicious property.",
     "The seriousness of the economic downturn provides sufficient warrant for emergency stimulus measures."),

    ("Warrior", "noun", "B1", "/ˈwɒr.i.ər/", "kesatria pejuang / prajurit gagah berani",
     "Prajurit yang berpengalaman dan pemberani dalam pertempuran; pembela keadilan.",
     "A brave or experienced soldier or fighter; a person who shows great vigor and courage.",
     ["Warfare", "Fighter", "Combatant"], ["Fighter", "Soldier", "Combatant", "Champion", "Knight"], ["Coward", "Pacifist"],
     "Ancient Spartan warriors were celebrated for their fierce battlefield discipline and physical prowess.",
     "She is a courageous environmental warrior who has fought against illegal forest logging for decades."),

    ("Wary", "adjective", "B2", "/ˈweə.ri/", "waspada berhati-hati / penuh kehati-hatian",
     "Merasa atau menunjukkan kehati-hatian tentang kemungkinan bahaya atau masalah yang timbul.",
     "Feeling or showing caution about possible dangers or problems; alert and cautious.",
     ["Warily", "Wariness", "Cautious"], ["Cautious", "Guarded", "Vigilant", "Chary", "Prudent"], ["Careless", "Reckless", "Heedless", "Trusting"],
     "Hikers should be wary of venomous snakes when walking through tall desert scrub brush.",
     "Consumers are advised to be wary of unsolicited emails requesting private banking passwords."),

    ("Weave", "verb", "B1", "/wiːv/", "menenun kain / merangkai alur cerita",
     "Membuat kain dengan menyilangkan benang pakan dan lungsin; merangkai cerita rumit.",
     "Form fabric by interlacing long threads passing in one direction with others at a right angle.",
     ["Weaver", "Woven", "Interlace"], ["Interlace", "Braid", "Knit", "Entwine", "Craft"], ["Unravel", "Dismantle"],
     "Skilled village artisans weave intricate songket fabrics using silk threads and real gold leaf.",
     "The novelist weaves multiple character perspectives into a captivating historical mystery."),

    ("Well-being", "noun", "B1", "/ˌwelˈbiː.ɪŋ/", "kesejahteraan lahir batin / kebahagiaan paripurna",
     "Kondisi merasa nyaman, sehat, bahagia, dan sejahtera dalam kehidupan jasmani dan rohani.",
     "The state of being comfortable, healthy, or happy; general health and welfare.",
     ["Welfare", "Health", "Prosperity"], ["Welfare", "Health", "Happiness", "Prosperity", "Comfort"], ["Misery", "Illness", "Suffering", "Deprivation"],
     "Regular exercise, mindful meditation, and balanced nutrition support overall mental and physical well-being.",
     "The modern company introduced flexible remote work policies to enhance employee emotional well-being."),

    ("Wilderness", "noun", "B1", "/ˈwɪl.də.nəs/", "belantara liar / alam liar yang belum terjamah",
     "Wilayah alami yang belum diolah, dihuni, atau diubah oleh peradaban manusia.",
     "An uncultivated, uninhabited, and hospitable region; a wild and natural area.",
     ["Wild", "Wilds", "Backcountry"], ["Backcountry", "Outback", "Jungle", "Wasteland", "Forest"], ["City", "Civilization", "Metropolis"],
     "The vast Alaskan wilderness is home to grizzly bears, moose, and pristine glacier rivers.",
     "Outdoor survival instructors teach navigation skills to prepare hikers for remote wilderness treks."),

    ("Wit", "noun", "B2", "/wɪt/", "kecerdasan kelakar / kecerdikan humor jenaka",
     "Kemampuan mental untuk berpikir cepat dan membuat ucapan jenaka yang cerdas dan menghibur.",
     "Mental sharpness and inventiveness; keen intelligence; a natural aptitude for humorous comment.",
     ["Witty", "Witticism", "Sharpness"], ["Sharpness", "Cleverness", "Humor", "Ingenuity", "Banter"], ["Dullness", "Stupidity"],
     "The playwright was renowned for his sharp wit and memorable satirical dialogue on social status.",
     "She used her charm and quick wit to diffuse the tense confrontation during the boardroom meeting."),

    ("Withstand", "verb", "B2", "/wɪðˈstænd/", "tahan terhadap / kokoh bertahan melawan guncangan",
     "Mampu bertahan melawan atau tidak rusak oleh kekuatan, tekanan, atau cobaan berat.",
     "Remain undamaged or unaffected by; resist or survive against adverse pressure.",
     ["Withstood", "Endure", "Resist"], ["Resist", "Endure", "Survive", "Tolerate", "Hold out"], ["Yield", "Surrender", "Succumb"],
     "The ancient Roman stone aqueduct was built with hydraulic cement that can withstand millennia.",
     "A resilient mental mindset helps individuals withstand professional setbacks with dignity."),

    ("Woe", "noun", "B2", "/wəʊ/", "duka lara nestapa / kesengsaraan hidup",
     "Kesedihan, duka cita, atau penderitaan yang sangat mendalam; masalah hidup yang membebani.",
     "Great sorrow or distress; things that cause sorrow or distress; troubles.",
     ["Woeful", "Woefully", "Misery"], ["Misery", "Sorrow", "Grief", "Anguish", "Distress"], ["Joy", "Happiness", "Bliss", "Fortune"],
     "The country's economic woes were compounded by severe drought and falling commodity export prices.",
     "Poets express the profound heartaches and woes of unrequited love in melancholy verses."),

    ("Wondrous", "adjective", "B2", "/ˈwʌn.drəs/", "sangat menakjubkan / ajaib mengagumkan jiwa",
     "Menginspirasi perasaan kagum atau takjub; sangat indah dan ajaib seperti mimpi.",
     "Inspiring a feeling of wonder or delight; marvelous.",
     ["Wonder", "Wonderfully", "Marvelous"], ["Marvelous", "Miraculous", "Enchanting", "Breathtaking", "Extraordinary"], ["Ordinary", "Commonplace", "Dull"],
     "Diving among the coral gardens of Raja Ampat revealed a wondrous underwater world of radiant marine life.",
     "Children stared in wondrous awe as the night sky lit up with dazzling multicolored fireworks."),

    ("Worthy", "adjective", "B2", "/ˈwɜː.ði/", "patut layak / bernilai mulia pantas dihargai",
     "Memiliki nilai, mutu, atau karakter yang pantas menerima perhatian atau penghargaan.",
     "Having or showing the qualities or abilities that merit recognition in a specified way.",
     ["Worth", "Worthiness", "Deserving"], ["Deserving", "Meritorious", "Commendable", "Admirable", "Honorable"], ["Unworthy", "Despicable", "Reprehensible"],
     "The youth community center is a worthy charitable cause that deserves generous corporate funding.",
     "She proved to be a worthy successor to the retiring medical director through her exceptional leadership."),

    ("Wrath", "noun", "C1", "/rɒθ/", "kemurkaan dahsyat / amarah amuk yang meluap",
     "Kemarahan yang sangat besar, ganas, dan intens; pembalasan murka yang menghukum.",
     "Extreme anger, especially when considered as a divine judgment or vengeance.",
     ["Wrathful", "Fury", "Rage"], ["Fury", "Rage", "Indignation", "Ire", "Vengeance"], ["Calm", "Peace", "Forgiveness", "Patience"],
     "The coastal kingdom feared the ancient sea god's wrath whenever violent winter gales battered ships.",
     "He faced the manager's wrath after missing the critical project deadline due to negligence."),

    ("Wretched", "adjective", "B2", "/ˈretʃ.ɪd/", "sangat malang merana / buruk menyedihkan kondisinya",
     "Dalam kondisi yang sangat tidak bahagia, malang, atau menyedihkan; kualitas sangat buruk.",
     "In a very unhappy or unfortunate state; of poor quality or very bad.",
     ["Wretch", "Miserable", "Pitiable"], ["Miserable", "Abject", "Pitiable", "Deplorable", "Woeful"], ["Joyful", "Fortunate", "Splendid", "Luxurious"],
     "The destitute refugees lived in wretched conditions without running water or warm blankets.",
     "She caught a wretched head cold during the winter holidays and had to stay in bed for three days."),

    ("Yearn", "verb", "B2", "/jɜːn/", "merindukan sangat mendalam / mendambakan dengan hasrat",
     "Merasakan keinginan yang intens, mendalam, dan penuh kerinduan untuk mendapatkan sesuatu.",
     "Have an intense feeling of longing for something, typically something that one has lost or been separated from.",
     ["Yearning", "Long", "Crave"], ["Long", "Pine", "Crave", "Hankering", "Ache for"], ["Despise", "Shun", "Reject"],
     "After months of working abroad in the cold northern winter, he yearned for the warm tropical sun.",
     "Children living in crowded high-rise apartment towers yearn for open green parks to run and play."),

    ("Yield", "noun", "B2", "/jiːld/", "hasil panen komoditas / tingkat imbal hasil keuntungan",
     "Jumlah produk pertanian yang dihasilkan dari sebidang tanah; persentase laba investasi.",
     "The full amount of an agricultural or industrial product produced; financial return.",
     ["Crop yield", "Harvest", "Return"], ["Harvest", "Return", "Output", "Produce", "Dividend"], ["Deficit", "Loss"],
     "Modern drip irrigation techniques significantly boosted the seasonal wheat crop yield.",
     "Government bonds offer investors a steady, predictable annual financial yield."),

    ("Zenith", "noun", "C1", "/ˈzen.ɪθ/", "titik kulminasi puncak / masa kejayaan tertinggi",
     "Waktu atau titik di mana sesuatu berada dalam kondisi paling kuat atau paling sukses; titik langit tepat di atas kepala.",
     "The time at which something is most powerful or successful; the point in the sky directly overhead.",
     ["Apex", "Pinnacle", "Peak"], ["Pinnacle", "Apex", "Peak", "Acme", "Climax"], ["Nadir", "Bottom", "Depth"],
     "The ancient civilization reached the magnificent zenith of its cultural and architectural power in the fifth century.",
     "The midday sun stood at its blazing zenith directly above the desert oasis."),

    ("Zealous", "adjective", "B2", "/ˈzel.əs/", "penuh semangat membara / tekun antusias gigih",
     "Menunjukkan semangat, dedikasi, dan antusiasme yang luar biasa besar terhadap suatu tujuan.",
     "Having or showing zeal; passionate and fervent in supporting an idea or enterprise.",
     ["Zeal", "Zealously", "Fervent"], ["Fervent", "Ardent", "Passionate", "Dedicated", "Eager"], ["Apathetic", "Indifferent", "Lethargic"],
     "The museum curator was a zealous collector of rare pre-colonial Indonesian gold coins.",
     "Zealous young community volunteers worked tirelessly to clean up plastic debris from the beaches.")
]

print("SZ Extra Part 3 loaded:", len(SZ_EXTRA_PART3))
