#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generates rich Oxford 3000/5000 dictionary entries for Part 2 (E-L), Part 3 (M-R), Part 4 (S-Z).
"""

OXFORD_PART2_EXTRA = [
    ("Emphasize", "verb", "B1", "/ˈem.fə.saɪz/", "menekankan / menggarisbawahi pentingnya",
     "Memberikan perhatian khusus atau menegaskan pentingnya suatu hal dalam percakapan.",
     "Give special importance or prominence to something in speaking or writing.",
     ["Emphasis", "Emphatic", "Highlight"], ["Highlight", "Stress", "Accentuate", "Underline", "Feature"], ["Understate", "Ignore", "Downplay"],
     "The teacher emphasized the importance of regular reading and vocabulary practice.",
     "During his opening address, the CEO emphasized safety and ethical integrity across operations."),

    ("Empower", "verb", "B2", "/ɪmˈpaʊ.ər/", "memberdayakan / memberi wewenang dan kekuatan",
     "Memberikan otoritas resmi, kekuatan hukum, atau rasa percaya diri kepada seseorang.",
     "Give someone the authority or power to do something; make someone stronger and more confident.",
     ["Empowerment", "Empowering", "Authorize"], ["Authorize", "Enable", "Equip", "Liberate", "Strengthen"], ["Disempower", "Weaken", "Constrain", "Restrict"],
     "The vocational workshop aims to empower young entrepreneurs with digital marketing skills.",
     "Education is the most potent tool to empower communities and eradicate systemic poverty."),

    ("Encounter", "verb", "B1", "/ɪŋˈkaʊn.tər/", "menjumpai / mengalami pertemuan tak terduga",
     "Bertemu atau menghadapi seseorang atau suatu rintangan secara tidak terduga.",
     "Unexpectedly be faced with or experience something hostile or difficult; meet someone.",
     ["Encounter", "Meet", "Confront"], ["Face", "Confront", "Meet", "Experience", "Come across"], ["Avoid", "Evade", "Elude", "Bypass"],
     "Explorers encountered severe blizzards while ascending the Himalayan mountain ridge.",
     "Whenever we encounter unexpected problems, we should analyze the root causes calmly."),

    ("Endless", "adjective", "B1", "/ˈend.ləs/", "tanpa akhir / tak berujung / tiada henti",
     "Tampak tidak memiliki batas akhir dalam waktu, ruang, atau jumlah pengulangan.",
     "Having or seeming to have no end or limit; ceaseless and infinite.",
     ["Endlessly", "Endlessness", "Infinite"], ["Infinite", "Ceaseless", "Perpetual", "Unbounded", "Interminable"], ["Finite", "Limited", "Brief", "Terminal"],
     "They gazed across the endless golden dunes of the Sahara Desert at sunset.",
     "Children have an endless curiosity about nature, asking hundreds of daily questions."),

    ("Enhance", "verb", "B2", "/ɪnˈhɑːns/", "meningkatkan mutu / memperindah kualitas",
     "Memperbaiki atau menambah keindahan, nilai, atau efektivitas sesuatu.",
     "Intensify, increase, or further improve the quality, value, or extent of something.",
     ["Enhancement", "Enhanced", "Improve"], ["Improve", "Augment", "Elevate", "Boost", "Enrich"], ["Diminish", "Damage", "Impair", "Lessen"],
     "Adding fresh herbs and garlic can greatly enhance the aroma and flavor of the soup.",
     "Modern noise-canceling software enhances voice clarity during high-level video conferences."),

    ("Enlighten", "verb", "C1", "/ɪnˈlaɪ.tən/", "mencerahkan wawasan / memberi pemahaman mendalam",
     "Memberikan pengetahuan dan pemahaman yang jelas untuk membebaskan dari ketidaktahuan.",
     "Give someone greater knowledge and understanding about a subject or situation.",
     ["Enlightenment", "Enlightened", "Illuminate"], ["Illuminate", "Educate", "Instruct", "Inform", "Edify"], ["Confuse", "Mislead", "Obscure", "Befuddle"],
     "The documentary served to enlighten viewers on the complexities of marine preservation.",
     "A great mentor strives to enlighten students rather than merely reciting facts."),

    ("Enterprise", "noun", "B2", "/ˈen.tə.praɪz/", "badan usaha perusahaan / daya inisiatif",
     "Proyek bisnis atau usaha komersial; kesiapan untuk mengambil inisiatif dan risiko.",
     "A project or undertaking, especially a bold or complex one; a business or company.",
     ["Enterprising", "Entrepreneur", "Venture"], ["Venture", "Business", "Company", "Initiative", "Endeavor"], ["Inaction", "Passivity"],
     "The tech startup grew from a modest garage project into a multimillion-dollar global enterprise.",
     "Success in free markets requires bold commercial enterprise, diligence, and adaptive innovation."),

    ("Entitle", "verb", "B2", "/ɪnˈtaɪ.təl/", "memberi hak resmi / memberi judul karya",
     "Memberikan hak yang sah kepada seseorang untuk memperoleh atau melakukan sesuatu.",
     "Give someone a legal right or a just claim to receive or do something; give a title to a book.",
     ["Entitlement", "Entitled", "Authorize"], ["Authorize", "Qualify", "Allow", "Empower", "Permit"], ["Disqualify", "Forbid", "Deny", "Prohibit"],
     "Purchasing a VIP pass entitles attendees to backstage access and priority seating.",
     "The author decided to entitle her new historical novel 'Whispers of the Archipelago.'"),

    ("Envy", "noun", "B1", "/ˈen.vi/", "rasa iri dengki / kedengkian atas keberhasilan orang",
     "Perasaan tidak senang atau cemburu karena menginginkan keunggulan milik orang lain.",
     "A feeling of discontented or resentful longing aroused by someone else's possessions or luck.",
     ["Envious", "Enviably", "Jealousy"], ["Jealousy", "Resentment", "Covetousness", "Bitterness"], ["Goodwill", "Generosity", "Contentment"],
     "Instead of feeling envy toward successful colleagues, strive to learn from their habits.",
     "His exceptional musical talents and humble persona made him the envy of the entire conservatory."),

    ("Episode", "noun", "A2", "/ˈep.ɪ.səʊd/", "episode tayangan / bagian babak peristiwa",
     "Satu bagian dari serial televisi atau radio; suatu kejadian dalam rangkaian peristiwa hidup.",
     "An event or a group of events occurring as part of a larger sequence; an installment of a show.",
     ["Episodic", "Installment", "Chapter"], ["Installment", "Chapter", "Segment", "Incident", "Occurrence"], ["Whole", "Compilation"],
     "Millions of fans tuned in to watch the thrilling season finale episode of the drama series.",
     "Moving abroad was a transformative episode in her career, broadening her worldview forever."),

    ("Equator", "noun", "B1", "/ɪˈkweɪ.tər/", "garis khatulistiwa / lintang nol derajat bumi",
     "Garis imajiner yang membagi bumi menjadi belahan utara dan belahan selatan.",
     "An imaginary line drawn around the earth equally distant from both poles, dividing it into halves.",
     ["Equatorial", "Equinox", "Latitude"], ["Parallel of 0 degrees", "Midline", "Central belt"], ["Pole"],
     "Countries situated near the equator experience warm tropical weather and rich rainforest biodiversity.",
     "Indonesia straddles the equator, enjoying abundant sunshine and fertile volcanic soil throughout the year."),

    ("Erroneous", "adjective", "C1", "/ɪˈrəʊ.ni.əs/", "keliru / salah perhitungan / tidak tepat",
     "Mengandung kekeliruan atau berakar dari asumsi yang tidak benar.",
     "Wrong; incorrect; based on false assumptions or flawed logical deductions.",
     ["Error", "Erroneously", "Incorrect"], ["Incorrect", "False", "Flawed", "Mistaken", "Inaccurate"], ["Correct", "Accurate", "Valid", "True"],
     "The audit revealed that previous profit forecasts were based on erroneous financial assumptions.",
     "Scientists corrected the erroneous conclusions after conducting a broader double-blind trial."),

    ("Etiquette", "noun", "B2", "/ˈet.ɪ.ket/", "tata krama / etiket kesopanan sosial",
     "Kode perilaku santun konvensional yang berlaku dalam pergaulan atau profesi tertentu.",
     "The customary code of polite behavior in society or among members of a particular profession.",
     ["Manners", "Protocol", "Decorum"], ["Protocol", "Manners", "Decorum", "Politeness", "Courtesy"], ["Rudeness", "Impoliteness", "Boorishness"],
     "Diplomats receive comprehensive training in international protocol and cultural dining etiquette.",
     "Maintaining courteous digital etiquette during video conferences creates a respectful workplace atmosphere."),

    ("Evoke", "verb", "B2", "/ɪˈvəʊk/", "membangkitkan kenangan / menggugah perasaan",
     "Mengingatkan pada sesuatu atau memunculkan kembali emosi dan kenangan lama.",
     "Bring or recall an emotion, feeling, memory, or image to the conscious mind.",
     ["Evocative", "Evocation", "Kindle"], ["Kindle", "Elicit", "Arouse", "Awaken", "Summon"], ["Suppress", "Stifle", "Repress", "Extinguish"],
     "The scent of fresh jasmine blossoms always evokes fond memories of her grandmother's garden.",
     "The composer's melancholic melody evoked a powerful emotional response from the concert audience."),

    ("Exemplify", "verb", "C1", "/ɪɡˈzem.plɪ.faɪ/", "memberi contoh nyata / merepresentasikan",
     "Menjadi contoh yang sangat jelas atau teladan utama dari suatu kualitas.",
     "Be a typical example of; illustrate or clarify by giving an example.",
     ["Example", "Exemplary", "Illustrate"], ["Illustrate", "Embody", "Represent", "Demonstrate", "Personify"], ["Misrepresent", "Distort", "Obscure"],
     "Her tireless volunteer work and humility exemplify the highest ideals of community service.",
     "The historic stone bridges in the city exemplify classical Roman engineering excellence."),

    ("Exempt", "adjective", "B2", "/ɪɡˈzempt/", "dikecualikan / dibebaskan dari kewajiban",
     "Bebas dari kewajiban, pembayaran pajak, atau aturan yang umumnya berlaku untuk orang lain.",
     "Free from an obligation or liability imposed on others.",
     ["Exemption", "Immune", "Excepted"], ["Immune", "Excused", "Spared", "Excepted", "Free"], ["Liable", "Subject", "Obligated", "Bound"],
     "Charitable and non-profit educational institutions are often exempt from corporate income taxes.",
     "Students with verified medical certificates were exempt from the rigorous physical fitness test."),

    ("Exile", "noun", "B2", "/ˈek.saɪl/", "pengasingan diri / pembuangan ke luar negeri",
     "Keadaan terusir atau terpaksa tinggal jauh dari tanah air karena alasan politis.",
     "The state of being barred from one's native country, typically for political reasons.",
     ["Exile", "Expatriate", "Banishment"], ["Banishment", "Expulsion", "Ostracism", "Deportation", "Displacement"], ["Repatriation", "Welcome", "Return"],
     "The poet spent twenty years in foreign exile, writing poignant verses about his distant homeland.",
     "After political upheaval subsided, former leaders were allowed to return safely from exile."),

    ("Exploit", "verb", "B2", "/ɪkˈsplɔɪt/", "memanfaatkan / mengeksploitasi sumber daya",
     "Menggunakan sumber daya secara maksimal; memperlakukan seseorang secara tidak adil demi laba.",
     "Make full use of and derive benefit from a resource; treat someone unfairly for profit.",
     ["Exploitation", "Exploitative", "Leverage"], ["Leverage", "Utilize", "Harness", "Capitalize on", "Abuse"], ["Neglect", "Waste", "Ignore"],
     "Modern green industries seek to exploit renewable solar and geothermal energy sustainably.",
     "Strict international labor conventions protect vulnerable workers from being unfairly exploited."),

    ("Feasible", "adjective", "B2", "/ˈfiː.zə.bəl/", "layak dijalankan / masuk akal dapat terlaksana",
     "Mungkin dan mudah dilakukan secara praktis dengan sumber daya yang tersedia.",
     "Possible and practical to do easily or conveniently; workable and viable.",
     ["Feasibility", "Feasibly", "Viable"], ["Viable", "Practical", "Workable", "Achievable", "Attainable"], ["Infeasible", "Impractical", "Impossible", "Unworkable"],
     "The engineering committee concluded that the high-speed railway tunnel proposal was technically feasible.",
     "Before launching the marketing campaign, the team conducted a detailed financial feasibility study."),

    ("Fluctuate", "verb", "B2", "/ˈflʌk.tʃu.eɪt/", "berfluktuasi / naik turun berubah-ubah",
     "Berubah-ubah secara tidak teratur dalam jumlah, tingkat, atau nilai tertentu.",
     "Rise and fall irregularly in number, quality, or amount.",
     ["Fluctuation", "Vary", "Shift"], ["Vary", "Shift", "Oscillate", "Waver", "Alternate"], ["Stabilize", "Remain steady", "Settle"],
     "Currency exchange rates fluctuate daily depending on global economic reports and oil prices.",
     "Body temperature naturally fluctuates in a rhythmic cycle throughout the day and night."),

    ("Forbid", "verb", "B1", "/fəˈbɪd/", "melarang keras / mengharamkan aturan",
     "Memerintahkan seseorang untuk tidak melakukan sesuatu; menyatakan tidak diizinkan.",
     "Refuse to allow something; order someone not to do something.",
     ["Forbidden", "Forbidding", "Prohibit"], ["Prohibit", "Ban", "Disallow", "Veto", "Interdict"], ["Allow", "Permit", "Authorize", "Encourage"],
     "National park safety regulations strictly forbid lighting campfires outside designated stone fire pits.",
     "The school policy forbids students from using mobile phones during formal exam sessions."),

    ("Foster", "verb", "B2", "/ˈfɒs.tər/", "membina / memupuk perkembangan / mengasuh",
     "Mendorong perkembangan atau pertumbuhan sesuatu yang bernilai baik; mengasuh anak.",
     "Encourage or promote the development of something; bring up a child that is not one's own.",
     ["Fosterage", "Nurture", "Cultivate"], ["Nurture", "Cultivate", "Encourage", "Promote", "Support"], ["Hinder", "Suppress", "Stifle", "Discourage"],
     "The interactive classroom environment helps foster creative problem-solving and collaboration.",
     "The generous couple decided to foster two young orphan siblings and support their education."),

    ("Fraction", "noun", "B1", "/ˈfræk.ʃən/", "pecahan matematika / sebagian kecil porsi",
     "Bagian kecil dari suatu keseluruhan; representasi bilangan pecahan.",
     "A small or tiny part, amount, or proportion of something; a numerical quantity not whole.",
     ["Fractional", "Portion", "Fragment"], ["Portion", "Fragment", "Segment", "Share", "Part"], ["Whole", "Total", "Entirety"],
     "Online digital streaming uses only a tiny fraction of the data bandwidth required a decade ago.",
     "The new energy-efficient light bulbs consume a fraction of the electricity used by incandescent bulbs."),

    ("Frantic", "adjective", "B2", "/ˈfræn.tɪk/", "panik tergesa-gesa / heboh kalut",
     "Sangat cemas, gelisah, atau tergesa-gesa karena ketakutan atau kekurangan waktu.",
     "Wild or distraught with fear, anxiety, or other emotion; conducted in a hurried manner.",
     ["Frantically", "Frenzied", "Panicked"], ["Frenzied", "Panicked", "Desperate", "Hectic", "Wild"], ["Calm", "Composed", "Serene", "Tranquil"],
     "There was a frantic search at the airport terminal when a traveler misplaced his passport.",
     "Paramedics worked at a frantic pace to stabilize victims following the sudden highway collision."),

    ("Furious", "adjective", "B1", "/ˈfjʊə.ri.əs/", "sangat murka / marah besar / dahsyat hebat",
     "Merasa sangat marah; berlangsung dengan kecepatan atau keganasan luar biasa.",
     "Extremely angry; full of fury; intensely violent or energetic.",
     ["Fury", "Furiously", "Enraged"], ["Enraged", "Infuriated", "Irate", "Fierce", "Tempestuous"], ["Calm", "Peaceful", "Delighted", "Placid"],
     "The homeowner was furious when vandals spray-painted graffiti across the front garden gate.",
     "A furious tropical storm battered the coastal harbor with howling winds and crashing waves."),

    ("Garment", "noun", "B2", "/ˈɡɑː.mənt/", "pakaian jadi / busana garmen tekstil",
     "Suatu jenis pakaian atau busana yang dikenakan manusia.",
     "An item of clothing; a manufactured apparel piece.",
     ["Apparel", "Clothing", "Attire"], ["Apparel", "Clothing", "Attire", "Robe", "Costume"], ["N/A"],
     "Eco-friendly fashion brands manufacture garments using recycled organic cotton fibers.",
     "The museum textile curator carefully preserved ancient silk garments from the Ming dynasty."),

    ("Generalize", "verb", "B2", "/ˈdʒen.ər.əl.aɪz/", "menyamaratakan / menarik simpulan umum",
     "Membuat pernyataan umum berdasarkan beberapa contoh atau pengamatan terbatas.",
     "Make a general or broad statement by inferring from specific cases.",
     ["Generalization", "General", "Synthesize"], ["Broaden", "Extrapolate", "Universalize", "Synthesize"], ["Specify", "Particularize", "Differentiate"],
     "Social scientists caution against attempting to generalize complex human behavior from small sample sizes.",
     "While it is tempting to generalize, each regional market presents unique cultural consumer nuances."),

    ("Genuine", "adjective", "B2", "/ˈdʒen.ju.ɪn/", "asli murni / tulus tanpa kepura-puraan",
     "Benar-benar seperti yang dinyatakan; tulus, jujur, dan tidak palsu.",
     "Truly what something is said to be; authentic, sincere, and free from hypocrisy.",
     ["Genuinely", "Genuineness", "Authentic"], ["Authentic", "Real", "Sincere", "Honest", "Bona fide"], ["Fake", "Counterfeit", "Insincere", "Bogus"],
     "Art appraisers verified that the oil canvas was a genuine seventeenth-century Dutch masterpiece.",
     "Her warm smile reflected genuine kindness and deep empathy for everyone she met."),

    ("Glimpse", "noun", "B1", "/ɡlɪmps/", "kilasan pandang sekilas / kilasan singkat",
     "Pandangan yang sangat singkat atau sepintas; gambaran singkat tentang suatu hal.",
     "A momentary or partial view; a brief sight of something or someone.",
     ["Glance", "Peek", "Sight"], ["Glance", "Peek", "Look", "Sight", "Flicker"], ["Stare", "Gaze", "Scrutiny"],
     "We caught a fleeting glimpse of the elusive snow leopard through our spotting telescope.",
     "The historical diary provides a fascinating glimpse into everyday Victorian London life."),

    ("Gorgeous", "adjective", "B1", "/ˈɡɔː.dʒəs/", "sangat menawan / luar biasa indah elok",
     "Sangat indah dipandang, megah, dan mempesona mata yang melihat.",
     "Beautiful; very attractive and pleasant to look at; magnificent.",
     ["Gorgeously", "Beautiful", "Stunning"], ["Stunning", "Magnificent", "Splendid", "Dazzling", "Breathtaking"], ["Ugly", "Hideous", "Dull", "Unattractive"],
     "The hotel balcony offered a gorgeous panoramic view of the sparkling Mediterranean coast.",
     "She wore a gorgeous hand-embroidered velvet evening gown to the charity gala."),

    ("Gradual", "adjective", "B2", "/ˈɡrædʒ.u.əl/", "bertahap perlahan / berangsur-angsur",
     "Terjadi atau berkembang secara perlahan dalam jangka waktu tertentu tanpa kejutan.",
     "Taking place or progressing slowly or by degrees; steady and sequential.",
     ["Gradually", "Progressive", "Steady"], ["Progressive", "Steady", "Step-by-step", "Incremental", "Sequential"], ["Sudden", "Abrupt", "Instant", "Rapid"],
     "With daily physical therapy exercises, the patient made a steady and gradual recovery.",
     "A gradual shift toward renewable solar energy helps reduce urban carbon emissions reliably."),

    ("Gratitude", "noun", "B1", "/ˈɡræt.ɪ.tjuːd/", "rasa terima kasih / syukur mendalam",
     "Perasaan berterima kasih dan penghargaan atas kebaikan atau pertolongan yang diterima.",
     "The quality of being thankful; readiness to show appreciation for and to return kindness.",
     ["Grateful", "Gratefully", "Thankfulness"], ["Thankfulness", "Appreciation", "Gratefulness", "Acknowledgment", "Indebtedness"], ["Ingratitude", "Unthankfulness"],
     "The rescued climbers expressed their profound gratitude to the brave mountain rescue team.",
     "Practicing daily gratitude by journaling positive moments improves mental well-being."),

    ("Grieve", "verb", "B2", "/ɡriːv/", "berduka cita / bersedih hati mendalam",
     "Merasakan kesedihan mendalam, terutama karena kehilangan orang yang dicintai.",
     "Feel intense sorrow, especially as a result of someone's death.",
     ["Grief", "Grieving", "Mourn"], ["Mourn", "Lament", "Sorrow", "Weep", "Ache"], ["Rejoice", "Celebrate", "Cheer"],
     "Families gathered at the memorial to grieve the brave firefighters who lost their lives.",
     "It takes time and compassionate support for a person to heal and grieve a major loss."),

    ("Guardian", "noun", "B2", "/ˈɡɑː.di.ən/", "wali pelindung / penjaga yang bertanggung jawab",
     "Seseorang yang bertanggung jawab secara hukum untuk melindungi atau merawat orang lain.",
     "A person who protects or defends something; a person legally responsible for a minor.",
     ["Guardianship", "Guard", "Protector"], ["Protector", "Custodian", "Defender", "Keeper", "Warden"], ["Attacker", "Enemy", "Oppressor"],
     "The child's aunt was appointed as her legal guardian following the unfortunate accident.",
     "Foresters act as guardians of the ancient redwood woodland, preventing unlawful poaching."),

    ("Habitual", "adjective", "B2", "/həˈbɪtʃ.u.əl/", "terbiasa lazim / berulang karena kebiasaan",
     "Dilakukan secara teratur atau berulang sebagai kebiasaan yang mendarah daging.",
     "Done constantly or as a habit; customary and established by long practice.",
     ["Habit", "Habitually", "Customary"], ["Customary", "Routine", "Chronic", "Persistent", "Accustomed"], ["Occasional", "Rare", "Sporadic", "Unusual"],
     "His habitual morning routine begins with a brisk 5-kilometer jog and green tea.",
     "Habitual late-night smartphone usage can disrupt natural circadian sleep rhythms."),

    ("Harvest", "noun", "B1", "/ˈhɑː.vɪst/", "panen raya / pemungutan hasil bumi",
     "Musim atau proses mengumpulkan hasil tanaman pertanian yang telah matang.",
     "The season or process of gathering in crops; the amount of crops gathered.",
     ["Harvester", "Harvest", "Yield"], ["Crop", "Yield", "Produce", "Reaping", "Gathering"], ["Planting", "Sowing"],
     "Farmers celebrated an abundant autumn harvest of golden wheat and organic apples.",
     "Modern combine harvesters make grain harvest efficient and minimize post-harvest field loss."),

    ("Haven", "noun", "B2", "/ˈheɪ.vən/", "tempat perlindungan aman / suaka yang damai",
     "Tempat yang memberikan keselamatan, ketenangan, atau perlindungan dari bahaya.",
     "A place of safety or refuge; a peaceful and sheltered sanctuary.",
     ["Safe haven", "Sanctuary", "Refuge"], ["Sanctuary", "Refuge", "Retreat", "Shelter", "Oasis"], ["Danger zone", "Hazard"],
     "The quiet botanical garden provided a tranquil haven from the noisy metropolitan traffic.",
     "The secluded island serves as a vital sanctuary and breeding haven for rare migratory sea birds."),

    ("Hazard", "noun", "B2", "/ˈhæz.əd/", "bahaya laten / risiko ancaman keselamatan",
     "Potensi sumber bahaya, cedera, atau konsekuensi yang merugikan keselamatan.",
     "A danger or risk; a potential source of harm or adverse health effect.",
     ["Hazardous", "Danger", "Risk"], ["Danger", "Peril", "Risk", "Threat", "Pitfall"], ["Safety", "Security", "Protection"],
     "Wet tiled floors without warning signs pose a serious slip hazard for hospital visitors.",
     "Proper protective equipment shields industrial workers from chemical and biological hazards."),

    ("Heirloom", "noun", "C1", "/ˈeə.luːm/", "pusaka keluarga / barang warisan leluhur",
     "Benda berharga bernilai sentimental yang diwariskan secara turun-temurun dalam keluarga.",
     "A valuable object that has belonged to a family for several generations.",
     ["Heritage", "Inheritance", "Legacy"], ["Legacy", "Inheritance", "Relic", "Antiquity", "Keepsake"], ["Novelty", "Trash"],
     "The delicate diamond necklace is a cherished family heirloom passed down since Victorian times.",
     "Craftsmen repaired the wooden grandfather clock that had been a family heirloom for two centuries."),

    ("Hereditary", "adjective", "B2", "/hɪˈred.ɪ.tər.i/", "turun-temurun / diwariskan secara genetik",
     "Diteruskan dari orang tua kepada anak melalui gen atau garis keturunan keluarga.",
     "Conferred by or based on inheritance; determined by genetic factors passed from parents.",
     ["Heredity", "Inherited", "Genetic"], ["Genetic", "Inherited", "Familial", "Inborn", "Ancestral"], ["Acquired", "Learned", "Non-genetic"],
     "Medical geneticists investigate whether certain cardiovascular conditions are hereditary.",
     "In historic monarchies, royal power and noble titles were entirely hereditary."),

    ("Hesitate", "verb", "B1", "/ˈhez.ɪ.teɪt/", "ragu-ragu sejenak / bimbang bertindak",
     "Berhenti sejenak sebelum mengatakan atau melakukan sesuatu karena ketidakyakinan.",
     "Pause before saying or doing something, especially through uncertainty or doubt.",
     ["Hesitation", "Hesitant", "Pause"], ["Pause", "Doubt", "Falter", "Waver", "Vacillate"], ["Proceed", "Advance", "Decide", "Act"],
     "Do not hesitate to contact our customer support team if you experience software issues.",
     "He hesitated for a second before stepping onto the stage to deliver his valedictory speech."),

    ("Hierarchy", "noun", "B2", "/ˈhaɪə.rɑː.ki/", "hierarki / jenjang tingkatan kepangkatan",
     "Sistem di mana orang atau kelompok disusun bertingkat menurut status atau otoritas.",
     "A system or organization in which people or groups are ranked one above the other.",
     ["Hierarchical", "Ranking", "Structure"], ["Pecking order", "Ranking", "Gradation", "Ladder", "Structure"], ["Equality", "Anarchy"],
     "Military command structures rely on a strict and indisputable hierarchy of rank.",
     "Modern tech companies frequently favor flat organization structures over rigid corporate hierarchy."),

    ("Hilarious", "adjective", "B1", "/hɪˈleə.ri.əs/", "sangat lucu / menggelikan mengundang tawa",
     "Sangat lucu dan mampu memancing gelak tawa yang riuh dan menyenangkan.",
     "Extremely amusing; causing loud merriment and laughter.",
     ["Hilarity", "Hilariously", "Funny"], ["Funny", "Comical", "Uproarious", "Humorous", "Side-splitting"], ["Sad", "Tragic", "Depressing", "Boring"],
     "The comedy troupe put on a hilarious performance that had the entire theater roaring with laughter.",
     "His hilarious travel anecdotes kept the dinner party entertained throughout the entire evening."),

    ("Hollow", "adjective", "B2", "/ˈhɒl.əʊ/", "berongga kosong / hampa tak bermakna",
     "Memiliki ruang kosong di dalamnya; tidak memiliki substansi atau ketulusan.",
     "Having a hole or empty space inside; without real significance or value.",
     ["Hollowness", "Cavity", "Empty"], ["Empty", "Vacant", "Cavernous", "Superficial", "Insincere"], ["Solid", "Filled", "Full", "Genuine", "Substantial"],
     "Owls often nest securely inside the hollow trunk of an ancient oak tree.",
     "Promises of reform without concrete actions sound hollow to frustrated citizens."),

    ("Hostile", "adjective", "B2", "/ˈhɒs.taɪl/", "bersikap memusuhi / tidak bersahabat / keras",
     "Menunjukkan kebencian, permusuhan, atau kondisi lingkungan yang sangat keras.",
     "Unfriendly; antagonistic; of or belonging to a military enemy; harsh and adverse.",
     ["Hostility", "Hostilely", "Unfriendly"], ["Antagonistic", "Unfriendly", "Adverse", "Aggressive", "Inhospitable"], ["Friendly", "Welcoming", "Hospitable", "Gentle"],
     "The desert presents a hostile climate with scorching daytime heat and freezing nights.",
     "Negotiators worked tirelessly to defuse the hostile tensions between the two opposing factions."),

    ("Humiliate", "verb", "B2", "/hjuːˈmɪl.i.eɪt/", "mempermalukan / merendahkan martabat orang",
     "Membuat seseorang merasa sangat malu atau kehilangan harga diri di depan publik.",
     "Make someone feel ashamed and foolish by injuring their dignity and pride, especially publicly.",
     ["Humiliation", "Humiliating", "Disgrace"], ["Disgrace", "Degrade", "Embarrass", "Shame", "Mortify"], ["Honor", "Respect", "Praise", "Elevate"],
     "Constructive teachers never humiliate students when correcting academic mistakes.",
     "The scandalous revelation served to humiliate the corrupt official before the public inquiry."),

    ("Hypothesis", "noun", "B2", "/haɪˈpɒθ.ə.sɪs/", "hipotesis / dugaan ilmiah sementara",
     "Penjelasan atau asumsi sementara yang dibuat atas dasar bukti terbatas untuk diuji.",
     "A proposed explanation made on the basis of limited evidence as a starting point for investigation.",
     ["Hypothetical", "Hypothesize", "Theory"], ["Theory", "Supposition", "Postulate", "Proposition", "Premise"], ["Fact", "Certainty", "Proof"],
     "The marine biologists formulated a hypothesis regarding changing sea temperatures and coral bleaching.",
     "Empirical laboratory experiments either support or invalidate the initial scientific hypothesis."),

    ("Ideal", "adjective", "A2", "/aɪˈdɪəl/", "ideal / sempurna sesuai harapan terbaik",
     "Sesuai dengan standar kesempurnaan tertinggi; paling cocok dan memuaskan.",
     "Satisfying one's conception of what is perfect; most suitable and desirable.",
     ["Ideally", "Idealism", "Perfect"], ["Perfect", "Optimal", "Flawless", "Exemplary", "Prime"], ["Imperfect", "Flawed", "Unsuitable", "Defective"],
     "Sunny skies and a gentle coastal breeze created ideal conditions for the outdoor sailing regatta.",
     "The peaceful countryside cottage provided an ideal retreat for writing her upcoming book."),

    ("Ignite", "verb", "B2", "/ɪɡˈnaɪt/", "menyulut / memantik api atau kobaran semangat",
     "Menyalakan api atau membuat sesuatu terbakar; memicu ledakan emosi atau minat.",
     "Catch fire or cause to catch fire; arouse or provoke a strong emotion or passion.",
     ["Ignition", "Kindle", "Spark"], ["Kindle", "Spark", "Trigger", "Arouse", "Inflame"], ["Extinguish", "Quench", "Smother", "Douse"],
     "A single electric spark was sufficient to ignite the combustible gas mixture in the engine cylinder.",
     "Her impassioned speech on youth leadership helped ignite a national volunteer movement."),

    ("Illuminate", "verb", "B2", "/ɪˈluː.mɪ.neɪt/", "menerangi / menjelaskan secara gamblang",
     "Menyinari dengan cahaya terang; membuat suatu persoalan menjadi mudah dipahami.",
     "Light up; help to clarify or explain a subject and make it easily understood.",
     ["Illumination", "Illuminating", "Brighten"], ["Light up", "Brighten", "Clarify", "Elucidate", "Explicate"], ["Darken", "Obscure", "Confuse", "Cloud"],
     "Lanterns illuminated the cobblestone avenues during the midnight mid-autumn festival.",
     "The professor used vivid historical diagrams to illuminate the causes of the industrial revolution."),

    ("Illusion", "noun", "B2", "/ɪˈluː.ʒən/", "ilusi optik / khayalan semu tak nyata",
     "Sesuatu yang tampak nyata atau benar namun sebenarnya merupakan tipuan persepsi.",
     "A deceptive appearance or impression; a false idea or belief.",
     ["Illusory", "Illusionist", "Delusion"], ["Delusion", "Mirage", "Hallucination", "Fantasy", "Deception"], ["Reality", "Truth", "Actuality", "Fact"],
     "Mirrors placed along the studio walls created the optical illusion of a vast ballroom.",
     "Holding onto the illusion of effortless wealth without honest work leads to bitter disappointment."),

    ("Immense", "adjective", "B2", "/ɪˈmens/", "sangat besar luas / amat dahsyat tak terukur",
     "Sangat besar dalam ukuran, skala, cakupan, atau derajat kekuatan.",
     "Extremely large or great, especially in scale, degree, volume, or dimensions.",
     ["Immensely", "Immensity", "Vast"], ["Vast", "Gigantic", "Colossal", "Enormous", "Monumental"], ["Tiny", "Minute", "Microscopic", "Negligible"],
     "The deep ocean waters harbor immense untapped biological and geothermal resources.",
     "Volunteers showed immense courage when evacuating stranded residents during the sudden river flood."),

    ("Immune", "adjective", "B2", "/ɪˈmjuːn/", "kebal tahan penyakit / terlindung dari hukuman",
     "Memiliki ketahanan biologis terhadap infeksi tertentu; bebas dari tuntutan atau dampak buruk.",
     "Resistant to a particular infection or toxin; protected from a duty, penalty, or harm.",
     ["Immunity", "Immunize", "Resistant"], ["Resistant", "Protected", "Exempt", "Invulnerable", "Shielded"], ["Susceptible", "Vulnerable", "Exposed", "Prone"],
     "Vaccines stimulate antibodies, making the human body immune to dangerous viral pathogens.",
     "No economy is entirely immune to the ripple effects of global trade disruptions."),

    ("Impede", "verb", "C1", "/ɪmˈpiːd/", "menghambat laju / merintangi kemajuan",
     "Memperlambat atau menghalangi kemajuan atau pergerakan seseorang atau sesuatu.",
     "Delay or prevent someone or something by obstructing them; hinder progress.",
     ["Impediment", "Obstacle", "Hinder"], ["Hinder", "Obstruct", "Hamper", "Delay", "Block"], ["Facilitate", "Accelerate", "Assist", "Promote"],
     "Dense morning sea fog threatened to impede the safe navigation of cargo freighters.",
     "Excessive administrative bureaucracy should not impede the timely delivery of disaster relief."),

    ("Imperative", "adjective", "B2", "/ɪmˈper.ə.tɪv/", "sangat mendesak / wajib mutlak dilakukan",
     "Sangat penting dan krusial sehingga harus segera dilaksanakan tanpa penundaan.",
     "Of vital importance; crucial; an essential and urgent requirement.",
     ["Imperatively", "Essential", "Crucial"], ["Crucial", "Vital", "Essential", "Compulsory", "Urgent"], ["Optional", "Secondary", "Trivial", "Voluntary"],
     "Immediate international climate action is imperative to protect vulnerable coastal habitats.",
     "In emergency surgery, swift and decisive communication among medical personnel is imperative.")
]

print("Oxford Part 2 Extra dataset loaded with", len(OXFORD_PART2_EXTRA), "entries.")
