#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Rich Oxford 3000/5000 headwords for Part 4 (S - Z).
Contains 200+ distinct headwords with comprehensive linguistic data.
"""

SZ_WORDS_DATASET = [
    ("Sacred", "adjective", "B2", "/ˈseɪ.krɪd/", "suci sakral / sangat dikeramatkan dan dihormati",
     "Berhubungan dengan Tuhan atau agama; sangat dihormati dan tidak boleh dinodai.",
     "Connected with God or a god or dedicated to a religious purpose and so deserving veneration.",
     ["Sacrament", "Holy", "Consecrated"], ["Holy", "Sanctified", "Blessed", "Hallowed", "Divine"], ["Profane", "Secular", "Unholy"],
     "Pilgrims traveled thousands of miles to pray at the ancient sacred mountain temple.",
     "Freedom of religious belief is considered a sacred and inviolable constitutional right."),

    ("Sacrifice", "noun", "B1", "/ˈsæk.rɪ.faɪs/", "pengorbanan tulus / persembahan sukarela",
     "Tindakan merelakan sesuatu yang berharga demi tujuan yang lebih penting atau mulia.",
     "An act of giving up something valued for the sake of something else regarded as more important.",
     ["Sacrificial", "Self-sacrifice", "Offer"], ["Surrender", "Offering", "Renunciation", "Forfeiture", "Oblation"], ["Selfishness", "Greed"],
     "Parents often make enormous financial sacrifices to provide quality education for their children.",
     "The memorial monument honors the brave sacrifices made by firefighters in the line of duty."),

    ("Salient", "adjective", "C1", "/ˈseɪ.li.ənt/", "sangat menonjol / poin paling utama dan mencolok",
     "Paling kentara atau penting; mudah diperhatikan dalam suatu kumpulan data atau uraian.",
     "Most noticeable or important; prominent and conspicuous.",
     ["Salience", "Prominent", "Striking"], ["Prominent", "Striking", "Notable", "Conspicuous", "Key"], ["Inconspicuous", "Minor", "Unimportant"],
     "The professor summarized the salient points of the international monetary treaty in three slides.",
     "A salient feature of the new sports car is its ultra-lightweight aerodynamic carbon chassis."),

    ("Salvage", "verb", "B2", "/ˈsæl.vɪdʒ/", "menyelamatkan barang / mendaur ulang sisa reruntuhan",
     "Menyelamatkan barang-barang berharga dari kapal karam, kebakaran, atau reruntuhan.",
     "Rescue a wrecked or disabled ship or its cargo from loss at sea; retrieve or preserve.",
     ["Salvageable", "Rescue", "Recover"], ["Rescue", "Recover", "Retrieve", "Save", "Reclaim"], ["Abandon", "Scrap", "Lose"],
     "Specialized marine divers worked to salvage historical gold coins from the sunken colonial galleon.",
     "Engineers managed to salvage critical computer server hard drives from the flooded basement."),

    ("Sanctuary", "noun", "B2", "/ˈsæŋk.tʃu.ə.ri/", "suaka alam / tempat suci perlindungan",
     "Tempat perlindungan bagi satwa liar atau manusia yang terancam bahaya; ruang suci ibadah.",
     "A place of refuge or safety; a nature reserve for wildlife; a holy place.",
     ["Sanctify", "Haven", "Refuge"], ["Haven", "Refuge", "Oasis", "Preserve", "Asylum"], ["Danger zone", "Battleground"],
     "The tropical island serves as a protected national sanctuary for endangered orangutans.",
     "The quiet botanical garden was a peaceful sanctuary where she could read and relax."),

    ("Sanity", "noun", "B2", "/ˈsæn.ə.ti/", "kewarasan akal / pertimbangan akal sehat",
     "Kondisi memiliki pikiran yang sehat dan waras; kemampuan mengambil keputusan masuk akal.",
     "The ability to think and behave in a normal and rational manner; sound mental health.",
     ["Sane", "Rationality", "Lucidity"], ["Lucidity", "Rationality", "Reason", "Mental health", "Stability"], ["Insanity", "Madness", "Lunacy"],
     "Taking daily quiet walks in nature helped her preserve emotional sanity during high-stress projects.",
     "In moments of collective panic, voices of reason and sanity must guide public policy."),

    ("Saturate", "verb", "B2", "/ˈsætʃ.ər.eɪt/", "menjenuhkan / membasahi hingga kuyup",
     "Menyebabkan sesuatu menjadi basah kuyup; mengisi pasar hingga tidak dapat menyerap lagi.",
     "Cause something to become thoroughly soaked with liquid; supply a market beyond demand.",
     ["Saturation", "Soak", "Drench"], ["Soak", "Drench", "Imbue", "Steep", "Infuse"], ["Dry", "Dehydrate", "Drain"],
     "Heavy seasonal monsoon rains saturated the fertile agricultural fields along the riverbank.",
     "Smartphone manufacturers realized that metropolitan consumer markets had become fully saturated."),

    ("Savage", "adjective", "B2", "/ˈsæv.ɪdʒ/", "buas ganas / liar tak terkendali",
     "Sangat ganas, galak, dan tak terjinakkan; serangan atau kritik yang sangat keras.",
     "Fierce, violent, and uncontrolled; primitive and uncivilized.",
     ["Savagery", "Fierce", "Wild"], ["Fierce", "Ferocious", "Wild", "Brutal", "Vicious"], ["Tame", "Gentle", "Civilized", "Mild"],
     "The arctic expedition faced savage blizzard winds and sub-zero temperatures across the tundra.",
     "Film critics published savage reviews of the poorly produced historical drama."),

    ("Scandal", "noun", "B1", "/ˈskæn.dəl/", "skandal memalukan / kegemparan aib publik",
     "Tindakan atau peristiwa yang dianggap salah secara moral dan memicu kemarahan publik.",
     "An action or event regarded as morally or legally wrong and causing general public outrage.",
     ["Scandalous", "Disgrace", "Outrage"], ["Disgrace", "Shame", "Outrage", "Affair", "Dishonor"], ["Praise", "Honor", "Admiration"],
     "The political corruption scandal led to the immediate resignation of the regional governor.",
     "Investigative journalists exposed the corporate tax evasion scandal on the newspaper's front page."),

    ("Scholar", "noun", "B1", "/ˈskɒl.ər/", "cendekiawan / sarjana pakar akademis",
     "Orang terpelajar yang menguasai suatu cabang ilmu pengetahuan secara mendalam.",
     "A specialist in a particular branch of study, especially the humanities; a learned person.",
     ["Scholarly", "Scholarship", "Academic"], ["Academic", "Intellectual", "Researcher", "Professor", "Savant"], ["Illiterate", "Layperson"],
     "The distinguished Sanskrit scholar spent decades translating ancient philosophical poetry.",
     "University scholarships support promising young scholars from underprivileged rural districts."),

    ("Scope", "noun", "B2", "/skəʊp/", "ruang lingkup / cakupan batas kajian",
     "Luas atau batas dari suatu subjek, tindakan, atau peluang untuk melakukan sesuatu.",
     "The extent of the area or subject matter that something deals with or to which it is relevant.",
     ["Breadth", "Extent", "Range"], ["Range", "Extent", "Reach", "Breadth", "Sphere"], ["Narrowness", "Limitation"],
     "The environmental research report expanded its scope to include coastal mangrove degradation.",
     "There is ample scope for young software developers to innovate in artificial intelligence."),

    ("Secluded", "adjective", "B2", "/sɪˈkluː.dɪd/", "terpencil tenang / tersembunyi dari keramaian",
     "Terlindung dari pandangan umum atau tidak dikunjungi banyak orang; sunyi dan damai.",
     "Not seen or visited by many people; sheltered and private.",
     ["Seclusion", "Isolated", "Private"], ["Private", "Sheltered", "Retreated", "Solitary", "Hidden"], ["Crowded", "Public", "Exposed", "Bustling"],
     "They spent their summer vacation at a secluded wooden cabin tucked deep inside the pine forest.",
     "The secluded white-sand cove provided a peaceful haven for nesting endangered sea birds."),

    ("Secular", "adjective", "B2", "/ˈsek.jə.lər/", "sekuler duniawi / terpisah dari urusan agama",
     "Tidak terikat oleh urusan keagamaan atau spiritual; berkaitan dengan kehidupan duniawi.",
     "Denoting attitudes, activities, or other things that have no religious or spiritual basis.",
     ["Secularism", "Secularize", "Worldly"], ["Worldly", "Temporal", "Nonreligious", "Civil", "Lay"], ["Religious", "Sacred", "Spiritual", "Clerical"],
     "The modern democratic constitution guarantees a secular public education system for all citizens.",
     "Medieval historians distinguish between ecclesiastical cathedral music and secular folk ballads."),

    ("Sedate", "adjective", "C1", "/sɪˈdeɪt/", "tenang anggun / kalem tidak tergesa-gesa",
     "Tenang, bermartabat, dan tidak terburu-buru; membuat rileks dan mengantuk.",
     "Calm, dignified, and unhurried; quiet and rather dull.",
     ["Sedation", "Sedative", "Serene"], ["Calm", "Composed", "Tranquil", "Placid", "Staid"], ["Agitated", "Excited", "Wild", "Frantic"],
     "The elderly couple enjoyed a sedate evening stroll around the manicured rose garden.",
     "The doctor administered a mild medication to keep the anxious surgery patient calm and sedate."),

    ("Sedentary", "adjective", "B2", "/ˈsed.ən.tər.i/", "kurang bergerak / banyak duduk pasif",
     "Banyak duduk dan melakukan sedikit sekali aktivitas fisik atau olahraga.",
     "Tending to spend much time seated; somewhat inactive physically.",
     ["Inactive", "Sitting", "Stationary"], ["Inactive", "Desk-bound", "Sitting", "Stationary", "Passive"], ["Active", "Mobile", "Energetic", "Dynamic"],
     "Office workers with sedentary desk jobs are encouraged to take standing and walking breaks hourly.",
     "A sedentary lifestyle without aerobic exercise increases the risk of chronic cardiovascular disease."),

    ("Sediment", "noun", "B2", "/ˈsed.ɪ.mənt/", "endapan sedimen / lumpur dasar cairan",
     "Zat padat yang mengendap di dasar cairan; batuan atau pasir yang terbawa aliran air.",
     "Matter that settles to the bottom of a liquid; dregs; mineral matter deposited by water.",
     ["Sedimentary", "Sedimentation", "Deposit"], ["Deposit", "Dregs", "Residue", "Silt", "Sludge"], ["Liquid", "Solution"],
     "Rivers carry rich mineral sediment from the volcanic highlands to fertilize coastal delta plains.",
     "Allow the freshly brewed herbal tea to rest so the fine leaf sediment settles at the bottom."),

    ("Segregate", "verb", "B2", "/ˈseɡ.rɪ.ɡeɪt/", "memisahkan mengasingkan / memilah kelompok",
     "Menetapkan atau membagi orang atau benda menjadi kelompok terpisah menurut kriteria.",
     "Set apart from the rest or from each other; isolate or divide.",
     ["Segregation", "Separate", "Isolate"], ["Separate", "Isolate", "Divide", "Disconnect", "Dissociate"], ["Integrate", "Unite", "Combine", "Merge"],
     "Municipal waste collection systems require residents to segregate organic and recyclable trash.",
     "Civil rights movements fought courageously to outlaw laws that segregated public schools."),

    ("Seize", "verb", "B1", "/siːz/", "merebut menyita / memanfaatkan peluang dengan cepat",
     "Mengambil sesuatu dengan cepat dan paksa; menyita barang berdasarkan hukum; menangkap peluang.",
     "Take hold of suddenly and forcibly; take illegal or legal possession of; grasp an opportunity.",
     ["Seizure", "Grasp", "Capture"], ["Grasp", "Snatch", "Capture", "Confiscate", "Appropriate"], ["Release", "Relinquish", "Surrender", "Drop"],
     "Customs inspection officers seized counterfeit luxury goods at the international harbor terminal.",
     "Ambitious young entrepreneurs must seize emerging market opportunities in green technology."),

    ("Semester", "noun", "A2", "/sɪˈmes.tər/", "semester kuliah / paruh tahun akademik",
     "Jangka waktu enam bulan dalam tahun ajaran akademik di perguruan tinggi atau sekolah.",
     "A half-year term in a school or university, typically lasting fifteen to eighteen weeks.",
     ["Academic term", "Session", "Trimester"], ["Term", "Session", "Period", "Quarter", "Trimester"], ["N/A"],
     "Students registered for advanced statistical programming courses during the autumn semester.",
     "The university library extends its opening hours during the final semester exam weeks."),

    ("Serene", "adjective", "B2", "/səˈriːn/", "tenang tenteram / teduh tanpa riak keresahan",
     "Tenang, damai, dan tidak terganggu; cuaca yang cerah dan jernih tanpa badai.",
     "Calm, peaceful, and untroubled; tranquil and clear.",
     ["Serenity", "Serenely", "Tranquil"], ["Tranquil", "Peaceful", "Placid", "Calm", "Restful"], ["Agitated", "Turbulent", "Stormy", "Chaotic"],
     "The mountain monastery overlooked a serene valley bathed in golden early morning mist.",
     "Practicing deep breathing helps maintain a serene and balanced state of mind under pressure."),

    ("Sermon", "noun", "B2", "/ˈsɜː.mən/", "khotbah keagamaan / wejangan nasihat moral",
     "Ceramah tentang topik keagamaan atau moral, biasanya disampaikan di rumah ibadah.",
     "A talk on a religious or moral subject, especially one given during a church service.",
     ["Preach", "Homily", "Discourse"], ["Homily", "Preaching", "Discourse", "Address", "Oration"], ["Chatter"],
     "The congregation listened attentively to the pastor's inspiring Sunday morning sermon on compassion.",
     "Parents should lead by positive personal example rather than giving endless moral sermons to teens."),

    ("Shatter", "verb", "B2", "/ˈʃæt.ər/", "hancur berkeping-keping / memupuskan harapan",
     "Pecah mendadak menjadi pecahan-pecahan kecil; merusak atau menghancurkan impian total.",
     "Break or cause to break suddenly and violently into pieces; damage or destroy severely.",
     ["Shattered", "Splinter", "Fracture"], ["Splinter", "Smash", "Fracture", "Crush", "Destroy"], ["Mend", "Repair", "Restore", "Heal"],
     "The crystal glass slipped from his fingers and shattered into a hundred fragments on the floor.",
     "The sudden disqualification shattered the Olympic sprinter's lifelong dream of winning gold."),

    ("Shimmer", "verb", "B2", "/ˈʃɪm.ər/", "berkilauan lembut / memancarkan kerlipan riak cahaya",
     "Bersinar dengan cahaya lembut yang tampak bergetar atau beriak halus.",
     "Shine with a soft, slightly wavering light.",
     ["Shimmering", "Glimmer", "Glitter"], ["Glimmer", "Glisten", "Twinkle", "Sparkle", "Gleam"], ["Darken", "Fade"],
     "The moonlight shimmered across the calm turquoise waters of the secluded tropical bay.",
     "Her evening silk dress shimmered softly under the gentle ambient lights of the grand ballroom."),

    ("Shortage", "noun", "B1", "/ˈʃɔː.tɪdʒ/", "kelangkaan pasokan / defisit kekurangan barang",
     "Keadaan di mana sesuatu yang dibutuhkan tidak dapat diperoleh dalam jumlah yang memadai.",
     "A state or situation in which something needed cannot be obtained in sufficient amounts.",
     ["Short", "Deficit", "Scarcity"], ["Scarcity", "Deficit", "Lack", "Dearth", "Paucity"], ["Abundance", "Surplus", "Excess", "Glut"],
     "Severe drought caused an acute drinking water shortage across several agricultural provinces.",
     "The hospital recruited international nurses to address the regional medical staffing shortage."),

    ("Shred", "noun", "B2", "/ʃred/", "potongan kecil carik / secuil bukti",
     "Secarik atau potongan kecil yang dirobek atau dipotong dari sesuatu; jumlah yang sangat kecil.",
     "A strip of some material, such as paper, cloth, or food, that has been torn or cut off.",
     ["Shredder", "Scrap", "Sliver"], ["Scrap", "Sliver", "Fragment", "Particle", "Tidbit"], ["Whole", "Mass"],
     "The forensic auditor found a shredded financial receipt that revealed the illicit payment.",
     "There was not a single shred of credible evidence supporting the wild conspiracy theory."),

    ("Shrewd", "adjective", "B2", "/ʃruːd/", "cerdik piawai / tajam pertimbangan bisnisnya",
     "Memiliki atau menunjukkan penilaian yang tajam, praktis, dan cerdik dalam mengambil keputusan.",
     "Having or showing sharp powers of judgment; astute and piercingly practical.",
     ["Shrewdness", "Shrewdly", "Astute"], ["Astute", "Sharp", "Sagacious", "Clever", "Discerning"], ["Naive", "Foolish", "Gullible", "Slow"],
     "Through shrewd real estate acquisitions, the entrepreneur built a thriving commercial portfolio.",
     "She gave a shrewd assessment of the competitor's vulnerabilities during the board meeting."),

    ("Shudder", "verb", "B2", "/ˈʃʌd.ər/", "bergidik gemetar / menggigil karena ngeri",
     "Gemetar hebat karena rasa dingin, takut, atau jijik yang mendalam.",
     "Tremble convulsively, typically as a result of fear, revulsion, or cold.",
     ["Tremble", "Quiver", "Shiver"], ["Shiver", "Quiver", "Tremble", "Quake", "Flinch"], ["Steady", "Calm"],
     "She shuddered with cold as icy arctic winds blew through the drafty cabin door.",
     "I still shudder at the terrifying memory of the near-miss traffic collision on the icy bridge."),

    ("Sibling", "noun", "A2", "/ˈsɪb.lɪŋ/", "saudara kandung / kakak atau adik sekandung",
     "Saudara laki-laki atau perempuan yang memiliki orang tua yang sama.",
     "Each of two or more children or offspring having one or both parents in common; a brother or sister.",
     ["Brother", "Sister", "Kin"], ["Brother", "Sister", "Kin", "Relative"], ["Stranger"],
     "Growing up with three siblings taught him the value of sharing, patience, and team play.",
     "The two siblings established a successful boutique graphic design studio together in Bandung."),

    ("Simulate", "verb", "B2", "/ˈsɪm.jə.leɪt/", "mensimulasikan / menirukan kondisi nyata",
     "Meniru penampilan, karakter, atau kondisi suatu sistem untuk tujuan pengujian atau pelatihan.",
     "Imitate the appearance or character of; produce a computer model of.",
     ["Simulation", "Simulator", "Mimic"], ["Mimic", "Imitate", "Replicate", "Model", "Emulate"], ["Differentiate", "Realize"],
     "Flight simulators allow trainee pilots to practice emergency landing procedures safely.",
     "Computer algorithms simulate global climate patterns to forecast extreme atmospheric storms."),

    ("Sincere", "adjective", "B1", "/sɪnˈsɪər/", "tulus ikhlas / jujur tanpa kepura-puraan",
     "Bebas dari kepura-puraan atau kemunafikan; tulus dan jujur dari lubuk hati terdalam.",
     "Free from pretense or deceit; proceeding from genuine feelings.",
     ["Sincerely", "Sincerity", "Genuine"], ["Genuine", "Honest", "Heartfelt", "Truthful", "Candid"], ["Insincere", "Hypocritical", "Deceitful", "Fake"],
     "Please accept our sincere gratitude for your generous support during our community rebuild.",
     "Her warm eyes and sincere apology quickly reconciled the strained friendship between the colleagues."),

    ("Singular", "adjective", "B2", "/ˈsɪŋ.ɡjə.lər/", "tunggal / luar biasa istimewa tiada duanya",
     "Bentuk gramatikal tunggal; sangat luar biasa, unik, atau menonjol secara istimewa.",
     "Form of a word referring to one person or thing; exceptionally good or remarkable; unique.",
     ["Singularity", "Unique", "Remarkable"], ["Unique", "Exceptional", "Extraordinary", "Distinctive", "Sole"], ["Plural", "Ordinary", "Commonplace"],
     "The prima ballerina possessed a singular talent for expressing dramatic emotion through movement.",
     "In English syntax, a singular subject requires a singular verb form in the present tense."),

    ("Sinister", "adjective", "B2", "/ˈsɪn.ɪ.stər/", "jahat menyeramkan / memberi firasat celaka",
     "Memberi kesan bahwa sesuatu yang jahat, berbahaya, atau mengerikan sedang mengancam.",
     "Giving the impression that something harmful or evil is happening or will happen; menacing.",
     ["Sinisterly", "Menacing", "Evil"], ["Menacing", "Ominous", "Malevolent", "Threatening", "Dark"], ["Innocent", "Benevolent", "Auspicious", "Friendly"],
     "The abandoned gothic mansion cast a sinister shadow across the foggy cobblestone lane.",
     "Cybersecurity investigators uncovered a sinister plot to disrupt the regional electrical power grid."),

    ("Skeleton", "noun", "A2", "/ˈskel.ə.tən/", "rangka tulang / kerangka dasar penopang",
     "Kerangka tulang internal yang menopang dan melindungi tubuh manusia atau hewan.",
     "An internal or external framework of bone, cartilage, or other rigid material supporting the body.",
     ["Skeletal", "Framework", "Bones"], ["Framework", "Bones", "Scaffold", "Structure", "Armature"], ["Flesh"],
     "The biology classroom has a full-scale anatomical model of the human skeleton.",
     "Archaeologists excavated the fossilized skeleton of a prehistoric predatory dinosaur in the quarry."),

    ("Skepticism", "noun", "B2", "/ˈskep.tɪ.sɪ.zəm/", "skeptisisme / sikap kritis penuh keraguan",
     "Sikap meragukan kebenaran suatu klaim atau teori sampai ada bukti empiris yang memadai.",
     "A skeptical attitude; doubt as to the truth of something; philosophy questioning knowledge.",
     ["Skeptic", "Skeptical", "Doubt"], ["Doubt", "Disbelief", "Incredulity", "Suspicion", "Cynicism"], ["Credulity", "Faith", "Belief", "Certainty"],
     "Scientists greeted the extraordinary cold fusion energy claims with healthy skepticism and demanded trials.",
     "A healthy dose of journalistic skepticism is essential when investigating political advertisements."),

    ("Slaughter", "verb", "B2", "/ˈslɔː.tər/", "menyembelih hewan ternak / membantai massal",
     "Memotong hewan untuk diambil dagingnya; membunuh banyak orang atau hewan secara kejam.",
     "Kill animals for food; kill people or animals in a cruel or violent way, typically in large numbers.",
     ["Slaughterhouse", "Butcher", "Carnage"], ["Butcher", "Massacre", "Slay", "Execute", "Annihilate"], ["Preserve", "Protect", "Save"],
     "Livestock must be slaughtered humanely according to strict hygiene and animal welfare regulations.",
     "Historians documented the horrific wartime slaughter that devastated ancient Mediterranean cities."),

    ("Slender", "adjective", "B1", "/ˈslen.dər/", "ramping semampai / tipis sedikit",
     "Ramping dan anggun bentuk tubuhnya; sangat sedikit atau tipis peluangnya.",
     "Gracefully thin; slender in build; barely sufficient in amount or size.",
     ["Slenderness", "Slim", "Lean"], ["Slim", "Lean", "Svelte", "Delicate", "Meager"], ["Plump", "Fat", "Thick", "Stocky"],
     "The tall, slender bamboo stalks swayed gracefully in the gentle afternoon breeze.",
     "With only one minute remaining, the trailing basketball team had a slender chance of victory."),

    ("Solitary", "adjective", "B2", "/ˈsɒl.ɪ.tər.i/", "menyendiri / terasing sebatang kara",
     "Dilakukan atau ada sendirian tanpa teman; menyukai kesendirian atau terpencil letaknya.",
     "Done or existing alone; living alone or tending to avoid the company of others.",
     ["Solitude", "Alone", "Isolated"], ["Alone", "Lonely", "Isolated", "Single", "Secluded"], ["Social", "Gregarious", "Accompanied", "Crowded"],
     "A solitary eagle soared high above the snow-capped crags of the Rocky Mountains.",
     "He enjoyed solitary walks along the misty shore to clear his thoughts after a busy work week."),

    ("Solitude", "noun", "B2", "/ˈsɒl.ɪ.tjuːd/", "kesendirian tenang / ketenteraman sunyi",
     "Keadaan menyendiri atau hidup terpencil, seringkali dirasakan sebagai sesuatu yang menenangkan.",
     "The state or situation of being alone, especially a pleasant and peaceful one.",
     ["Solitary", "Seclusion", "Peace"], ["Seclusion", "Privacy", "Isolation", "Peace", "Quiet"], ["Crowd", "Company", "Society"],
     "She cherished the peaceful morning solitude of her garden before the household awoke.",
     "Many great poets and philosophers sought deep solitude in mountain cabins to write their masterpieces."),

    ("Sombre", "adjective", "B2", "/ˈsɒm.bər/", "suram kelam / bernuansa khidmat muram",
     "Gelap atau suram warnanya; memiliki suasana yang serius, muram, dan penuh duka.",
     "Dark or dull in color or tone; gloomy; solemnly grave in character.",
     ["Somberly", "Gloomy", "Grave"], ["Gloomy", "Grave", "Solemn", "Melancholy", "Dismal"], ["Bright", "Cheerful", "Joyful", "Lively"],
     "Mourners dressed in sombre black attire gathered quietly for the cathedral memorial service.",
     "A sombre mood settled over the conference room as the company announced financial restructuring."),

    ("Spark", "noun", "B1", "/spɑːk/", "percikan api / pemantik inspirasi kilat",
     "Partikel pijar kecil menyala yang terlempar dari api; sesuatu yang memicu peristiwa besar.",
     "A small fiery particle thrown off from a fire, engine, or electrical device; a flash of inspiration.",
     ["Sparkle", "Kindle", "Flash"], ["Flash", "Flicker", "Glimmer", "Trigger", "Inspiration"], ["Extinction"],
     "A stray electrical spark ignited dry brush along the edge of the arid highway.",
     "The child's early curiosity about stars was the spark that ignited a lifelong career in astronomy."),

    ("Specialize", "verb", "B1", "/ˈspeʃ.əl.aɪz/", "berspesialisasi / mendalami keahlian khusus",
     "Memusatkan perhatian dan usaha pada bidang studi, profesi, atau keterampilan tertentu.",
     "Concentrate on and become expert in a particular subject or skill.",
     ["Specialist", "Specialization", "Expert"], ["Focus", "Concentrate", "Major in", "Hone", "Narrow down"], ["Diversify", "Generalize"],
     "After completing medical school, the young doctor decided to specialize in pediatric cardiology.",
     "The boutique law firm specializes in international intellectual property and copyright protection."),

    ("Spectacular", "adjective", "B1", "/spekˈtæk.jə.lər/", "spektakuler megah / memukau luar biasa",
     "Sangat dramatis, memukau mata, dan mengesankan untuk disaksikan penonton.",
     "Beautiful in a dramatic and eye-catching way; striking and sensational.",
     ["Spectacle", "Spectacularly", "Stunning"], ["Stunning", "Breathtaking", "Dazzling", "Magnificent", "Sensational"], ["Unimpressive", "Dull", "Ordinary", "Bland"],
     "The New Year fireworks display over Sydney Harbour was a spectacular visual feast.",
     "From the airplane window, passengers witnessed a spectacular sunrise over the snowy Alps."),

    ("Spectator", "noun", "B1", "/spekˈteɪ.tər/", "penonton pertandingan / saksi mata di stadion",
     "Seseorang yang menonton pertunjukan, pertandingan olahraga, atau peristiwa publik.",
     "A person who watches at a show, game, or other public event.",
     ["Spectate", "Viewer", "Onlooker"], ["Onlooker", "Viewer", "Watcher", "Observer", "Bystander"], ["Participant", "Player", "Performer"],
     "Over eighty thousand cheering spectators packed the national Olympic stadium for the soccer final.",
     "The colorful street carnival attracted thousands of enthusiastic local and international spectators."),

    ("Spectrum", "noun", "B2", "/ˈspek.trəm/", "spektrum warna gelombang / rentang ragam luas",
     "Pita warna yang dihasilkan dari pembiasan cahaya; rentang luas dari kondisi atau gagasan.",
     "A band of colors, as seen in a rainbow, produced by separation of light; broad range of conditions.",
     ["Spectroscopy", "Range", "Continuum"], ["Range", "Continuum", "Gamut", "Span", "Scale"], ["Point", "Monolith"],
     "A glass prism separates white sunlight into the rich visible color spectrum from violet to red.",
     "The international symposium welcomed speakers from across the entire political and economic spectrum."),

    ("Sphere", "noun", "B1", "/sfɪər/", "bola bundar / ranah lingkup pengaruh",
     "Benda bulat sempurna seperti bola; bidang kegiatan, minat, atau pengaruh kekuasaan.",
     "A round solid figure whose surface is everywhere equidistant from its center; an area of activity.",
     ["Spherical", "Atmosphere", "Domain"], ["Globe", "Orb", "Domain", "Realm", "Arena"], ["Plane", "Cube"],
     "The Earth is not a flat disc but a slightly oblate planetary sphere orbiting the Sun.",
     "She is widely recognized as an influential thought leader in the sphere of international education."),

    ("Spiral", "noun", "B2", "/ˈspaɪə.rəl/", "spiral berpilin / pola melingkar berputar",
     "Bentuk melengkung yang berputar mengelilingi titik pusat sambil terus menjauh atau mendekat.",
     "A curve which winds round a fixed center point at a continuously increasing or decreasing distance.",
     ["Spiraling", "Helix", "Coil"], ["Helix", "Coil", "Corkscrew", "Whirl", "Vortex"], ["Straight line"],
     "The nautilus seashell exhibits a mathematically perfect logarithmic golden spiral in its chambers.",
     "The historic medieval cathedral features a steep stone spiral staircase leading to the bell tower."),

    ("Spiritual", "adjective", "B1", "/ˈspɪr.ɪ.tʃu.əl/", "spiritual rohani / berkaitan dengan jiwa batin",
     "Berkaitan dengan jiwa, roh, atau nilai-nilai keagamaan daripada hal-hal materi duniawi.",
     "Relating to or affecting the human spirit or soul as opposed to material or physical things.",
     ["Spirituality", "Spiritually", "Sacred"], ["Sacred", "Divine", "Holy", "Incorporeal", "Soulful"], ["Material", "Physical", "Secular", "Corporeal"],
     "Many travelers visit the ancient mountain shrines seeking quiet spiritual peace and renewal.",
     "Traditional acoustic flute music holds deep spiritual significance for indigenous island communities."),

    ("Splendid", "adjective", "B1", "/ˈsplen.dɪd/", "sangat indah megah / luar biasa hebat mengagumkan",
     "Sangat luar biasa megah, mempesona, atau menyenangkan hati orang yang melihat.",
     "Magnificent; very impressive; excellent, fine, or very satisfactory.",
     ["Splendor", "Splendidly", "Magnificent"], ["Magnificent", "Glorious", "Superb", "Grand", "Marvelous"], ["Dull", "Poor", "Terrible", "Awful"],
     "The hotel balcony offered a splendid panoramic view of the golden sunset over the bay.",
     "The young orchestra musicians gave a splendid performance of Beethoven's Fifth Symphony."),

    ("Spontaneous", "adjective", "B2", "/spɒnˈteɪ.ni.əs/", "spontan serta-merta / terjadi alami tanpa rencana",
     "Terjadi atau dilakukan sebagai hasil dari dorongan mendadak tanpa direncanakan sebelumnya.",
     "Performed or occurring as a result of a sudden impulse or inclination and without premeditation.",
     ["Spontaneously", "Spontaneity", "Impulsive"], ["Impulsive", "Unplanned", "Natural", "Instinctive", "Unprompted"], ["Planned", "Premeditated", "Rehearsed", "Forced"],
     "The audience broke into spontaneous standing applause as the violinist finished the difficult cadenza.",
     "Spontaneous weekend camping road trips often create the most joyful and memorable family stories."),

    ("Sporadic", "adjective", "B2", "/spəˈræd.ɪk/", "sporadis jarang-jarang / terjadi tidak teratur",
     "Terjadi pada interval yang tidak teratur atau hanya di beberapa tempat terpisah.",
     "Occurring at irregular intervals or only in a few places; scattered or isolated.",
     ["Sporadically", "Occasional", "Intermittent"], ["Intermittent", "Occasional", "Infrequent", "Scattered", "Irregular"], ["Continuous", "Constant", "Regular", "Steady"],
     "The coastal weather forecast warned of sporadic heavy thunderstorms throughout the afternoon.",
     "The rebel forces engaged in sporadic skirmishes before peace negotiations were formally launched."),

    ("Spouse", "noun", "B1", "/spaʊs/", "pasangan hidup / suami atau istri sah",
     "Suami atau istri yang terikat dalam pernikahan yang sah secara hukum dan agama.",
     "A husband or wife, considered in relation to their partner.",
     ["Espousal", "Husband", "Wife"], ["Partner", "Husband", "Wife", "Mate", "Companion"], ["Single"],
     "Employees may enroll their legal spouse and dependent children in the company medical health insurance.",
     "She expressed sincere gratitude to her loving spouse for supporting her through doctoral research."),

    ("Sprinkle", "verb", "B1", "/ˈsprɪŋ.kəl/", "menaburkan / memercikkan butiran halus",
     "Menyebarkan butiran kecil atau tetesan cairan secara merata di atas permukaan sesuatu.",
     "Scatter or pour small drops or particles of a substance over an object or surface.",
     ["Sprinkler", "Scatter", "Dust"], ["Scatter", "Dust", "Spray", "Strew", "Drizzle"], ["Gather", "Collect"],
     "Sprinkle freshly chopped basil and parmesan cheese over the pasta before serving.",
     "A gentle spring shower sprinkled tiny water droplets across the blossoming cherry petals."),

    ("Sprout", "verb", "B2", "/spraʊt/", "bertunas berkecambah / tumbuh bermunculan pesat",
     "Mulai tumbuh tunas dari benih tanaman; mulai berkembang atau muncul dalam jumlah banyak.",
     "Of a plant, put out shoots; begin to grow; grow or develop rapidly in large numbers.",
     ["Sprout", "Germinate", "Shoot"], ["Germinate", "Bud", "Shoot", "Spring up", "Emerge"], ["Wither", "Die", "Decay"],
     "With fertile soil and regular watering, sunflower seeds will sprout within five to seven days.",
     "Dozens of trendy boutique coffee shops have sprouted across the creative downtown quarter."),

    ("Stabilize", "verb", "B2", "/ˈsteɪ.bə.laɪz/", "menstabilkan / memulihkan kestabilan kondisi",
     "Membuat sesuatu menjadi stabil, teguh, tidak mudah berguncang atau berubah drastis.",
     "Make or become unlikely to change, fail, or decline; steady.",
     ["Stability", "Stable", "Steady"], ["Steady", "Secure", "Balance", "Anchor", "Firm up"], ["Destabilize", "Disrupt", "Shake", "Fluctuate"],
     "Emergency paramedics worked swiftly to stabilize the injured driver's vital signs at the scene.",
     "Central bank monetary policies aim to stabilize domestic currency values and curb inflation."),

    ("Stagnant", "adjective", "B2", "/ˈstæɡ.nənt/", "menggenang terhenti / stagnan tanpa kemajuan",
     "Air yang tidak mengalir dan seringkali berbau; situasi ekonomi yang tidak berkembang maju.",
     "Of a body of water or the atmosphere of a confined space, having no current or flow; sluggish.",
     ["Stagnate", "Stagnation", "Motionless"], ["Motionless", "Static", "Dormant", "Sluggish", "Inactive"], ["Flowing", "Dynamic", "Vibrant", "Growing"],
     "Mosquitoes breed rapidly in stagnant water pools left in discarded plastic containers.",
     "Without technological innovation and capital investment, national industrial output remained stagnant."),

    ("Stamina", "noun", "B2", "/ˈstæm.ɪ.nə/", "stamina daya tahan / kekuatan fisik dan mental bertahan",
     "Kekuatan fisik atau mental yang memungkinkan seseorang bertahan dalam upaya lama.",
     "The ability to sustain prolonged physical or mental effort; endurance.",
     ["Endurance", "Resilience", "Vigor"], ["Endurance", "Resilience", "Fortitude", "Vigor", "Energy"], ["Weakness", "Lethargy", "Fatigue", "Frailty"],
     "Training for a marathon builds cardiovascular endurance and mental stamina over months.",
     "Surgeons require exceptional stamina to maintain steady precision during ten-hour operations."),

    ("Stance", "noun", "B2", "/stɑːns/", "posisi kuda-kuda / sikap pandangan resmi",
     "Cara berdiri atau posisi tubuh; sikap mental atau pandangan resmi terhadap suatu isu.",
     "The way in which someone stands, especially when playing a sport; an attitude or viewpoint.",
     ["Posture", "Attitude", "Position"], ["Posture", "Attitude", "Standpoint", "Position", "Viewpoint"], ["Indifference"],
     "The martial arts instructor corrected the student's defensive stance to improve balance.",
     "The foreign ministry maintained a resolute diplomatic stance against unilateral trade sanctions."),

    ("Staple", "noun", "B1", "/ˈsteɪ.pəl/", "makanan pokok utama / komoditas primer",
     "Makanan utama yang dikonsumsi secara rutin; barang atau komponen penting yang esensial.",
     "A main or important element of something, especially of a diet or commercial trade.",
     ["Basic", "Essential", "Foundation"], ["Basic", "Essential", "Primary food", "Cornerstone", "Pillar"], ["Luxury", "Extra"],
     "Rice is the dietary staple for billions of people across Asia and the Pacific islands.",
     "Plain white t-shirts and denim jeans are enduring wardrobe staples for casual wear."),

    ("Startling", "adjective", "B2", "/ˈstɑː.tlɪŋ/", "sangat mengejutkan / menggemparkan tak terduga",
     "Sangat mengejutkan, mencengangkan, atau menarik perhatian seketika karena keanehannya.",
     "Very surprising, astonishing, or remarkable in an alarming or striking way.",
     ["Startle", "Startled", "Astonishing"], ["Astonishing", "Shocking", "Stunning", "Alarming", "Unexpected"], ["Predictable", "Ordinary", "Expected", "Calm"],
     "The biological survey revealed a startling decline in native honeybee populations across the valley.",
     "She made the startling discovery that the antique wooden desk concealed a secret compartment."),

    ("Static", "adjective", "B2", "/ˈstæt.ɪk/", "statis diam / tidak bergerak atau berubah",
     "Kurang bergerak, bertindak, atau berubah; listrik statis yang tidak mengalir dalam sirkuit.",
     "Lacking in movement, action, or change, especially in a desirable way; stationary.",
     ["Stationary", "Immobile", "Fixed"], ["Stationary", "Immobile", "Fixed", "Unchanging", "Constant"], ["Dynamic", "Fluid", "Mobile", "Changing"],
     "In a fast-evolving digital world, business models cannot remain static if they wish to survive.",
     "Rubbing a rubber balloon on wool creates static electrical attraction that lifts human hair."),

    ("Statistic", "noun", "A2", "/stəˈtɪs.tɪk/", "data statistik / angka fakta kuantitatif",
     "Fakta atau data numerik dari studi sampel besar; cabang matematika pengolahan data.",
     "A fact or piece of data from a study of a large quantity of numerical data.",
     ["Statistical", "Statistician", "Data"], ["Figure", "Datum", "Metric", "Number", "Measure"], ["Anecdote"],
     "According to government statistics, youth unemployment declined by three percent this quarter.",
     "Descriptive statistics summarize raw survey findings into clear charts and averages."),

    ("Statute", "noun", "C1", "/ˈstætʃ.uːt/", "undang-undang tertulis / statut hukum resmi",
     "Hukum tertulis yang disahkan oleh badan legislatif parlemen negara.",
     "A written law passed by a legislative body; an official rule of an institution.",
     ["Statutory", "Legislation", "Act"], ["Act", "Law", "Ordinance", "Decree", "Enactment"], ["Custom", "Tradition"],
     "Under federal environmental statutes, industrial polluters face heavy fines and remediation orders.",
     "The university statute regulates academic accreditation, faculty tenure, and student conduct."),

    ("Steadfast", "adjective", "C1", "/ˈsted.fɑːst/", "teguh setia / pantang goyah dalam komitmen",
     "Teguh berpegang pada tujuan, keyakinan, atau kesetiaan tanpa pernah goyah.",
     "Resolutely or dutifully firm and unwavering; loyal and constant.",
     ["Steadfastly", "Loyal", "Firm"], ["Unwavering", "Loyal", "Faithful", "Resolute", "Dedicated"], ["Fickle", "Unfaithful", "Wavering", "Irresolute"],
     "Throughout years of political hardship, she remained a steadfast advocate for human dignity.",
     "Their steadfast friendship endured across decades and thousands of miles of separation."),

    ("Stimulate", "verb", "B2", "/ˈstɪm.jə.leɪt/", "menstimulasi / merangsang gairah pertumbuhan",
     "Mendorong perkembangan atau peningkatan aktivitas pada suatu proses, indra, atau organ.",
     "Raise levels of physiological or nervous activity; encourage development of an activity.",
     ["Stimulation", "Stimulant", "Arouse"], ["Arouse", "Inspire", "Galvanize", "Invigorate", "Provoke"], ["Dampen", "Depress", "Inhibit", "Stifle"],
     "Interactive puzzles and reading games stimulate intellectual curiosity in preschool children.",
     "Lowering central bank lending rates helps stimulate commercial borrowing and capital investment."),

    ("Stipulate", "verb", "C1", "/ˈstɪp.jə.leɪt/", "mensyaratkan / menetapkan klausul mutlak",
     "Menuntut atau menentukan suatu persyaratan sebagai bagian dari kesepakatan atau kontrak.",
     "Demand or specify a requirement, typically as part of a bargain or agreement.",
     ["Stipulation", "Specify", "Require"], ["Specify", "Require", "Prescribe", "Demand", "Condition"], ["Waive", "Overlook", "Ignore"],
     "The construction contract stipulates that all structural steel must meet international earthquake codes.",
     "Company policy stipulates that travel expense receipts must be submitted within thirty days."),

    ("Straightforward", "adjective", "B2", "/ˌstreɪtˈfɔː.wəd/", "lugas jelas / jujur dan mudah dipahami",
     "Tidak rumit dan mudah dipahami; jujur dan terus terang tanpa berbelit-belit.",
     "Uncomplicated and easy to do or understand; honest and frank.",
     ["Straightforwardly", "Direct", "Simple"], ["Simple", "Direct", "Candid", "Uncomplicated", "Clear-cut"], ["Complicated", "Ambiguous", "Devious", "Intricate"],
     "The user manual provides straightforward step-by-step instructions for assembling the bookshelf.",
     "I appreciate her straightforward communication style; she always speaks honestly and respectfully."),

    ("Strenuous", "adjective", "B2", "/ˈstren.ju.əs/", "menguras tenaga / berat membutuhkan kerja keras",
     "Membutuhkan atau menggunakan banyak tenaga fisik atau mental; penuh semangat membara.",
     "Requiring or using great exertion; arduous, strenuous, and demanding.",
     ["Strenuously", "Arduous", "Demanding"], ["Arduous", "Demanding", "Exhausting", "Taxing", "Tough"], ["Easy", "Effortless", "Light", "Relaxed"],
     "Hikers rested at the alpine shelter after a strenuous six-hour trek up the steep rocky ridge.",
     "The defense lawyer made a strenuous objection against the introduction of unverified hearsay."),

    ("Stride", "noun", "B2", "/straɪd/", "langkah panjang tegap / kemajuan lompatan besar",
     "Langkah panjang yang mantap dan tegas; langkah kemajuan yang signifikan menuju tujuan.",
     "A long, decisive step; a significant step in the progress toward an aim.",
     ["Stride", "Pace", "Progress"], ["Pace", "Step", "Progress", "Advancement", "Leap"], ["Regression", "Stumble"],
     "She walked into the conference auditorium with a confident, purposeful stride.",
     "Medical science has made remarkable strides in developing targeted immunotherapies for cancer."),

    ("Strive", "verb", "B2", "/straɪv/", "berjuang keras / berikhtiar sekuat tenaga",
     "Berusaha dengan sungguh-sungguh dan gigih untuk mencapai atau mendapatkan sesuatu.",
     "Make great efforts to achieve or obtain something; struggle or fight vigorously.",
     ["Striving", "Strive", "Endeavor"], ["Endeavor", "Struggle", "Labor", "Aim", "Aspire"], ["Slacken", "Surrender", "Idle"],
     "We must continually strive for professional excellence and ethical integrity in all endeavors.",
     "Educators strive to create inclusive classroom environments where every child feels valued."),

    ("Stubborn", "adjective", "B1", "/ˈstʌb.ən/", "keras kepala bersikukuh / sulit diatasi",
     "Bersikukuh tidak mau mengubah pendirian atau sikapnya; masalah atau noda yang sukar hilang.",
     "Having or showing dogged determination not to change one's attitude or position; obstinate.",
     ["Stubbornness", "Obstinate", "Headstrong"], ["Obstinate", "Headstrong", "Tenacious", "Inflexible", "Pigheaded"], ["Flexible", "Pliant", "Docile", "Accommodating"],
     "He was too stubborn to admit his navigation mistake until the car ran completely out of fuel.",
     "Use concentrated warm lemon water to lift stubborn tea stains from porcelain mugs."),

    ("Subdue", "verb", "B2", "/səbˈdʒuː/", "menaklukkan / meredakan gejolak emosi kemarahan",
     "Mengatasi, menenangkan, atau mengendalikan seseorang atau perasaan dengan kekuatan.",
     "Overcome, quieten, or bring under control a feeling, person, or group.",
     ["Subdued", "Suppress", "Conquer"], ["Conquer", "Tame", "Vanquish", "Quell", "Repress"], ["Inflame", "Incite", "Provoke", "Surrender"],
     "Trained security personnel acted swiftly to subdue the unruly intruder without causing harm.",
     "Taking deep, slow breaths helped her subdue her rising anxiety before delivering the speech."),

    ("Sublime", "adjective", "C1", "/səˈblaɪm/", "sangat agung luhur / menakjubkan tak terlukiskan",
     "Memiliki keagungan, keelokan, atau nilai spiritual yang membangkitkan kekaguman mendalam.",
     "Of very great excellence or beauty; inspiring great admiration or awe.",
     ["Sublimely", "Sublimity", "Transcendent"], ["Transcendent", "Magnificent", "Exquisite", "Noble", "Elevated"], ["Abysmal", "Ordinary", "Crude", "Trivial"],
     "Gazing at the Milky Way galaxy from the silent desert was a sublime spiritual experience.",
     "Mozart's Requiem contains sublime choral harmonies that continue to move audiences globally."),

    ("Subsequent", "adjective", "B2", "/ˈsʌb.sɪ.kwənt/", "berikutnya menyusul / terjadi setelahnya",
     "Datang setelah sesuatu dalam waktu; menyusul setelah peristiwa sebelumnya.",
     "Coming after something in time; following.",
     ["Subsequently", "Following", "Successive"], ["Following", "Successive", "Consequent", "Later", "Next"], ["Previous", "Prior", "Preceding", "Earlier"],
     "The initial prototype failed laboratory stress tests, but subsequent versions proved durable.",
     "She graduated with honors and subsequently secured a research fellowship in Cambridge."),

    ("Subside", "verb", "B2", "/səbˈsaɪd/", "mereda menyusut / berangsur-angsur tenang",
     "Menjadi kurang kuat, keras, atau aktif; surutnya genangan air atau amarah.",
     "Become less intense, violent, or severe; of water, go down to a lower level.",
     ["Subsidence", "Abate", "Recede"], ["Abate", "Recede", "Wane", "Dwindle", "Diminish"], ["Surge", "Intensify", "Rise", "Escalate"],
     "We waited inside the timber lodge until the violent thunderstorm winds began to subside.",
     "Pain medication helped the acute toothache pain subside so the patient could sleep peacefully."),

    ("Subsidy", "noun", "B2", "/ˈsʌb.sɪ.di/", "subsidi bantuan dana / tunjangan pemerintah",
     "Bantuan uang yang diberikan oleh pemerintah untuk menjaga harga barang tetap terjangkau.",
     "A sum of money granted by the government to assist an industry or business so prices remain low.",
     ["Subsidize", "Grant", "Allowance"], ["Grant", "Allowance", "Aid", "Contribution", "Support"], ["Tax", "Levy", "Fine"],
     "Government subsidies for rooftop solar panel installations encourage green energy adoption.",
     "Agricultural subsidies help family farmers withstand volatile global commodity price swings."),

    ("Substantial", "adjective", "B2", "/səbˈstæn.ʃəl/", "berjumlah besar signifikan / kokoh berbobot",
     "Berjumlah, bernilai, atau penting dalam skala yang besar; memiliki struktur fisik kokoh.",
     "Of considerable importance, size, or worth; strongly built or made.",
     ["Substantially", "Considerable", "Significant"], ["Significant", "Considerable", "Ample", "Sizable", "Solid"], ["Insignificant", "Slight", "Trivial", "Flimsy"],
     "The pharmaceutical company invested a substantial budget in oncological vaccine research.",
     "The ancient stone cathedral was built upon substantial granite foundation pillars."),

    ("Subtle", "adjective", "B2", "/ˈsʌt.əl/", "halus samar / sukar ditangkap tapi mendalam",
     "Sangat halus dan tidak mencolok sehingga sukar diperhatikan atau dijelaskan secara gamblang.",
     "So delicate or precise as to be difficult to analyze or describe; understated.",
     ["Subtlety", "Subtly", "Delicate"], ["Delicate", "Nuanced", "Understated", "Faint", "Elusive"], ["Obvious", "Blatant", "Crude", "Harsh"],
     "The pastry chef added a subtle hint of organic cardamom to enhance the vanilla custard.",
     "Diplomats noticed a subtle shift in body language that signaled a willingness to compromise."),

    ("Succumb", "verb", "C1", "/səˈkʌm/", "tunduk menyerah / tak kuasa menahan godaan",
     "Gagal melawan tekanan, godaan, atau penyakit parah; akhirnya menyerah.",
     "Fail to resist pressure, temptation, or an illness; surrender or yield.",
     ["Yield", "Surrender", "Submit"], ["Yield", "Submit", "Surrender", "Capitulate", "Collapse"], ["Resist", "Withstand", "Prevail", "Conquer"],
     "Do not succumb to discouragement when faced with initial entrepreneurial obstacles.",
     "After fighting bravely for weeks, the ancient fortified garrison had to succumb to the siege."),

    ("Summit", "noun", "B1", "/ˈsʌm.ɪt/", "puncak gunung tertinggi / konferensi tingkat tinggi KTT",
     "Titik tertinggi dari sebuah gunung; pertemuan puncak resmi antara kepala negara.",
     "The highest point of a hill or mountain; a meeting between heads of government.",
     ["Peak", "Apex", "Conference"], ["Peak", "Apex", "Zenith", "Climax", "Conclave"], ["Base", "Bottom", "Foot", "Nadir"],
     "Tired mountaineers cheered joyfully as they finally stood upon the snowy Himalayan summit.",
     "World leaders gathered at the environmental climate summit to sign the renewable energy accord."),

    ("Superfluous", "adjective", "C1", "/suːˈpɜː.flu.əs/", "berlebihan tidak perlu / mubazir melimpah sia-sia",
     "Lebih dari yang dibutuhkan; tidak perlu dan dapat dihilangkan tanpa mengurangi fungsi.",
     "Unnecessary, especially through being more than enough; redundant.",
     ["Superfluity", "Redundant", "Excess"], ["Redundant", "Excess", "Unneeded", "Surplus", "Extraneous"], ["Essential", "Necessary", "Vital", "Needed"],
     "The editor deleted superfluous adverbs to make the novel's action scenes more crisp and direct.",
     "Avoid packing superfluous heavy clothing when embarking on a long backpacking mountain trek."),

    ("Superior", "adjective", "B1", "/suːˈpɪə.ri.ər/", "unggul berkelas tinggi / atasan pangkat",
     "Lebih tinggi dalam tingkatan, status, mutu, atau kualitas dibandingkan yang lain.",
     "Higher in rank, status, or quality; greater in size or power.",
     ["Superiority", "Superb", "Better"], ["Better", "Higher", "Supreme", "Paramount", "Dominant"], ["Inferior", "Subordinate", "Poorer", "Lesser"],
     "Optical lenses made from coated quartz glass provide superior clarity and scratch resistance.",
     "Employees should report workplace safety violations directly to their departmental superior."),

    ("Surpass", "verb", "B2", "/səˈpɑːs/", "melampaui rekor / melebihi ekspektasi",
     "Menjadi lebih baik, lebih besar, atau lebih unggul daripada orang lain atau target yang ada.",
     "Exceed; be greater than; do better than expected.",
     ["Surpassing", "Exceed", "Outdo"], ["Exceed", "Outdo", "Outstrip", "Eclipse", "Transcend"], ["Fail", "Fall behind", "Trail"],
     "Quarterly export revenues surpassed all economic forecasts, reaching historic high benchmarks.",
     "Her extraordinary violin performance surpassed the audience's already lofty expectations."),

    ("Surrender", "verb", "B2", "/səˈren.dər/", "menyerah kalah / menyerahkan kekuasaan",
     "Menghentikan perlawanan kepada musuh dan tunduk pada kekuasaannya; melepaskan hak milik.",
     "Stop resisting to an enemy or opponent and submit to their authority; give up a right.",
     ["Surrender", "Capitulate", "Yield"], ["Capitulate", "Yield", "Submit", "Relinquish", "Cede"], ["Resist", "Fight", "Conquer", "Defend"],
     "The besieged castle garrison was forced to surrender after running out of fresh water.",
     "He decided to surrender his driver's license voluntarily due to failing eyesight in old age."),

    ("Surveillance", "noun", "B2", "/səˈveɪ.ləns/", "pengawasan intelijen / pemantauan ketat keamanan",
     "Pengamatan ketat terhadap seseorang atau tempat, terutama oleh polisi atau militer.",
     "Close observation, especially of a suspected spy or criminal; monitoring.",
     ["Survey", "Monitor", "Observation"], ["Observation", "Monitoring", "Vigilance", "Scrutiny", "Watch"], ["Neglect", "Inattention"],
     "High-definition surveillance cameras guard the bank vaults twenty-four hours a day.",
     "Wildlife biologists use satellite surveillance to track the seasonal migration paths of whales."),

    ("Sustain", "verb", "B2", "/səˈsteɪn/", "mempertahankan kelestarian / menopang beban",
     "Memperkuat atau mendukung secara fisik atau mental; membiarkan sesuatu berlanjut lama.",
     "Strengthen or support physically or mentally; cause to continue or be prolonged.",
     ["Sustainability", "Sustainable", "Uphold"], ["Uphold", "Maintain", "Support", "Nourish", "Preserve"], ["Destroy", "Abandon", "Undermine"],
     "Nutritious balanced meals and clean water are essential to sustain human physical health.",
     "Community solar cooperatives help sustain local green economies without polluting rivers."),

    ("Tactile", "adjective", "B2", "/ˈtæk.taɪl/", "taktil peraba / berkaitan dengan indra sentuhan",
     "Berkaitan dengan indra peraba; dapat dirasakan atau disentuh secara fisik.",
     "Connected with the sense of touch; perceptible by touch or tangible.",
     ["Touch", "Tangible", "Palpable"], ["Tangible", "Palpable", "Haptic", "Physical", "Touchable"], ["Intangible", "Abstract"],
     "Braille books use raised tactile dot patterns that allow visually impaired people to read.",
     "The museum's interactive children's room offers engaging tactile sensory exhibits."),

    ("Tangible", "adjective", "B2", "/ˈtæn.dʒə.bəl/", "berwujud nyata / dapat diraba dan diukur jelas",
     "Dapat dirasakan dengan sentuhan; nyata dan tidak bersifat imajiner atau abstrak.",
     "Perceptible by touch; clear, definite, and real rather than imaginary.",
     ["Tangibility", "Concrete", "Palpable"], ["Concrete", "Palpable", "Substantial", "Real", "Actual"], ["Intangible", "Abstract", "Illusory", "Vague"],
     "The environmental cleanup program produced tangible improvements in urban river water clarity.",
     "Investors look for tangible business assets like land and machinery when evaluating loan security."),

    ("Tedious", "adjective", "B2", "/ˈtiː.di.əs/", "menjemukan melelahkan / membosankan bertele-tele",
     "Terlalu panjang, lambat, atau membosankan sehingga melelahkan pikiran.",
     "Too long, slow, or dull; tiresome or monotonous.",
     ["Tedium", "Tediously", "Boring"], ["Boring", "Monotonous", "Dull", "Wearisome", "Tiresome"], ["Exciting", "Interesting", "Fascinating", "Lively"],
     "Manually sorting through thousands of paper invoices was a tedious and exhausting task.",
     "Automated spreadsheet software spares accountants from performing tedious repetitive calculations."),

    ("Tenacious", "adjective", "C1", "/təˈneɪ.ʃəs/", "ulet gigih pantang kendur / memegang teguh",
     "Cenderung memegang erat sesuatu; bertekad kuat dan tidak mudah menyerah.",
     "Tending to keep a firm hold of something; clinging or adhering closely; persistent.",
     ["Tenacity", "Tenaciously", "Persistent"], ["Persistent", "Determined", "Stubborn", "Resolute", "Dogged"], ["Yielding", "Weak", "Faltering", "Irresolute"],
     "The investigative reporter was tenacious in uncovering corporate corruption despite subtle threats.",
     "Ivy plants have tenacious roots that cling firmly to brick and masonry walls."),

    ("Threshold", "noun", "B2", "/ˈθreʃ.həʊld/", "ambang batas / titik awal mula perubahan",
     "Papan atau batu di bagian bawah pintu masuk; tingkat atau titik di mana sesuatu mulai berlaku.",
     "A strip of wood or stone forming the bottom of a doorway; the magnitude that must be exceeded.",
     ["Doorstep", "Brink", "Limit"], ["Brink", "Verge", "Boundary", "Doorstep", "Inception"], ["Center", "Middle"],
     "He paused at the threshold of the grand library before stepping into the silent hall.",
     "Human hearing has an acoustic threshold below which sound vibrations cannot be perceived."),

    ("Thrive", "verb", "B2", "/θraɪv/", "tumbuh subur makmur / berkembang pesat jaya",
     "Tumbuh atau berkembang dengan pesat dan sehat; berhasil dan makmur dalam hidup.",
     "Grow or develop well or vigorously; flourish and prosper.",
     ["Thriving", "Flourish", "Prosper"], ["Flourish", "Prosper", "Bloom", "Succeed", "Blossom"], ["Wither", "Decline", "Stagnate", "Fail"],
     "Tropical orchids thrive in warm, humid environments with filtered dappled sunlight.",
     "Small independent bookstores thrive when they host vibrant community reading clubs and author talks."),

    ("Tolerate", "verb", "B2", "/ˈtɒl.ər.eɪt/", "mentoleransi / membiarkan atau tahan menerima",
     "Mengizinkan keberadaan sesuatu tanpa melarang; menahan kondisi atau rasa sakit tanpa mengeluh.",
     "Allow the existence or occurrence of something without interference; endure.",
     ["Tolerance", "Tolerant", "Endure"], ["Endure", "Bear", "Accept", "Permit", "Abide"], ["Forbid", "Prohibit", "Reject"],
     "A democratic and civilized society must tolerate diverse opinions and philosophical viewpoints.",
     "Desert cacti can tolerate extreme heat and long periods without rainfall effortlessly."),

    ("Transform", "verb", "B1", "/trænsˈfɔːm/", "mentransformasi / merombak bentuk dan fungsi total",
     "Mengubah bentuk, sifat, atau karakter sesuatu secara menyeluruh menjadi lebih baik.",
     "Make a marked change in the form, nature, or appearance of something.",
     ["Transformation", "Transformative", "Convert"], ["Convert", "Revolutionize", "Metamorphose", "Alter", "Remake"], ["Preserve", "Stagnate"],
     "Solar power and electric transport will transform modern cities into clean sustainable habitats.",
     "Education has the transformative power to lift families out of generational poverty."),

    ("Transparent", "adjective", "B2", "/trænˈspær.ənt/", "transparan bening / terbuka jujur tanpa rahasia",
     "Membiarkan cahaya menembusnya sehingga benda di belakangnya terlihat jelas; jujur dan terbuka.",
     "Allowing light to pass through so that objects behind can be distinctly seen; open and honest.",
     ["Transparency", "Transparently", "Clear"], ["Clear", "Lucid", "Crystalline", "Open", "Candid"], ["Opaque", "Cloudy", "Secretive", "Deceptive"],
     "The aquarium was enclosed in massive transparent acrylic panels showcasing sharks and stingrays.",
     "Public government institutions must maintain transparent budgeting to build civic trust."),

    ("Triumph", "noun", "B2", "/ˈtraɪ.ʌmf/", "kemenangan gilang-gemilang / kejayaan luar biasa",
     "Keberhasilan atau kemenangan besar yang diraih setelah perjuangan keras.",
     "A great victory or achievement; the state of being victorious or triumphant.",
     ["Triumphant", "Triumphantly", "Victory"], ["Victory", "Conquest", "Success", "Feat", "Masterstroke"], ["Defeat", "Failure", "Loss", "Disaster"],
     "Landing the robotic exploration rover safely on Mars was a glorious triumph for science.",
     "The young chess grandmaster celebrated her tournament triumph with her proud family."),

    ("Ultimate", "adjective", "B1", "/ˈʌl.tɪ.mət/", "terakhir puncak / paling mendasar pamungkas",
     "Berada di akhir suatu proses panjang; terbaik atau paling ekstrem dari jenisnya.",
     "Being or happening at the end of a process; final; the best or most extreme of its kind.",
     ["Ultimately", "Ultimatum", "Supreme"], ["Final", "Supreme", "Paramount", "Definitive", "Peak"], ["Initial", "First", "Beginning", "Elementary"],
     "The ultimate goal of medical science is to eradicate preventable illnesses worldwide.",
     "Climbing Mount Everest remains the ultimate physical challenge for mountaineering adventurers."),

    ("Undergo", "verb", "B2", "/ˌʌn.dəˈɡəʊ/", "menjalani proses / mengalami perubahan atau ujian",
     "Mengalami atau merasakan sesuatu yang seringkali berat, tidak menyenangkan, atau mendalam.",
     "Experience or be subjected to something, typically something unpleasant, arduous, or surgical.",
     ["Underwent", "Undergone", "Experience"], ["Experience", "Endure", "Suffer", "Encounter", "Bear"], ["Avoid", "Bypass", "Escape"],
     "The historic suspension bridge will undergo major seismic structural strengthening next month.",
     "Athletes undergo rigorous daily training regimens to prepare for international championships."),

    ("Underlying", "adjective", "B2", "/ˌʌn.dəˈlaɪ.ɪŋ/", "mendasari / akar tersembunyi yang menjadi sebab",
     "Terletak di bawah permukaan; menjadi dasar atau penyebab utama dari suatu masalah.",
     "Situated beneath something; being the fundamental cause or basis of something.",
     ["Underlie", "Fundamental", "Basic"], ["Fundamental", "Basic", "Root", "Intrinsic", "Subsurface"], ["Superficial", "Surface", "Incidental"],
     "Doctors investigated the underlying hormonal cause of the patient's persistent fatigue.",
     "The dispute over fishing quotas exposed underlying political tensions between the two coastal states."),

    ("Undertake", "verb", "B2", "/ˌʌn.dəˈteɪk/", "mengemban tugas / berkomitmen memulai proyek",
     "Berkomitmen untuk melakukan atau memulai suatu proyek, tugas, atau tanggung jawab besar.",
     "Commit oneself to and begin an enterprise or task; take on a responsibility.",
     ["Undertaking", "Assume", "Embark on"], ["Embark on", "Assume", "Launch", "Execute", "Tackle"], ["Abandon", "Decline", "Neglect"],
     "The international scientific consortium agreed to undertake a deep-sea ecological survey.",
     "University students undertake rigorous capstone research projects during their final year."),

    ("Unify", "verb", "B2", "/ˈjuː.nɪ.faɪ/", "mempersatukan / melebur menjadi satu keutuhan",
     "Membuat sesuatu menjadi satu kesatuan utuh; menyatukan kelompok yang berbeda.",
     "Make or become united, uniform, or whole; join together as a single entity.",
     ["Unification", "Unified", "Unite"], ["Unite", "Consolidate", "Integrate", "Fuse", "Merge"], ["Divide", "Separate", "Fragment", "Split"],
     "Shared cultural heritage helped unify the diverse archipelago islands into a proud republic.",
     "The new corporate intranet system was designed to unify communications across global branch offices."),

    ("Unprecedented", "adjective", "B2", "/ʌnˈpres.ɪ.den.tɪd/", "belum pernah terjadi sebelumnya / luar biasa baru",
     "Belum pernah dilakukan, diketahui, atau dialami sebelumnya dalam sejarah.",
     "Never done or known before; extraordinary and without previous parallel.",
     ["Precedent", "Unparalleled", "Novel"], ["Unparalleled", "Extraordinary", "Novel", "Groundbreaking", "Historic"], ["Common", "Precedented", "Familiar", "Ordinary"],
     "The sudden scientific breakthrough triggered an unprecedented wave of venture capital investment.",
     "The island experienced an unprecedented period of sustained economic growth and stability."),

    ("Upbeat", "adjective", "B2", "/ˈʌp.biːt/", "ceria optimis / penuh semangat positif",
     "Penuh keceriaan, harapan, dan pandangan positif terhadap masa depan.",
     "Cheerful; optimistic; high in positive spirits and energy.",
     ["Optimistic", "Cheerful", "Buoyant"], ["Optimistic", "Cheerful", "Buoyant", "Hopeful", "Enthusiastic"], ["Gloomy", "Pessimistic", "Depressed", "Downbeat"],
     "Despite the rainy weather, the outdoor festival maintained an upbeat and festive community atmosphere.",
     "The CEO gave an upbeat presentation outlining new product launches and expanding global sales."),

    ("Urgent", "adjective", "B1", "/ˈɜː.dʒənt/", "mendesak darurat / menuntut tindakan segera",
     "Memerlukan tindakan atau perhatian segera karena situasi kritis.",
     "Requiring immediate action or attention; acute and pressing.",
     ["Urgency", "Urgently", "Pressing"], ["Pressing", "Critical", "Imperative", "Crucial", "Emergency"], ["Unimportant", "Trivial", "Optional", "Deferred"],
     "The hospital issued an urgent public appeal for rare blood group donors following the train accident.",
     "Protecting vulnerable coastal wetlands from industrial pollution is an urgent ecological priority."),

    ("Utilize", "verb", "B2", "/ˈjuː.təl.aɪz/", "mendayagunakan / memanfaatkan untuk tujuan guna",
     "Membuat penggunaan praktis dan efektif dari sesuatu sumber daya yang ada.",
     "Make practical and effective use of a resource or tool.",
     ["Utilization", "Utility", "Employ"], ["Employ", "Use", "Harness", "Leverage", "Exploit"], ["Waste", "Misuse", "Ignore", "Discard"],
     "Modern green factories utilize rooftop solar panels to generate sustainable clean power.",
     "Teachers utilize interactive multimedia diagrams to explain complex biological concepts clearly."),

    ("Validate", "verb", "B2", "/ˈvæl.ɪ.deɪt/", "memvalidasi / mengesahkan kebenaran dan keabsahan",
     "Memeriksa atau membuktikan keabsahan, keakuratan, atau nilai sesuatu secara resmi.",
     "Check or prove the validity or accuracy of something; make or declare legally valid.",
     ["Validation", "Validity", "Verify"], ["Verify", "Confirm", "Authenticate", "Substantiate", "Certify"], ["Invalidate", "Disprove", "Reject", "Nullify"],
     "Clinical laboratory trials are required to validate the safety and efficacy of the new medicine.",
     "The ticket machine will validate your electronic boarding pass before you enter the platform."),

    ("Variable", "adjective", "B2", "/ˈveə.ri.ə.bəl/", "berubah-ubah variatif / tidak tetap nilainya",
     "Dapat berubah atau disesuaikan; tidak memiliki nilai atau pola yang tetap dan konstan.",
     "Not consistent or having a fixed pattern; liable to change; variable in magnitude.",
     ["Variability", "Vary", "Changeable"], ["Changeable", "Shifting", "Fluctuating", "Fluid", "Mutable"], ["Constant", "Fixed", "Stable", "Invariant"],
     "Mountain weather is notoriously variable, with bright sunshine turning into blizzards within minutes.",
     "In algebraic mathematics, a variable represents an unknown numerical value in an equation."),

    ("Versatile", "adjective", "B2", "/ˈvɜː.sə.taɪl/", "serbaguna serbabisa / luwes beradaptasi",
     "Mampu beradaptasi atau disesuaikan dengan banyak fungsi atau aktivitas yang berbeda.",
     "Able to adapt or be adapted to many different functions or activities.",
     ["Versatility", "Adaptable", "Multipurpose"], ["Adaptable", "Flexible", "Multipurpose", "Resourceful", "Handy"], ["Inflexible", "Limited", "Rigid", "Specialized"],
     "Coconut oil is a versatile kitchen ingredient used in gourmet cooking, baking, and skincare.",
     "She is a versatile actress who excels equally in dramatic Shakespearean roles and light comedies."),

    ("Viable", "adjective", "B2", "/ˈvaɪ.ə.bəl/", "layak hidup berkembang / dapat terlaksana sukses",
     "Mampu bekerja dengan sukses; mampu bertahan hidup dan tumbuh mandiri.",
     "Capable of working successfully; feasible; capable of surviving or living successfully.",
     ["Viability", "Viably", "Feasible"], ["Feasible", "Workable", "Practicable", "Sustainable", "Achievable"], ["Inviable", "Impractical", "Unworkable", "Futile"],
     "Solar photovoltaic microgrids offer a commercially viable energy solution for remote island villages.",
     "The venture committee reviewed the proposal to ensure the business model was economically viable."),

    ("Vibrant", "adjective", "B2", "/ˈvaɪ.brənt/", "semarak bersemangat / cerah memikat penuh daya",
     "Penuh energi, vitalitas, dan antusiasme; warna yang cerah, mencolok, dan memukau.",
     "Full of energy, enthusiasm, and life; of color, bright and striking.",
     ["Vibrancy", "Vibrantly", "Lively"], ["Lively", "Dynamic", "Energetic", "Vivid", "Radiant"], ["Dull", "Lifeless", "Drab", "Monotonous"],
     "The night street market was filled with vibrant colors, exotic aromas, and lively chatter.",
     "Yogyakarta is celebrated for its vibrant traditional arts, batik workshops, and shadow puppetry."),

    ("Virtual", "adjective", "B1", "/ˈvɜː.tʃu.əl/", "virtual maya / hampir nyata secara fungsional",
     "Dihasilkan oleh perangkat lunak komputer; hampir mendekati nyata dalam segala hal esensial.",
     "Not physically existing as such but made by software to appear to do so; almost or nearly as.",
     ["Virtually", "Virtual reality", "Digital"], ["Digital", "Cyber", "Simulated", "Practical", "Effective"], ["Physical", "Real", "Actual", "Concrete"],
     "Virtual reality headsets transport students on simulated walking tours of ancient Roman ruins.",
     "With online collaboration tools, the multinational design team functions as a seamless virtual office."),

    ("Visible", "adjective", "A2", "/ˈvɪz.ə.bəl/", "terlihat kasatmata / tampak jelas di mata",
     "Dapat dilihat oleh mata; jelas terlihat atau mudah diperhatikan keberadaannya.",
     "Able to be seen; clear, manifest, or conspicuous to the eye.",
     ["Visibility", "Visibly", "Noticeable"], ["Noticeable", "Observable", "Perceptible", "Clear", "Conspicuous"], ["Invisible", "Hidden", "Unseen", "Concealed"],
     "The snow-covered peak of Mount Fuji was clearly visible on the crisp winter morning.",
     "There has been a visible improvement in urban air quality since the introduction of electric buses."),

    ("Visionary", "adjective", "B2", "/ˈvɪʒ.ən.ri/", "visioner berwawasan masa depan / penuh impian agung",
     "Memiliki pemikiran atau perencanaan masa depan dengan imajinasi dan kebijaksanaan luhur.",
     "Thinking about or planning the future with imagination or wisdom; ahead of its time.",
     ["Vision", "Farsighted", "Pioneering"], ["Farsighted", "Pioneering", "Innovative", "Prophetic", "Imaginative"], ["Shortsighted", "Unimaginative", "Pedestrian"],
     "Steve Jobs was widely regarded as a visionary tech leader who transformed multiple industries.",
     "The architect presented a visionary urban masterplan featuring rooftop gardens and canal transit."),

    ("Vital", "adjective", "B1", "/ˈvaɪ.təl/", "amat vital penting / mutlak perlu bagi kehidupan",
     "Sangat penting dan krusial; mutlak diperlukan untuk kelangsungan hidup atau keberhasilan.",
     "Absolutely necessary or essential; essential to life and living organisms.",
     ["Vitality", "Vitally", "Crucial"], ["Crucial", "Essential", "Indispensable", "Critical", "Fundamental"], ["Inessential", "Minor", "Trivial", "Optional"],
     "Access to clean drinking water is vital for preventing acute infectious diseases in disaster zones.",
     "Trust and honest communication are vital ingredients for any healthy personal relationship."),

    ("Vivid", "adjective", "B2", "/ˈvɪv.ɪd/", "jelas hidup / warna cemerlang membekas di ingatan",
     "Menghasilkan gambaran yang sangat kuat dan jelas dalam pikiran; warna yang cerah cemerlang.",
     "Producing powerful feelings or strong, clear images in the mind; intensely deep or bright in color.",
     ["Vividly", "Vividness", "Graphic"], ["Graphic", "Lively", "Bright", "Lucid", "Brilliant"], ["Vague", "Faint", "Dull", "Bland"],
     "She gave a vivid description of her exciting trek through the Amazonian tropical rainforest.",
     "The sunset painted the sky in vivid shades of crimson, violet, and molten gold."),

    ("Vulnerable", "adjective", "B2", "/ˈvʌl.nər.ə.bəl/", "rentan mudah terluka / rawan terkena bahaya",
     "Mudah diserang atau dilukai secara fisik maupun emosional; rawan terkena dampak buruk.",
     "Susceptible to physical or emotional attack or harm; in need of special care or protection.",
     ["Vulnerability", "Vulnerably", "Susceptible"], ["Susceptible", "Exposed", "Fragile", "Defenseless", "Sensitive"], ["Invulnerable", "Protected", "Resilient", "Secure"],
     "Coastal fishing villages are especially vulnerable to rising sea levels and typhoon storm surges.",
     "Non-profit welfare shelters provide safe housing for vulnerable homeless mothers and infants."),

    ("Wealthy", "adjective", "A2", "/ˈwel.θi/", "kaya raya berlimpah harta / makmur berkecukupan",
     "Memiliki banyak uang, properti, atau sumber daya materi; hidup berkecukupan.",
     "Having a great deal of money, resources, or assets; rich and affluent.",
     ["Wealth", "Affluent", "Rich"], ["Rich", "Affluent", "Prosperous", "Well-to-do", "Opulent"], ["Poor", "Impoverished", "Destitute", "Penniless"],
     "The wealthy philanthropist donated millions of dollars to build free public science libraries.",
     "The island kingdom grew wealthy through maritime spice trade and sustainable pearl harvesting."),

    ("Widespread", "adjective", "B2", "/ˈwaɪd.spred/", "meluas di mana-mana / tersebar merata",
     "Ditemukan atau terjadi di wilayah yang luas atau di antara banyak orang.",
     "Found or distributed over a large area or number of people; prevalent and common.",
     ["Prevalent", "Extensive", "Pervasive"], ["Prevalent", "Extensive", "Universal", "Ubiquitous", "Broad"], ["Rare", "Localized", "Limited", "Confined"],
     "The government health advisory received widespread media coverage across television and radio.",
     "Smartphone usage has become widespread among students of all ages across the nation."),

    ("Wisdom", "noun", "B1", "/ˈwɪz.dəm/", "kebijaksanaan kearifan / hikmah kedewasaan",
     "Kualitas memiliki pengalaman, pengetahuan, dan penilaian yang baik; kearifan hidup.",
     "The quality of having experience, knowledge, and good judgment; the quality of being wise.",
     ["Wise", "Wisely", "Insight"], ["Sagacity", "Insight", "Prudence", "Discretion", "Enlightenment"], ["Folly", "Stupidity", "Ignorance", "Foolishness"],
     "Village elders are deeply respected for their accumulated life wisdom and conflict mediation skills.",
     "Proverbs and folk parables pass down ancient moral wisdom from generation to generation."),

    ("Withdraw", "verb", "B2", "/wɪðˈdrɔː/", "menarik kembali / mengundurkan diri / mengambil uang",
     "Menarik uang dari bank; mundur dari posisi atau perlombaan; mencabut pernyataan.",
     "Remove money from a bank account; move back or away from a position; retract a statement.",
     ["Withdrawal", "Retract", "Depart"], ["Retract", "Retreat", "Pull out", "Depart", "Recede"], ["Deposit", "Advance", "Insert", "Submit"],
     "She stopped by the automated bank teller to withdraw cash before taking the taxi.",
     "The injured tennis player was reluctantly forced to withdraw from the semifinal match."),

    ("Withstand", "verb", "B2", "/wɪðˈstænd/", "bertahan menghadapi / tahan terhadap gempuran",
     "Mampu bertahan melawan atau tidak rusak oleh kekuatan, tekanan, atau serangan yang kuat.",
     "Remain undamaged or unaffected by; resist or survive in the face of pressure.",
     ["Endure", "Resist", "Survive"], ["Endure", "Resist", "Survive", "Tolerate", "Hold out against"], ["Yield", "Collapse", "Succumb", "Fail"],
     "Modern skyscrapers in Tokyo are engineered to withstand severe earthquake tremors safely.",
     "Quality marine paint helps wooden boat hulls withstand continuous salt water corrosion."),

    ("Worthwhile", "adjective", "B1", "/ˌwɜːθˈwaɪl/", "berharga bernilai / sepadan dengan usaha",
     "Pantas untuk dilakukan karena memberikan manfaat, kepuasan, atau hasil yang sepadan.",
     "Worth the time, money, or effort spent; of value or importance.",
     ["Worthy", "Valuable", "Rewarding"], ["Rewarding", "Valuable", "Beneficial", "Productive", "Meritorious"], ["Useless", "Futile", "Worthless", "Pointless"],
     "Volunteering at the community children's shelter is a deeply rewarding and worthwhile experience.",
     "Learning a second foreign language requires dedication, but the career rewards make it worthwhile."),

    ("Yield", "verb", "B2", "/jiːld/", "menghasilkan panen keuntungan / mengalah memberi jalan",
     "Menghasilkan tanaman pangan atau keuntungan finansial; menyerah atau memberi prioritas di jalan.",
     "Produce or provide a natural product or financial profit; surrender or give way to traffic.",
     ["Yield", "Produce", "Surrender"], ["Produce", "Generate", "Supply", "Relinquish", "Concede"], ["Withhold", "Resist", "Deny"],
     "Organic farming practices yield healthy nutrient-rich crops while preserving topsoil fertility.",
     "Drivers approaching a traffic roundabout must yield to oncoming vehicles already in the circle."),

    ("Zeal", "noun", "C1", "/ziːl/", "kegigihan membara / semangat antusiasme tinggi",
     "Semangat, dedikasi, dan antusiasme yang luar biasa besar dalam mengejar suatu tujuan mulia.",
     "Great energy or enthusiasm in pursuit of a cause or an objective; fervor.",
     ["Zealous", "Zealot", "Fervor"], ["Fervor", "Passion", "Ardor", "Enthusiasm", "Devotion"], ["Apathy", "Indifference", "Lethargy"],
     "The young environmental scientist pursued marine conservation research with unflagging zeal.",
     "Community volunteers worked with incredible zeal to plant thousands of native saplings on the hill.")
]

print("SZ Words Dataset loaded:", len(SZ_WORDS_DATASET))
