#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Oxford Gap Closer - Final MR entries and SZ entries to surpass 260.
"""

MR_GAP_CLOSER = [
    ("Proclaim", "verb", "B2", "/prəˈkleɪm/", "memproklamasikan / mengumumkan secara resmi terbuka",
     "Mengumumkan sesuatu secara resmi atau terbuka kepada masyarakat luas.",
     "Announce officially or publicly to all people.",
     ["Proclamation", "Declare", "Announce"], ["Declare", "Announce", "Promulgate", "Broadcast", "Trumpet"], ["Conceal", "Suppress", "Hide"],
     "The prime minister stepped up to the podium to proclaim national independence day.",
     "Artistic creations often proclaim the universal beauty of peace and human fraternity."),

    ("Prolific", "adjective", "B2", "/prəˈlɪf.ɪk/", "sangat produktif / menghasilkan karya berlimpah",
     "Menghasilkan banyak karya, buku, buah, atau keturunan dalam jumlah besar.",
     "Producing much fruit or foliage or many offspring; producing many works.",
     ["Prolifically", "Productive", "Fertile"], ["Productive", "Fertile", "Creative", "Abundant", "Bountiful"], ["Unproductive", "Barren", "Sterile"],
     "The prolific composer wrote more than thirty symphonies and chamber pieces in his lifetime.",
     "Tropical coral ecosystems provide a prolific breeding nursery for thousands of fish species."),

    ("Prominent", "adjective", "B2", "/ˈprɒm.ɪ.nənt/", "terkemuka menonjol / terkenal dan disegani",
     "Penting, terkenal, dan mudah dilihat atau dikenal dalam masyarakat atau bidang tertentu.",
     "Important; famous; projecting or situated so as to catch the attention readily.",
     ["Prominence", "Prominently", "Eminent"], ["Eminent", "Distinguished", "Famous", "Conspicuous", "Salient"], ["Obscure", "Unknown", "Inconspicuous"],
     "She is a prominent pediatric surgeon known globally for advancing laparoscopic techniques.",
     "The historic bronze clock tower is the most prominent visual landmark in the town square."),

    ("Prompt", "adjective", "B1", "/prɒmpt/", "cepat tanggap tepat waktu / tanpa penundaan",
     "Dilakukan tanpa penundaan; tepat waktu dan cepat dalam bertindak atau merespons.",
     "Done without delay; immediate; punctual in action.",
     ["Promptly", "Promptness", "Punctual"], ["Punctual", "Immediate", "Swift", "Expeditious", "Quick"], ["Slow", "Tardy", "Delayed", "Sluggish"],
     "The customer service department earned high ratings for prompt and courteous assistance.",
     "A prompt medical emergency response saved the marathon runner from heat exhaustion."),

    ("Prone", "adjective", "B2", "/prəʊn/", "rentan cenderung / berbaring telungkup",
     "Cenderung atau mudah terkena sesuatu yang tidak menyenangkan; posisi telungkup.",
     "Likely to or liable to suffer from, do, or experience something unpleasant; lying face downward.",
     ["Prone to", "Vulnerable", "Susceptible"], ["Susceptible", "Vulnerable", "Inclined", "Liable", "Predisposed"], ["Immune", "Resistant", "Unlikely"],
     "Low-lying coastal farming valleys are prone to seasonal river flooding during rainy months.",
     "Patients with chronic allergies are especially prone to sinus irritation in the spring."),

    ("Prosper", "verb", "B1", "/ˈprɒs.pər/", "makmur berkembang pesat / sukses sejahtera",
     "Berhasil dalam kegiatan ekonomi; berkembang subur dan sejahtera dalam kehidupan.",
     "Succeed in material terms; be financially flourishing and successful; thrive.",
     ["Prosperity", "Prosperous", "Thrive"], ["Thrive", "Flourish", "Succeed", "Bloom", "Advance"], ["Fail", "Decline", "Stagnate", "Wither"],
     "Local artisanal businesses prosper when communities actively support domestic markets.",
     "With good irrigation and fertile soil, the family vineyard began to prosper remarkably."),

    ("Prudent", "adjective", "B2", "/ˈpruː.dənt/", "bijaksana hemat cermat / berhati-hati penuh pertimbangan",
     "Bertindak atau menunjukkan kepedulian dan kebijaksanaan untuk masa depan.",
     "Acting with or showing care and thought for the future; discreet and wise.",
     ["Prudence", "Prudently", "Sensible"], ["Sensible", "Wise", "Judicious", "Sagacious", "Frugal"], ["Imprudent", "Reckless", "Rash", "Wasteful"],
     "It is prudent to maintain a household emergency savings reserve for unforeseen events.",
     "The financial manager took prudent measures to safeguard company assets during inflation."),

    ("Quaint", "adjective", "B2", "/kweɪnt/", "unik kuno memesona / antik bergaya lama menawan",
     "Menarik atau memesona karena memiliki keunikan cara lama atau antik yang menyenangkan.",
     "Attractively unusual or old-fashioned in character or appearance.",
     ["Quaintness", "Charming", "Picturesque"], ["Charming", "Picturesque", "Old-fashioned", "Whimsical", "Idyllic"], ["Modern", "Ugly", "Conventional"],
     "We spent the afternoon exploring quaint seaside fishing villages with thatched-roof stone cottages.",
     "The antique bookshop featured quaint winding spiral staircases and wooden reading benches."),

    ("Quarantine", "noun", "B1", "/ˈkwɒr.ən.tiːn/", "karantina isolasi / pencegahan penularan penyakit",
     "Keadaan atau periode isolasi di mana orang atau hewan yang mungkin terinfeksi ditahan.",
     "A state, period, or place of isolation in which people or animals that have been exposed to infectious disease are placed.",
     ["Quarantined", "Isolation", "Seclusion"], ["Isolation", "Seclusion", "Confinement", "Sanitary cordon"], ["Freedom", "Release"],
     "Incoming agricultural shipments are kept in temporary quarantine to prevent invasive pests.",
     "Public health guidelines established a ten-day quarantine protocol for returning international travelers."),

    ("Quell", "verb", "C1", "/kwel/", "meredakan memadamkan / menenangkan keresahan dengan tegas",
     "Mengakhiri pemberontakan atau kekacauan, biasanya dengan menggunakan kekuasaan; meredakan rasa cemas.",
     "Put an end to a rebellion or other disorder, typically by the use of force; subdue.",
     ["Quelling", "Subdue", "Suppress"], ["Subdue", "Suppress", "Extinguish", "Calm", "Pacify"], ["Inflame", "Incite", "Provoke", "Agitate"],
     "The security officers acted swiftly to quell the riot before any property was damaged.",
     "A gentle cup of chamomile tea and soothing classical music helped quell her evening anxiety."),

    ("Quench", "verb", "B2", "/kwentʃ/", "memuaskan dahaga / memadamkan api yang membara",
     "Memuaskan rasa haus dengan minum; memadamkan api atau nyala terang dengan air.",
     "Satisfy one's thirst by drinking; extinguish a fire or light.",
     ["Quenched", "Extinguish", "Slake"], ["Slake", "Satisfy", "Satiate", "Extinguish", "Douse"], ["Ignite", "Kindle", "Thirst"],
     "Fresh cold coconut water is an ideal tropical natural beverage to quench deep thirst.",
     "The volunteer firefighters poured buckets of river water to quench the smoldering campfire."),

    ("Radical", "adjective", "B2", "/ˈræd.ɪ.kəl/", "radikal mendasar / menyeluruh dan revolusioner",
     "Berkaitan dengan atau memengaruhi sifat dasar atau fundamental dari sesuatu; drastis.",
     "Relating to or affecting the fundamental nature of something; far-reaching or thorough.",
     ["Radically", "Fundamental", "Drastic"], ["Fundamental", "Drastic", "Revolutionary", "Profound", "Sweeping"], ["Superficial", "Conservative", "Minor"],
     "The university introduced a radical overhaul of its engineering curriculum to emphasize AI.",
     "Transforming transportation requires radical shifts toward renewable clean power grids."),

    ("Radiant", "adjective", "B2", "/ˈreɪ.di.ənt/", "berseri-seri gembira / bersinar terang memancar",
     "Bersinar atau memancarkan cahaya terang; memancarkan kegembiraan dan kebahagiaan.",
     "Shining or glowing brightly; emitting radiant light; radiating love and joy.",
     ["Radiance", "Radiancy", "Glowing"], ["Glowing", "Beaming", "Luminous", "Brilliant", "Effulgent"], ["Dim", "Dark", "Gloomy", "Muted"],
     "The bride looked radiant as she walked down the aisle surrounded by white orchids.",
     "The morning sun cast a radiant golden glow across the calm surface of the lake."),

    ("Rapport", "noun", "B2", "/ræpˈɔːr/", "hubungan akrab serasi / keharmonisan saling memahami",
     "Hubungan yang erat dan harmonis di mana pihak-pihak saling memahami perasaan dan gagasan.",
     "A close and harmonious relationship in which the people or groups understand each other's feelings or ideas.",
     ["Affinity", "Harmony", "Sympathy"], ["Harmony", "Sympathy", "Affinity", "Bond", "Accord"], ["Discord", "Hostility", "Alienation"],
     "The school counselor quickly established a warm empathetic rapport with the new students.",
     "Successful sales partnerships rely on mutual trust, clear communication, and personal rapport."),

    ("Reassure", "verb", "B1", "/ˌriː.əˈʃɔːr/", "menenangkan hati / meyakinkan kembali rasa aman",
     "Mengatakan atau melakukan sesuatu untuk menghilangkan keraguan dan ketakutan seseorang.",
     "Say or do something to remove the doubts and fears of someone; restore confidence.",
     ["Reassurance", "Reassuring", "Comfort"], ["Comfort", "Console", "Encourage", "Cheer", "Soothe"], ["Alarm", "Frighten", "Intimidate", "Discourage"],
     "The flight attendant smiled warmly to reassure the nervous passenger during minor turbulence.",
     "Doctors spoke with calm confidence to reassure the anxious parents before the operation.")
]

SZ_GAP_CLOSER = [
    ("Tactful", "adjective", "B2", "/ˈtækt.fəl/", "bijak menjaga perasaan / diplomatis dan penuh tenggang rasa",
     "Memiliki atau menunjukkan kepekaan dan keterampilan dalam menangani situasi sulit.",
     "Having or showing skill and sensitivity in dealing with others or with difficult issues.",
     ["Tact", "Tactfully", "Diplomatic"], ["Diplomatic", "Discreet", "Considerate", "Polite", "Sensitive"], ["Tactless", "Blunt", "Rude", "Indiscreet"],
     "The human resources director gave tactful and constructive feedback to the underperforming employee.",
     "Being tactful allows leaders to resolve team disputes without causing unnecessary embarrassment."),

    ("Talisman", "noun", "B2", "/ˈtæl.ɪz.mən/", "jimat keberuntungan / benda pembawa berkah perlindungan",
     "Objek yang dianggap memiliki kekuatan magis atau membawa keberuntungan bagi pemiliknya.",
     "An object, typically an inscribed ring or stone, that is thought to have magic powers and to bring good luck.",
     ["Amulet", "Charm", "Fetish"], ["Amulet", "Charm", "Mascot", "Totem", "Keepsake"], ["Curse"],
     "The sailor wore a carved jade talisman around his neck for safe voyages across the ocean.",
     "In folklore, the silver coin was kept as a protective talisman against ill fortune."),

    ("Taper", "verb", "B2", "/ˈteɪ.pər/", "meruncing menyempit / berkurang bertahap ke ujung",
     "Menjadi semakin tipis, sempit, atau berkurang perlahan menuju ke satu ujung.",
     "Diminish or reduce in thickness toward one end; gradually lessen.",
     ["Tapering", "Narrow", "Dwindle"], ["Narrow", "Slim", "Recede", "Decrease", "Subside"], ["Widen", "Expand", "Enlarge", "Swell"],
     "The ancient stone obelisk tapers gracefully to a pointed golden pyramidal apex.",
     "Traffic congestion begins to taper off significantly after seven o'clock in the evening."),

    ("Temperate", "adjective", "B2", "/ˈtem.pər.ət/", "beriklim sedang / terkendali tidak ekstrem",
     "Menunjukkan sikap atau perilaku yang terkendali; daerah yang memiliki suhu nyaman sedang.",
     "Showing moderation or self-restraint; relating to or denoting a region with mild temperatures.",
     ["Temperance", "Mild", "Moderate"], ["Moderate", "Mild", "Clement", "Equable", "Restrained"], ["Extreme", "Severe", "Harsh", "Intemperate"],
     "The temperate coastal climate allows vineyards to grow sweet grape varieties throughout the year.",
     "A temperate response to harsh online criticism demonstrates emotional maturity and composure."),

    ("Temporal", "adjective", "B2", "/ˈtem.pər.əl/", "bersifat duniawi fana / berkaitan dengan waktu",
     "Berkaitan dengan urusan duniawi yang fana daripada spiritual; berkaitan dengan dimensi waktu.",
     "Relating to worldly as opposed to spiritual affairs; secular; relating to time.",
     ["Temporality", "Secular", "Time-bound"], ["Secular", "Earthly", "Worldly", "Mundane", "Chronological"], ["Spiritual", "Eternal", "Sacred"],
     "Monks dedicate their daily lives to spiritual reflection rather than temporal wealth and possessions.",
     "The philosopher explored temporal concepts of past, present, and future in human consciousness."),

    ("Tenacity", "noun", "B2", "/təˈnæs.ə.ti/", "kegigihan keuletan / keteguhan tekad tak kenal menyerah",
     "Kualitas mempertahankan tujuan dengan sangat gigih; keuletan dan keteguhan tekad.",
     "The quality or fact of being able to grip something firmly; determination; persistence.",
     ["Tenacious", "Persistence", "Perseverance"], ["Perseverance", "Persistence", "Determination", "Resilience", "Grit"], ["Weakness", "Surrender", "Hesitation"],
     "Her extraordinary academic tenacity helped her overcome financial hardship and complete her degree.",
     "Climbing ivy demonstrates incredible physical tenacity as it scales sheer stone walls."),

    ("Tender", "adjective", "A2", "/ˈten.dər/", "empuk lembut / penuh kasih sayang manis",
     "Mudah dipotong atau dikunyah; menunjukkan kelembutan, kehangatan, dan cinta kasih mendalam.",
     "Easy to cut or chew; showing gentleness, kindness, and affection.",
     ["Tenderness", "Tenderly", "Gentle"], ["Gentle", "Affectionate", "Soft", "Loving", "Delicate"], ["Tough", "Hard", "Harsh", "Callous"],
     "The slow-roasted beef brisket was juicy and incredibly tender.",
     "The mother sang a tender lullaby to soothe her baby to sleep in the nursery."),

    ("Terminate", "verb", "B2", "/ˈtɜː.mɪ.neɪt/", "mengakhiri / menuntaskan kontrak atau proses",
     "Membawa sesuatu sampai ke ujung akhir; memberhentikan perjanjian atau proses kerja.",
     "Bring to an end; conclude; discontinue a contract or agreement.",
     ["Termination", "Conclude", "Cease"], ["Conclude", "End", "Finish", "Discontinue", "Cancel"], ["Begin", "Initiate", "Start", "Renew"],
     "Either party may terminate the rental tenancy agreement by providing sixty days of written notice.",
     "The commuter train terminates at the central downtown terminal station."),

    ("Thaw", "verb", "B1", "/θɔː/", "mencairkan es / melunakkan hubungan yang kaku",
     "Berubah dari bentuk beku menjadi cair karena kenaikan suhu panas; menjadi lebih ramah.",
     "Become liquid or soft as a result of warming; make or become friendlier.",
     ["Thawing", "Melt", "Defrost"], ["Melt", "Defrost", "Dissolve", "Unfreeze", "Warm"], ["Freeze", "Solidify", "Congeal"],
     "As spring arrives, mountain snowfields begin to thaw and fill rushing alpine creeks.",
     "A shared cup of warm tea helped thaw the frosty tension between the two negotiators."),

    ("Thrive", "verb", "B1", "/θraɪv/", "tumbuh subur makmur / berkembang dengan sangat baik",
     "Tumbuh atau berkembang dengan penuh semangat; berkembang sangat makmur dan berhasil.",
     "Grow or develop well or vigorously; prosper and flourish.",
     ["Thriving", "Flourish", "Prosper"], ["Flourish", "Prosper", "Boom", "Blossom", "Succeed"], ["Wither", "Decline", "Stagnate", "Fail"],
     "Wild orchids thrive in the humid, warm canopy shade of tropical rainforests.",
     "Creative technology startups thrive in vibrant cities that foster entrepreneurship and talent."),

    ("Timber", "noun", "B1", "/ˈtɪm.bər/", "kayu gelondongan / bahan bangunan kayu olahan",
     "Kayu yang disiapkan untuk digunakan dalam bangunan dan pertukangan kayu; pepohonan hutan.",
     "Wood prepared for use in building and carpentry; standing trees grown for timber.",
     ["Wood", "Lumber", "Forest"], ["Lumber", "Wood", "Plank", "Beams", "Trees"], ["Plastic", "Steel"],
     "Sustainable forestry practices ensure that harvested timber is replenished with new saplings.",
     "The mountain cabin was constructed from sturdy cedar timber that resists dampness."),

    ("Timely", "adjective", "B2", "/ˈtaɪm.li/", "tepat pada waktunya / terjadi di saat yang pas",
     "Dilakukan atau terjadi pada saat yang tepat dan menguntungkan; tepat waktu.",
     "Done or occurring at a favorable or useful time; opportune.",
     ["Timeliness", "Opportune", "Punctual"], ["Opportune", "Well-timed", "Seasonable", "Appropriate", "Prompt"], ["Untimely", "Inopportune", "Late"],
     "The surgeon's timely emergency intervention prevented irreversible tissue damage.",
     "Receiving a timely scholarship grant enabled him to register for the international semester."),

    ("Tolerant", "adjective", "B1", "/ˈtɒl.ər.ənt/", "toleran berlapang dada / menghargai perbedaan ragam",
     "Menunjukkan kemauan untuk menerima atau menghormati perbedaan pendapat atau keyakinan.",
     "Showing willingness to allow the existence of opinions or behavior that one does not necessarily agree with.",
     ["Tolerance", "Tolerate", "Broad-minded"], ["Broad-minded", "Patient", "Open-minded", "Liberal", "Permissive"], ["Intolerant", "Bigoted", "Prejudiced", "Narrow-minded"],
     "A democratic society flourishes when citizens are tolerant of diverse cultural perspectives.",
     "Desert succulents are remarkably tolerant of intense heat and prolonged drought conditions."),

    ("Torment", "noun", "B2", "/ˈtɔː.ment/", "siksaan batin derita / kepedihan mendalam",
     "Penderitaan fisik atau mental yang parah; sesuatu yang menjadi sumber penderitaan.",
     "Severe physical or mental suffering; a cause of suffering.",
     ["Tormented", "Agony", "Anguish"], ["Agony", "Anguish", "Torture", "Affliction", "Misery"], ["Comfort", "Peace", "Solace", "Joy"],
     "Waiting for the medical biopsy diagnosis was an agonizing torment for the whole family.",
     "In myth, Sisyphus endured the eternal torment of pushing a boulder up a steep hill."),

    ("Tradition", "noun", "A2", "/trəˈdɪʃ.ən/", "tradisi adat istiadat / warisan budaya turun-temurun",
     "Penerusan adat istiadat atau kepercayaan dari generasi ke generasi; adat kebiasaan.",
     "The transmission of customs or beliefs from generation to generation.",
     ["Traditional", "Traditionally", "Custom"], ["Custom", "Heritage", "Ritual", "Convention", "Folklore"], ["Innovation", "Modernity"],
     "The annual harvest celebration is an ancient agrarian tradition uniting all village families.",
     "Balinese dance performances carry forward centuries of sacred cultural traditions."),

    ("Trajectory", "noun", "B2", "/trəˈdʒek.tər.i/", "lintasan lintasan edar / arah alur perkembangan",
     "Jalur yang dilalui oleh benda terbang yang bergerak di bawah aksi gaya gravitasi; alur karier.",
     "The path followed by a projectile flying or an object moving under the action of given forces; course.",
     ["Path", "Course", "Orbit"], ["Path", "Course", "Flight path", "Track", "Direction"], ["N/A"],
     "Aerospace engineers calculated the rocket's exact atmospheric trajectory into orbit.",
     "Her artistic career followed an impressive upward trajectory following her solo gallery debut."),

    ("Tremendous", "adjective", "B1", "/trɪˈmen.dəs/", "sangat dahsyat luar biasa / berukuran sangat besar",
     "Sangat hebat dalam jumlah, skala, atau intensitas; sangat luar biasa mengagumkan.",
     "Very great in amount, scale, or intensity; extremely good.",
     ["Tremendously", "Immense", "Enormous"], ["Immense", "Enormous", "Colossal", "Huge", "Fantastic"], ["Tiny", "Minor", "Insignificant"],
     "Volunteers contributed a tremendous amount of time and effort to restore the wildlife habitat.",
     "The concert hall erupted in tremendous applause when the maestro concluded the finale."),

    ("Triumph", "noun", "B1", "/ˈtraɪ.ʌmf/", "kemenangan gemilang / kejayaan agung membanggakan",
     "Kemenangan besar atau pencapaian gemilang setelah perjuangan keras; rasa puas gembira.",
     "A great victory or achievement; the joy of victory.",
     ["Triumphant", "Triumphantly", "Victory"], ["Victory", "Conquest", "Success", "Achievement", "Feat"], ["Defeat", "Failure", "Disaster"],
     "The eradication of the disease in the country was celebrated as a historic public health triumph.",
     "The underdog soccer team enjoyed an emotional triumph in the national championship final."),

    ("Turbulence", "noun", "B2", "/ˈtɜː.bjə.ləns/", "turbulensi pergolakan / arus golak tak teratur",
     "Gerakan udara atau air yang tidak stabil dan bergolak; keadaan kebingungan atau kekacauan.",
     "Violent or unsteady movement of air or water, or of some other fluid; a state of conflict or confusion.",
     ["Turbulent", "Commotion", "Instability"], ["Instability", "Commotion", "Unrest", "Agitation", "Disorder"], ["Calm", "Stability", "Peace", "Serenity"],
     "Passengers were instructed to fasten seatbelts due to sudden atmospheric clear-air turbulence.",
     "The region endured economic turbulence during the rapid currency devaluation crisis."),

    ("Twilight", "noun", "B1", "/ˈtwaɪ.laɪt/", "senja temaram / cahaya remang menjelang malam",
     "Cahaya lembut yang tersebar dari langit ketika matahari berada di bawah cakrawala; masa peralihan.",
     "The soft glowing light from the sky when the sun is below the horizon; a period of decline.",
     ["Dusk", "Sundown", "Gloom"], ["Dusk", "Nightfall", "Sunset", "Gloom", "Half-light"], ["Dawn", "Daybreak", "Noon"],
     "We strolled through the quiet botanical gardens in the romantic golden glow of evening twilight.",
     "Fireflies began blinking softly among the river reeds as twilight faded into night."),

    ("Typify", "verb", "B2", "/ˈtɪp.ɪ.faɪ/", "mencerminkan tipikal / menjadi contoh khas",
     "Menjadi contoh representatif atau simbol khas dari suatu kelompok atau gaya tertentu.",
     "Be characteristic or a representative example of something.",
     ["Typical", "Typified", "Epitomize"], ["Epitomize", "Represent", "Personify", "Characterize", "Embody"], ["Deviate", "Contrast"],
     "The historic row houses typify Victorian architectural craftsmanship in London.",
     "Her selflessness and calm determination typify the spirit of humanitarian aid workers."),

    ("Ultimate", "adjective", "B1", "/ˈʌl.tɪ.mət/", "paling utama pamungkas / puncak tertinggi terakhir",
     "Terjadi di akhir proses; yang terbaik, paling ekstrem, atau paling mendasar.",
     "Being or happening at the end of a process; final; best achieving maximum degree.",
     ["Ultimately", "Ultimatum", "Supreme"], ["Supreme", "Paramount", "Definitive", "Final", "Consummate"], ["Initial", "Primary", "Minor"],
     "Reaching the summit of Mount Everest was the ultimate milestone in her climbing career.",
     "Our ultimate objective is providing universal clean drinking water to every rural village."),

    ("Undergo", "verb", "B2", "/ˌʌn.dəˈɡəʊ/", "menjalani mengalami / melewati proses perubahan",
     "Mengalami atau mengalami sesuatu, biasanya suatu proses, perubahan, atau operasi bedah.",
     "Experience or be subjected to something, typically a process or situation.",
     ["Underwent", "Experience", "Endure"], ["Experience", "Endure", "Sustain", "Pass through", "Submit to"], ["Avoid", "Bypass"],
     "The historic downtown district will undergo a major revitalization program this winter.",
     "Athletes undergo rigorous physiological fitness screening before international championships."),

    ("Undertake", "verb", "B2", "/ˌʌn.dəˈteɪk/", "mengemban menyanggupi / memulai tugas besar",
     "Berkomitmen untuk melakukan atau memulai suatu proyek, tugas, atau ekspedisi resmi.",
     "Commit oneself to and begin an enterprise or responsibility; take on.",
     ["Undertaking", "Assume", "Commence"], ["Embark upon", "Commence", "Assume", "Tackle", "Initiate"], ["Neglect", "Abandon", "Decline"],
     "A team of international marine scientists will undertake a deep-sea research voyage.",
     "The municipality agreed to undertake the repair of all flood-damaged bridges."),

    ("Universalize", "verb", "C1", "/ˌjuː.nɪˈvɜː.səl.aɪz/", "menguniversalkan / memberlakukan secara menyeluruh",
     "Menjadikan sesuatu dapat diterapkan atau tersedia secara universal bagi semua orang.",
     "Make universal; generalize or apply universally across communities.",
     ["Universal", "Generalize", "Standardize"], ["Generalize", "Standardize", "Globalize", "Popularize"], ["Localize", "Restrict"],
     "Public health leaders strive to universalize access to essential preventive medicines.",
     "The educational reform sought to universalize high-quality secondary schooling nationwide."),

    ("Uproot", "verb", "B2", "/ʌpˈruːt/", "mencabut hingga akar / memindahkan paksa dari kampung",
     "Mencabut tanaman beserta seluruh akarnya dari tanah; memindahkan seseorang dari tempat asalnya.",
     "Pull something, especially a tree or plant, out of the ground by its roots; displace.",
     ["Uprooted", "Displace", "Eradicate"], ["Eradicate", "Dislodge", "Extirpate", "Displace", "Deracinate"], ["Plant", "Settle", "Establish", "Root"],
     "Violent typhoon winds managed to uproot several ancient banyan trees along the boulevard.",
     "The war forced thousands of innocent families to uproot their lives and seek safety abroad."),

    ("Utilize", "verb", "B1", "/ˈjuː.təl.aɪz/", "memanfaatkan / menggunakan secara berdaya guna",
     "Membuat penggunaan praktis dan efektif dari sesuatu sumber daya yang tersedia.",
     "Make practical and effective use of a resource or tool.",
     ["Utilization", "Useful", "Employ"], ["Employ", "Harness", "Apply", "Exploit", "Deploy"], ["Waste", "Misuse", "Ignore"],
     "Solar panel arrays utilize direct sunlight to generate clean electrical energy for the hospital.",
     "The workshop teaches small business owners how to utilize cloud computing tools efficiently."),

    ("Vacate", "verb", "B2", "/vəˈkeɪt/", "mengosongkan tempat / meninggalkan ruangan atau jabatan",
     "Meninggalkan suatu tempat seperti kamar atau bangunan; melepaskan jabatan resmi.",
     "Leave a place that one previously occupied; give up a position or post.",
     ["Vacation", "Vacancy", "Evacuate"], ["Evacuate", "Leave", "Abandon", "Relinquish", "Quit"], ["Occupy", "Inhabit", "Enter", "Fill"],
     "Hotel guests are kindly requested to vacate their rooms by eleven in the morning for cleaning.",
     "The judge will vacate her seat on the appellate court upon her official retirement in June."),

    ("Venerate", "verb", "C1", "/ˈven.ər.eɪt/", "memuliakan menghormati / memuja dengan takzim",
     "Menghormati dengan penuh rasa hormat yang mendalam dan kekaguman yang suci.",
     "Regard with great respect; revere and honor deeply.",
     ["Veneration", "Venerable", "Revere"], ["Revere", "Worship", "Honor", "Adore", "Hallow"], ["Despise", "Disdain", "Scorn", "Mock"],
     "Traditional communities venerate ancestral wisdom and practice mindful conservation of forests.",
     "Art historians venerate Renaissance master painters for their pioneering spatial perspectives."),

    ("Veracity", "noun", "C1", "/vəˈræs.ə.ti/", "kebenaran kejujuran / keakuratan fakta yang sahih",
     "Kesesuaian dengan fakta kebenaran; keakuratan dan kejujuran yang tidak diragukan.",
     "Conformity to facts; accuracy; habitual truthfulness.",
     ["Veracious", "Truth", "Accuracy"], ["Truthfulness", "Accuracy", "Correctness", "Fidelity", "Authenticity"], ["Falsehood", "Deceit", "Inaccuracy", "Lie"],
     "The investigative journalist spent weeks verifying the veracity of the leaked financial records.",
     "Historical scholars rely on primary source documents to verify the veracity of eyewitness chronicles."),

    ("Versatile", "adjective", "B2", "/ˈvɜː.sə.taɪl/", "serbaguna serbabisa / luwes beradaptasi aneka peran",
     "Mampu beradaptasi atau disesuaikan dengan berbagai fungsi atau kegiatan yang berbeda.",
     "Able to adapt or be adapted to many different functions or activities.",
     ["Versatility", "Adaptable", "Multipurpose"], ["Adaptable", "Multipurpose", "Flexible", "All-around", "Handy"], ["Inflexible", "Limited", "Rigid"],
     "The olive oil is a versatile culinary staple used for roasting vegetables, sauteing, and dressings.",
     "She is a versatile software engineer skilled in both frontend design and database architecture."),

    ("Vigilance", "noun", "B2", "/ˈvɪdʒ.əl.əns/", "kewaspadaan siaga / kesiagaan menjaga bahaya",
     "Tindakan atau keadaan tetap waspada terhadap kemungkinan bahaya atau kesulitan.",
     "The action or state of keeping careful watch for possible danger or difficulties.",
     ["Vigilant", "Vigilantly", "Watchfulness"], ["Watchfulness", "Alertness", "Caution", "Carefulness", "Surveillance"], ["Negligence", "Inattention", "Carelessness"],
     "Airport customs officials maintain strict security vigilance to prevent illegal wildlife smuggling.",
     "Cybersecurity experts emphasize continuous system vigilance against phishing attempts."),

    ("Vindicate", "verb", "C1", "/ˈvɪn.dɪ.keɪt/", "membersihkan nama baik / membuktikan kebenaran tuduhan",
     "Membersihkan seseorang dari tuduhan atau kecurigaan; membuktikan sesuatu itu benar.",
     "Clear someone of blame or suspicion; show or prove to be right, reasonable, or justified.",
     ["Vindication", "Justify", "Exonerate"], ["Exonerate", "Absolve", "Acquit", "Justify", "Defend"], ["Condemn", "Incriminate", "Blame"],
     "Newly discovered DNA evidence served to completely vindicate the wrongfully accused defendant.",
     "The triumphant clinical trial results vindicated the scientist's controversial vaccine hypothesis."),

    ("Volatile", "adjective", "B2", "/ˈvɒl.ə.taɪl/", "mudah menguap / labil bergejolak cepat berubah",
     "Mudah menguap pada suhu normal; cenderung berubah cepat dan tidak terduga, terutama menjadi lebih buruk.",
     "Liable to change rapidly and unpredictably, especially for the worse; evaporating rapidly.",
     ["Volatility", "Unstable", "Mercurial"], ["Unstable", "Mercurial", "Erratic", "Fickle", "Explosive"], ["Stable", "Constant", "Steady", "Calm"],
     "Stock market prices can be highly volatile during unexpected geopolitical developments.",
     "Ethanol and acetone are volatile organic chemical compounds that evaporate quickly at room temperature."),

    ("Vulnerable", "adjective", "B2", "/ˈvʌl.nər.ə.bəl/", "rentan mudah terluka / berisiko terserang bahaya",
     "Mudah terluka secara fisik atau emosional; rentan terhadap serangan atau bahaya.",
     "Susceptible to physical or emotional attack or harm; in need of special care.",
     ["Vulnerability", "Exposed", "Defenseless"], ["Defenseless", "Exposed", "Susceptible", "Unprotected", "Fragile"], ["Resilient", "Protected", "Invulnerable", "Secure"],
     "Small newborn sea turtles are extremely vulnerable to beach predators while scurrying to the ocean.",
     "Senior citizens and young infants are especially vulnerable to severe seasonal flu infections."),

    ("Waveform", "noun", "B2", "/ˈweɪv.fɔːm/", "bentuk gelombang / pola grafik osilasi frekuensi",
     "Bentuk visual dari gelombang suara, sinyal listrik, atau getaran yang digambarkan pada grafik.",
     "A curve showing the shape of a wave at a given time or position.",
     ["Wave", "Oscillation", "Frequency"], ["Oscillation", "Frequency curve", "Signal profile", "Graph"], ["N/A"],
     "Audio sound engineers analyze speech waveforms on screen to remove background noise clicks.",
     "An oscilloscope displays rhythmic cardiac electrical waveforms during medical monitoring."),

    ("Weary", "adjective", "B1", "/ˈwɪə.ri/", "sangat lelah letih / bosan jenuh berkepanjangan",
     "Merasa atau menunjukkan kelelahan fisik atau mental yang hebat; jenuh.",
     "Feeling or showing tiredness, especially as a result of excessive exertion or lack of sleep.",
     ["Weariness", "Tired", "Exhausted"], ["Exhausted", "Fatigued", "Tired", "Drained", "Worn out"], ["Refreshed", "Energetic", "Invigorated"],
     "The weary desert hikers rejoiced when they reached the shade and cool spring of the oasis.",
     "Citizens grew weary of unfulfilled campaign promises and demanded transparent governance."),

    ("Wondrously", "adverb", "B2", "/ˈwʌn.drəs.li/", "secara menakjubkan / dengan luar biasa memesona",
     "Dengan cara yang sangat menginspirasi rasa kagum, takjub, dan keajaiban.",
     "In a wonderful, delightful, or marvelous manner.",
     ["Wondrous", "Marvelously", "Superbly"], ["Marvelously", "Miraculously", "Splendidly", "Divinely", "Superbly"], ["Terribly", "Poorly"],
     "The night sky was wondrously clear, revealing the bright arc of the Milky Way galaxy.",
     "The violinist played wondrously, drawing deep emotional resonance from her antique instrument.")
]

print("Expanded gap closer: MR=", len(MR_GAP_CLOSER), "SZ=", len(SZ_GAP_CLOSER))
