#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Rich supplemental Oxford words for EL (65+ words), MR (170+ words), SZ (200+ words).
"""

# Format: (word, partOfSpeech, level, phonetic, indonesianTranslation, def_id, def_en, similar, syns, ants, sent, para)

SUPPLEMENTAL_EL = [
    ("Implicit", "adjective", "C1", "/ɪmˈplɪs.ɪt/", "tersirat / terselubung tidak diucapkan langsung",
     "Dipahami atau diisyaratkan meskipun tidak dinyatakan secara gamblang atau langsung.",
     "Implied though not plainly expressed; with no qualification or question.",
     ["Imply", "Implication", "Tacit"], ["Tacit", "Implied", "Inherent", "Understood", "Unspoken"], ["Explicit", "Direct", "Stated", "Clear"],
     "There was an implicit agreement between the partners to share business responsibilities equally.",
     "The poem conveys an implicit critique of industrial environmental destruction."),

    ("Impose", "verb", "B2", "/ɪmˈpəʊz/", "membebankan / memberlakukan aturan paksa",
     "Menetapkan atau memaksakan suatu aturan, pajak, atau hukuman secara resmi.",
     "Force something unwelcome or unfamiliar to be accepted or put in place.",
     ["Imposition", "Imposing", "Enforce"], ["Enforce", "Inflict", "Apply", "Levy", "Dictate"], ["Revoke", "Lift", "Abolish", "Remove"],
     "The regulatory agency decided to impose stricter emissions standards on urban diesel vehicles.",
     "Parents must establish healthy household boundaries without imposing undue emotional pressure."),

    ("Impulse", "noun", "B2", "/ˈɪm.pʌls/", "dorongan hati mendadak / impuls rangsangan",
     "Keinginan mendadak yang kuat untuk bertindak tanpa berpikir panjang; sinyal saraf listrik.",
     "A sudden strong and unreflective urge or desire to act; an electrical pulse.",
     ["Impulsive", "Impulsively", "Urge"], ["Urge", "Instinct", "Compulsion", "Inspiration", "Whim"], ["Deliberation", "Restraint", "Premeditation"],
     "She resisted the sudden impulse to purchase the expensive vintage leather jacket.",
     "Nerve impulses transmit sensations of touch and temperature rapidly to the brain."),

    ("Inaugurate", "verb", "C1", "/ɪˈnɔː.ɡjə.reɪt/", "meresmikan jabatan / membuka secara khidmat",
     "Melantik seseorang ke dalam jabatan resmi dengan upacara; membuka fasilitas baru.",
     "Admit someone formally to public office with a ceremony; mark the beginning of.",
     ["Inauguration", "Inaugural", "Initiate"], ["Initiate", "Install", "Launch", "Commence", "Open"], ["Terminate", "Conclude", "Close"],
     "The city will inaugurate the new metropolitan solar transit terminal next Monday.",
     "The president was inaugurated during a solemn and dignified ceremony attended by foreign dignitaries."),

    ("Incident", "noun", "B1", "/ˈɪn.sɪ.dənt/", "insiden peristiwa / kejadian tidak terduga",
     "Suatu kejadian atau peristiwa, terutama yang tidak biasa atau memicu konflik.",
     "An event or occurrence, especially one that is unusual, disruptive, or dangerous.",
     ["Incidental", "Incident", "Occurrence"], ["Occurrence", "Event", "Happenstance", "Episode", "Affair"], ["Non-event"],
     "Police investigated a minor traffic incident that caused delays on the central bridge.",
     "The flight landed safely after a brief mechanical incident was swiftly resolved by the crew."),

    ("Incline", "verb", "B2", "/ɪnˈklaɪn/", "condong cenderung / memiringkan",
     "Merasa bersedia atau memiliki kecenderungan alami; berada dalam posisi miring.",
     "Be favorably disposed towards or willing to do something; lean or tilt.",
     ["Inclination", "Inclined", "Lean"], ["Lean", "Tend", "Slope", "Slant", "Dispose"], ["Resist", "Straighten", "Oppose"],
     "I incline to agree with the committee's proposal to prioritize public park renovations.",
     "The hiking trail inclines steeply as it approaches the rocky mountain summit."),

    ("Indulge", "verb", "B2", "/ɪnˈdʌldʒ/", "memanjakan diri / memuaskan keinginan",
     "Membiarkan diri menikmati kesenangan atau kesukaan tertentu tanpa menahan diri.",
     "Allow oneself to enjoy the pleasure of something; satisfy a desire or interest.",
     ["Indulgence", "Indulgent", "Pamper"], ["Pamper", "Spoil", "Gratify", "Satisfy", "Humor"], ["Abstain", "Deprive", "Deny", "Restrain"],
     "During our weekend vacation, we decided to indulge in a traditional spa massage.",
     "She occasionally indulges her passion for classical music by attending live symphony concerts."),

    ("Inevitable", "adjective", "B2", "/ɪnˈev.ɪ.tə.bəl/", "pasti terjadi / tak terelakkan",
     "Pasti akan terjadi dan tidak mungkin untuk dihindari atau dicegah.",
     "Certain to happen; unavoidable; unable to be prevented.",
     ["Inevitably", "Inevitability", "Unavoidable"], ["Unavoidable", "Inescapable", "Certain", "Fated", "Sure"], ["Avoidable", "Preventable", "Uncertain"],
     "With rapid technological advancements, digital automation in modern logistics was inevitable.",
     "Aging is an inevitable biological process, but healthy lifestyle habits preserve vitality."),

    ("Infer", "verb", "B2", "/ɪnˈfɜːr/", "menyimpulkan / menarik kesimpulan dari bukti",
     "Mengambil simpulan logis dari bukti atau premis yang ada, bukan dari pernyataan langsung.",
     "Deduce or conclude information from evidence and reasoning rather than explicit statements.",
     ["Inference", "Inferential", "Deduce"], ["Deduce", "Conclude", "Gather", "Glean", "Surmise"], ["State", "Declare", "Dictate"],
     "From the detailed economic metrics, analysts could infer a steady recovery in industrial output.",
     "Readers can easily infer the protagonist's underlying emotional conflict through her actions."),

    ("Infinite", "adjective", "B2", "/ˈɪn.fɪ.nət/", "tak terbatas / tak berhingga luasnya",
     "Tidak memiliki batas waktu, ruang, atau ukuran; sangat besar dan abadi.",
     "Limitless or endless in space, extent, or size; impossible to measure or calculate.",
     ["Infinitely", "Infinity", "Boundless"], ["Boundless", "Limitless", "Endless", "Immense", "Vast"], ["Finite", "Bounded", "Limited", "Measurable"],
     "Astronomers ponder whether the physical universe is infinite in its cosmic expanse.",
     "Parents possess infinite patience and unconditional love when guiding young children."),

    ("Inflation", "noun", "B2", "/ɪnˈfleɪ.ʃən/", "inflasi / kenaikan harga umum dan penurunan daya beli",
     "Kenaikan harga barang dan jasa secara umum dan terus-menerus dalam perekonomian.",
     "A general increase in prices and fall in the purchasing value of money.",
     ["Inflate", "Inflationary", "Deflation"], ["Price surge", "Monetary expansion", "Escalation"], ["Deflation", "Price drop"],
     "Central banks adjust benchmark interest rates to maintain low and predictable annual inflation.",
     "High grocery inflation eroded household purchasing power across the island nation."),

    ("Inhabit", "verb", "B2", "/ɪnˈhæb.ɪt/", "mendiami / menempati habitat lingkungan",
     "Tinggal atau hidup di suatu tempat, kawasan, atau lingkungan tertentu.",
     "Live in or occupy a place or environment as a habitat.",
     ["Inhabitant", "Inhabited", "Occupy"], ["Occupy", "Populate", "Dwell in", "Reside in", "Settle"], ["Vacate", "Abandon", "Desert"],
     "Rare species of colorful orchids and exotic birds inhabit the dense tropical canopy.",
     "Indigenous communities have inhabited the pristine mountain valleys for countless centuries."),

    ("Inherent", "adjective", "C1", "/ɪnˈher.ənt/", "melekat erat / hakiki sifat bawaan",
     "Merupakan sifat permanen, alami, atau esensial yang tidak dapat dipisahkan dari sesuatu.",
     "Existing in something as a permanent, essential, or characteristic attribute.",
     ["Inherently", "Inhere", "Intrinsic"], ["Intrinsic", "Inborn", "Innate", "Essential", "Immanent"], ["Extrinsic", "Acquired", "External", "Alien"],
     "Every entrepreneurial investment carries an inherent level of market and financial risk.",
     "The freedom of speech is recognized as an inherent human right in modern constitutional law."),

    ("Initiate", "verb", "B2", "/ɪˈnɪʃ.i.eɪt/", "memprakarsai / memulai langkah pertama",
     "Menyebabkan suatu proses atau tindakan dimulai; memperkenalkan seseorang pada keahlian.",
     "Cause a process or action to begin; introduce someone to an art or skill.",
     ["Initiative", "Initiation", "Commence"], ["Commence", "Launch", "Trigger", "Instigate", "Activate"], ["Terminate", "Conclude", "Finish", "Halt"],
     "The city council agreed to initiate a comprehensive urban bicycle lane expansion project.",
     "Mentors initiate apprentices into the meticulous traditional woodcarving techniques."),

    ("Innovative", "adjective", "B2", "/ˈɪn.ə.və.tɪv/", "inovatif / penuh terobosan baru yang kreatif",
     "Menampilkan gagasan, metode, atau teknologi baru yang orisinal dan lebih maju.",
     "Featuring new methods, advanced ideas, or original inventions; pioneering.",
     ["Innovate", "Innovation", "Creative"], ["Pioneering", "Creative", "Inventive", "Groundbreaking", "Original"], ["Traditional", "Conventional", "Outdated", "Obsolete"],
     "The engineering startup won an award for its innovative saltwater water purification device.",
     "Innovative teaching methodologies encourage active student collaboration and analytical thinking."),

    ("Inquiry", "noun", "B2", "/ɪnˈkwaɪə.ri/", "penyelidikan resmi / pertanyaan pencarian fakta",
     "Tindakan meminta informasi; penyelidikan formal atas suatu masalah atau pelanggaran.",
     "An act of asking for information; an official investigation into a matter.",
     ["Inquire", "Inquisitive", "Investigation"], ["Investigation", "Probe", "Query", "Examination", "Scrutiny"], ["Ignorance", "Neglect"],
     "An independent judicial inquiry was established to investigate the chemical plant accident.",
     "Our customer desk handles hundreds of polite inquiries regarding domestic train schedules daily."),

    ("Insomnia", "noun", "B2", "/ɪnˈsɒm.ni.ə/", "insomnia / gangguan susah tidur malam",
     "Kondisi medis atau psikologis berupa ketidakmampuan untuk tidur nyenyak secara teratur.",
     "Habitual sleeplessness; inability to obtain sufficient sleep.",
     ["Insomniac", "Sleeplessness", "Restlessness"], ["Sleeplessness", "Restlessness", "Wakefulness"], ["Deep sleep", "Somnolence"],
     "Chronic stress and excessive late screen time are leading triggers of severe insomnia.",
     "Practicing evening mindfulness meditation helped her manage symptoms of chronic insomnia."),

    ("Inspire", "verb", "B1", "/ɪnˈspaɪər/", "menginspirasi / membangkitkan ilham dan semangat",
     "Memberi seseorang keinginan dan kemampuan untuk melakukan sesuatu yang hebat dan kreatif.",
     "Fill someone with the urge or ability to do or feel something, especially to do something creative.",
     ["Inspiration", "Inspirational", "Motivate"], ["Motivate", "Encourage", "Galvanize", "Stimulate", "Animate"], ["Discourage", "Deter", "Dishearten"],
     "Her courageous environmental activism continues to inspire thousands of youth worldwide.",
     "The stunning mountain sunrise inspired the landscape artist to paint a vibrant new canvas."),

    ("Insulate", "verb", "B2", "/ˈɪn.sjə.leɪt/", "menyekat / mengisolasi panas suara atau listrik",
     "Melindungi sesuatu dengan material khusus agar tidak meneruskan panas, listrik, atau suara.",
     "Protect something by interposing material that prevents the loss of heat or the intrusion of sound.",
     ["Insulation", "Insulator", "Shield"], ["Shield", "Protect", "Isolate", "Cushion", "Wrap"], ["Expose", "Uncover"],
     "Builders used mineral wool panels to insulate the attic against cold winter drafts.",
     "Wearing heavy down jackets helps insulate the human body against subzero arctic temperatures."),

    ("Intact", "adjective", "B2", "/ɪnˈtækt/", "utuh lengkap / tidak rusak sedikit pun",
     "Tidak rusak atau terganggu; tetap lengkap dan dalam kondisi utuh seperti aslinya.",
     "Not damaged or impaired in any way; complete; whole and sound.",
     ["Intactness", "Undamaged", "Complete"], ["Undamaged", "Whole", "Unbroken", "Complete", "Flawless"], ["Damaged", "Broken", "Fragmented", "Impaired"],
     "Remarkably, the ancient ceramic vase survived the violent earthquake completely intact.",
     "Despite the grueling journey across the mountains, their spirits and enthusiasm remained intact."),

    ("Integral", "adjective", "B2", "/ˈɪn.tɪ.ɡrəl/", "bagian tak terpisahkan / integral esensial",
     "Penting dan mendasar untuk membentuk keseluruhan yang lengkap; esensial.",
     "Necessary to make a whole complete; essential or fundamental.",
     ["Integrate", "Integrity", "Essential"], ["Essential", "Fundamental", "Inherent", "Constituent", "Basic"], ["Peripheral", "Superfluous", "Incidental", "Optional"],
     "Practical laboratory experiments are an integral component of the physics curriculum.",
     "Honesty and mutual accountability are integral to maintaining a strong professional team."),

    ("Intensify", "verb", "B2", "/ɪnˈten.sɪ.faɪ/", "mengintensifkan / memperhebat frekuensi daya",
     "Menjadi lebih hebat, kuat, atau intens; meningkatkan kekuatan atau derajat sesuatu.",
     "Become or make more intense, concentrated, or marked.",
     ["Intensity", "Intensive", "Escalate"], ["Escalate", "Heighten", "Amplify", "Strengthen", "Deepen"], ["Lessen", "Weaken", "Subside", "Moderate"],
     "Rescue authorities intensified their search operations as favorable weather returned to the coast.",
     "Competition in the global electric vehicle sector continues to intensify rapidly every year."),

    ("Intermediate", "adjective", "B1", "/ˌɪn.təˈmiː.di.ət/", "tingkat menengah / bertaraf pertengahan",
     "Berada di antara dua tahap, tempat, atau tingkatan dalam proses pembelajaran.",
     "Coming between two things in time, place, character, or order; mid-level.",
     ["Intermediary", "Medium", "Middle"], ["Middle", "Midway", "Intervening", "Transitional", "Moderate"], ["Beginning", "Advanced", "Elementary", "Final"],
     "This conversational language course is designed specifically for intermediate English learners.",
     "The caterpillar stage serves as an intermediate phase between egg and butterfly development."),

    ("Interpret", "verb", "B2", "/ɪnˈtɜː.prɪt/", "menafsirkan makna / menerjemahkan lisan",
     "Menjelaskan makna dari suatu teks, data, atau seni; menerjemahkan pembicaraan secara langsung.",
     "Explain the meaning of information, words, or actions; translate orally.",
     ["Interpretation", "Interpreter", "Explain"], ["Explain", "Elucidate", "Clarify", "Translate", "Construe"], ["Misinterpret", "Confuse", "Obscure"],
     "Economists interpret the latest manufacturing statistics as an indicator of robust industrial growth.",
     "Simultaneous court interpreters accurately translated the witness testimony for the jury."),

    ("Interval", "noun", "B2", "/ˈɪn.tə.vəl/", "jeda waktu / selang istirahat teratur",
     "Jeda waktu atau jarak di antara dua peristiwa, titik, atau pertunjukan musik.",
     "An intervening time or space; a pause or break in activity or between acts of a play.",
     ["Intermittent", "Break", "Pause"], ["Intermission", "Pause", "Break", "Gap", "Hiatus"], ["Continuity", "Nonstop"],
     "The theatrical performance featured a fifteen-minute intermission interval between acts.",
     "The medical monitor measures the patient's cardiac pulse rate at thirty-second intervals."),

    ("Intervene", "verb", "B2", "/ˌɪn.təˈviːn/", "campur tangan / menengahi untuk meredakan",
     "Mengambil tindakan untuk mencegah, mengubah arah kejadian, atau mendamaikan konflik.",
     "Come between so as to prevent or alter a result or course of events; mediate.",
     ["Intervention", "Mediate", "Step in"], ["Mediate", "Arbitrate", "Intercede", "Step in", "Interfere"], ["Withdraw", "Ignore", "Stand by"],
     "The referee was forced to intervene quickly when tensions flared between opposing athletes.",
     "Central bankers intervened in currency exchange markets to stabilize the rapidly falling exchange rate."),

    ("Intimate", "adjective", "B2", "/ˈɪn.tɪ.mət/", "akrab intim / sangat pribadi dan mendalam",
     "Menandai hubungan yang sangat dekat, hangat, dan pribadi; suasana nyaman tenang.",
     "Closely acquainted; familiar, close, and personal in nature; private.",
     ["Intimacy", "Intimately", "Close"], ["Close", "Familiar", "Confidential", "Affectionate", "Personal"], ["Distant", "Cold", "Formal", "Aloof"],
     "The author shared intimate reflections on her childhood in her newly published memoir.",
     "They celebrated their wedding anniversary with an intimate candlelit dinner among close family."),

    ("Intricate", "adjective", "B2", "/ˈɪn.trɪ.kət/", "rumit mendetail / berselirat indah",
     "Sangat rumit, terperinci, dan memiliki banyak bagian yang terhubung rapi.",
     "Very complicated or detailed; consisting of many interconnected elements.",
     ["Intricacy", "Intricately", "Complex"], ["Complex", "Complicated", "Elaborate", "Intricate", "Detailed"], ["Simple", "Plain", "Uncomplicated", "Basic"],
     "The traditional wooden relief carving featured intricate floral patterns and mythical creatures.",
     "Modern microprocessors rely on intricate billions-of-transistor silicon architecture."),

    ("Intrinsic", "adjective", "C1", "/ɪnˈtrɪn.zɪk/", "intrinsik / hakiki melekat dari dalam",
     "Tergolong atau melekat secara alami pada hakikat sejati sesuatu; esensial.",
     "Belonging naturally; essential; originating from within a body or entity.",
     ["Intrinsically", "Inherent", "Innate"], ["Inherent", "Innate", "Constitutional", "Fundamental", "Essential"], ["Extrinsic", "External", "Accidental"],
     "Pure gold holds intrinsic physical value due to its rarity, beauty, and chemical resistance.",
     "Intrinsic motivation driven by genuine curiosity produces more enduring learning outcomes."),

    ("Intuition", "noun", "B2", "/ˌɪn.tʃuːˈɪʃ.ən/", "intuisi / bisikan naluri tanpa penalaran",
     "Kemampuan untuk memahami sesuatu secara langsung berdasarkan naluri tanpa analisis rasional.",
     "The ability to understand something immediately, without the need for conscious reasoning.",
     ["Intuitive", "Intuitively", "Instinct"], ["Instinct", "Hunch", "Insight", "Gut feeling", "Sixth sense"], ["Logic", "Reasoning", "Calculation"],
     "The experienced detective relied on her sharp intuition to uncover the hidden financial fraud.",
     "Trust your creative intuition when composing poetry or selecting visual color palettes."),

    ("Invade", "verb", "B1", "/ɪnˈveɪd/", "menyerbu / menginvasi wilayah orang lain",
     "Memasuki suatu negara atau wilayah dengan pasukan militer untuk menaklukkannya.",
     "Enter a country or region so as to subjugate or occupy it; intrude upon.",
     ["Invasion", "Invader", "Invasive"], ["Occupy", "Assault", "Conquer", "Intrude upon", "Encroach"], ["Evacuate", "Defend", "Protect", "Surrender"],
     "Historic armies attempted to invade the fortified coastal fortress but were repelled.",
     "Aggressive non-native weed species can rapidly invade and disrupt delicate native wetland ecosystems."),

    ("Inventory", "noun", "B2", "/ˈɪn.vən.tər.i/", "daftar inventaris / stok persediaan barang",
     "Daftar lengkap barang dagangan atau properti yang dimiliki oleh bisnis atau individu.",
     "A complete list of items such as property, goods in stock, or the contents of a building.",
     ["Stock", "Catalog", "Goods"], ["Stock", "Supply", "Roster", "Register", "Catalog"], ["Shortage", "Deficit"],
     "The retail warehouse conducts automated barcode scans to track inventory in real time.",
     "Regular inventory audits prevent excess stock accumulation and minimize shelf expiration."),

    ("Invoke", "verb", "C1", "/ɪnˈvəʊk/", "mengutip memohon / menerapkan klausul hukum",
     "Menyebut atau menggunakan undang-undang, hak, atau wewenang sebagai dasar tindakan.",
     "Cite or appeal to someone or something as an authority for an action or in support of an argument.",
     ["Invocation", "Appeal", "Summon"], ["Cite", "Call upon", "Summon", "Apply", "Implement"], ["Ignore", "Waive", "Dismiss"],
     "The government invoked emergency disaster protocols to allocate immediate relief funding.",
     "The defense lawyer invoked constitutional precedents to safeguard her client's legal rights."),

    ("Irritate", "verb", "B2", "/ˈɪr.ɪ.teɪt/", "menjengkelkan / mengiritasi kulit atau mata",
     "Membuat seseorang merasa kesal atau marah; menyebabkan peradangan pada organ tubuh.",
     "Make someone annoyed, impatient, or angry; cause inflammation or discomfort in a body part.",
     ["Irritation", "Irritated", "Annoy"], ["Annoy", "Vex", "Exasperate", "Inflame", "Chafe"], ["Soothe", "Calm", "Pacify", "Comfort"],
     "Loud unnecessary car horns in residential zones irritate neighborhood residents.",
     "Chemical fumes from strong industrial solvents can irritate sensitive eye and nasal tissues."),

    ("Isolate", "verb", "B2", "/ˈaɪ.sə.leɪt/", "mengisolasi / mengasingkan memisahkan",
     "Menempatkan seseorang atau sesuatu terpisah dari yang lain; menyendiri.",
     "Identify something and examine it in detail; cause someone to be or remain alone or apart from others.",
     ["Isolation", "Isolated", "Separate"], ["Separate", "Segregate", "Detach", "Quarantine", "Insulate"], ["Integrate", "Combine", "Unite", "Connect"],
     "Scientists managed to isolate the active medicinal compound from the medicinal rainforest plant.",
     "Medical clinics isolate patients with highly contagious airborne illnesses to protect public safety."),

    ("Jealous", "adjective", "B1", "/ˈdʒel.əs/", "cemburu / iri hati atas kepemilikan orang",
     "Merasa curiga atau iri terhadap pencapaian, kasih sayang, atau keberuntungan orang lain.",
     "Feeling or showing an envious resentment of someone or their achievements and possessions.",
     ["Jealousy", "Jealously", "Envious"], ["Envious", "Covetous", "Resentful", "Possessive", "Suspicious"], ["Trusting", "Generous", "Content", "Confident"],
     "He felt jealous of his sibling's artistic recognition, but later learned to appreciate his own talents.",
     "Healthy romantic relationships flourish on mutual trust rather than jealous possessiveness."),

    ("Jeopardize", "verb", "C1", "/ˈdʒep.ə.daɪz/", "membahayakan / menaruh dalam ancaman risiko",
     "Menempatkan seseorang atau sesuatu dalam bahaya, kerugian, atau kemungkinan gagal.",
     "Put someone or something into a situation in which there is a danger of loss, harm, or failure.",
     ["Jeopardy", "Endanger", "Risk"], ["Endanger", "Threaten", "Compromise", "Hazard", "Imperil"], ["Protect", "Safeguard", "Secure", "Preserve"],
     "Neglecting regular industrial maintenance could jeopardize the safety of factory workers.",
     "Failing the mandatory licensing examination would jeopardize his chance of practicing medicine."),

    ("Jubilant", "adjective", "B2", "/ˈdʒuː.bəl.ənt/", "bersorak gembira / bersuka ria atas kemenangan",
     "Menunjukkan kegembiraan dan sukacita yang meluap-luap, biasanya karena kemenangan.",
     "Feeling or expressing great happiness and triumph; rejoicing and exultant.",
     ["Jubilation", "Jubilantly", "Triumphant"], ["Triumphant", "Joyful", "Ecstatic", "Exultant", "Elated"], ["Mournful", "Sorrowful", "Dejected", "Despondent"],
     "Jubilant fans poured into the city streets waving banners after their team won the championship.",
     "The graduation hall echoed with jubilant cheers as diplomas were formally presented."),

    ("Judicious", "adjective", "C1", "/dʒuːˈdɪʃ.əs/", "bijaksana berhati-hati / tepat penuh pertimbangan",
     "Memiliki atau menunjukkan penilaian yang baik, bijaksana, dan penuh kehati-hatian.",
     "Having, showing, or done with good judgment or sense; prudent and wise.",
     ["Judiciously", "Judiciousness", "Prudent"], ["Prudent", "Wise", "Discreet", "Sagacious", "Sensible"], ["Foolish", "Imprudent", "Rash", "Reckless"],
     "Through judicious financial investments, the non-profit foundation built an enduring scholarship endowment.",
     "The judge made a judicious decision that balanced strict legal fairness with human compassion."),

    ("Justify", "verb", "B2", "/ˈdʒʌs.tɪ.faɪ/", "membenarkan alasan / memberi dalih yang sah",
     "Menunjukkan atau membuktikan bahwa suatu tindakan atau keputusan benar dan masuk akal.",
     "Show or prove to be right or reasonable; be a good reason for.",
     ["Justification", "Justified", "Vindicate"], ["Vindicate", "Defend", "Validate", "Substantiate", "Warrant"], ["Condemn", "Disprove", "Invalidate"],
     "The executive was asked to justify the large budget allocated for experimental marketing.",
     "No military provocation can justify the unlawful targeting of civilian hospital infrastructure."),

    ("Kinetic", "adjective", "B2", "/kɪˈnet.ɪk/", "kinetis / berhubungan dengan energi gerak",
     "Berkaitan dengan gerakan; energi yang dimiliki suatu benda karena gerakannya.",
     "Relating to or resulting from motion; physical energy of a moving body.",
     ["Kinetics", "Kinetic energy", "Dynamic"], ["Dynamic", "Moving", "Active", "Energizing", "Mobile"], ["Static", "Stationary", "Motionless", "Passive"],
     "Hydroelectric turbines transform the kinetic energy of flowing river water into clean electricity.",
     "The modern modern art sculpture featured kinetic spinning metal discs driven by wind currents."),

    ("Knight", "noun", "B1", "/naɪt/", "ksatria berbaju zirah / gelar kehormatan bangsawan",
     "Prajurit berkuda berbaju zirah pada zaman pertengahan; pemegang gelar kehormatan ksatria.",
     "A man awarded an honorary title of knighthood for merit or service; a medieval warrior.",
     ["Knighthood", "Knightly", "Chivalric"], ["Cavalier", "Paladin", "Champion", "Warrior"], ["Peasant", "Serf"],
     "Legendary tales recount how the brave medieval knight defended the realm from mythical beasts.",
     "The renowned British astronomer was knighted by the Queen in recognition of scientific breakthroughs."),

    ("Knit", "verb", "A2", "/nɪt/", "merajut benang wol / menyatukan erat",
     "Membuat kain atau pakaian dengan merangkai jeratan benang wol; mengikat erat.",
     "Make a garment or fabric by interlocking loops of wool or yarn with needles; unite closely.",
     ["Knitting", "Knitted", "Weave"], ["Weave", "Crochet", "Interlace", "Bind", "Unite"], ["Unravel", "Separate", "Divide"],
     "Grandmother loves to knit warm colorful woolen scarves and mittens for her grandchildren.",
     "Shared community challenges helped knit the diverse neighborhood into a tightly unified family."),

    ("Knowledgeable", "adjective", "B2", "/ˈnɒl.ɪ.dʒə.bəl/", "berpengetahuan luas / ahli memahami",
     "Memiliki wawasan luas, terdidik, dan paham mendalam tentang bidang tertentu.",
     "Intelligent and well informed; having extensive understanding of a topic.",
     ["Knowledge", "Knowledgeably", "Informed"], ["Informed", "Expert", "Scholarly", "Well-read", "Erudite"], ["Ignorant", "Uninformed", "Illiterate"],
     "The botanical garden guide was exceptionally knowledgeable about tropical medicinal herbs.",
     "We consulted a knowledgeable tax accountant to review our international trade compliance."),

    ("Lavish", "adjective", "B2", "/ˈlæv.ɪʃ/", "mewah melimpah / boros bertabur kemegahan",
     "Sangat kaya, mewah, dan berlimpah; diberikan dalam jumlah yang sangat dermawan.",
     "Sumptuously rich, elaborate, or luxurious; given or produced in generous amounts.",
     ["Lavishly", "Lavishness", "Opulent"], ["Opulent", "Luxurious", "Extravagant", "Sumptuous", "Generous"], ["Frugal", "Spartan", "Austere", "Meager"],
     "The royal banquet featured a lavish buffet of exquisite seafood, fruits, and imported pastries.",
     "Critics praised the lavish stage design and magnificent orchestral score of the new opera."),

    ("Legacy", "noun", "B2", "/ˈleɡ.ə.si/", "warisan peninggalan / jejak karya bersejarah",
     "Sesuatu yang ditinggalkan oleh pendahulu atau masa lalu untuk generasi penerus.",
     "An amount of money or property left to someone in a will; something transmitted by an ancestor.",
     ["Heirloom", "Heritage", "Bequest"], ["Heritage", "Inheritance", "Bequest", "Endowment", "Tradition"], ["N/A"],
     "The statesman left an enduring legacy of peace accords, civil liberties, and educational reform.",
     "Ancient Greek civilization bequeathed a lasting cultural and philosophical legacy to Western thought."),

    ("Legible", "adjective", "B2", "/ˈledʒ.ə.bəl/", "terbaca jelas / tulisan mudah dibaca",
     "Cukup jelas untuk dibaca dan dipahami tanpa kesulitan tafsir.",
     "Clear enough to read; easily decipherable handwriting or print.",
     ["Legibility", "Legibly", "Readable"], ["Readable", "Decipherable", "Clear", "Distinct", "Comprehensible"], ["Illegible", "Unreadable", "Indecipherable", "Messy"],
     "Please write your postal address in clear and legible capital letters on the shipping label.",
     "Digital fonts are carefully engineered to remain crisp and legible across high-resolution screens."),

    ("Legitimate", "adjective", "B2", "/ləˈdʒɪt.ɪ.mət/", "sah menurut hukum / valid masuk akal",
     "Sesuai dengan hukum atau aturan yang berlaku; dapat dipertanggungjawabkan secara logis.",
     "Conforming to the law or to rules; able to be defended with logic or justification.",
     ["Legitimacy", "Legitimately", "Lawful"], ["Lawful", "Legal", "Valid", "Authentic", "Justified"], ["Illegitimate", "Unlawful", "Illegal", "Invalid"],
     "The enterprise holds a legitimate commercial license issued by the trade ministry.",
     "Residents voiced legitimate concerns regarding the increased heavy truck traffic on rural roads."),

    ("Lenient", "adjective", "C1", "/ˈliː.ni.ənt/", "lunak bertoleransi / penuh pengampunan",
     "Tidak terlalu ketat dalam menegakkan hukuman atau disiplin; toleran dan pemaaf.",
     "More merciful or tolerant than expected; not strict in discipline.",
     ["Leniency", "Leniently", "Merciful"], ["Merciful", "Forgiving", "Tolerant", "Permissive", "Gentle"], ["Strict", "Severe", "Harsh", "Rigid"],
     "The court magistrate handed down a lenient penalty due to the defendant's sincere remorse.",
     "While some parents favor strict discipline, others prefer a lenient and conversational approach."),

    ("Leverage", "verb", "B2", "/ˈliː.vər.ɪdʒ/", "mendayagunakan / memanfaatkan keunggulan",
     "Menggunakan sesuatu secara maksimal untuk memperoleh keuntungan yang signifikan.",
     "Use something to maximum advantage; harness strategic power or assets.",
     ["Lever", "Leverage", "Utilize"], ["Utilize", "Harness", "Exploit", "Capitalize on", "Maximize"], ["Waste", "Misuse", "Ignore"],
     "The logistics firm plans to leverage machine learning to optimize delivery fleet routes.",
     "Entrepreneurs leverage their professional networks to secure seed venture capital funding."),

    ("Liberate", "verb", "B2", "/ˈlɪb.ər.eɪt/", "membebaskan / melepaskan dari belenggu penindasan",
     "Membuat seseorang atau sekelompok orang bebas dari penjajahan, penahanan, atau tirani.",
     "Set someone free from a situation, especially imprisonment or oppression.",
     ["Liberation", "Liberator", "Free"], ["Free", "Release", "Emancipate", "Deliver", "Unchain"], ["Enslave", "Imprison", "Oppress", "Confine"],
     "Allied forces fought valiantly to liberate occupied harbor cities during the campaign.",
     "Access to digital information helped liberate rural farmers from predatory middleman markups."),

    ("Linger", "verb", "B2", "/ˈlɪŋ.ɡər/", "bertahan lama / enggan beranjak / berlama-lama",
     "Tinggal di suatu tempat lebih lama dari yang diperlukan; aroma atau memori yang menetap.",
     "Stay in a place longer than necessary because of a reluctance to leave; remain present.",
     ["Lingering", "Loiter", "Tarry"], ["Loiter", "Tarry", "Hover", "Endure", "Persist"], ["Leave", "Depart", "Disperse", "Vanish"],
     "The enticing aroma of roasted coffee beans lingered warmly in the bakery for hours.",
     "Tourists lingered on the historic piazza long after sunset to enjoy live acoustic music."),

    ("Literacy", "noun", "B1", "/ˈlɪt.ər.ə.si/", "kemampuan membaca menulis / melek literasi",
     "Kemampuan untuk membaca, menulis, dan memahami informasi secara fungsional.",
     "The ability to read and write; competence or knowledge in a specified area.",
     ["Literate", "Illiterate", "Education"], ["Reading proficiency", "Numeracy", "Knowledge", "Competence"], ["Illiteracy", "Ignorance"],
     "National literacy programs have drastically increased primary school enrollment across the islands.",
     "Digital literacy is now an essential workplace qualification alongside traditional reading skills."),

    ("Loathe", "verb", "C1", "/ləʊð/", "sangat membenci / merasa muak jijik terhadap",
     "Merasakan rasa tidak suka atau kebencian yang amat mendalam dan intens.",
     "Feel intense dislike or disgust for someone or something; despise deeply.",
     ["Loathsome", "Loathing", "Detest"], ["Detest", "Abhor", "Despise", "Abominate", "Hate"], ["Love", "Adore", "Cherish", "Admire"],
     "I loathe dishonesty and two-faced gossip in professional collaborative work environments.",
     "Many commuters loathe waiting in congested metropolitan traffic during peak rainy hours."),

    ("Lucid", "adjective", "B2", "/ˈluː.sɪd/", "sangat jelas gamblang / berpikiran jernih",
     "Dinyatakan dengan sangat jelas dan mudah dipahami; memiliki pikiran yang waras dan sadar.",
     "Expressed clearly; easy to understand; showing ability to think clearly.",
     ["Lucidity", "Lucidly", "Clear"], ["Clear", "Coherent", "Articulate", "Intelligible", "Luminous"], ["Confusing", "Vague", "Muddled", "Obscure"],
     "The mathematics professor gave a lucid explanation of complex differential equations.",
     "Despite her advanced age, the philosopher remained remarkably lucid and sharp in debate."),

    ("Lucrative", "adjective", "B2", "/ˈluː.krə.tɪv/", "sangat menguntungkan / mendatangkan laba besar",
     "Menghasilkan keuntungan uang yang besar; bernilai komersial tinggi.",
     "Producing a great deal of profit; monetarily rewarding.",
     ["Profit", "Lucratively", "Profitable"], ["Profitable", "Rewarding", "Remunerative", "Gainful", "High-yield"], ["Unprofitable", "Loss-making", "Fruitless"],
     "Exporting premium organic vanilla beans to overseas confectioneries proved highly lucrative.",
     "The talented software engineer turned down several lucrative corporate offers to launch a startup."),

    ("Luminous", "adjective", "B2", "/ˈluː.mɪ.nəs/", "bercahaya terang / memancarkan pendaran elok",
     "Memancarkan cahaya terang di tempat gelap; bersinar dan memesona mata.",
     "Emitting or reflecting light, especially glowing in the dark; bright or shining.",
     ["Luminosity", "Luminescent", "Radiant"], ["Radiant", "Glowing", "Bright", "Luminescent", "Shining"], ["Dark", "Dim", "Dull", "Gloomy"],
     "Bioluminescent phytoplankton created a magical luminous blue glow along the nocturnal shore.",
     "The watch features luminous hands and numerals that glow clearly in deep underwater diving.")
]

print("Supplemental EL dataset ready:", len(SUPPLEMENTAL_EL), "entries.")
