#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Rich additional Oxford words for SZ (Part 4) to ensure > 260 words.
"""

SZ_EXTRA_PART2 = [
    ("Unanimous", "adjective", "B2", "/juːˈnæn.ɪ.məs/", "aklamasi bulat / sepakat serempak tanpa bantahan",
     "Pendapat atau keputusan yang disetujui sepenuhnya oleh semua pihak tanpa ada yang menentang.",
     "Held or arrived at by the agreement of everyone involved; consensus.",
     ["Unanimously", "Unanimity", "Consensus"], ["Consensus", "Agreed", "Harmonious", "United", "Undivided"], ["Divided", "Split", "Conflicted"],
     "The jury reached a unanimous verdict of not guilty after reviewing the surveillance footage.",
     "The school board took a unanimous vote to construct a modern STEM science laboratory."),

    ("Uncanny", "adjective", "C1", "/ʌnˈkæn.i/", "aneh misterius / mirip luar biasa menakjubkan",
     "Aneh atau misterius sehingga membangkitkan rasa takjub; kemiripan yang sangat luar biasa.",
     "Strange or mysterious, especially in an unsettling way; remarkable resemblance.",
     ["Uncannily", "Eerie", "Mysterious"], ["Eerie", "Mysterious", "Freakish", "Weird", "Supernatural"], ["Ordinary", "Normal", "Familiar"],
     "The portrait painter had an uncanny ability to capture the hidden personality of his subjects.",
     "The twin sisters shared an uncanny knack for finishing each other's sentences spontaneously."),

    ("Undermine", "verb", "B2", "/ˌʌn.dəˈmaɪn/", "merongrong merusak / melemahkan fondasi otoritas",
     "Mengikis fondasi di bawah sesuatu; melemahkan atau merusak wibawa atau efektivitas perlahan.",
     "Erode the base or foundation of; damage or weaken gradually, especially insidious.",
     ["Undermined", "Weaken", "Subvert"], ["Weaken", "Subvert", "Compromise", "Erode", "Sabotage"], ["Strengthen", "Reinforce", "Bolster", "Support"],
     "Spreading unfounded rumors can undermine mutual trust and psychological safety within a team.",
     "Heavy coastal erosion threatened to undermine the stone foundations of the historic lighthouse."),

    ("Understatement", "noun", "B2", "/ˈʌn.dəˌsteɪt.mənt/", "pernyataan merendah / penyederhanaan situasi genting",
     "Pernyataan yang menggambarkan sesuatu kurang penting atau buruk daripada kenyataan sebenarnya.",
     "The presentation of something as being smaller, worse, or less important than it actually is.",
     ["Understate", "Euphemism", "Restraint"], ["Restraint", "Euphemism", "Modesty", "Minimization"], ["Overstatement", "Exaggeration", "Hyperbole"],
     "To say the Arctic winter is chilly is a humorous understatement; it is freezing cold.",
     "Saying the marathon was difficult was an understatement after six hours running in pouring rain."),

    ("Unfathomable", "adjective", "C1", "/ʌnˈfæð.ə.mə.bəl/", "tak terselami / tak terduga dalamnya",
     "Tidak mampu dipahami sepenuhnya karena terlalu misterius atau sangat dalam.",
     "Incapable of being fully explored or understood; impossible to measure the depth of.",
     ["Fathom", "Inscrutable", "Mysterious"], ["Inscrutable", "Incomprehensible", "Bottomless", "Abyssal", "Enigmatic"], ["Fathomable", "Comprehensible", "Clear", "Simple"],
     "The sheer physical scale of the observable universe remains unfathomable to the human mind.",
     "Why the ancient civilization abandoned their stone mountain cities remains an unfathomable mystery."),

    ("Uniform", "adjective", "B2", "/ˈjuː.nɪ.fɔːm/", "seragam selaras / memiliki bentuk yang sama konsisten",
     "Tetap sama dalam segala hal; tidak berbeda dari satu bagian atau waktu ke yang lain.",
     "Remaining the same in all cases and at all times; unchanging in form or character.",
     ["Uniformity", "Uniformly", "Consistent"], ["Consistent", "Equal", "Homogeneous", "Regular", "Standard"], ["Varied", "Diverse", "Irregular", "Uneven"],
     "The bakery ensures that all artisanal sourdough loaves are baked to a uniform golden crust.",
     "The international shipping containers have uniform standard dimensions for intermodal transport."),

    ("Unique", "adjective", "A2", "/juːˈniːk/", "unik tiada duanya / istimewa khas tersendiri",
     "Satu-satunya dari jenisnya; berbeda dari yang lain dan memiliki ciri khas istimewa.",
     "Being the only one of its kind; unlike anything else; remarkable and special.",
     ["Uniqueness", "Uniquely", "Singular"], ["Singular", "Distinctive", "Incomparable", "Sole", "Peculiar"], ["Common", "Generic", "Ordinary", "Standard"],
     "Each human fingerprint exhibits a unique ridge pattern that remains unchanged for life.",
     "Indonesia's rich cultural heritage is celebrated for its unique blend of ancient traditions."),

    ("Universal", "adjective", "B1", "/ˌjuː.nɪˈvɜː.səl/", "universal menyeluruh / berlaku bagi semua di dunia",
     "Berlaku atau dialami oleh semua orang atau di semua tempat; mencakup seluruh dunia.",
     "Of, affecting, or done by all people or things in the world or in a particular group; applicable everywhere.",
     ["Universally", "Universe", "Global"], ["Global", "Worldwide", "Omnipresent", "All-inclusive", "Ubiquitous"], ["Local", "Regional", "Particular", "Specific"],
     "A mother's tender love for her newborn baby is an enduring and universal human emotion.",
     "The United Nations adopted the Universal Declaration of Human Rights to safeguard human dignity."),

    ("Unravel", "verb", "B2", "/ʌnˈræv.əl/", "mengurai benang kusut / membongkar teka-teki rahasia",
     "Menguraikan serat atau benang yang terjalin; menyelidiki dan memecahkan misteri rumit.",
     "Undo twisted, knitted, or woven threads; investigate and solve or explain something complicated.",
     ["Unraveling", "Untangle", "Solve"], ["Untangle", "Decipher", "Resolve", "Disentangle", "Unwind"], ["Tangle", "Complicate", "Knot"],
     "Geneticists used modern genome sequencing technology to unravel the mystery of the inherited condition.",
     "The knitted wool scarf began to unravel when a loose thread caught on the wire fence."),

    ("Untangle", "verb", "B2", "/ʌnˈtæŋ.ɡəl/", "menguraikan kekusutan / melepaskan simpul ruwet",
     "Membuat bebas dari kusut atau jeratan; menyelesaikan masalah atau kesalahpahaman yang rumit.",
     "Free something from a tangled, knotted, or confusing condition; make clear.",
     ["Disentangle", "Unravel", "Clarify"], ["Disentangle", "Unwind", "Unravel", "Straighten", "Sort out"], ["Entangle", "Snarl", "Knot", "Twist"],
     "She patiently untangled the long string of decorative holiday fairy lights before hanging them.",
     "Experienced mediators helped untangle the web of complex contract disputes between the firms."),

    ("Unveil", "verb", "B2", "/ʌnˈveɪl/", "membuka selubung / meluncurkan produk perdana",
     "Membuka kain penutup patung atau monumen; memperkenalkan produk atau rencana baru ke publik.",
     "Remove a veil or covering from, in particular uncover a new monument; reveal or introduce.",
     ["Veil", "Reveal", "Launch"], ["Reveal", "Disclose", "Launch", "Introduce", "Expose"], ["Conceal", "Cover", "Hide", "Mask"],
     "The tech automaker will officially unveil its next-generation hydrogen electric SUV at the expo.",
     "The mayor gathered with community leaders to unveil the bronze memorial statue in the city park."),

    ("Uphold", "verb", "B2", "/ʌpˈhəʊld/", "menjunjung tinggi / menegakkan keadilan dan sumpah",
     "Mempertahankan atau mendukung keputusan atau hukum yang benar dan adil; menjaga prinsip.",
     "Maintain or support a law, decision, or principle against opposition; confirm or validate.",
     ["Upholder", "Sustain", "Defend"], ["Defend", "Sustain", "Champion", "Preserve", "Vindicate"], ["Violate", "Overturn", "Subvert", "Abandon"],
     "Judges take a solemn oath to uphold the constitutional principles of fairness and human rights.",
     "The supreme court voted to uphold the landmark clean water environmental protection ruling."),

    ("Upright", "adjective", "B2", "/ˈʌp.raɪt/", "berdiri tegak lurus / berbudi luhur jujur",
     "Berdiri lurus ke atas; seseorang yang memiliki integritas moral tinggi dan jujur luhur.",
     "In a vertical position; strictly honorable, honest, and morally respectable.",
     ["Uprightness", "Vertical", "Honorable"], ["Vertical", "Erect", "Honorable", "Righteous", "Virtuous"], ["Prone", "Horizontal", "Dishonorable", "Corrupt"],
     "Always maintain an upright posture while working at the desk to prevent lower spinal strain.",
     "He was known throughout the town as an upright and compassionate civic leader of noble character."),

    ("Uprising", "noun", "B2", "/ˈʌpˌraɪ.zɪŋ/", "pemberontakan rakyat / perlawanan massal menegakkan hak",
     "Tindakan perlawanan massal atau pemberontakan rakyat melawan penguasa tirani.",
     "An act of resistance or rebellion; a revolt against oppressive authority.",
     ["Rise", "Rebellion", "Insurrection"], ["Rebellion", "Revolt", "Insurrection", "Mutiny", "Revolution"], ["Suppression", "Submission", "Peace"],
     "The historic peasant uprising paved the way for sweeping land tenure and agricultural reforms.",
     "Citizens staged an unarmed civil uprising to demand democratic elections and freedom of speech."),

    ("Uproar", "noun", "B2", "/ˈʌp.rɔːr/", "kegemparan ribut / hiruk-pikuk protes kemarahan",
     "Keadaan ribut, gaduh, dan gempar akibat protes keras publik atau kekacauan.",
     "A public expression of protest or outrage; a condition of noise and tumultuous excitement.",
     ["Tumult", "Commotion", "Hubbub"], ["Tumult", "Commotion", "Hubbub", "Clamor", "Outcry"], ["Quiet", "Silence", "Tranquility", "Calm"],
     "The sudden cancellation of the popular weekend train service caused an uproar among commuters.",
     "The courtroom erupted in an uproar when the surprising confession was unexpectedly announced."),

    ("Uptake", "noun", "B2", "/ˈʌp.teɪk/", "daya serap pemanfaatan / kecepatan memahami sesuatu",
     "Tindakan menyerap atau memanfaatkan sesuatu yang tersedia; kecepatan memahami penjelasan.",
     "The taking up or absorption of that which is available; the rate of understanding.",
     ["Absorption", "Adoption", "Consumption"], ["Absorption", "Adoption", "Consumption", "Intake", "Assimilation"], ["Rejection", "Discharge"],
     "Public health centers reported a high community uptake rate for the seasonal influenza vaccine.",
     "She is remarkably quick on the uptake, grasping complex mathematical proofs on her first try."),

    ("Urban", "adjective", "A2", "/ˈɜː.bən/", "perkotaan urban / berkaitan dengan kehidupan kota",
     "Berkaitan dengan kota atau ciri khas kehidupan masyarakat di wilayah perkotaan.",
     "Relating to, or characteristic of a town or city rather than the countryside.",
     ["Urbanization", "Suburban", "Metropolitan"], ["Metropolitan", "City", "Civic", "Municipal", "Town-based"], ["Rural", "Pastoral", "Rustic", "Agrarian"],
     "Urban planning experts promote bicycle lanes and green rooftop parks to cool downtown districts.",
     "Rapid urban growth requires substantial public investments in clean water and rapid transit."),

    ("Utter", "adjective", "B2", "/ˈʌt.ər/", "mutlak sama sekali / menyeluruh tanpa keraguan",
     "Lengkap, mutlak, dan menyeluruh; tidak terbatas sama sekali kualitasnya.",
     "Complete; absolute; unqualified in extent or degree.",
     ["Utterly", "Absolute", "Complete"], ["Absolute", "Complete", "Total", "Outright", "Sheer"], ["Partial", "Incomplete", "Moderate", "Slight"],
     "The surprise birthday celebration was an utter shock to her, bringing joyful tears to her eyes.",
     "The abandoned mountain ghost town was cloaked in utter silence beneath the starry night sky."),

    ("Vague", "adjective", "B1", "/veɪɡ/", "samar tidak jelas / kabur rancu penjelasannya",
     "Kurang jelas, kabur, atau tidak terdefinisikan dengan baik; tidak spesifik maknanya.",
     "Of uncertain, indefinite, or unclear character or meaning; thinking or communicating in an unfocused way.",
     ["Vaguely", "Vagueness", "Indefinite"], ["Indefinite", "Ambiguous", "Hazy", "Obscure", "Faint"], ["Clear", "Explicit", "Precise", "Definite"],
     "The contract contained several vague clauses regarding payment deadlines that needed legal revision.",
     "I have only a vague recollection of visiting that quaint lakeside cottage during my early childhood."),

    ("Vain", "adjective", "B2", "/veɪn/", "sia-sia tak berbuah / sombong memamerkan rupa",
     "Tidak membuahkan hasil positif atau sia-sia; terlalu bangga akan penampilan diri.",
     "Producing no result; useless; having or showing an excessively high opinion of one's appearance.",
     ["Vanity", "In vain", "Futile"], ["Futile", "Fruitless", "Pointless", "Conceited", "Narcissistic"], ["Effective", "Productive", "Humble", "Modest"],
     "Rescue teams made valiant but vain efforts to save the wooden sailing ship from the jagged reef.",
     "He was so vain that he spent twenty minutes checking his reflection in every storefront mirror."),

    ("Valiant", "adjective", "B2", "/ˈvæl.i.ənt/", "pemberani gagah perkasa / berani berkorban",
     "Menunjukkan keberanian dan tekad yang besar, terutama dalam menghadapi bahaya besar.",
     "Possessing or showing courage or determination; brave and heroic.",
     ["Valiantly", "Valor", "Heroic"], ["Heroic", "Brave", "Courageous", "Dauntless", "Gallant"], ["Cowardly", "Timid", "Fearful", "Craven"],
     "The valiant firefighters entered the burning timber warehouse to rescue trapped warehouse workers.",
     "Despite the championship loss, the young underdog football team put up a valiant performance."),

    ("Valid", "adjective", "A2", "/ˈvæl.ɪd/", "sah berlaku / berdasar kuat dan logis",
     "Memiliki dasar yang kuat dalam logika atau fakta; sah menurut hukum dan peraturan resmi.",
     "Having a sound basis in logic or fact; reasonable; legally or officially acceptable.",
     ["Validity", "Validate", "Sound"], ["Legitimate", "Sound", "Authentic", "Legal", "Reasonable"], ["Invalid", "Void", "False", "Illegitimate"],
     "Please ensure your international travel passport is valid for at least six months before departure.",
     "The research team raised a valid scientific question regarding sample size discrepancies."),

    ("Valor", "noun", "B2", "/ˈvæl.ər/", "keberanian perkasa / ketabahan luhur di medan laga",
     "Keberanian atau ketabahan yang luar biasa besar, terutama dalam pertempuran atau bahaya.",
     "Great courage in the face of danger, especially in battle; heroism.",
     ["Valiant", "Heroism", "Bravery"], ["Bravery", "Heroism", "Courage", "Fortitude", "Gallantry"], ["Cowardice", "Fear", "Timidity"],
     "The decorated veteran was honored with a medal of valor for saving comrades in battle.",
     "Folklore ballads celebrate the noble valor and selfless dedication of legendary knights."),

    ("Vanish", "verb", "A2", "/ˈvæn.ɪʃ/", "lenyap menghilang / sirna tanpa jejak",
     "Menghilang secara tiba-tiba dan tuntas dari pandangan atau keberadaan.",
     "Disappear suddenly and completely; cease to exist or be perceptible.",
     ["Disappear", "Evaporate", "Fade"], ["Disappear", "Dissolve", "Evaporate", "Fade", "Melt away"], ["Appear", "Emerge", "Materialize", "Arrive"],
     "The morning mist began to vanish as warm golden sunshine bathed the mountain valley.",
     "Ancient tropical rain forests risk vanishing forever unless strict anti-logging laws are enforced."),

    ("Vanity", "noun", "B2", "/ˈvæn.ə.ti/", "kesombongan rupa / kesia-siaan fana",
     "Rasa bangga yang berlebihan atas penampilan atau prestasi diri; sifat fana yang sia-sia.",
     "Excessive pride in or admiration of one's own appearance or achievements; futility.",
     ["Vain", "Conceit", "Pride"], ["Conceit", "Narcissism", "Pride", "Egotism", "Futility"], ["Humility", "Modesty", "Meekness"],
     "His excessive vanity made him obsessed with social media follower counts and selfie lighting.",
     "The ancient philosopher wrote a famous essay on the fleeting vanity of earthly wealth and fame."),

    ("Vanguard", "noun", "C1", "/ˈvæn.ɡɑːd/", "garda terdepan / pelopor barisan perintis",
     "Bagian terdepan dari pasukan militer; kelompok orang yang memimpin gerakan atau ide baru.",
     "The foremost part of an advancing army; a group of people leading the way in new ideas.",
     ["Forefront", "Pioneer", "Frontline"], ["Forefront", "Frontline", "Spearhead", "Trailblazer", "Pioneer"], ["Rearguard", "Followers"],
     "Biotech researchers at the university are in the vanguard of genetic immunotherapy innovation.",
     "Youth environmental activists formed the courageous vanguard of the global reforestation movement."),

    ("Vast", "adjective", "B1", "/vɑːst/", "sangat luas membentang / luar biasa besarnya",
     "Berukuran, berluas, atau berjumlah sangat besar sekali; membentang sejauh mata memandang.",
     "Of very great extent or quantity; immense; occupying an exceptionally large area.",
     ["Vastly", "Vastness", "Immense"], ["Immense", "Enormous", "Colossal", "Expansive", "Boundless"], ["Tiny", "Small", "Narrow", "Confined"],
     "The Sahara Desert is a vast expanse of shifting golden sand dunes and rocky plateaus.",
     "The digital search engine indexes a vast library of academic research papers globally."),

    ("Vault", "noun", "B2", "/vɒlt/", "kubah langit-langit / ruang besi penyimpan khazanah",
     "Langit-langit melengkung dari batu atau beton; ruang bawah tanah yang aman untuk menyimpan uang.",
     "A curved ceiling or roof made of masonry; a secure room in a bank for storing valuables.",
     ["Arched ceiling", "Safe", "Treasury"], ["Safe", "Treasury", "Repository", "Strongroom", "Crypt"], ["N/A"],
     "The central bank stores national gold bullion reserves inside a subterranean reinforced vault.",
     "Gothic cathedral architects designed soaring stone ribbed vaults that withstand centuries."),

    ("Velocity", "noun", "B2", "/vəˈlɒs.ə.ti/", "kecepatan laju / kelajuan gerak berarah",
     "Kecepatan sesuatu ke arah tertentu; laju pergerakan atau perubahan pesat dalam fisika.",
     "The speed of something in a given direction; rapid rate of movement.",
     ["Accelerate", "Speed", "Pace"], ["Speed", "Pace", "Swiftness", "Rapidity", "Tempo"], ["Slowness", "Inertia", "Stagnation"],
     "The ballistic missile achieved hypersonic velocity during its atmospheric re-entry phase.",
     "Wind velocity anemometers mounted on the weather tower recorded gale-force gusts."),

    ("Vendor", "noun", "B1", "/ˈven.dər/", "penjual pedagang / penyedia barang dan jasa",
     "Orang atau perusahaan yang menawarkan barang atau jasa untuk dijual ke konsumen.",
     "A person or company offering something for sale, especially a trader in the street or supplier.",
     ["Vend", "Vending machine", "Merchant"], ["Merchant", "Supplier", "Dealer", "Seller", "Trader"], ["Buyer", "Purchaser", "Customer"],
     "Street food vendors along Malioboro boulevard serve delicious traditional gudeg and warm wedang.",
     "The software firm evaluated proposals from three certified cloud infrastructure vendors."),

    ("Venerable", "adjective", "C1", "/ˈven.ər.ə.bəl/", "sangat dihormati / sepuh berwibawa mulia",
     "Diberikan rasa hormat yang besar, terutama karena usia tua, kebijaksanaan, atau martabat luhur.",
     "Accorded a great deal of respect, especially because of age, wisdom, or character.",
     ["Venerate", "Veneration", "Respected"], ["Respected", "Revered", "Honored", "Distinguished", "Eminent"], ["Disreputable", "Disgraced", "Unworthy"],
     "The venerable Buddhist monk welcomed monastery visitors with gentle warmth and wise words.",
     "Oxford University was founded in the twelfth century, making it a venerable center of scholarship."),

    ("Verdict", "noun", "B2", "/ˈvɜː.dɪkt/", "putusan vonis juri / ketetapan akhir pengadilan",
     "Keputusan tentang suatu masalah fakta dalam kasus perdata atau pidana yang diambil oleh juri.",
     "A decision on a disputed issue in a civil or criminal case or an inquest; judgment.",
     ["Judgment", "Ruling", "Decision"], ["Ruling", "Judgment", "Finding", "Decision", "Decree"], ["Accusation", "Charge"],
     "After deliberating for three days, the jury returned a unanimous verdict of guilty on all counts.",
     "Critics gave an enthusiastic positive verdict on the young conductor's debut symphony performance."),

    ("Vessel", "noun", "B2", "/ˈves.əl/", "kapal layar samudera / wadah bejana cairan",
     "Kapal atau perahu besar; wadah atau bejana untuk menampung cairan; pembuluh darah tubuh.",
     "A ship or large boat; a hollow container, especially one used to hold liquid; a blood duct.",
     ["Ship", "Container", "Craft"], ["Ship", "Boat", "Craft", "Container", "Urn"], ["N/A"],
     "The maritime container vessel navigated safely through the narrow waters of the Suez Canal.",
     "Blood vessels, including arteries and veins, transport oxygen and nutrients to every living cell.")
]

print("SZ Extra Part 2 loaded:", len(SZ_EXTRA_PART2))
