#!/usr/bin/env python3
# -*- coding: utf-8 -*-

WORDS_PART1 = [
    # --- A ---
    ("Abbreviate", "verb", "B2", "/əˈbriː.vi.eɪt/", "menyingkat / memendekkan kata",
     "Membuat kata atau frasa menjadi lebih pendek.", "To shorten a word or phrase by leaving out letters.",
     ["Abbreviation", "Abridge", "Shorten"], ["Shorten", "Condense", "Truncate", "Contract"], ["Expand", "Lengthen", "Extend"],
     "In medical records, nurses abbreviate complex clinical diagnoses.",
     "The style guide advises authors to spell out terms initially before they abbreviate them in technical reports."),

    ("Abbreviation", "noun", "B1", "/əˌbriː.viˈeɪ.ʃən/", "singkatan / kependekan kata",
     "Bentuk pendek dari suatu kata atau istilah.", "A shortened form of a word or phrase.",
     ["Acronym", "Initialism", "Contraction"], ["Acronym", "Contraction", "Shortening"], ["Full form", "Expansion"],
     "UNESCO is a globally known abbreviation for the United Nations Educational, Scientific and Cultural Organization.",
     "Dictionaries list standard abbreviation symbols alongside pronunciation guides to assist learners."),

    ("Abide", "verb", "B2", "/əˈbaɪd/", "mematuhi / mentaati aturan / tinggal",
     "Menerima dan menaati aturan atau keputusan.", "To accept or follow a rule or decision.",
     ["Abiding", "Compliance", "Adhere"], ["Comply", "Obey", "Follow", "Endure"], ["Violate", "Disobey", "Defy"],
     "All motorists must abide by the posted highway speed limits.",
     "Citizens who value democratic stability agree to abide by judicial rulings, even when disputes arise."),

    ("Abnormal", "adjective", "B2", "/æbˈnɔː.məl/", "abnormal / tidak normal / menyimpang",
     "Menyimpang dari apa yang biasa atau standar.", "Deviating from what is normal, typical, or expected.",
     ["Anomaly", "Deviation", "Irregularity"], ["Unusual", "Atypical", "Irregular", "Anomalous"], ["Normal", "Typical", "Regular"],
     "The physician noticed abnormal enzyme levels in the blood test.",
     "Climatologists warned that abnormal ocean surface temperatures would increase storm intensities."),

    ("Aboard", "adverb", "B1", "/əˈbɔːd/", "di atas kapal / pesawat / kereta api",
     "Di dalam atau menaiki kendaraan transportasi.", "On or into a ship, train, aircraft, or vehicle.",
     ["Board", "Embark", "Onboard"], ["Onboard", "Embarked", "Inside"], ["Ashore", "Off"],
     "The captain warmly welcomed all passengers aboard the cruise ship.",
     "Once all cargo was secured aboard, the vessel set sail across the ocean."),

    ("Abolition", "noun", "C1", "/ˌæb.əˈlɪʃ.ən/", "penghapusan resmi / peniadaan hukum",
     "Tindakan resmi mengakhiri hukum atau praktik.", "The act of formally ending a law, system, or institution.",
     ["Abolish", "Repeal", "Annulment"], ["Annulment", "Repeal", "Elimination"], ["Establishment", "Institution"],
     "The abolition of slavery was a monumental victory for human rights.",
     "Humanitarian organizations campaign vigorously for the universal abolition of capital punishment."),

    ("Abrupt", "adjective", "B2", "/əˈbrʌpt/", "tiba-tiba / mendadak / kasar",
     "Terjadi mendadak tanpa peringatan; bersikap terburu-buru.", "Sudden and unexpected; brief to the point of rudeness.",
     ["Abruptly", "Sudden", "Sharp"], ["Sudden", "Sharp", "Precipitous", "Brusque"], ["Gradual", "Gentle", "Smooth"],
     "The meeting came to an abrupt halt when the emergency siren sounded.",
     "Drivers were startled by the abrupt stop of the vehicle ahead on the highway."),

    ("Absolute", "adjective", "B1", "/ˈæb.sə.luːt/", "mutlak / tanpa syarat / pasti",
     "Lengkap, bulat, dan tanpa batasan.", "Complete, total, and not qualified or diminished.",
     ["Absolutely", "Absoluteness", "Certainty"], ["Total", "Complete", "Unconditional", "Definitive"], ["Relative", "Partial", "Conditional"],
     "She had absolute confidence in her legal defense team.",
     "Scientists seek absolute empirical accuracy when verifying experimental outcomes in laboratory trials."),

    ("Abstain", "verb", "C1", "/æbˈsteɪn/", "menahan diri / tidak memilih / berpantang",
     "Secara sukarela memilih untuk tidak melakukan sesuatu.", "To choose deliberately not to do or consume something; refrain from voting.",
     ["Abstinence", "Refrain", "Forbear"], ["Refrain", "Desist", "Withhold", "Avoid"], ["Indulge", "Participate", "Consume"],
     "Ten council members voted in favor, while three chose to abstain.",
     "Nutritionists recommend patients abstain from processed sugars to manage blood glucose levels."),

    ("Abuse", "verb", "B2", "/əˈbjuːz/", "menyalahgunakan / memperlakukan buruk",
     "Menggunakan sesuatu untuk tujuan jahat; menganiaya seseorang.", "To use something improperly; to treat cruelly.",
     ["Abusive", "Abuser", "Misuse"], ["Misuse", "Mistreat", "Exploit", "Maltreat"], ["Protect", "Respect", "Preserve"],
     "Public officials must never abuse their delegated executive power.",
     "Social workers intervene promptly when individuals abuse vulnerable elders or children."),

    ("Academic", "adjective", "B1", "/ˌæk.əˈdem.ɪk/", "akademis / ilmiah / keilmuan",
     "Berkaitan dengan pendidikan tinggi atau penelitian ilmiah.", "Relating to schools, colleges, scholarship, or study.",
     ["Academy", "Academically", "Academia"], ["Scholarly", "Educational", "Intellectual", "Pedagogical"], ["Practical", "Vocational"],
     "She received numerous academic honors for her groundbreaking research in biochemistry.",
     "Universities encourage students to participate in academic symposiums and publish research papers."),

    ("Accede", "verb", "C1", "/əkˈsiːd/", "menyetujui permintaan / naik tahta",
     "Menyetujui usulan atau menduduki posisi penting.", "To agree to a demand or request; to assume an office.",
     ["Accession", "Consent", "Yield"], ["Consent", "Concede", "Assent", "Agree"], ["Refuse", "Reject", "Decline"],
     "The management agreed to accede to the workers' reasonable salary demands.",
     "The prince will accede to the throne following the formal constitutional coronation."),

    ("Accent", "noun", "B1", "/ˈæk.sənt/", "aksen / logat / tekanan suara",
     "Ciri khas pengucapan bahasa dari daerah tertentu.", "A distinctive pronunciation of a language by a group.",
     ["Accentuate", "Dialect", "Intonation"], ["Dialect", "Pronunciation", "Inflection", "Cadence"], ["Monotone"],
     "He speaks fluent English with a distinct Scottish accent.",
     "Language instructors help students refine their accent while maintaining natural expressive rhythm."),

    ("Acceptable", "adjective", "B1", "/əkˈsep.tə.bəl/", "dapat diterima / memadai / patut",
     "Cukup baik untuk disetujui atau dianggap memuaskan.", "Able to be agreed on; suitable or adequate.",
     ["Accept", "Acceptance", "Acceptably"], ["Satisfactory", "Tolerable", "Permissible", "Adequate"], ["Unacceptable", "Unsuitable"],
     "A delay of five minutes is acceptable under severe weather conditions.",
     "Quality control auditors ensure all manufacturing tolerances meet strictly acceptable standards."),

    ("Access", "noun", "B1", "/ˈæk.ses/", "akses / jalan masuk / izin menggunakan",
     "Hak atau cara untuk memasuki atau memakai sesuatu.", "The means or opportunity to enter or use something.",
     ["Accessible", "Accessibility", "Inaccessible"], ["Admission", "Entry", "Approach", "Availability"], ["Bar", "Restriction", "Blockade"],
     "Every community needs reliable access to clean water and high-speed internet.",
     "The new library design ensures universal barrier-free access for wheelchair users and seniors."),

    ("Accident", "noun", "A2", "/ˈæk.sɪ.dənt/", "kecelakaan / insiden tak terduga",
     "Peristiwa tak terduga yang menimbulkan kerugian.", "An unfortunate event that happens unexpectedly.",
     ["Accidental", "Accidentally", "Mishap"], ["Mishap", "Collision", "Incident", "Casualty"], ["Plan", "Design", "Intention"],
     "He escaped injury during the traffic accident because he wore a seatbelt.",
     "Workplace safety programs aim to reduce industrial accident rates across manufacturing plants."),

    ("Accidental", "adjective", "B2", "/ˌæk.sɪˈden.təl/", "tidak disengaja / karena kebetulan",
     "Terjadi tanpa rencana yang disengaja.", "Happening by chance or without intention.",
     ["Accident", "Accidentally", "Coincidence"], ["Unintentional", "Inadvertent", "Chance", "Fortuitous"], ["Deliberate", "Intentional", "Planned"],
     "The accidental discovery of antibiotics revolutionized modern medicine.",
     "The author noted that similarities to real individuals were purely accidental."),

    ("Acclaim", "noun", "C1", "/əˈkleɪm/", "pujian meriah / sanjungan publik",
     "Pujian antusias dari masyarakat atau para kritikus.", "Enthusiastic public praise and approval.",
     ["Acclaimed", "Praise", "Applause"], ["Praise", "Commendation", "Applause", "Tribute"], ["Condemnation", "Criticism", "Derision"],
     "The novel won critical acclaim for its nuanced historical portrayal.",
     "Her violin performance earned standing ovations and international acclaim at the festival."),

    ("Accommodation", "noun", "B1", "/əˌkɒm.əˈdeɪ.ʃən/", "akomodasi / penginapan / penyesuaian",
     "Tempat tinggal atau menginap; penyesuaian kebutuhan.", "A room, group of rooms, or building in which someone may live or stay.",
     ["Accommodate", "Accommodating", "Lodging"], ["Lodging", "Housing", "Quarters", "Shelter", "Residence"], ["Homelessness"],
     "University student accommodation includes furnished study bedrooms and shared kitchens.",
     "The travel agency booked five-star seaside hotel accommodation for the corporate retreat."),

    ("Accord", "noun", "B2", "/əˈkɔːd/", "kesepakatan resmi / perjanjian damai",
     "Perjanjian resmi antara dua belah pihak atau negara.", "An official agreement or treaty; harmonious relations.",
     ["Accordance", "According", "Consensus"], ["Pact", "Treaty", "Agreement", "Consensus"], ["Discord", "Dispute", "Conflict"],
     "Representatives signed a historic peace accord ending years of regional strife.",
     "Both trading partners reached an economic accord reducing cross-border agricultural tariffs."),

    ("Account", "noun", "A2", "/əˈkaʊnt/", "rekening / akun / laporan penjelasan",
     "Catatan keuangan di bank atau uraian rinci tentang kejadian.", "A financial arrangement; a report of an event.",
     ["Accountable", "Accountant", "Accounting"], ["Report", "Description", "Narrative", "Ledger"], ["Concealment"],
     "She opened a savings account with low fees and attractive interest rates.",
     "The journalist gave a vivid first-hand account of the rescue operation in flooded towns."),

    ("Accountable", "adjective", "B2", "/əˈkaʊn.tə.bəl/", "bertanggung jawab / wajib mempertanggungjawabkan",
     "Wajib menjelaskan atau memikul akibat dari keputusan.", "Required or expected to justify actions or decisions.",
     ["Accountability", "Account", "Responsible"], ["Responsible", "Answerable", "Liable"], ["Unaccountable", "Irresponsible"],
     "Elected officials must remain accountable to the citizens they represent.",
     "Auditing standards hold executive managers strictly accountable for financial transparency."),

    ("Accumulate", "verb", "B2", "/əˈkjuː.mjə.leɪt/", "mengumpulkan / menimbun / bertambah banyak",
     "Mengumpulkan secara bertahap dalam jumlah meningkat.", "To gather or amass an increasing quantity over time.",
     ["Accumulation", "Cumulative", "Amass"], ["Amass", "Gather", "Collect", "Build up"], ["Disperse", "Scatter", "Deplete"],
     "Dust tends to accumulate behind heavy bookshelves if left uncleaned.",
     "Prudent investors accumulate wealth gradually by reinvesting dividend earnings year after year."),

    ("Accuse", "verb", "B1", "/əˈkjuːz/", "menuduh / mendakwa kesalahan",
     "Menyatakan bahwa seseorang telah berbuat salah atau melanggar hukum.", "To charge someone with an offense or fault.",
     ["Accusation", "Accuser", "Accused"], ["Charge", "Indict", "Blame", "Implicate"], ["Defend", "Exonerate", "Acquit"],
     "Do not accuse others without concrete, verifiable evidence.",
     "The prosecutor moved to accuse the corporation of deceptive consumer advertising."),

    ("Accustomed", "adjective", "B2", "/əˈkʌs.təmd/", "terbiasa / lazim dengan",
     "Sudah terbiasa dengan suatu hal karena sering mengalaminya.", "Familiar with something through habit or experience.",
     ["Accustom", "Custom", "Habituated"], ["Habituated", "Used to", "Familiar", "Inured"], ["Unaccustomed", "Unfamiliar"],
     "Having lived in the north for decades, he was accustomed to snowy winters.",
     "Nurses become accustomed to working irregular shifts in intensive care units."),

    ("Achievement", "noun", "B1", "/əˈtʃiːv.mənt/", "prestasi / pencapaian gemilang",
     "Sesuatu yang diraih dengan kerja keras dan keterampilan.", "A thing done successfully through effort or courage.",
     ["Achieve", "Achiever", "Triumph"], ["Feat", "Triumph", "Accomplishment", "Success"], ["Failure", "Defeat", "Loss"],
     "Graduating at the top of her class was a remarkable personal achievement.",
     "Eradicating infectious diseases through widespread vaccination is a crowning human achievement."),

    ("Acid", "noun", "B1", "/ˈæs.ɪd/", "asam / zat kimia ber-pH rendah",
     "Zat kimia ber-pH di bawah 7 yang bersifat masam.", "A chemical substance with a pH below 7.",
     ["Acidic", "Acidity", "Sour"], ["Sour substance", "Corrosive compound"], ["Base", "Alkali"],
     "Citric acid gives oranges and lemons their distinct tangy flavor.",
     "Industrial safety regulations require protective gear when handling concentrated sulfuric acid."),

    ("Acoustic", "adjective", "B2", "/əˈkuː.stɪk/", "akustik / berkaitan dengan suara",
     "Berkaitan dengan bunyi atau alat musik non-elektronik.", "Relating to sound or the sense of hearing.",
     ["Acoustics", "Acoustically", "Auditory"], ["Auditory", "Sonic", "Sound"], ["Silent", "Visual"],
     "The singer delivered an acoustic guitar performance in the small hall.",
     "Architects designed the auditorium walls with acoustic panels to prevent unwanted echo."),

    ("Acquaint", "verb", "B2", "/əˈkweɪnt/", "mengenalkan / mengakrabkan dengan info",
     "Membuat seseorang mengetahui atau memahami sesuatu.", "To make someone aware of or familiar with.",
     ["Acquaintance", "Acquainted", "Inform"], ["Familiarize", "Inform", "Enlighten", "Introduce"], ["Misinform", "Conceal"],
     "Please acquaint yourself with the safety regulations before entering the workshop.",
     "The orientation program helps new hires acquaint themselves with corporate workflows."),

    ("Acquisition", "noun", "B2", "/ˌæk.wɪˈzɪʃ.ən/", "akuisisi / perolehan barang atau aset",
     "Tindakan mendapatkan aset atau keterampilan baru.", "The act of acquiring something; an asset gained.",
     ["Acquire", "Acquired", "Procurement"], ["Purchase", "Gain", "Addition", "Procurement"], ["Loss", "Disposal", "Divestiture"],
     "The library celebrated the acquisition of rare medieval manuscripts.",
     "Early childhood language acquisition progresses rapidly through conversational storytelling."),

    ("Acre", "noun", "B2", "/ˈeɪ.kər/", "ekar / satuan luas tanah",
     "Satuan luas tanah setara dengan sekitar 4.047 meter persegi.", "A unit of land area equal to 4,840 square yards.",
     ["Plot", "Area", "Land"], ["Plot", "Tract", "Parcel"], ["N/A"],
     "The family owns fifty acres of organic farmland in the valley.",
     "The forestry department planted pine saplings across a hundred acres of hillside."),

    ("Action", "noun", "A1", "/ˈæk.ʃən/", "tindakan / perbuatan / aksi",
     "Proses melakukan sesuatu atau langkah nyata.", "The process of doing something; a deed or conduct.",
     ["Active", "Act", "Activate"], ["Deed", "Act", "Measure", "Operation"], ["Inaction", "Passivity", "Inertia"],
     "Prompt action by lifeguards prevented a serious drowning incident.",
     "Environmental leaders urged immediate collective action to reduce carbon emissions."),

    ("Activism", "noun", "B2", "/ˈæk.tɪ.vɪ.zəm/", "aktivisme / perjuangan pembelaan isu sosial",
     "Upaya aktif mengkampanyekan perubahan politik atau sosial.", "Vigorous campaigning for political or social change.",
     ["Activist", "Active", "Advocacy"], ["Advocacy", "Campaigning", "Militancy", "Reform"], ["Apathy", "Passivity", "Inaction"],
     "Student activism played a pivotal role in promoting renewable university campus policies.",
     "Community activism led to the preservation of the urban park from real estate development."),

    ("Actual", "adjective", "B1", "/ˈæk.tʃu.əl/", "sebenarnya / nyata / faktual",
     "Benar-benar ada atau terjadi; bukan khayalan.", "Existing in fact; real rather than assumed or theoretical.",
     ["Actually", "Actuality", "Real"], ["Real", "Genuine", "Factual", "True", "Authentic"], ["Imaginary", "Theoretical", "Hypothetical"],
     "The actual cost of renovation was slightly lower than the initial estimate.",
     "Historians compare legend with actual archival evidence to reconstruct past battles."),

    ("Adaptation", "noun", "B2", "/ˌæd.æpˈteɪ.ʃən/", "adaptasi / penyesuaian diri / gubahan",
     "Proses menyesuaikan diri atau karya yang diubah untuk format baru.", "The process of adjusting; a modified version of a work.",
     ["Adapt", "Adaptable", "Modification"], ["Adjustment", "Modification", "Version", "Revision"], ["Rigidity", "Originality"],
     "Cacti exhibit physiological adaptation to retain moisture in arid desert regions.",
     "The stage adaptation of the fantasy book received rave reviews from critics."),

    ("Addict", "noun", "B2", "/ˈæd.ɪkt/", "pecandu / orang yang kecanduan",
     "Seseorang yang memiliki ketergantungan kuat pada suatu zat atau aktivitas.", "A person who is dependent on a substance or activity.",
     ["Addiction", "Addictive", "Addicted"], ["Dependent", "User", "Enthusiast"], ["Abstainer", "Nonuser"],
     "Support groups provide compassionate counseling for recovering drug addicts.",
     "Self-described book addicts spend their weekends browsing antiquarian bookshops."),

    ("Addition", "noun", "A2", "/əˈdɪʃ.ən/", "penambahan / tambahan / penjumlahan",
     "Tindakan menambahkan sesuatu atau item baru yang ditambahkan.", "The action of adding something; an added item.",
     ["Add", "Additional", "Additionally"], ["Inclusion", "Extension", "Supplement", "Sum"], ["Subtraction", "Deduction", "Removal"],
     "The new swimming pool was a welcomed addition to the community sports complex.",
     "Elementary school students practice addition and subtraction with visual counters."),

    ("Additional", "adjective", "B1", "/əˈdɪʃ.ən.əl/", "tambahan / ekstra / pelengkap",
     "Ditambahkan di atas apa yang sudah ada sebelumnya.", "Added, extra, or supplementary to what already exists.",
     ["Addition", "Additionally", "Extra"], ["Extra", "Supplementary", "Further", "More"], ["Base", "Essential", "Primary"],
     "The teacher provided additional exercises for students preparing for the final exam.",
     "Travelers can purchase additional baggage allowance online prior to departure."),

    ("Address", "verb", "B2", "/əˈdres/", "mengatasi masalah / berpidato di hadapan",
     "Membahas atau menangani suatu persoalan; berbicara kepada audiens.", "To direct attention to a problem; to speak formally to an audience.",
     ["Address", "Addressee", "Tackle"], ["Tackle", "Handle", "Confront", "Speak to"], ["Ignore", "Avoid", "Evade"],
     "The mayor organized a town hall meeting to address public transportation issues.",
     "The keynote speaker will address international delegates on artificial intelligence governance."),

    ("Adherent", "noun", "C1", "/ədˈhɪər.ənt/", "pengikut setia / penganut ajaran",
     "Seseorang yang mendukung gagasan, partai, atau filosofi tertentu.", "A person who supports a particular party, person, or set of ideas.",
     ["Adhere", "Adherence", "Follower"], ["Follower", "Supporter", "Devotee", "Advocate"], ["Opponent", "Critic", "Detractor"],
     "The philosopher attracted thousands of adherents who studied his ethics texts.",
     "Political movements rely on devoted adherents to organize grassroots community events."),

    ("Adjourn", "verb", "C1", "/əˈdʒɜːn/", "menunda sidang / menutup rapat sementara",
     "Menghentikan sementara rapat atau sidang sampai waktu lain.", "To break off a meeting or session with the intention of resuming later.",
     ["Adjournment", "Postpone", "Suspend"], ["Postpone", "Suspend", "Delay", "Recess"], ["Convene", "Begin", "Continue"],
     "The judge decided to adjourn the court hearing until tomorrow morning.",
     "After reaching consensus on the main budget items, the board voted to adjourn the annual meeting."),

    ("Adjust", "verb", "B1", "/əˈdʒʌst/", "menyesuaikan / menyetel / mengutak-atik",
     "Mengubah sedikit letak atau setelan agar lebih pas.", "To alter or move slightly to achieve the desired fit or result.",
     ["Adjustment", "Adjustable", "Modify"], ["Modify", "Adapt", "Regulate", "Tune", "Align"], ["Disrupt", "Upset", "Leave alone"],
     "You can adjust the seat height for ergonomic comfort while typing at the desk.",
     "New students take a few weeks to adjust to university campus life and independent study."),

    ("Adjustment", "noun", "B2", "/əˈdʒʌst.mənt/", "penyesuaian / pengaturan ulang",
     "Perubahan kecil yang dilakukan untuk memperbaiki posisi atau kondisi.", "A small alteration or movement made to achieve desired status.",
     ["Adjust", "Adjustable", "Change"], ["Alteration", "Modification", "Tuning", "Adaptation"], ["Stagnation", "Rigidity"],
     "The mechanic made a slight adjustment to the car engine timing to improve fuel efficiency.",
     "Living in a foreign country involves a period of cultural and psychological adjustment."),

    ("Administer", "verb", "B2", "/ədˈmɪn.ɪ.stər/", "mengelola / mengadministrasikan / memberikan obat",
     "Mengatur jalannya tugas atau memberikan perawatan/obat.", "To manage or organize; to give or apply something like medicine.",
     ["Administration", "Administrator", "Administrative"], ["Manage", "Direct", "Dispense", "Distribute", "Execute"], ["Neglect", "Mismanage"],
     "The nurse was trained to administer intravenous medication safely.",
     "A neutral electoral commission was formed to administer the national presidential voting process."),

    ("Administration", "noun", "B1", "/ədˌmɪn.ɪˈstreɪ.ʃən/", "administrasi / tata kelola / manajemen pemerintahan",
     "Pengelolaan urusan bisnis atau publik; periode pemerintahan.", "The management of public affairs or business; a government term.",
     ["Administer", "Administrative", "Administrator"], ["Management", "Governance", "Direction", "Executive"], ["Anarchy", "Disorder"],
     "The university administration introduced online course registration to reduce queuing times.",
     "The presidential administration enacted major healthcare reforms during its first year in office."),

    ("Administrative", "adjective", "B2", "/ədˈmɪn.ɪ.strə.tɪv/", "administratif / berkaitan dengan urusan kantor",
     "Berkaitan dengan pekerjaan kantor atau tata kelola organisasi.", "Relating to the running of a business, organization, or government.",
     ["Administer", "Administration", "Managerial"], ["Managerial", "Executive", "Organizational", "Operational"], ["Operative", "Manual"],
     "The department is hiring an administrative assistant to handle scheduling and correspondence.",
     "Administrative costs were streamlined by implementing cloud document archiving software."),

    ("Administrator", "noun", "B2", "/ədˈmɪn.ɪ.streɪ.tər/", "administrator / pengelola sistem / pejabat tata kelola",
     "Orang yang bertanggung jawab mengatur operasional atau sistem.", "A person responsible for running a business, organization, or digital system.",
     ["Administer", "Administration", "Manager"], ["Manager", "Director", "Executive", "Supervisor"], ["Subordinate", "Worker"],
     "Contact the database administrator if you experience difficulties accessing user accounts.",
     "The school administrator worked with teachers to draft the academic calendar for the upcoming year."),

    ("Admission", "noun", "B1", "/ədˈmɪʃ.ən/", "penerimaan masuk / pengakuan kesalahan / tiket masuk",
     "Izin untuk masuk ke tempat atau institusi; pernyataan mengakui sesuatu.", "Permission to enter a place or institution; an acknowledgment of fact.",
     ["Admit", "Admittance", "Confession"], ["Entry", "Access", "Confession", "Acknowledgment"], ["Denial", "Exclusion", "Rejection"],
     "University admission depends on academic transcripts, recommendations, and entrance exams.",
     "His public admission of error earned him respect from colleagues who valued transparency."),

    ("Adoption", "noun", "B2", "/əˈdɒp.ʃən/", "adopsi anak / pengadopsian kebijakan baru",
     "Proses mengadopsi anak atau penerapan sistem baru.", "The action of adopting a child or implementing a policy/system.",
     ["Adopt", "Adoptive", "Implementation"], ["Acceptance", "Implementation", "Fostering", "Approval"], ["Rejection", "Abandonment"],
     "The global adoption of renewable solar power has accelerated significantly in recent years.",
     "Social services provide guidance to prospective parents undergoing the legal adoption process."),

    ("Advance", "verb", "B1", "/ədˈvɑːns/", "bergerak maju / memajukan ilmu / meminjamkan dana",
     "Bergerak ke depan; membuat kemajuan dalam karier atau sains.", "To move forward; make progress; pay money before due.",
     ["Advanced", "Advancement", "Progress"], ["Progress", "Proceed", "Further", "Promote", "Develop"], ["Retreat", "Regress", "Halt"],
     "Medical scientists advance treatments through rigorous clinical research and trials.",
     "Troops were ordered not to advance until the scout team confirmed the terrain was clear."),

    ("Advancement", "noun", "B2", "/ədˈvɑːns.mənt/", "kemajuan / peningkatan karier / perkembangan",
     "Proses berkembang atau naik ke tingkat yang lebih tinggi.", "The promotion of a person or progress in development.",
     ["Advance", "Advanced", "Progress"], ["Progress", "Improvement", "Promotion", "Growth"], ["Decline", "Regression", "Demotion"],
     "Technological advancement in machine learning is reshaping numerous industries rapidly.",
     "The corporate fellowship program provides equal opportunities for professional career advancement."),

    ("Advantage", "noun", "A2", "/ədˈvɑːn.tɪdʒ/", "keuntungan / keunggulan / manfaat positif",
     "Kondisi atau faktor yang memberikan posisi lebih unggul.", "A condition or circumstance that puts one in a favorable position.",
     ["Advantageous", "Disadvantage", "Perk"], ["Benefit", "Edge", "Asset", "Superiority", "Favor"], ["Disadvantage", "Drawback", "Handicap"],
     "Fluency in multiple languages gives job seekers a distinct competitive advantage.",
     "One advantage of electric cars is their substantially lower maintenance and operating costs."),

    ("Advantageous", "adjective", "B2", "/ˌæd.vænˈteɪ.dʒəs/", "menguntungkan / membawa faedah",
     "Memberikan manfaat atau posisi yang lebih baik.", "Involving or creating favorable circumstances that lead to success.",
     ["Advantage", "Disadvantageous", "Beneficial"], ["Beneficial", "Favorable", "Profitable", "Helpful"], ["Disadvantageous", "Detrimental", "Harmful"],
     "It is advantageous to start saving for retirement early to benefit from compound interest.",
     "Establishing strategic partnerships with international distributors was highly advantageous for the brand."),

    ("Adventure", "noun", "A2", "/ədˈven.tʃər/", "petualangan / pengalaman seru menantang",
     "Pengalaman luar biasa yang penuh tantangan dan risiko.", "An unusual and exciting, typically hazardous, experience or activity.",
     ["Adventurous", "Adventurer", "Journey"], ["Escapade", "Expedition", "Quest", "Venture"], ["Monotony", "Routine"],
     "Backpacking across the Andes mountains was an unforgettable adventure for the university friends.",
     "The documentary chronicles the perilous Arctic adventure of early twentieth-century explorers."),

    ("Adverse", "adjective", "B2", "/ˈæd.vɜːs/", "merugikan / buruk / tidak menguntungkan",
     "Mencegah keberhasilan atau perkembangan; tidak ramah/berbahaya.", "Preventing success or development; harmful or unfavorable.",
     ["Adversely", "Adversity", "Hostile"], ["Unfavorable", "Disadvantageous", "Hostile", "Negative", "Harmful"], ["Favorable", "Beneficial", "Positive"],
     "Clinical trials must monitor for any potential adverse side effects in patients.",
     "The airline canceled coastal flights due to adverse meteorological conditions and severe turbulence."),

    ("Adversity", "noun", "C1", "/ədˈvɜː.sə.ti/", "kemalangan / masa sulit / kesulitan hidup",
     "Kesulitan besar atau kondisi kemalangan yang menimpa.", "Difficulties, misfortune, or challenging hardship.",
     ["Adverse", "Adversely", "Hardship"], ["Hardship", "Misfortune", "Tribulation", "Affliction"], ["Prosperity", "Good fortune", "Ease"],
     "Her inspiring ability to display grace in the face of profound adversity moved everyone.",
     "History demonstrates that resilient communities often emerge stronger after enduring economic adversity."),

    ("Advert", "noun", "B1", "/ˈæd.vɜːt/", "iklan / pariwara / advertensi",
     "Pemberitahuan publik untuk mempromosikan barang atau jasa.", "A public notice promoting a product, service, or event.",
     ["Advertise", "Advertisement", "Commercial"], ["Advertisement", "Commercial", "Notice", "Poster"], ["N/A"],
     "I saw an interesting advert for a remote software engineering vacancy in the weekend paper.",
     "Companies place digital adverts on social media platforms to reach younger demographic audiences."),

    ("Advertise", "verb", "B1", "/ˈæd.və.taɪz/", "mengiklankan / mempromosikan produk",
     "Memberitahukan kepada khalayak ramai agar produk dikenal.", "To describe or display a product, service, or event publicly to encourage sales.",
     ["Advertisement", "Advertiser", "Promote"], ["Promote", "Market", "Publicize", "Broadcast"], ["Conceal", "Hide", "Suppress"],
     "Local artisanal bakeries advertise their fresh sourdough batches on Instagram daily.",
     "The university will advertise the new research fellowship position internationally across scholarly portals."),

    ("Affair", "noun", "B2", "/əˈfeər/", "urusan / masalah publik / hubungan asmara rahasia",
     "Peristiwa atau rangkaian acara; masalah bisnis atau hubungan pribadi.", "An event or sequence of events; a matter or romantic relationship.",
     ["Affairs", "Business", "Matter"], ["Matter", "Event", "Incident", "Business", "Concern"], ["N/A"],
     "The Ministry of Foreign Affairs manages diplomatic relations with international governments.",
     "Organizing the international book fair was a complex affair requiring months of coordination."),

    ("Affect", "verb", "A2", "/əˈfekt/", "mempengaruhi / berdampak pada / menyentuh emosi",
     "Memberikan pengaruh atau menimbulkan perubahan pada sesuatu.", "To have an effect on; make a difference to.",
     ["Effect", "Affection", "Impact"], ["Influence", "Impact", "Alter", "Touch", "Modify"], ["Leave unaffected"],
     "Poor air quality can negatively affect respiratory health, especially in young children.",
     "The economic downturn did not affect the technology company's long-term research investments."),

    ("Affection", "noun", "B2", "/əˈfek.ʃən/", "kasih sayang / rasa cinta hangat",
     "Perasaan menyukai atau mencintai seseorang dengan tulus.", "A gentle feeling of fondness, love, or liking.",
     ["Affectionate", "Affectionately", "Fondness"], ["Fondness", "Love", "Warmth", "Tenderness", "Devotion"], ["Hatred", "Aversion", "Coldness", "Dislike"],
     "The therapy dog showed immense affection toward the residents at the senior living center.",
     "She held a deep affection for the coastal seaside village where she had spent her childhood summers."),

    ("Affiliation", "noun", "C1", "/əˌfɪl.iˈeɪ.ʃən/", "afiliasi / hubungan keanggotaan / pertalian",
     "Keterikatan atau hubungan resmi dengan organisasi atau lembaga.", "The state or process of affiliating or being affiliated with an organization.",
     ["Affiliate", "Associated", "Alliance"], ["Association", "Connection", "Alliance", "Partnership"], ["Separation", "Dissociation"],
     "Scholarly articles always state the author's university affiliation beneath the title.",
     "The hospital maintains an academic affiliation with the state medical school for clinical training."),

    ("Affirm", "verb", "B2", "/əˈfɜːm/", "menegaskan / membenarkan / menyatakan sah",
     "Menyatakan secara yakin dan pasti sebagai kebenaran.", "To state as a fact; assert strongly and publicly.",
     ["Affirmation", "Affirmative", "Assert"], ["Assert", "Declare", "Confirm", "Endorse", "Maintain"], ["Deny", "Refute", "Contradict"],
     "The supreme court voted to affirm the validity of the environmental protection statute.",
     "In their annual shareholder meeting, executives affirm their commitment to ethical governance."),

    ("Agency", "noun", "B1", "/ˈeɪ.dʒən.si/", "agensi / badan perwakilan / daya bertindak mandiri",
     "Organisasi yang memberikan layanan tertentu; kemampuan bertindak mandiri.", "A business or organization providing a service; capacity to exert power.",
     ["Agent", "Agencies", "Bureau"], ["Bureau", "Organization", "Firm", "Authority", "Instrumentality"], ["N/A"],
     "The international relief agency distributed emergency medical kits to disaster zones.",
     "Psychologists study how fostering personal agency empowers young people to overcome adversity."),

    ("Agenda", "noun", "B1", "/əˈdʒen.də/", "agenda / daftar rencana rapat / tujuan tersembunyi",
     "Daftar topik yang akan dibahas dalam rapat; rencana program kerja.", "A list of items to be discussed at a formal meeting; a plan of things to do.",
     ["Schedule", "Program", "Plan"], ["Schedule", "Program", "Itinerary", "Plan", "Timetable"], ["Disorganization"],
     "The chairperson distributed the board meeting agenda two days in advance.",
     "Environmental sustainability was placed at the very top of the international summit agenda."),

    ("Agent", "noun", "B1", "/ˈeɪ.dʒənt/", "agen perantara / zat kimia aktif / perwakilan",
     "Orang yang bertindak atas nama orang lain; zat aktif.", "A person who acts on behalf of another; a chemical substance producing an effect.",
     ["Agency", "Agentry", "Representative"], ["Representative", "Broker", "Operative", "Factor", "Medium"], ["Principal"],
     "The real estate agent arranged a guided walkthrough of the historic brownstone house.",
     "Water is a powerful geological agent of rock erosion in mountainous river valleys."),

    ("Agreement", "noun", "A2", "/əˈɡriː.mənt/", "perjanjian / kesepakatan bersama / persetujuan",
     "Kesepahaman atau kontrak resmi antara dua pihak.", "Harmony or accordance in opinion or feeling; a negotiated contract.",
     ["Agree", "Agreeable", "Contract"], ["Contract", "Accord", "Pact", "Consensus", "Concurrence"], ["Disagreement", "Discord", "Conflict"],
     "Both companies signed a mutual non-disclosure agreement before sharing proprietary algorithms.",
     "There was broad agreement among climate scientists regarding the urgency of carbon reductions."),

    ("Agriculture", "noun", "B1", "/ˈæɡ.rɪ.kʌl.tʃər/", "pertanian / agrikultur / budidaya pangan",
     "Ilmu dan praktik bercocok tanam serta beternak.", "The science or practice of farming, cultivating soil, and rearing animals.",
     ["Agricultural", "Agriculturist", "Farming"], ["Farming", "Cultivation", "Agronomy", "Husbandry"], ["Urbanization", "Industry"],
     "Modern sustainable agriculture combines precision sensor technology with organic composting methods.",
     "A large portion of the regional workforce is employed in commercial agriculture and food processing."),

    ("Aid", "noun", "B1", "/eɪd/", "bantuan / pertolongan darurat / sarana pendukung",
     "Bantuan uang, makanan, atau peralatan bagi yang membutuhkan.", "Help, typically of a practical or financial nature.",
     ["Aide", "Assist", "Assistance"], ["Help", "Assistance", "Relief", "Support", "Subsidy"], ["Hindrance", "Obstacle", "Impediment"],
     "Emergency humanitarian aid arrived within forty-eight hours of the earthquake.",
     "Visual diagrams serve as an effective memory aid when studying complex anatomical structures."),

    ("Aim", "noun", "A2", "/eɪm/", "tujuan / sasaran / bidikan",
     "Hasil atau tujuan yang ingin dicapai melalui usaha.", "A purpose or intention; a desired outcome.",
     ["Aimless", "Aimfully", "Target"], ["Goal", "Objective", "Target", "Purpose", "End"], ["Aimlessness", "Drift"],
     "The primary aim of the public campaign is to reduce cardiovascular diseases through dietary awareness.",
     "She adjusted her optical rifle sight to ensure precise target aim at long distance."),

    ("Alienate", "verb", "C1", "/ˈeɪ.li.ə.neɪt/", "mengasingkan / menjauhkan hubungan persahabatan",
     "Membuat seseorang merasa terasing, terisolasi, atau bermusuhan.", "To cause someone to feel isolated, estranged, or hostile.",
     ["Alienation", "Alien", "Estranged"], ["Estrange", "Isolate", "Distance", "Disconnect", "Sever"], ["Unite", "Reconcile", "Befriend"],
     "Arrogant leadership behavior will quickly alienate talented employees from the organization.",
     "Strict disciplinary policies without empathetic dialogue can alienate struggling adolescent students."),

    ("Allege", "verb", "B2", "/əˈledʒ/", "menduga / mendalilkan tanpa bukti final",
     "Menyatakan sesuatu sebagai fakta meski belum terbukti sepenuhnya di pengadilan.", "To claim or assert that someone has done something illegal, often without full proof.",
     ["Allegation", "Alleged", "Claim"], ["Claim", "Assert", "Contend", "Maintain", "Accuse"], ["Prove", "Verify", "Deny"],
     "The prosecution will allege that the defendant intentionally altered financial records.",
     "Whistleblowers allege that safety protocols were bypassed during pipeline construction."),

    ("Allure", "noun", "C1", "/əˈljʊər/", "daya pikat / pesona memikat / daya tarik",
     "Kualitas memikat yang menarik atau menggoda secara kuat.", "The quality of being powerfully and mysteriously attractive or fascinating.",
     ["Alluring", "Alluringly", "Charm"], ["Charm", "Fascination", "Appeal", "Magnetism", "Glamour"], ["Repulsion", "Revulsion", "Ugliness"],
     "The mystical allure of ancient pyramids attracts millions of curious travelers annually.",
     "Despite the grueling work hours, the allure of startup entrepreneurship continues to draw ambitious innovators."),

    ("Ally", "noun", "B2", "/ˈæl.aɪ/", "sekutu / mitra kerja sama / sahabat koalisi",
     "Negara atau orang yang bekerja sama demi tujuan bersama.", "A state or person formally cooperating with another for a military or shared purpose.",
     ["Alliance", "Allied", "Partner"], ["Partner", "Associate", "Colleague", "Confederate", "Supporter"], ["Enemy", "Adversary", "Opponent", "Foe"],
     "The two neighboring nations remained steadfast allies throughout the geopolitical treaty negotiations.",
     "Mentors serve as valuable career allies when navigating competitive corporate workplace transitions."),

    ("Amateur", "noun", "B2", "/ˈæm.ə.tər/", "amatir / pemula yang belum profesional",
     "Seseorang yang melakukan kegiatan karena hobi, bukan profesi berbayar.", "A person who engages in a pursuit on an unpaid rather than professional basis.",
     ["Amateurish", "Nonprofessional", "Novice"], ["Novice", "Layman", "Dilettante", "Beginner"], ["Professional", "Expert", "Veteran"],
     "The astronomy club allows amateur stargazers to observe planetary rings through high-powered telescopes.",
     "Although she was an amateur runner, she finished the city half-marathon in under two hours."),

    ("Animation", "noun", "B1", "/ˌæn.ɪˈmeɪ.ʃən/", "animasi / pembuatan film kartun / kegairahan",
     "Proses pembuatan gambar bergerak; semangat hidup dan keceriaan.", "The technique of photographing successive drawings; liveliness and vigor.",
     ["Animate", "Animated", "Animator"], ["Liveliness", "Vitality", "Vigor", "Cartooning", "Movement"], ["Lifelessness", "Dullness"],
     "Computer-generated 3D animation has revolutionized modern cinema storytelling.",
     "She spoke with immense animation and expressive hand gestures when describing her travels."),

    ("Announce", "verb", "A2", "/əˈnaʊns/", "mengumumkan / memberitahukan secara resmi",
     "Menyampaikan informasi secara terbuka dan resmi kepada publik.", "To make a formal public statement about a fact, event, or intention.",
     ["Announcement", "Announcer", "Declare"], ["Declare", "Proclaim", "Broadcast", "Publicize", "State"], ["Conceal", "Suppress", "Hide"],
     "The government will announce the new fiscal stimulus package tomorrow morning.",
     "The train conductor used the intercom to announce the next platform arrival."),

    ("Announcement", "noun", "B1", "/əˈnaʊns.mənt/", "pengumuman / maklumat resmi",
     "Pernyataan resmi yang disiarkan kepada publik.", "A formal public statement about an occurrence or intention.",
     ["Announce", "Announcer", "Declaration"], ["Declaration", "Proclamation", "Notice", "Statement", "Broadcast"], ["Secret", "Silence"],
     "Students listened attentively to the morning principal's announcement regarding graduation dates.",
     "The corporate press announcement confirmed the merger between the two international airlines."),

    ("Annual", "adjective", "B1", "/ˈæn.ju.əl/", "tahunan / terjadi sekali setiap tahun",
     "Terjadi atau diterbitkan satu kali dalam kurun satu tahun.", "Occurring once every year; calculated over a year.",
     ["Annually", "Yearly", "Perennial"], ["Yearly", "Perennial", "Every year"], ["N/A"],
     "The company holds its annual shareholder meeting in early November.",
     "Tropical regions experience an annual monsoon season that replenishes regional water reservoirs."),

    ("Anonymous", "adjective", "B2", "/əˈnɒn.ɪ.məs/", "anonim / tanpa nama pengarang / tidak dikenal",
     "Tidak menyebutkan nama asli; tidak diketahui identitasnya.", "Not identified by name; of unknown name.",
     ["Anonymously", "Anonymity", "Unnamed"], ["Unnamed", "Nameless", "Unidentified", "Incognito"], ["Named", "Identified", "Known"],
     "An anonymous donor contributed two million dollars to build the children's oncology wing.",
     "Whistleblowers can submit safety hazard reports through an anonymous digital tip portal."),

    ("Anxiety", "noun", "B1", "/æŋˈzaɪ.ə.ti/", "kecemasan / kegelisahan / rasa waswas",
     "Perasaan cemas, khawatir, atau tidak tenang tentang masa depan.", "A feeling of worry, nervousness, or unease about an uncertain outcome.",
     ["Anxious", "Anxiously", "Worry"], ["Apprehension", "Nervousness", "Unease", "Dread", "Fretfulness"], ["Calmness", "Serenity", "Tranquility"],
     "Deep breathing exercises and mindfulness help reduce exam-related anxiety in students.",
     "Clinical therapists provide cognitive coping strategies for patients struggling with generalized anxiety."),

    ("Appeal", "noun", "B1", "/əˈpiːl/", "daya tarik / permohonan bantuan / banding hukum",
     "Kualitas yang memikat minat; permohonan resmi bantuan dana atau hukum.", "The quality of being attractive; an earnest or formal request.",
     ["Appealing", "Appealingly", "Plea"], ["Attraction", "Charm", "Plea", "Petition", "Solicitation"], ["Repulsion", "Aversion"],
     "The simplicity of minimalist architecture holds wide appeal for modern urban homeowners.",
     "The legal defense team filed an appeal against the court verdict based on newly uncovered evidence."),

    ("Appetite", "noun", "B1", "/ˈæp.ə.taɪt/", "nafsu makan / hasrat kuat akan sesuatu",
     "Keinginan alami untuk makan; hasrat kuat terhadap pengalaman.", "A natural desire to satisfy a bodily need, especially for food.",
     ["Appetizer", "Appetizing", "Hunger"], ["Hunger", "Craving", "Desire", "Taste", "Relish"], ["Aversion", "Revulsion", "Satiety"],
     "A brisk morning walk in the crisp alpine air stimulates a healthy breakfast appetite.",
     "Global financial markets exhibited a strong appetite for technology stocks this quarter."),

    ("Applicable", "adjective", "B2", "/əˈplɪk.ə.bəl/", "dapat diterapkan / berlaku relevan",
     "Sesuai atau relevan untuk situasi tertentu.", "Relevant or appropriate to a situation or context.",
     ["Apply", "Application", "Relevant"], ["Relevant", "Appropriate", "Suitable", "Pertinent", "Fitting"], ["Inapplicable", "Irrelevant", "Inappropriate"],
     "These safety regulations are strictly applicable to all personnel working on the oil rig.",
     "Verify whether the promotional discount code is applicable to international online orders."),

    ("Applicant", "noun", "B1", "/ˈæp.lɪ.kənt/", "pelamar kerja / pemohon beasiswa",
     "Seseorang yang mengajukan permohonan resmi untuk pekerjaan.", "A person who makes a formal application for something, typically a job.",
     ["Apply", "Application", "Candidate"], ["Candidate", "Jobseeker", "Aspirant", "Claimant", "Petitioner"], ["Employer", "Recruiter"],
     "Each applicant must submit a curriculum vitae, cover letter, and three professional references.",
     "Over five hundred applicants vied for the prestigious biomedical research scholarship."),

    ("Application", "noun", "B1", "/ˌæp.lɪˈkeɪ.ʃən/", "aplikasi software / lamaran kerja / penerapan",
     "Program komputer; berkas lamaran; praktik menerapkan teori.", "A formal request; a software program; practical use of an idea.",
     ["Apply", "Applicable", "App"], ["Software", "Program", "Petition", "Implementation", "Utilization"], ["Withdrawal"],
     "Mobile banking applications allow users to transfer funds and pay utility bills securely.",
     "The practical application of solar energy has expanded dramatically in off-grid rural communities."),

    ("Appoint", "verb", "B1", "/əˈpɔɪnt/", "mengangkat jabatan / menunjuk / menentukan waktu",
     "Menetapkan seseorang untuk menduduki posisi; menentukan jadwal.", "To assign a job or role to someone; to determine a time or place.",
     ["Appointment", "Appointee", "Designate"], ["Designate", "Nominate", "Name", "Assign", "Commission"], ["Dismiss", "Discharge", "Reject"],
     "The board of directors voted to appoint a new chief sustainability officer.",
     "The committee agreed to appoint Friday morning for the final contract signing ceremony."),

    ("Appointment", "noun", "A2", "/əˈpɔɪnt.mənt/", "janji temu / pengangkatan jabatan resmi",
     "Kesepakatan waktu untuk bertemu; penetapan posisi kerja.", "An arrangement to meet someone; the assignment of a person to a job.",
     ["Appoint", "Appointee", "Meeting"], ["Meeting", "Consultation", "Designation", "Engagement", "Session"], ["Cancellation"],
     "Please call the medical clinic to schedule a dental checkup appointment for next week.",
     "His official appointment as ambassador was confirmed by a unanimous senate vote."),

    ("Appreciation", "noun", "B2", "/əˌpriː.ʃiˈeɪ.ʃən/", "apresiasi / penghargaan / peningkatan nilai",
     "Rasa terima kasih atau pengakuan atas nilai baik; kenaikan harga.", "Recognition of good qualities; gratitude; an increase in value.",
     ["Appreciate", "Appreciative", "Gratitude"], ["Gratitude", "Thanks", "Esteem", "Valuation", "Increase"], ["Ingratitude", "Depreciation"],
     "The company organized a banquet in appreciation of its long-serving staff members.",
     "Art appreciation courses teach students how to analyze composition, lighting, and cultural themes."),

    ("Approach", "verb", "B1", "/əˈprəʊtʃ/", "mendekati / menyikapi masalah / menghampiri",
     "Bergerak mendekat ke seseorang; mulai menangani masalah.", "To come near to someone; to start dealing with a problem in a certain way.",
     ["Approach", "Approachable", "Near"], ["Near", "Advance toward", "Tackle", "Address", "Confront"], ["Depart", "Withdraw", "Retreat"],
     "Winter is beginning to approach, bringing cooler winds and shorter daylight hours.",
     "Scientists approach complex ecological questions using computational simulation models."),

    ("Appropriate", "adjective", "B1", "/əˈprəʊ.pri.ət/", "pantas / sesuai / tepat pada tempatnya",
     "Cocok dan tepat untuk orang, kondisi, atau tujuan tertentu.", "Suitable or proper in the circumstances.",
     ["Appropriately", "Appropriateness", "Suitable"], ["Suitable", "Fitting", "Proper", "Apt", "Applicable"], ["Inappropriate", "Unsuitable", "Improper"],
     "Casual sports attire is not appropriate for a formal diplomatic reception.",
     "The judge imposed a fair and appropriate sanction reflecting the severity of the offense."),

    ("Approval", "noun", "B1", "/əˈpruː.vəl/", "persetujuan resmi / restu / izin",
     "Izin resmi untuk melakukan sesuatu; pandangan positif.", "Official agreement to something; a positive opinion.",
     ["Approve", "Disapproval", "Consent"], ["Consent", "Sanction", "Authorization", "Endorsement", "Assent"], ["Disapproval", "Refusal", "Denial", "Veto"],
     "The architectural blueprints must receive municipal zoning approval before construction starts.",
     "Her innovative research proposal gained the unanimous approval of the university grant committee."),

    ("Approve", "verb", "B1", "/əˈpruːv/", "menyetujui / merestui / mengesahkan",
     "Secara resmi menerima atau membenarkan rencana.", "To officially agree to or accept as satisfactory.",
     ["Approval", "Approved", "Sanction"], ["Sanction", "Authorize", "Endorse", "Validate", "Permit"], ["Reject", "Disapprove", "Veto", "Decline"],
     "The city council voted to approve the construction of a new public park along the riverfront.",
     "Health authorities review clinical trials thoroughly before they approve new vaccines for distribution."),

    ("Approximate", "adjective", "B1", "/əˈprɒk.sɪ.mət/", "kira-kira / mendekati tepat / perkiraan",
     "Hampir tepat tetapi tidak persis sepenuhnya.", "Close to the actual, but not completely accurate or exact.",
     ["Approximately", "Approximation", "Rough"], ["Estimated", "Rough", "Close", "Near", "Imprecise"], ["Exact", "Precise", "Accurate"],
     "The approximate travel time between the two regional capitals is four hours by express rail.",
     "Can you give me an approximate cost estimate for repairing the damaged roof shingles?"),

    ("Architect", "noun", "A2", "/ˈɑː.kɪ.tekt/", "arsitek / perancang bangunan / penggagas",
     "Orang yang merancang bangunan; penggagas rencana besar.", "A person who designs buildings and oversees their construction; an originator.",
     ["Architecture", "Architectural", "Designer"], ["Designer", "Planner", "Creator", "Originator", "Builder"], ["Destroyer"],
     "The celebrated architect designed an eco-friendly skyscraper powered entirely by geothermal energy.",
     "Economists regard the former minister as the chief architect of the nation's financial reforms."),

    ("Architecture", "noun", "B1", "/ˈɑː.kɪ.tek.tʃər/", "arsitektur / seni merancang gedung / struktur sistem",
     "Seni dan ilmu merancang bangunan; struktur internal sistem komputer.", "The art or practice of designing buildings; structure of a system.",
     ["Architect", "Architectural", "Design"], ["Design", "Construction", "Structure", "Framework", "Style"], ["Chaos", "Disorder"],
     "Classical Greek architecture is celebrated for symmetrical marble columns and grand pediments.",
     "Software engineers designed a microservices architecture to improve application scalability."),

    ("Archive", "noun", "B2", "/ˈɑː.kaɪv/", "arsip / tempat penyimpanan dokumen bersejarah",
     "Kumpulan dokumen atau catatan bersejarah yang disimpan rapi.", "A collection of historical documents or records providing information about a place or group.",
     ["Archivist", "Archival", "Records"], ["Repository", "Records", "Chronicle", "Registry", "Storage"], ["N/A"],
     "Historians searched through the national archive to uncover letters from the independence era.",
     "The digital museum archive allows scholars worldwide to inspect high-resolution scans of ancient papyri."),

    ("Argue", "verb", "A2", "/ˈɑːɡ.juː/", "berdebat / berargumen / membantah",
     "Bertukar pandangan yang bertolak belakang; memberikan alasan logis.", "To give reasons or cite evidence in support of an idea; exchange diverging views angrily.",
     ["Argument", "Argumentative", "Debate"], ["Debate", "Contend", "Dispute", "Assert", "Maintain"], ["Agree", "Concur", "Harmonize"],
     "Lawyers argue their cases based on statutory law, precedents, and material evidence.",
     "Siblings occasionally argue over household chores, but they quickly make amends afterwards."),

    ("Argument", "noun", "A2", "/ˈɑːɡ.jə.mənt/", "argumen / perdebatan / alasan pembuktian",
     "Rangkaian alasan untuk membuktikan sesuatu; pertengkaran kata.", "A reason or set of reasons given with the aim of persuading; a heated dispute.",
     ["Argue", "Argumentative", "Debate"], ["Debate", "Dispute", "Contention", "Reasoning", "Thesis"], ["Agreement", "Harmony", "Concurrence"],
     "The essay presented a compelling logical argument in support of expanding urban green belts.",
     "A heated argument erupted between delegates regarding the division of carbon offset credits."),

    ("Arise", "verb", "B2", "/əˈraɪz/", "muncul / timbul / bangkit dari keadaan",
     "Terjadi atau mulai terlihat sebagai akibat dari keadaan.", "To emerge, become apparent, or occur as a result of a situation.",
     ["Arose", "Arisen", "Emerge"], ["Emerge", "Occur", "Happen", "Originate", "Stem"], ["Disappear", "Vanish", "Cease", "End"],
     "Should any technical issues arise during testing, our engineering team is available twenty-four hours.",
     "Complications may arise if patients do not follow postoperative care instructions strictly."),

    ("Armed", "adjective", "B1", "/ɑːmd/", "bersenjata / diperlengkapi senjata",
     "Membawa senjata atau diperlengkapi sarana pertahanan.", "Equipped with or carrying weapons.",
     ["Arm", "Armor", "Armed forces"], ["Equipped", "Fortified", "Weaponized", "Defended"], ["Unarmed", "Defenseless", "Vulnerable"],
     "Security personnel remained on high alert during the arrival of the foreign dignitaries.",
     "Armed escorts protected the scientific research convoy traveling through remote frontier territory."),

    ("Array", "noun", "B2", "/əˈreɪ/", "deretan / susunan beraneka ragam / larik data",
     "Koleksi atau susunan benda yang menarik dan beragam.", "An impressive display or range of a particular type of thing; an arrangement of data.",
     ["Arrange", "Arrangement", "Display"], ["Display", "Assortment", "Collection", "Range", "Formation"], ["Disarray", "Disorder", "Scattering"],
     "The boutique confectionery displayed a dazzling array of handcrafted chocolates and pastries.",
     "The research laboratory utilizes a wide array of optical sensors to monitor atmospheric pollution."),

    ("Arrest", "verb", "B1", "/əˈrest/", "menangkap pelaku kejahatan / menghentikan laju",
     "Menahan seseorang secara hukum; menghentikan perkembangan penyakit.", "To seize someone by legal authority; to stop or check progress.",
     ["Arrest", "Arrested", "Detain"], ["Detain", "Apprehend", "Capture", "Halt", "Check"], ["Release", "Free", "Accelerate", "Spur"],
     "Police officers acted swiftly to arrest the suspects fleeing the scene of the diamond robbery.",
     "Prompt medical interventions can arrest the rapid spread of bacterial infections in patients."),

    ("Arrival", "noun", "A2", "/əˈraɪ.vəl/", "kedatangan / kedatangan tamu / tibanya saat",
     "Tindakan sampai di tempat tujuan; munculnya hal baru.", "The action or process of arriving somewhere; the appearance of something new.",
     ["Arrive", "Arriving", "Advent"], ["Advent", "Appearance", "Entrance", "Coming", "Landing"], ["Departure", "Exit", "Leaving"],
     "Hotel staff prepared floral garlands to celebrate the arrival of the honeymoon couple.",
     "The arrival of digital photography transformed the print publishing and journalism industries."),

    ("Arrive", "verb", "A1", "/əˈraɪv/", "tiba / sampai di tujuan / mencapai saat",
     "Mencapai suatu tempat setelah melakukan perjalanan.", "To reach a destination at the end of a journey or stage.",
     ["Arrival", "Arriving", "Reach"], ["Reach", "Land", "Come", "Turn up", "Appear"], ["Depart", "Leave", "Go"],
     "The high-speed express train will arrive at the central platform at ten o'clock sharp.",
     "Migratory birds arrive in the southern wetlands every autumn to escape harsh northern frosts."),

    ("Artist", "noun", "A1", "/ˈɑː.tɪst/", "seniman / pelukis / perupa kreatif",
     "Orang yang menciptakan karya seni seperti lukisan, patung, atau musik.", "A person who creates paintings, sculptures, music, or other art forms.",
     ["Artistic", "Artistry", "Art"], ["Painter", "Creator", "Sculptor", "Musician", "Performer"], ["N/A"],
     "The contemporary artist showcased her colorful canvas collection at the international gallery.",
     "Street artists in Melbourne transform urban brick alleyways into celebrated open-air murals."),

    ("Artistic", "adjective", "B1", "/ɑːˈtɪs.tɪk/", "artistik / bernilai seni / berbakat seni",
     "Memiliki keindahan seni atau bakat kreatif dalam berkarya.", "Having or revealing natural creative skill in the arts.",
     ["Artist", "Artistically", "Creative"], ["Creative", "Imaginative", "Expressive", "Aesthetic", "Talented"], ["Inartistic", "Uncreative", "Crude"],
     "She showed remarkable artistic talent from an early age, sculpting clay miniatures with precision.",
     "The film director was praised for his visionary artistic direction and evocative lighting choices."),

    ("Artwork", "noun", "B1", "/ˈɑːt.wɜːk/", "karya seni / ilustrasi visual / lukisan",
     "Karya lukisan, patung, atau ilustrasi visual yang memiliki nilai estetika.", "Works of art, such as paintings or sculptures; illustrations prepared for print.",
     ["Art", "Artist", "Masterpiece"], ["Masterpiece", "Creation", "Piece", "Illustration", "Canvas"], ["N/A"],
     "The art gallery secured funding to restore several valuable 18th-century landscape artworks.",
     "Graphic designers submit digitized artwork files in vector format for promotional magazine banners."),

    ("Ash", "noun", "B2", "/æʃ/", "abu / sisa pembakaran / abu vulkanik",
     "Bubuk abu-abu yang tersisa setelah sesuatu terbakar habis.", "The powdery residue left after the burning of any substance.",
     ["Ashes", "Ashen", "Cinder"], ["Cinder", "Residue", "Embers", "Dust", "Soot"], ["Flame", "Fuel"],
     "Volcanic ash from the eruption drifted across surrounding farmland, blanketing roofs in gray.",
     "Firefighters checked the camp fire pit carefully to ensure no glowing embers remained in the ash."),

    ("Aspect", "noun", "B1", "/ˈæs.pekt/", "aspek / segi pandang / sisi persoalan",
     "Bagian atau ciri khusus dari suatu masalah, situasi, atau gagasan.", "A particular part or feature of something; a direction facing.",
     ["Perspective", "Facet", "Feature"], ["Facet", "Feature", "Dimension", "Angle", "Side"], ["Whole", "Entity"],
     "One crucial aspect of learning a foreign language is developing active listening comprehension.",
     "Architects carefully consider solar aspect and wind exposure when positioning residential windows."),

    ("Aspiration", "noun", "B2", "/ˌæs.pɪˈreɪ.ʃən/", "aspirasi / cita-cita luhur / harapan besar",
     "Harapan kuat atau cita-cita untuk mencapai hal hebat.", "A hope or ambition of achieving something great.",
     ["Aspire", "Aspiring", "Ambition"], ["Ambition", "Dream", "Goal", "Objective", "Endeavor"], ["Apathy", "Despair", "Indifference"],
     "Her highest career aspiration is to lead an international environmental research laboratory.",
     "Youth mentorship programs encourage teenagers to pursue their vocational aspirations with confidence."),

    ("Aspire", "verb", "B2", "/əˈspaɪər/", "bercita-cita / mendambakan pencapaian",
     "Mengarahkan tekad dan harapan untuk meraih cita-cita tinggi.", "To direct one's hopes or ambitions toward achieving something.",
     ["Aspiration", "Aspiring", "Strive"], ["Aim", "Strive", "Seek", "Desire", "Yearn"], ["Surrender", "Give up"],
     "Many young medical researchers aspire to find curative therapies for rare pediatric diseases.",
     "Developing nations aspire to establish renewable energy self-sufficiency within this generation."),

    ("Assassinate", "verb", "B2", "/əˈsæs.ɪ.neɪt/", "membunuh tokoh politik / membunuh berencana",
     "Membunuh tokoh politik atau publik penting secara terencana.", "To murder an important person in a surprise attack for political or religious reasons.",
     ["Assassination", "Assassin", "Murder"], ["Murder", "Kill", "Execute", "Liquidate", "Slay"], ["Protect", "Guard", "Defend"],
     "Conspirators plotted in secret to assassinate the visiting imperial archduke.",
     "Security protocols around heads of state are designed to prevent attempts to assassinate leaders."),

    ("Assault", "noun", "B2", "/əˈsɒlt/", "penyerangan fisik / serangan militer / serbuan",
     "Tindakan kekerasan fisik menyerang seseorang atau serbuan militer.", "A physical attack on a person; a concerted military attack.",
     ["Assailant", "Assault", "Attack"], ["Attack", "Assault", "Offensive", "Strike", "Charge"], ["Defense", "Protection", "Retreat"],
     "The police arrested the suspect and charged him with aggravated physical assault.",
     "Military historians documented the courageous dawn amphibious assault on Normandy beaches."),

    ("Assemble", "verb", "B2", "/əˈsem.bəl/", "merakit komponen / mengumpulkan orang / berkumpul",
     "Memasang bagian-bagian menjadi satu; berkumpul bersama di satu tempat.", "To fit together the parts of something; to gather together in one place.",
     ["Assembly", "Assembler", "Gather"], ["Gather", "Congregate", "Muster", "Construct", "Build"], ["Disassemble", "Dismantle", "Disperse", "Scatter"],
     "Students will assemble in the main auditorium for the morning awards ceremony.",
     "The furniture package includes clear illustrated diagrams explaining how to assemble the desk."),

    ("Assembly", "noun", "B2", "/əˈsem.bli/", "majelis perwakilan / perakitan mesin / pertemuan",
     "Kelompok orang yang berkumpul untuk tujuan resmi; perakitan produk.", "A group of people gathered together in one place; fitting together parts.",
     ["Assemble", "Assembler", "Gathering"], ["Gathering", "Congregation", "Convention", "Fabrication", "Council"], ["Dispersal", "Disassembly"],
     "The United Nations General Assembly convened in New York to deliberate global poverty initiatives.",
     "Automated robotic arms on the vehicle assembly line weld chassis frames with sub-millimeter precision."),

    ("Assertion", "noun", "C1", "/əˈsɜː.ʃən/", "pernyataan tegas / penegasan klaim",
     "Pernyataan yang dibuat dengan yakin dan tegas mengenai suatu fakta.", "A confident and forceful statement of fact or belief.",
     ["Assert", "Assertive", "Claim"], ["Claim", "Declaration", "Affirmation", "Contention", "Statement"], ["Denial", "Refutation", "Doubt"],
     "The scientific report challenged the company's assertion that the chemical was harmless.",
     "Debaters must support every factual assertion with credible peer-reviewed statistical citations."),

    ("Assistant", "noun", "A2", "/əˈsɪs.tənt/", "asisten / pembantu tugas / ajudan",
     "Seseorang yang membantu orang lain dalam pekerjaannya.", "A person who helps or aids someone in a particular role.",
     ["Assist", "Assistance", "Aide"], ["Aide", "Helper", "Deputy", "Attendant", "Associate"], ["Supervisor", "Boss"],
     "The research assistant cataloged thousands of botanical specimen samples in the herbarium.",
     "She worked as an executive assistant managing calendar schedules and travel logistics for the CEO."),

    ("Attachment", "noun", "B1", "/əˈtætʃ.mənt/", "lampiran email / ikatan emosional / sambungan",
     "Berkas yang dilampirkan pada pesan elektronik; kasih sayang erat.", "An extra document added to an email; an emotional bond.",
     ["Attach", "Attached", "Bond"], ["Affection", "Bond", "Enclosure", "Accessory", "Extension"], ["Detachment", "Separation"],
     "Please check the email attachment for the complete financial balance sheet and audit notes.",
     "Children develop a secure psychological attachment to caregivers who provide consistent nurturing care."),

    ("Attraction", "noun", "B1", "/əˈtræk.ʃən/", "daya tarik / tempat wisata populer / gaya tarik",
     "Daya pikat yang menarik minat; objek wisata yang digemari turis.", "The action or power of drawing someone; a place people visit for pleasure.",
     ["Attract", "Attractive", "Appeal"], ["Appeal", "Charm", "Magnetism", "Sight", "Landmark"], ["Repulsion", "Deterrent"],
     "The historic medieval castle is the most famous tourist attraction in the highland region.",
     "Newtonian physics describes gravitational attraction between planetary bodies in orbit."),

    ("Average", "noun", "A2", "/ˈæv.ər.ɪdʒ/", "rata-rata / nilai tengah / taraf biasa",
     "Nilai tengah yang diperoleh dari pembagian total; taraf normal.", "A number expressing the central value in data; typical standard.",
     ["Averaging", "Median", "Mean"], ["Mean", "Median", "Norm", "Standard", "Par"], ["Extreme", "Outlier"],
     "The average test score for the chemistry class was eighty-five percent this semester.",
     "An average adult requires between seven and nine hours of restful sleep each night."),

    ("Avoid", "verb", "A2", "/əˈvɔɪd/", "menghindari / mencegah terjadinya bahaya",
     "Menjauhkan diri dari sesuatu yang berbahaya atau merugikan.", "To keep away from or stop oneself from doing something.",
     ["Avoidance", "Avoidable", "Evade"], ["Evade", "Elude", "Shun", "Dodge", "Steer clear of"], ["Confront", "Face", "Embrace", "Seek"],
     "Drivers should avoid using mobile phones while operating motor vehicles.",
     "To avoid dehydration during long summer hikes, drink plenty of water and wear sun protection."),

    ("Award", "noun", "A2", "/əˈwɔːd/", "penghargaan / piala kehormatan / hadiah prestasi",
     "Hadiah atau penghargaan yang diberikan atas pencapaian luar biasa.", "A prize or other mark of recognition given in honor of an achievement.",
     ["Reward", "Prize", "Honors"], ["Prize", "Trophy", "Honor", "Accolade", "Grant"], ["Penalty", "Forfeiture"],
     "The documentary filmmaker received a prestigious international award at the Sundance Festival.",
     "The scientific foundation granted a research award of fifty thousand dollars to the laboratory.")
]

print(f"Loaded {len(WORDS_PART1)} words in PART 1")
